# -*- coding: utf-8 -*-
"""VIEM DE - buoc 3: sinh KHUNG PHO BAN DONG ban JX1.

Vi sao KHONG chep thang \\script\\missions\\basemission\\dungeon.lua cua Linux:

  1. Linux chay MOT state Lua chung cho ca may chu, nen `DungeonList` (bang
     idBanDo -> pho ban) chia se duoc giua readymap.lua / ready.lua / npc.lua.
     JX1 cho MOI TEP mot state rieng - `Include` chinh la `lua_dofile` vao state
     cua tep GOI (ScriptFuns.cpp:1969), nen moi tep se co MOT BAN SAO RIENG cua
     DungeonList. => Trang thai dung chung PHAI nam trong bo nho cua engine.
     O day dung BIEN MISSION cua chinh ban do do (KMission.h: m_MissionValue
     thuoc SubWorld, chi so 1..99, doc/ghi qua GetMissionV/SetMissionV sau khi
     dat bien toan cuc `SubWorld` = chi so ban do).

  2. Linux nhan ban ban do luc chay (ApplyDungeonMap goi vao engine). JX1 nap
     ban do MOT LAN luc khoi dong tu WorldSet (KSubWorldSet::Load). Nen ta khai
     truoc mot BE ban do tinh (buoc 2: 1003-1017, cung tro ve thu muc ban do cua
     852) roi phat/thu id. Nguoi choi thay y het ban goc: moi to doi mot phong rieng.

  3. Linux dung usepack/curpack de doi state khi goi lai ham; JX1 timer JX2
     (KJx2League.cpp:1051 LuaJX2_AddTimer) goi ham NGAY TRONG state cua tep da
     dat hen, nen bo han lop pack.

Sinh 1 tep:  \\script\\missions\\basemission\\dungeon.lua
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, r"C:\Users\nguye\.claude\skills\swordonline-dev\scripts")
from vn_to_octal import unicode_to_tcvn3_bytes

SRV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
GUONG = r"D:\GAMEDEVNEW\serverscript_jx2\viemde"
DICH = r"\script\missions\basemission\dungeon.lua"


def V(s):
    return unicode_to_tcvn3_bytes(s).decode("latin-1")


POOL_DAU, POOL_CUOI = 1003, 1017

L = []
a = L.append

a("-- ==========================================================================")
a("-- KHUNG PHO BAN DONG (dungeon) - ban JX1")
a("-- SINH TU DONG boi ReverseTools\\viemde\\v03_gen_dungeon.py - DUNG SUA TAY")
a("--")
a("-- Dich nguoc tu \\script\\missions\\basemission\\dungeon.lua cua ban Linux,")
a("-- viet lai cho JX1 vi 2 khac biet co ban:")
a("--   * JX1 moi tep Lua mot state rieng => trang thai chung phai nam o BIEN")
a("--     MISSION cua chinh ban do (SubWorld[i].m_MissionArray), khong dung bien Lua.")
a("--   * JX1 nap ban do mot lan luc khoi dong => dung BE ban do tinh khai truoc")
a("--     trong MapList.ini + WorldSet_GameServer.ini (%d-%d)." % (POOL_DAU, POOL_CUOI))
a("-- ==========================================================================")
a("")
a("-- --- chi so bien mission dung cho quan ly be (KMission.h: 1..99; Viem De")
a("-- --- dung 1..49 tren ban do TRAN nen 90.. la vung trong) ---")
a("DG_V_BUSY   = 90    -- 0 = ranh, khac 0 = mot to doi dang dung")
a("DG_V_TPL    = 91    -- id ban do khuon ma phong nay nhan ban tu do")
a("DG_V_COUNT  = 92    -- so nguoi dang dung trong phong")
a("DG_V_TYPE   = 93    -- ma loai pho ban (xem DG_TYPE_*)")
a("DG_V_SERIAL = 94    -- so thu tu lan cap phat, de phan biet hai luot dung chung id")
a("")
a("DG_TYPE_YDBZ_READY = 1   -- phong cho Viem De Bao Tang")
a("")
a("-- --- be ban do theo tung khuon ---")
a("DUNGEON_POOL = {}")
a("DUNGEON_POOL[852] = {%s}" % ", ".join(str(i) for i in range(POOL_DAU, POOL_CUOI + 1)))
a("")
a("")
a("-- ==========================================================================")
a("-- Doc/ghi bien mission cua MOT ban do bat ky (tu dong tra lai SubWorld cu)")
a("-- ==========================================================================")
a("function DG_GetVar(nMapId, nIdx)")
a("\tlocal nIdxMap = SubWorldID2Idx(nMapId)")
a("\tif nIdxMap < 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdxMap")
a("\tlocal nRet = GetMissionV(nIdx)")
a("\tSubWorld = nOld")
a("\treturn nRet")
a("end")
a("")
a("function DG_SetVar(nMapId, nIdx, nValue)")
a("\tlocal nIdxMap = SubWorldID2Idx(nMapId)")
a("\tif nIdxMap < 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdxMap")
a("\tSetMissionV(nIdx, nValue)")
a("\tSubWorld = nOld")
a("\treturn 1")
a("end")
a("")
a("")
a("-- ==========================================================================")
a("-- Cap phat / thu hoi ban do trong be  (thay cho 3 ham engine cua ban Linux)")
a("-- ==========================================================================")
a("")
a("-- Ban Linux: PreApplyDungeonMap(nTpl, 0, 0) - dat truoc mot so ban sao.")
a("-- Ban JX1: be la TINH, ham nay chi don sach trang thai thua cua lan chay truoc")
a("-- (vi du may chu vua khoi dong lai giua chung mot dot).")
a("function PreApplyDungeonMap(nTpl, nUnused1, nUnused2)")
a("\tlocal tbPool = DUNGEON_POOL[nTpl]")
a("\tif not tbPool then")
a('\t\tprint("[DUNGEON] PreApplyDungeonMap: khuon "..nTpl.." chua khai be")')
a("\t\treturn 0")
a("\tend")
a("\tlocal i")
a("\tlocal nOk = 0")
a("\tfor i = 1, getn(tbPool) do")
a("\t\tlocal nMapId = tbPool[i]")
a("\t\tif SubWorldID2Idx(nMapId) >= 0 then")
a("\t\t\tDG_SetVar(nMapId, DG_V_BUSY, 0)")
a("\t\t\tDG_SetVar(nMapId, DG_V_COUNT, 0)")
a("\t\t\tDG_SetVar(nMapId, DG_V_TPL, nTpl)")
a("\t\t\tDG_SetVar(nMapId, DG_V_TYPE, 0)")
a("\t\t\tnOk = nOk + 1")
a("\t\telse")
a('\t\t\tprint("[DUNGEON] ban do be "..nMapId.." CHUA NAP - kiem MapList.ini va WorldSet_GameServer.ini")')
a("\t\tend")
a("\tend")
a('\tprint("[DUNGEON] be khuon "..nTpl..": "..nOk.."/"..getn(tbPool).." ban do san sang")')
a("\treturn nOk")
a("end")
a("")
a("-- Tra ve id ban do ranh trong be, hoac 0 neu het.")
a("function ApplyDungeonMap(nTpl)")
a("\tlocal tbPool = DUNGEON_POOL[nTpl]")
a("\tif not tbPool then")
a("\t\treturn 0")
a("\tend")
a("\tlocal i")
a("\tfor i = 1, getn(tbPool) do")
a("\t\tlocal nMapId = tbPool[i]")
a("\t\tif SubWorldID2Idx(nMapId) >= 0 and DG_GetVar(nMapId, DG_V_BUSY) == 0 then")
a("\t\t\tDG_SetVar(nMapId, DG_V_BUSY, 1)")
a("\t\t\tDG_SetVar(nMapId, DG_V_COUNT, 0)")
a("\t\t\tDG_SetVar(nMapId, DG_V_TPL, nTpl)")
a("\t\t\tDG_SetVar(nMapId, DG_V_SERIAL, DG_GetVar(nMapId, DG_V_SERIAL) + 1)")
a("\t\t\treturn nMapId")
a("\t\tend")
a("\tend")
a("\treturn 0")
a("end")
a("")
a("-- Chu y CHINH TA: ban Linux viet sai thanh 'Dungenon' (thieu chu). Giu nguyen")
a("-- ten do de kich ban goc goi duoc, va them mot ten viet dung lam bi danh.")
a("function ReturnDungenonMap(nTpl, nMapId)")
a("\tif not nMapId or nMapId <= 0 then")
a("\t\treturn 0")
a("\tend")
a("\tDG_SetVar(nMapId, DG_V_BUSY, 0)")
a("\tDG_SetVar(nMapId, DG_V_COUNT, 0)")
a("\tDG_SetVar(nMapId, DG_V_TYPE, 0)")
a("\treturn 1")
a("end")
a("")
a("function ReturnDungeonMap(nTpl, nMapId)")
a("\treturn ReturnDungenonMap(nTpl, nMapId)")
a("end")
a("")
a("-- Ban Linux con co ApplyDelDungeonMap (xoa han ban sao). Be tinh khong xoa duoc,")
a("-- nen anh xa ve thu hoi cho khoi vo kich ban nao lo goi.")
a("function ApplyDelDungeonMap(nTpl, nMapId)")
a("\treturn ReturnDungenonMap(nTpl, nMapId)")
a("end")
a("")
a("")
a("-- ==========================================================================")
a("-- Lop Dungeon (giu nguyen mat ngoai cua ban Linux de kich ban goc goi duoc)")
a("-- ==========================================================================")
a("DungeonList = {}")
a("DungeonType = {}")
a("DungeonTypeCount = {}")
a("Dungeon = {}")
a("")
a("function Dungeon:new_type(szKey)")
a("\tlocal tb = {}")
a("\tlocal k, v")
a("\tfor k, v in self do")
a("\t\ttb[k] = v")
a("\tend")
a("\ttb.szDungeonType = szKey")
a("\tDungeonType[szKey] = tb")
a("\treturn tb")
a("end")
a("")
a("function Dungeon:new(nMapId, nTemplateMapId, tbInitParam)")
a("\tif DungeonList[nMapId] then")
a("\t\tDungeonList[nMapId]:close()")
a("\tend")
a("\tlocal tb = {}")
a("\tlocal k, v")
a("\tfor k, v in self do")
a("\t\ttb[k] = v")
a("\tend")
a("\ttb.nTemplateMapId = nTemplateMapId")
a("\ttb.nMapId = nMapId")
a("\ttb.tbNpc = {}")
a("\tif SubWorldID2Idx(nMapId) < 0 then")
a("\t\treturn nil")
a("\tend")
a("\tDungeonTypeCount[self.szDungeonType] = (DungeonTypeCount[self.szDungeonType] or 0) + 1")
a("\tDungeonList[nMapId] = tb")
a("\t-- ban Linux goi tb:_init(unpack(tbInitParam)); Lua 4.0 cua JX1 khong co unpack")
a("\t-- nen truyen thang bang table (kich ban Viem De khong dung tham so nao).")
a("\tlocal bRet = tb:_init(tbInitParam)")
a("\tif not bRet then")
a("\t\ttb:free()")
a("\t\treturn nil")
a("\tend")
a("\treturn tb")
a("end")
a("")
a("function Dungeon:new_dungeon(nTemplateMapId, tbInitParam)")
a("\tlocal nMapId = ApplyDungeonMap(nTemplateMapId)")
a("\tif nMapId > 0 then")
a("\t\tlocal p = self:new(nMapId, nTemplateMapId, tbInitParam)")
a("\t\tif not p then")
a("\t\t\tReturnDungenonMap(nTemplateMapId, nMapId)")
a("\t\tend")
a("\t\treturn p")
a("\tend")
a("end")
a("")
a("function Dungeon:_init(tbParam)")
a("\treturn 1")
a("end")
a("")
a("function Dungeon:OnEnterMap()")
a("end")
a("")
a("function Dungeon:OnLeaveMap()")
a("end")
a("")
a("-- --- so nguoi trong phong: doc/ghi qua bien mission nen MOI TEP deu thay ---")
a("function Dungeon:GetCount()")
a("\treturn DG_GetVar(self.nMapId, DG_V_COUNT)")
a("end")
a("")
a("function Dungeon:AddCount(nDelta)")
a("\tlocal n = DG_GetVar(self.nMapId, DG_V_COUNT) + nDelta")
a("\tif n < 0 then")
a("\t\tn = 0")
a("\tend")
a("\tDG_SetVar(self.nMapId, DG_V_COUNT, n)")
a("\treturn n")
a("end")
a("")
a("-- --- NPC do pho ban sinh ra: nho lai de don sach luc dong ---")
a("function Dungeon:RememberNpc(nNpcIndex)")
a("\tif nNpcIndex and nNpcIndex > 0 then")
a("\t\ttinsert(self.tbNpc, nNpcIndex)")
a("\tend")
a("\treturn nNpcIndex")
a("end")
a("")
a("function Dungeon:ClearNpc()")
a("\tlocal i")
a("\tfor i = 1, getn(self.tbNpc) do")
a("\t\tif self.tbNpc[i] and self.tbNpc[i] > 0 then")
a("\t\t\tDelNpc(self.tbNpc[i])")
a("\t\tend")
a("\tend")
a("\tself.tbNpc = {}")
a("end")
a("")
a("function Dungeon:AddTimer(nFrame, fn, tbParam)")
a('\tlocal nTimerId = AddTimer(nFrame, "Dungeon:OnTime", self.nMapId)')
a("\tif nTimerId and nTimerId > 0 then")
a("\t\tself._timer_ = self._timer_ or {}")
a("\t\tself._timer_[nTimerId] = {fn, tbParam}")
a("\tend")
a("\treturn nTimerId")
a("end")
a("")
a("function Dungeon:OnTime(nMapId, nTimerId)")
a("\tlocal pDungeon = DungeonList[nMapId]")
a("\tif not pDungeon or not pDungeon._timer_ then")
a("\t\treturn 0, 0")
a("\tend")
a("\tlocal tb = pDungeon._timer_[nTimerId]")
a("\tif not tb then")
a("\t\treturn 0, 0")
a("\tend")
a("\tlocal nFrame = call(tb[1], tb[2])")
a("\tif nFrame and nFrame > 0 then")
a("\t\treturn nFrame, nMapId")
a("\tend")
a("\tif pDungeon._timer_ then")
a("\t\tpDungeon._timer_[nTimerId] = nil")
a("\tend")
a("\treturn 0, 0")
a("end")
a("")
a("function Dungeon:free()")
a("\tlocal szType = self.szDungeonType")
a("\tif DungeonTypeCount[szType] then")
a("\t\tDungeonTypeCount[szType] = DungeonTypeCount[szType] - 1")
a("\t\tif DungeonTypeCount[szType] <= 0 then")
a("\t\t\tDungeonTypeCount[szType] = nil")
a("\t\tend")
a("\tend")
a("\tif self._timer_ then")
a("\t\tlocal nTimerId, tb")
a("\t\tfor nTimerId, tb in self._timer_ do")
a("\t\t\tDelTimer(nTimerId)")
a("\t\tend")
a("\t\tself._timer_ = nil")
a("\tend")
a("\tself:ClearNpc()")
a("\tDungeonList[self.nMapId] = nil")
a("\tif self.nTemplateMapId then")
a("\t\tReturnDungenonMap(self.nTemplateMapId, self.nMapId)")
a("\tend")
a("end")
a("")
a("function Dungeon:close()")
a("\tif self.OnClose then")
a("\t\tself:OnClose()")
a("\tend")
a("\tself:free()")
a("end")
a("")
a("-- Ban Linux con co Dungeon:SetForbitItem (cam mang vat pham theo loai ban do).")
a("-- JX1 khong co he set_MapType/add_Item2Map, de rong cho kich ban goc goi khong vo.")
a("function Dungeon:SetForbitItem(nMapId)")
a("end")
a("")
a("-- Ban Linux: SubWorldName(nIdx) tra ten ban do. JX1 chua co ham engine nay,")
a("-- kich ban chi dung de in log go roi (player_death.lua:20).")
a("function SubWorldName(nIdxSubWorld)")
a('\treturn "map#"..nIdxSubWorld')
a("end")
a("")

noi_dung = "\r\n".join(L)

for goc in (SRV, GUONG):
    p = goc + DICH
    os.makedirs(os.path.dirname(p), exist_ok=True)
    io.open(p, "w", encoding="latin-1", newline="").write(noi_dung)
    print("da ghi %-6s %s  (%d dong)" % ("", p, len(L)))
