# -*- coding: utf-8 -*-
"""VIEM DE - buoc 6b: sinh LOP DUNG CHUNG TRANG THAI ban JX1.

Van de: ban Linux chay MOT state Lua chung nen bang `tbReady` dung chung duoc
giua 3 tep o 3 state khac nhau:
    npc\\yandibaozang_main.lua   doc nState, goi NewPartyId/AddPartyMember
    readymap\\ready.lua          dinh nghia tbReady, bo hen gio doi nState
    readymap\\readymap.lua       tru nMapCount khi dong phong
JX1 cho MOI TEP mot state rieng (`Include` = lua_dofile vao state cua tep goi,
ScriptFuns.cpp:1969) nen moi tep se om MOT BAN SAO RIENG -> khong bao gio thay nhau.

Cach lam: dua toan bo trang thai dung chung xuong KHO CUA ENGINE.

    tbReady.nState        -> bien mission 90 cua ban do NEO (852, khuon, khong ai vao)
    tbReady.nMaxPartyId   -> bien mission 91
    tbReady.nCurTime      -> bien mission 92
    tbReady.tbPlayer      -> AddMSPlayer(YDBZ_MISSION_READY, nPlayerIndex, nPartyId)
                             (chinh la co che ma ban goc DA DUNG cho pha danh tran,
                              ready.lua:214 AddMSPlayer(YDBZ_MISSION_MATCH,...))
    tbReady.nMapCount     -> dem co ban trong be pho ban (dungeon.lua DG_V_BUSY)
    tbReady.tbMapId       -> chinh la be pho ban

Sinh 1 tep: \\script\\missions\\yandibaozang\\readymap\\ydbz_share.lua
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bangtxt import uni2tcvn as V

SRV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
GUONG = r"D:\GAMEDEVNEW\serverscript_jx2\viemde"
DICH = r"\script\missions\yandibaozang\readymap\ydbz_share.lua"

L = []
a = L.append

a("-- ==========================================================================")
a("-- VIEM DE - LOP DUNG CHUNG TRANG THAI (ban JX1)")
a("-- SINH TU DONG boi ReverseTools\\viemde\\v10_gen_share.py - DUNG SUA TAY")
a("--")
a("-- Ban Linux giu hang doi bao danh trong bang Lua `tbReady` va dung chung duoc")
a("-- giua cac tep vi may chu do chay MOT state Lua. JX1 cho MOI TEP mot state")
a("-- rieng, nen o day moi thu dung chung deu nam trong KHO CUA ENGINE:")
a("--   * so lieu  -> bien mission cua ban do NEO (khuon 852, khong ai vao)")
a("--   * danh sach nguoi bao danh -> AddMSPlayer/GetNextPlayer, dung y het co che")
a("--     ma chinh ban goc dung cho pha danh tran (ready.lua:214)")
a("-- ==========================================================================")
a("")
a('Include("\\\\script\\\\missions\\\\basemission\\\\dungeon.lua")')
a("")
a("YDBZ_NEO_MAPID        = 852     -- ban do khuon, dung lam noi giu so lieu chung")
a("-- !! KHONG dung 50/51: ban Linux da danh 50 cho mission TRAN DANH va 51 cho")
a("-- mission phong cho cu (settings\task\missions.txt) - da khai dung nhu vay o JX1.")
a("-- Khe 60 chi la O CHUA NGUOI (khong can dong script trong missions.txt: engine")
a("-- doc GetString(id+1,2) tra rong thi khong chay script nao, van tao o binh thuong).")
a("YDBZ_MISSION_READY    = 60      -- mission giu danh sach nguoi dang bao danh")
a("YDBZ_RV_STATE         = 90      -- 0 chua mo, 1 dang bao danh, 2 chuan bi, 3 da bat dau")
a("YDBZ_RV_MAXPARTY      = 91      -- bo dem id to doi")
a("YDBZ_RV_CURTIME       = 92      -- so giay da troi qua trong pha bao danh")
a("")
a("-- Hai hang so nay GIU DUNG SO CUA BAN LINUX:")
a("--   200  = co TaskTemp \"dang trong mot hoat dong\" - JX1 dung chung cho 17 tinh nang")
a("--          (leaguematch/head.lua:519 chu thich ro: cam doi tran doanh). Bo soat id")
a("--          bao \"200 da bi dung\" la BAO DONG GIA: day la quy uoc dung chung, khong")
a("--          phai xung dot - doi so moi la lam sai khac ban goc.")
a("--   2618 = task dem so lan tham gia trong ngay (bo soat da xac nhan JX1 chua ai dung).")
a("YDBZ_TASKTEMP_TRONGTRAN = 200")
a("YDBZ_TASK_DEMNGAY       = 2618")
a("")
a("")
a("-- ---------------------------------------------------------------- so lieu")
a("function YDBZ_GetRV(nIdx)")
a("\treturn DG_GetVar(YDBZ_NEO_MAPID, nIdx)")
a("end")
a("")
a("function YDBZ_SetRV(nIdx, nValue)")
a("\treturn DG_SetVar(YDBZ_NEO_MAPID, nIdx, nValue)")
a("end")
a("")
a("-- Mo mission tren ban do neo (bay #4: GetMissionV tra 0 ca khi mission chua ton")
a("-- tai, nen phai hoi IsMission chu khong hoi gia tri).")
a("function YDBZ_MoMissionNeo()")
a("\tlocal nIdx = SubWorldID2Idx(YDBZ_NEO_MAPID)")
a("\tif nIdx < 0 then")
a('\t\tprint("[YDBZ] ban do neo "..YDBZ_NEO_MAPID.." CHUA NAP")')
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdx")
a("\tif IsMission(YDBZ_MISSION_READY) ~= 1 then")
a("\t\tOpenMission(YDBZ_MISSION_READY)")
a("\tend")
a("\tSubWorld = nOld")
a("\treturn 1")
a("end")
a("")
a("")
a("-- ------------------------------------------------- danh sach nguoi bao danh")
a("-- Ban Linux: tbReady.tbPlayer[szName] = nPartyId")
a("-- Ban JX1  : nguoi choi duoc ghi vao mission YDBZ_MISSION_READY, nhom = nPartyId")
a("function YDBZ_ThemNguoi(nPlayerIndex, nPartyId)")
a("\tif nPlayerIndex <= 0 then")
a("\t\treturn 0")
a("\tend")
a("\tYDBZ_MoMissionNeo()")
a("\tlocal nIdx = SubWorldID2Idx(YDBZ_NEO_MAPID)")
a("\tif nIdx < 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdx")
a("\tAddMSPlayer(YDBZ_MISSION_READY, nPlayerIndex, nPartyId)")
a("\tSubWorld = nOld")
a("\tlocal nCu = PlayerIndex")
a("\tPlayerIndex = nPlayerIndex")
a("\tSetTask(YDBZ_TEAMS_TASKID, nPartyId)")
a("\tPlayerIndex = nCu")
a("\treturn 1")
a("end")
a("")
a("function YDBZ_BoNguoi(nPlayerIndex)")
a("\tif nPlayerIndex <= 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nIdx = SubWorldID2Idx(YDBZ_NEO_MAPID)")
a("\tif nIdx < 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdx")
a("\tDelMSPlayer(YDBZ_MISSION_READY, nPlayerIndex, 0)")
a("\tSubWorld = nOld")
a("\treturn 1")
a("end")
a("")
a("-- Tra ve bang {[nPartyId] = {chi so nguoi choi, ...}} - thay cho vong lap")
a("-- `for szName, nPartyId in self.tbPlayer` cua ban Linux (ready.lua:173).")
a("-- Bay #3: GetNextPlayer(id, idx, 0) coi 0 la TAT CA, con GetMSPlayerCount(id, 0)")
a("-- lai dem RIENG nhom 0 - nen o day chi dung GetNextPlayer voi nhom 0.")
a("function YDBZ_LayDanhSach()")
a("\tlocal tbParty = {}")
a("\tlocal nIdx = SubWorldID2Idx(YDBZ_NEO_MAPID)")
a("\tif nIdx < 0 then")
a("\t\treturn tbParty")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tlocal nCu = PlayerIndex")
a("\tSubWorld = nIdx")
a("\tlocal i = 0")
a("\tlocal p = 0")
a("\tlocal nVong = 0")
a("\twhile nVong < 500 do")
a("\t\tnVong = nVong + 1")
a("\t\ti, p = GetNextPlayer(YDBZ_MISSION_READY, i, 0)")
a("\t\tif p and p > 0 then")
a("\t\t\tPlayerIndex = p")
a("\t\t\tlocal nPartyId = GetTask(YDBZ_TEAMS_TASKID)")
a("\t\t\ttbParty[nPartyId] = tbParty[nPartyId] or {}")
a("\t\t\ttinsert(tbParty[nPartyId], p)")
a("\t\tend")
a("\t\tif not i or i <= 0 then")
a("\t\t\tbreak")
a("\t\tend")
a("\tend")
a("\tPlayerIndex = nCu")
a("\tSubWorld = nOld")
a("\treturn tbParty")
a("end")
a("")
a("function YDBZ_XoaDanhSach()")
a("\tlocal nIdx = SubWorldID2Idx(YDBZ_NEO_MAPID)")
a("\tif nIdx < 0 then")
a("\t\treturn 0")
a("\tend")
a("\tlocal nOld = SubWorld")
a("\tSubWorld = nIdx")
a("\tif IsMission(YDBZ_MISSION_READY) == 1 then")
a("\t\tCloseMission(YDBZ_MISSION_READY)")
a("\tend")
a("\tOpenMission(YDBZ_MISSION_READY)")
a("\tSubWorld = nOld")
a("\treturn 1")
a("end")
a("")
a("")
a("-- ------------------------------------------------------------- be phong cho")
a("-- Ban Linux: tbReady.nMapCount / tbReady.tbMapId")
a("-- Ban JX1  : suy thang tu co ban cua be pho ban")
a("function YDBZ_DemPhong()")
a("\tlocal tbPool = DUNGEON_POOL[YDBZ_NEO_MAPID]")
a("\tif not tbPool then")
a("\t\treturn 0")
a("\tend")
a("\tlocal n = 0")
a("\tlocal i")
a("\tfor i = 1, getn(tbPool) do")
a("\t\tif DG_GetVar(tbPool[i], DG_V_BUSY) ~= 0 then")
a("\t\t\tn = n + 1")
a("\t\tend")
a("\tend")
a("\treturn n")
a("end")
a("")
a("function YDBZ_MoiPhong(szMsg)")
a("\tlocal tbPool = DUNGEON_POOL[YDBZ_NEO_MAPID]")
a("\tif not tbPool then")
a("\t\treturn")
a("\tend")
a("\tlocal i")
a("\tfor i = 1, getn(tbPool) do")
a("\t\tif DG_GetVar(tbPool[i], DG_V_BUSY) ~= 0 then")
a("\t\t\tMsg2Map(tbPool[i], szMsg)")
a("\t\tend")
a("\tend")
a("end")
a("")
a("")
a("-- ---------------------------------------------------------------- id to doi")
a("function YDBZ_IdToDoiMoi()")
a("\tlocal n = YDBZ_GetRV(YDBZ_RV_MAXPARTY) + 1")
a("\tYDBZ_SetRV(YDBZ_RV_MAXPARTY, n)")
a("\treturn n")
a("end")
a("")

noi_dung = "\r\n".join(L)
for goc in (SRV, GUONG):
    p = goc + DICH
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tam = p + ".dangghi"
    with open(tam, "wb") as f:
        f.write(noi_dung.encode("latin-1"))
    os.replace(tam, p)
    print("da ghi %s  (%d dong)" % (p, len(L)))
