# -*- coding: utf-8 -*-
"""VIEM DE - buoc 6b-2a: sinh lai readymap\\ready.lua cho JX1.

Giu NGUYEN logic, thong diep, moc thoi gian va thuat toan chia doi cua ban Linux.
Chi thay LOP LUU TRU cua trang thai dung chung:

    tbReady.nState / nCurTime / nMaxPartyId  -> bien mission ban do neo (ydbz_share.lua)
    tbReady.tbPlayer[szName] = nPartyId      -> AddMSPlayer / GetNextPlayer
    tbReady.nMapCount / tbMapId              -> co ban cua be pho ban

Vi sao phai thay: JX1 cho MOI TEP mot state Lua rieng (`Include` = lua_dofile vao
state cua tep GOI, ScriptFuns.cpp:1969). Ban Linux chay mot state chung nen 3 tep
o 3 state khac nhau van thay chung mot bang `tbReady`; sang JX1 moi tep se om mot
ban sao rieng va khong bao gio thay nhau.

Khac biet co y so voi ban Linux (ghi ro de con doi chieu):
  * `tbParty` chua CHI SO NGUOI CHOI thay vi TEN. Ban Linux luu ten roi goi
    SearchPlayer(szName) de lay lai chi so; o day danh sach lay tu GetNextPlayer
    von da la chi so song, nen bo duoc mot vong tra nguoc.
  * bo `usepack/curpack`: he hen gio JX2 cua JX1 (KJx2League.cpp:1051) goi ham
    NGAY TRONG state cua tep da dat hen, khong can doi pack.
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bangtxt import uni2tcvn as V

SRV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
GUONG = r"D:\GAMEDEVNEW\serverscript_jx2\viemde"
DICH = r"\script\missions\yandibaozang\readymap\ready.lua"

L = []
a = L.append


def s(txt):
    a(V(txt))


s("-- ==========================================================================")
s("-- VIEM DE - PHA BAO DANH  (ban JX1)")
s("-- SINH TU DONG boi ReverseTools\\viemde\\v11_gen_ready.py - DUNG SUA TAY")
s("--")
s("-- Dich tu \\script\\missions\\yandibaozang\\readymap\\ready.lua cua ban Linux.")
s("-- Logic / thong diep / moc thoi gian / thuat toan chia doi GIU NGUYEN.")
s("-- Chi doi cho luu tru trang thai dung chung: xem ydbz_share.lua.")
s("-- ==========================================================================")
s("")
s('Include("\\\\script\\\\lib\\\\common.lua")')
s('Include("\\\\script\\\\activitysys\\\\functionlib.lua")')
s('Include("\\\\script\\\\missions\\\\basemission\\\\dungeon.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\head.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\include.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\readymap\\\\ydbz_share.lua")')
s('Include("\\\\script\\\\lib\\\\awardtemplet.lua")')
s('Include("\\\\script\\\\lib\\\\log.lua")')
s("")
s("tbReady = {}")
s("tbReady.nTemplateMapId = 852")
s("tbReady.nIntervalTime = 60")
s("tbReady.nReadyTime = 5*60")
s("")
s("tbReady.tbPos =")
s("{")
s("\t{1590,3195},")
s("\t{1590,3170},")
s("\t{1601,3184},")
s("}")
s("")
s("-- ---------------------------------------------------------------- vong doi")
s("function tbReady:Init()")
s("\tself:close()")
s("\tYDBZ_MoMissionNeo()")
s("\tYDBZ_XoaDanhSach()")
s("\tYDBZ_SetRV(YDBZ_RV_MAXPARTY, 0)")
s("\tYDBZ_SetRV(YDBZ_RV_CURTIME, 0)")
s("\tYDBZ_SetRV(YDBZ_RV_STATE, 1)")
s("\tPreApplyDungeonMap(self.nTemplateMapId, 0, 0)")
s('\tself._timer_ = AddTimer(self.nIntervalTime * 18, "tbReady:OnTime", 0)')
s("\treturn 1")
s("end")
s("")
s("function tbReady:close()")
s("\tif self.OnClose then")
s("\t\tself:OnClose()")
s("\tend")
s("\tif self._timer_ then")
s("\t\tDelTimer(self._timer_)")
s("\t\tself._timer_ = nil")
s("\tend")
s("end")
s("")
s("-- Ban Linux: Msg2Map cho tung ban do trong tbReady.tbMapId")
s("function tbReady:BroadCast(szMsg)")
s("\tYDBZ_MoiPhong(szMsg)")
s("end")
s("")
s("function tbReady:OnTime(nParam, nTimerId)")
s("\tlocal nState = YDBZ_GetRV(YDBZ_RV_STATE)")
s("\tlocal nCurTime = YDBZ_GetRV(YDBZ_RV_CURTIME) + self.nIntervalTime")
s("\tYDBZ_SetRV(YDBZ_RV_CURTIME, nCurTime)")
s("\tif nState == 1 then")
s("\t\tif nCurTime >= self.nReadyTime then")
s("\t\t\tYDBZ_SetRV(YDBZ_RV_STATE, 2)")
s('\t\t\tself:BroadCast(format("Th\u1eddi gian b\u00e1o danh v\u01b0\u1ee3t \u1ea3i b\u1ea3o t\u00e0ng vi\u00eam \u0111\u1ebf \u0111\u00e3 k\u1ebft th\u00fac, xin m\u1eddi c\u00e1c v\u00f5 l\u00e2m nh\u00e2n s\u1ef9 h\u00e3y chu\u1ea9n b\u1ecb l\u1ea7n cu\u1ed1i, c\u00f2n %s b\u1eaft \u0111\u1ea7u.", 30))')
s("\t\t\treturn 30*18, nParam")
s("\t\telse")
s('\t\t\tself:BroadCast(format("V\u01b0\u1ee3t \u1ea3i b\u1ea3o t\u00e0ng vi\u00eam \u0111\u1ebf c\u00f2n <color=yellow>%s ph\u00fat<color> k\u1ebft th\u00fac th\u1eddi gian b\u00e1o danh, h\u00e3y nhanh nhanh b\u00e1o danh.", floor((self.nReadyTime - nCurTime)/60)))')
s("\t\tend")
s("\telseif nState == 2 then")
s("\t\tYDBZ_SetRV(YDBZ_RV_STATE, 3)")
s("\t\tself:close()")
s("\t\treturn 0, nParam")
s("\tend")
s("\treturn self.nIntervalTime * 18, nParam")
s("end")
s("")
s("-- ------------------------------------------------------- danh sach bao danh")
s("function tbReady:NewPartyId()")
s("\treturn YDBZ_IdToDoiMoi()")
s("end")
s("")
s("-- Ban Linux nhan TEN; o JX1 nhan CHI SO NGUOI CHOI (danh sach lay tu engine)")
s("function tbReady:AddPartyMember(nPartyId, nPlayerIndex)")
s("\treturn YDBZ_ThemNguoi(nPlayerIndex, nPartyId)")
s("end")
s("")
s("function tbReady:DelPartyMember(nPlayerIndex)")
s("\treturn YDBZ_BoNguoi(nPlayerIndex)")
s("end")
s("")
s("-- ------------------------------------------------------------ chia ban do")
s("-- GIU NGUYEN thuat toan cua ban Linux (ready.lua:117-150)")
s("function tbReady:Group(tbParty)")
s("\tlocal nGroupCount = getn(tbParty)")
s("\ttbParty = lib:ShuffleTable(tbParty, 1, nGroupCount)")
s("\tlocal tbMapGroup = {}")
s("\tif nGroupCount == 1 then")
s("\t\treturn tbMapGroup")
s("\tend")
s("\tif 1 < nGroupCount and nGroupCount <= 3 then")
s("\t\ttbMapGroup[1] = {}")
s("\t\ttbMapGroup[1] = tbParty")
s("\telseif nGroupCount > 3 and mod(nGroupCount, 3) == 0 then")
s("\t\tlocal nMapCount = floor(nGroupCount / 3)")
s("\t\tfor i = 1, nMapCount do")
s("\t\t\ttbMapGroup[i] = {}")
s("\t\tend")
s("\t\tfor i = 1, nGroupCount do")
s("\t\t\ttinsert(tbMapGroup[floor((i-1) / 3) + 1], tbParty[i])")
s("\t\tend")
s("\telseif nGroupCount > 3 and mod(nGroupCount, 3) ~= 0 then")
s("\t\tlocal nSpGroup = 2 * (3 - mod(nGroupCount, 3))")
s("\t\tlocal nMapCount = floor(nGroupCount / 3) + 1")
s("\t\tfor i = 1, nMapCount do")
s("\t\t\ttbMapGroup[i] = {}")
s("\t\tend")
s("\t\tfor i = 1, nGroupCount - nSpGroup do")
s("\t\t\ttinsert(tbMapGroup[floor((i-1) / 3) + 1], tbParty[i])")
s("\t\tend")
s("\t\tlocal offset = floor((nGroupCount - nSpGroup - 1)/3) + 2")
s("\t\tfor i = nGroupCount - nSpGroup + 1, nGroupCount do")
s("\t\t\ttinsert(tbMapGroup[floor((i - nGroupCount + nSpGroup - 1)/ 2) + offset], tbParty[i])")
s("\t\tend")
s("\tend")
s("\treturn tbMapGroup")
s("end")
s("")
s("function tbReady:ShowGroup(tbMapGroup)")
s("\tfor i = 1, getn(tbMapGroup) do")
s('\t\tYDBZ_debug("group "..i.." co "..getn(tbMapGroup[i]).." chi doi")')
s("\tend")
s("end")
s("")
s("-- ------------------------------------------------------------- ket thuc pha")
s("function tbReady:OnClose()")
s("\tlocal tbMaplist = {}")
s("\tfor i = 1, getn(YDBZ_MAP_MAP) do")
s("\t\tif SubWorldID2Idx(YDBZ_MAP_MAP[i]) >= 0 then")
s("\t\t\ttinsert(tbMaplist, YDBZ_MAP_MAP[i])")
s("\t\tend")
s("\tend")
s("\t-- ban Linux: duyet self.tbPlayer (bang Lua). Ban JX1: lay tu engine.")
s("\tlocal tbPartyMap = YDBZ_LayDanhSach()")
s("\tYDBZ_XoaDanhSach()")
s("\tlocal tbParty = {}")
s("\tlocal nPartyId, v")
s("\tfor nPartyId, v in tbPartyMap do")
s("\t\ttinsert(tbParty, v)")
s("\tend")
s("\tif getn(tbParty) == 0 then")
s("\t\treturn")
s("\tend")
s("\tlocal nMapCount = getn(tbMaplist)")
s("\tlocal tbMapGroup = self:Group(tbParty)")
s("\tself:ShowGroup(tbMapGroup)")
s("\tif getn(tbMapGroup) == 0 then")
s("\t\tself:KickOutGroup(tbParty)")
s("\t\treturn")
s("\tend")
s("\tfor i = 1, getn(tbMapGroup) do")
s("\t\tif i <= nMapCount then")
s("\t\t\tself:InitMatchMission(tbMaplist[i], tbMapGroup[i])")
s("\t\tend")
s("\tend")
s("\tfor i = 1, getn(tbMapGroup) do")
s("\t\tif i <= nMapCount then")
s("\t\t\tself:ToMatch(tbMaplist[i], tbMapGroup[i])")
s("\t\telse")
s("\t\t\tself:KickOutGroup(tbMapGroup[i])")
s("\t\tend")
s("\tend")
s("end")
s("")
s("function tbReady:ToMatch(nMapId, tbGroup)")
s("\tlocal nMapIndex = SubWorldID2Idx(nMapId)")
s("\tif nMapIndex < 0 then")
s("\t\treturn")
s("\tend")
s("\tfor i = 1, getn(tbGroup) do")
s("\t\tlocal tbParty = tbGroup[i]")
s("\t\tlocal nDoiTruong = tbParty[1]")
s("\t\tif nDoiTruong and nDoiTruong > 0 then")
s("\t\t\tlocal nCu = PlayerIndex")
s("\t\t\tPlayerIndex = nDoiTruong")
s("\t\t\tlocal szTen = GetName()")
s("\t\t\tPlayerIndex = nCu")
s("\t\t\tlib:DoFunInWorld(nMapIndex, SetMissionS, YDBZ_TEAM_NAME[i], szTen)")
s("\t\tend")
s("\t\tfor j = 1, getn(tbParty) do")
s("\t\t\tlocal nPlayerIndex = tbParty[j]")
s("\t\t\tif nPlayerIndex > 0 then")
s("\t\t\t\tlib:DoFunInWorld(nMapIndex, AddMSPlayer, YDBZ_MISSION_MATCH, nPlayerIndex, i)")
s("\t\t\t\tCallPlayerFunction(nPlayerIndex, self.PlayerEnterMatch, self, i, nMapId)")
s("\t\t\tend")
s("\t\tend")
s("\tend")
s('\tMsg2Map(nMapId, format("khu v\u1ef1c \u0111\u00f3 c\u00f3 Kho B\u00e1u Vi\u00eam \u0110\u1ebf %d chi \u0111\u1ed9i, \u0111\u1ea1i hi\u1ec7p ph\u1ea3i c\u1ed1 g\u1eafng nh\u00e9!!!", getn(tbGroup)))')
s("end")
s("")
s("function tbReady:PlayerEnterMatch(nCamp, nMapId)")
s("\tNewWorld(nMapId, floor(YDBZ_BOAT_POS[nCamp][1]/32), floor(YDBZ_BOAT_POS[nCamp][2]/32))")
s("\tlocal nCountState = GetTask(YDBZ_TASK_DEMNGAY)")
s('\tlocal nCurDate = tonumber(GetLocalDate("%y%m%d"))')
s("\tif floor(nCountState/256) ~= nCurDate then")
s("\t\tnCountState = nCurDate * 256")
s("\t\tSetTask(YDBZ_TASK_DEMNGAY, nCountState)")
s("\tend")
s("\tSetTask(YDBZ_TASK_DEMNGAY, nCountState + 1)")
s("\tYDBZ_UpdateTask()")
s("\tif YDBZ_sdl_getTaskByte(YDBZ_ITEM_YANDILING,1,1) ~= 1 then")
s("\t\tYDBZ_sdl_addTaskByte(YDBZ_PLAY_LIMIT_COUNT,2,1)")
s("\t\tYDBZ_sdl_addTaskByte(YDBZ_PLAY_LIMIT_COUNT,4,1)")
s("\tend")
s("\tSetTask(YDBZ_TEAMS_TASKID,0)")
s("\tSetTempRevPos(nMapId, YDBZ_BOAT_POS[nCamp][1], YDBZ_BOAT_POS[nCamp][2])")
s("\tYDBZ_sdl_setTaskByte(YDBZ_ITEM_YANDILING,2, nCamp)")
s("\tForbitTrade(0)")
s("\tLeaveTeam()")
s("\tSetTmpCamp(nCamp);")
s("\tSetFightState(1);")
s("\tSetLogoutRV(1);")
s("\tSetPunish(0);")
s("\tSetCreateTeam(0);")
s("\tSetPKFlag(1)")
s("\tForbidChangePK(1);")
s("\tSetDeathScript(YDBZ_SCRIPT_PLAYER_DEATH);")
s("\tDisabledUseTownP(1)")
s("\tForbidEnmity(1)")
s("\tSetTaskTemp(YDBZ_TASKTEMP_TRONGTRAN,1)")
s("\tSetDeathType(-1)")
s('\tEventSys:GetType("YanDiBaoZang"):OnPlayerEvent("OnEnter", PlayerIndex)')
s('\tG_ACTIVITY:OnMessage("SignUpYDBZ", PlayerIndex)')
s("end")
s("")
s("-- --------------------------------------------------------------- day ra ngoai")
s("function tbReady:KickOutGroup(tbGroup)")
s("\tfor i = 1, getn(tbGroup) do")
s("\t\tlocal tbParty = tbGroup[i]")
s("\t\tlocal nMapId, nX, nY = self:GetSignUpPos()")
s("\t\tif nMapId then")
s("\t\t\tfor j = 1, getn(tbParty) do")
s("\t\t\t\tlocal nPlayerIndex = tbParty[j]")
s("\t\t\t\tif nPlayerIndex > 0 then")
s("\t\t\t\t\tCallPlayerFunction(nPlayerIndex, self.KickOut, self, nMapId, nX, nY)")
s("\t\t\t\tend")
s("\t\t\tend")
s("\t\tend")
s("\tend")
s("end")
s("")
s("function tbReady:GiveItem(tbItem)")
s("\tif CalcFreeItemCellCount() >= tbItem.nCount then")
s('\t\ttbAwardTemplet:Give(tbItem, 1, {"yandibaozang", "kick out give item"})')
s("\telse")
s('\t\ttbLog:PlayerActionLog("yandibaozang", "kick out give item fail", tbItem.nCount, tbItem.tbProp[1], tbItem.tbProp[2], tbItem.tbProp[3], tbItem.tbProp[4])')
s("\tend")
s("end")
s("")
s("function tbReady:KickOut(nMapId, nPosX, nPosY)")
s("\tlocal tbItem = {}")
s("\tif YDBZ_sdl_getTaskByte(YDBZ_ITEM_YANDILING,1,1) == 1 then")
s("\t\ttbItem.tbProp={YDBZ_LIMIT_DOUBEL_ITEM[1][1], YDBZ_LIMIT_DOUBEL_ITEM[1][2], YDBZ_LIMIT_DOUBEL_ITEM[1][3], 1, 0, 0}")
s("\t\ttbItem.nCount = YDBZ_LIMIT_DOUBEL_ITEM[2]")
s("\telse")
s("\t\ttbItem.tbProp={YDBZ_LIMIT_ITEM[1][1], YDBZ_LIMIT_ITEM[1][2], YDBZ_LIMIT_ITEM[1][3], 1, 0, 0}")
s("\t\ttbItem.nCount = YDBZ_LIMIT_ITEM[2]")
s("\tend")
s("\tself:GiveItem(tbItem)")
s("\tNewWorld(nMapId, nPosX, nPosY)")
s("end")
s("")
s("function tbReady:GetSignUpPos()")
s("\tlocal tbPos =")
s("\t{")
s("\t\t{37,1714,3173},")
s("\t\t{37,1642,3145},")
s("\t\t{37,1622,3019},")
s("\t\t{37,1857,2968},")
s("\t}")
s("\tlocal nMapIndex = SubWorldID2Idx(37)")
s("\tif nMapIndex >= 0 then")
s("\t\tlocal nIdx = random(1, getn(tbPos))")
s("\t\treturn tbPos[nIdx][1], tbPos[nIdx][2], tbPos[nIdx][3]")
s("\tend")
s("end")
s("")
s("function tbReady:InitMatchMission(nMapId, tbGroup)")
s("\tlocal nMapIndex = SubWorldID2Idx(nMapId)")
s("\tif nMapIndex < 0 then")
s("\t\treturn")
s("\tend")
s("\tlocal nSignMapId, nX, nY = self:GetSignUpPos()")
s("\tif not nSignMapId then")
s("\t\treturn")
s("\tend")
s("\tlib:DoFunInWorld(nMapIndex, OpenMission, YDBZ_MISSION_MATCH)")
s("\tlib:DoFunInWorld(nMapIndex, SetMissionV, YDBZ_SIGNUP_WORLD, nSignMapId)")
s("\tlib:DoFunInWorld(nMapIndex, SetMissionV, YDBZ_SIGNUP_POSX, nX)")
s("\tlib:DoFunInWorld(nMapIndex, SetMissionV, YDBZ_SIGNUP_POSY, nY)")
s("\tlib:DoFunInWorld(nMapIndex, SetMissionV, YDBZ_TEAM_COUNT, getn(tbGroup))")
s("\tlib:DoFunInWorld(nMapIndex, SetMissionV, YDBZ_TEAM_SUM, getn(tbGroup))")
s("end")
s("")

noi_dung = "\r\n".join(L)
for goc in (SRV, GUONG):
    p = goc + DICH
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tam = p + ".dangghi"
    with open(tam, "wb") as f:
        f.write(noi_dung.encode("latin-1"))
    os.replace(tam, p)
    print("da ghi %s  (%d dong)" % (p, len(L)))
