# -*- coding: utf-8 -*-
"""VIEM DE - buoc 6b-2c: sinh lai npc\\yandibaozang_main.lua (NPC Binh Binh co nuong).

Giu nguyen logic/thong diep cua ban Linux. Chi doi cho doc-ghi trang thai dung chung
(tbReady.nState / NewPartyId / AddPartyMember / nMapCount) sang ydbz_share.lua,
va truyen CHI SO NGUOI CHOI thay vi TEN (xem ghi chu o v11_gen_ready.py).
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bangtxt import uni2tcvn
# 🔴 BAY DA DINH 26/08: ma hoa HAI LAN.
# `V(...)` long ben trong roi ham bao ngoai lai ma hoa lan nua -> byte TCVN3 (vd 0xB8)
# bi dua vao unicode_to_tcvn3_bytes lan hai, khong khop bang nao va BI BO -> chu Viet
# rung het dau ("Cach choi vuot ai moi" -> "Cch chi vt i mii").
# Cach chan: V() o day la KHONG LAM GI; chi ham bao ngoai (s()/r()) moi ma hoa, DUNG MOT LAN.
def V(x):
    return x


SRV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
GUONG = r"D:\GAMEDEVNEW\serverscript_jx2\viemde"
DICH = r"\script\missions\yandibaozang\npc\yandibaozang_main.lua"

L = []


def s(txt):
    L.append(uni2tcvn(txt))


s("-- ==========================================================================")
s("-- VIEM DE - NPC BAO DANH  (ban JX1)")
s("-- SINH TU DONG boi ReverseTools\\viemde\\v13_gen_mainnpc.py - DUNG SUA TAY")
s("-- Dich tu \\script\\missions\\yandibaozang\\npc\\yandibaozang_main.lua ban Linux.")
s("-- ==========================================================================")
s("")
s('Include("\\\\script\\\\lib\\\\common.lua")')
s('Include("\\\\script\\\\dailogsys\\\\dailogsay.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\head.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\include.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\readymap\\\\ydbz_share.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\readymap\\\\ready.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\readymap\\\\readymap.lua")')
s('Include("\\\\script\\\\missions\\\\yandibaozang\\\\readymap\\\\include.lua")')
s('Include("\\\\script\\\\lib\\\\log.lua")')
s("")
s("function main()")
s('\tlocal szTitle = "%s"' % V("<npc>Cách chơi vượt ải mới, nội dung mới, boss mới, bản đồ mới, vô vàn kỳ trân dị bảo, rất thích hợp các trang bị hoàng kim của môn phái chỉ có tại bảo tàng viêm đế. Các hạ đã chuẩn bị chưa?"))
s("\tlocal tbOpt =")
s("\t{")
s('\t\t{"%s", YDBZ_view_player},' % V("Xem tình hình tổ đội"))
s('\t\t{"%s", YDBZ_about},' % V("Nguồn gốc bảo tàng viêm đế"))
s('\t\t{"%s"},' % V(" Nhân tiện ghé qua thôi"))
s("\t}")
s("\tif YDBZ_GetRV(YDBZ_RV_STATE) == 1 then")
s('\t\ttinsert(tbOpt, 1, {"%s", YDBZ_want_play})' % V("Báo danh tham gia"))
s("\tend")
s("\tCreateNewSayEx(szTitle, tbOpt)")
s("end")
s("")
s("function YDBZ_PlayerCheck()")
s("\tif GetCamp() == 0 then")
s('\t\treturn nil, "%s"' % V("Thành viên trong tổ đội có người chưa gia nhập môn phái, không thể tham gia hoạt động."))
s("\tend")
s("\tif (GetLevel() < YDBZ_LIMIT_PLAYER_LEVEL) then")
s('\t\treturn nil, format("%s", GetName(), YDBZ_LIMIT_PLAYER_LEVEL)' % V("Trong đội ngũ người chơi %s đẳng cấp không đạt %d, không thể tham gia hoạt động."))
s("\tend")
s("\tlocal ncount, ndaycount = YDBZ_UpdateTask()")
s("\tlocal nDoubleItemCount = CalcEquiproomItemCount(YDBZ_LIMIT_DOUBEL_ITEM[1][1],YDBZ_LIMIT_DOUBEL_ITEM[1][2],YDBZ_LIMIT_DOUBEL_ITEM[1][3],-1)")
s("\tlocal nItemCount = CalcEquiproomItemCount(YDBZ_LIMIT_ITEM[1][1],YDBZ_LIMIT_ITEM[1][2],YDBZ_LIMIT_ITEM[1][3],-1)")
s("\tif nDoubleItemCount < YDBZ_LIMIT_DOUBEL_ITEM[2] then")
s("\t\tif ncount >= YDBZ_LIMIT_WEEK_COUNT then")
s('\t\t\treturn nil, format("%s", GetName())' % V("trong đội ngũ người chơi %s đã đến mức giới hạn tham gia trong tuần."))
s("\t\tend")
s("\t\tif ndaycount >= YDBZ_LIMIT_DAY_COUNT then")
s('\t\t\treturn nil, format("%s", GetName())' % V("trong đội ngũ người chơi %s đã đến mức giới hạn tham gia trong ngày."))
s("\t\tend")
s("\telse")
s("\t\treturn 1")
s("\tend")
s("\tif nItemCount < YDBZ_LIMIT_ITEM[2] then")
s('\t\treturn nil, format("%s", GetName(), YDBZ_LIMIT_ITEM[3])' % V("%s người chơi không mang theo %s."))
s("\tend")
s("\tYDBZ_sdl_setTaskByte(YDBZ_ITEM_YANDILING,1,0)")
s("\tYDBZ_sdl_setTaskByte(YDBZ_ITEM_YANDILING,2,0)")
s("\treturn 1")
s("end")
s("")
s("function YDBZ_view_player()")
s("\tif (GetTeamSize() < YDBZ_TEAM_COUNT_LIMIT or GetTeamSize() > YDBZ_TEAM_COUNT_MAXLIMIT) then")
s('\t\tlocal szTitle = "%s"..YDBZ_TEAM_COUNT_LIMIT.."%s"..YDBZ_TEAM_COUNT_MAXLIMIT.."%s"'
  % (V("<npc>Tổ đội tham gia bảo tang viêm đế cần ít nhất <color=red>"),
     V("<color> người và không thể vượt quá <color=red>"),
     V("<color>. Trước mắt số người trong tổ đội không phù hợp yêu cầu.")))
s("\t\tlocal tbOpt =")
s("\t\t{")
s('\t\t\t{"%s"}' % V(" Biết rồi!"))
s("\t\t}")
s("\t\tCreateNewSayEx(szTitle, tbOpt)")
s("\t\treturn")
s("\tend")
s("\tif YDBZ_PartyCheck() == 1 then")
s('\t\tTalk(1, "", "%s")' % V("Tổ đội của các hạ phù hợp với điều kiện tiến vào bảo tàng viêm đế"))
s("\tend")
s("end")
s("")
s("function YDBZ_PartyCheck()")
s("\tlocal flag = nil")
s("\tfor i = 1, GetTeamSize() do")
s("\t\tlocal nPlayerIndex = GetTeamMember(i)")
s("\t\tif nPlayerIndex > 0 then")
s("\t\t\tlocal ok, err = CallPlayerFunction(nPlayerIndex, YDBZ_PlayerCheck)")
s("\t\t\tif ok ~= 1 then")
s("\t\t\t\tMsg2Player(err)")
s("\t\t\t\tflag = 1")
s("\t\t\tend")
s("\t\tend")
s("\tend")
s("\tif flag == 1 then")
s("\t\treturn")
s("\telse")
s("\t\treturn 1")
s("\tend")
s("end")
s("")
s("function YDBZ_PlayerConsume()")
s("\tlocal nDoubleItemCount = CalcEquiproomItemCount(YDBZ_LIMIT_DOUBEL_ITEM[1][1],YDBZ_LIMIT_DOUBEL_ITEM[1][2],YDBZ_LIMIT_DOUBEL_ITEM[1][3],-1)")
s("\tlocal nItemCount = CalcEquiproomItemCount(YDBZ_LIMIT_ITEM[1][1],YDBZ_LIMIT_ITEM[1][2],YDBZ_LIMIT_ITEM[1][3],-1)")
s("\tif nDoubleItemCount >= YDBZ_LIMIT_DOUBEL_ITEM[2] then")
s("\t\tif ConsumeEquiproomItem(YDBZ_LIMIT_DOUBEL_ITEM[2], YDBZ_LIMIT_DOUBEL_ITEM[1][1],YDBZ_LIMIT_DOUBEL_ITEM[1][2],YDBZ_LIMIT_DOUBEL_ITEM[1][3],-1) == 1 then")
s("\t\t\tYDBZ_sdl_setTaskByte(YDBZ_ITEM_YANDILING,1,1)")
s("\t\t\tAddSkillState(461,1, 1,30*60*18,1)")
s("\t\t\tSetTask(YDBZ_ITEM_YANDILING_SUM,(GetTask(YDBZ_ITEM_YANDILING_SUM)+1))")
s('\t\t\ttbLog:PlayerActionLog("TinhNangKey","BaoDanhViemDe_SDViemDeLenh")')
s("\t\telse")
s('\t\t\ttbLog:PlayerActionLog("yandibaozang","consume error", "SDViemDeLenh", nDoubleItemCount)')
s("\t\tend")
s("\t\treturn 1")
s("\tend")
s("\tif nItemCount >= YDBZ_LIMIT_ITEM[2] then")
s("\t\tif ConsumeEquiproomItem(YDBZ_LIMIT_ITEM[2], YDBZ_LIMIT_ITEM[1][1],YDBZ_LIMIT_ITEM[1][2],YDBZ_LIMIT_ITEM[1][3],-1) == 1 then")
s('\t\t\ttbLog:PlayerActionLog("TinhNangKey","BaoDanhViemDe_SDAnhHungThiep")')
s("\t\telse")
s('\t\t\ttbLog:PlayerActionLog("yandibaozang","consume error", "SDAnhHungThiep", nItemCount)')
s("\t\tend")
s("\t\treturn 1")
s("\tend")
s('\ttbLog:PlayerActionLog("yandibaozang","consume error")')
s("\treturn nil")
s("end")
s("")
s("function YDBZ_PartyConsume()")
s("\tfor i = 1, GetTeamSize() do")
s("\t\tlocal nPlayerIndex = GetTeamMember(i)")
s("\t\tif nPlayerIndex > 0 then")
s("\t\t\tif CallPlayerFunction(nPlayerIndex, YDBZ_PlayerConsume) ~= 1 then")
s("\t\t\t\treturn nil")
s("\t\t\tend")
s("\t\tend")
s("\tend")
s("\treturn 1")
s("end")
s("")
s("function YDBZ_want_play()")
s("\tif YDBZ_GetRV(YDBZ_RV_STATE) ~= 1 then")
s('\t\tTalk(1, "", "%s")' % V("xin lỗi, vẫn chưa đến thời gian báo danh."))
s("\t\treturn")
s("\tend")
s("\tif (IsCaptain() ~= 1) then")
s('\t\tTalk(1, "", "%s")' % V("Tham gia hoạt động vượt ải viêm đế bảo tàng cần phải do đội trưởng báo danh mới vào được."))
s("\t\treturn")
s("\tend")
s("\tif (GetTeamSize() < YDBZ_TEAM_COUNT_LIMIT or GetTeamSize() > YDBZ_TEAM_COUNT_MAXLIMIT) then")
s('\t\tTalk(1, "", "%s"..YDBZ_TEAM_COUNT_LIMIT.."%s"..YDBZ_TEAM_COUNT_MAXLIMIT.."%s")'
  % (V("Tổ đội tham gia bảo tang viêm đế cần ít nhất <color=red>"),
     V("<color> người và không thể vượt quá <color=red>"),
     V("<color>. Trước mắt số người trong tổ đội không phù hợp yêu cầu.")))
s("\t\treturn 1")
s("\tend")
s("\tif YDBZ_PartyCheck() ~= 1 then")
s("\t\treturn")
s("\tend")
s("")
s("\tlocal nMapId = ReadyMap:GetFreeMap()")
s("\tif nMapId > 0 then")
s("\t\tif YDBZ_PartyConsume() ~= 1 then")
s('\t\t\tMsg2Player("%s")' % V("trạng thái bất thường, xin hãy liên lạc với bộ phận chăm sóc khách hàng."))
s("\t\t\treturn")
s("\t\tend")
s("\t\tlocal nPartyId = YDBZ_IdToDoiMoi()")
s("\t\tlocal nIdx = random(1, getn(tbReady.tbPos))")
s("\t\tlocal nPosX = tbReady.tbPos[nIdx][1]")
s("\t\tlocal nPosY = tbReady.tbPos[nIdx][2]")
s("")
s("\t\tlocal tbTeamMember = {}")
s("\t\tfor i = 1, GetTeamSize() do")
s("\t\t\ttbTeamMember[i] = GetTeamMember(i)")
s("\t\tend")
s("")
s("\t\tfor i = 1, getn(tbTeamMember) do")
s("\t\t\tlocal nPlayerIndex = tbTeamMember[i]")
s("\t\t\tif nPlayerIndex > 0 then")
s("\t\t\t\tYDBZ_ThemNguoi(nPlayerIndex, nPartyId)")
s("\t\t\t\tCallPlayerFunction(nPlayerIndex, NewWorld, nMapId, nPosX, nPosY)")
s("\t\t\tend")
s("\t\tend")
s("\telse")
s('\t\tTalk(1, "", "%s")' % V("xin lỗi, hiện tại khu vực này không có nhiệm vụ Kho Báu Viêm Đế. Hãy đợi đến lúc có thì quay lại tham gia nhé.~"))
s("\tend")
s("end")
s("")
s("function YDBZ_about()")
s('\tSay(format("%s", "%s"),0)'
  % (V("Cách chơi vượt ải mới, nội dung mới, boss mới, bản đồ mới, vô vàn kỳ trân dị bảo, rất thích hợp các trang bị hoàng kim của môn phái chỉ có tại bảo tàng viêm đế! <enter>Mỗi ngày %s, hãy đến trước 5 phút để báo danh ở Bình Bình cô nương."),
     "8:30, 9:30, 10:30, 12:30, 14:30, 16:30, 20:30, 22:30"))
s("end")
s("")
s("-- Engine JX1 goi OnRevive cho MOI NPC co script chet (bay #6) - de rong cho khoi")
s("-- spam ScriptError moi nhip.")
s("function OnRevive()")
s("end")
s("")

noi_dung = "\r\n".join(L)
for goc in (SRV, GUONG):
    p = goc + DICH
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tam = p + ".dangghi"
    with open(tam, "wb") as f:
        f.write(noi_dung.encode("latin-1"))
    os.replace(tam, p)
print("da ghi yandibaozang_main.lua  (%d dong)" % len(L))
