# -*- coding: utf-8 -*-
r"""[PETSYS 30/08] Logic thuoc tinh trang bi + duc lai theo BANG GOC:
- Mac vao: roll 3 gia tri trong khoang {min..max} cua tung thuoc tinh,
  luu o 5170 + (slot-1)*3 .. +2
- Duc lai (nut "Duc lai" -> op 10 -> chon mon): TIEU HAO 1 Ket Tinh Dong
  Hanh (item goc 4927), roll lai 3 gia tri, hien CU va MOI, cho chon
  "Giu lai" hay "Tu bo" (dung khuon cua so goc 720a151f).
- C: doc 30 o nay + ap len NPC pet bang KMagicAttrib khi goi ra.
"""
import io
import sys

sys.path.insert(0, r"C:\Users\nguye\.claude\skills\swordonline-dev\scripts")
from vn_edit import vn  # noqa: E402

CR = chr(13)
BS = chr(92)
SV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"

noi = "\n".join([
    'Include("' + BS * 2 + 'script' + BS * 2 + 'petsys' + BS * 2 + 'head.lua")',
    'Include("' + BS * 2 + 'script' + BS * 2 + 'petsys' + BS * 2 + 'lang.lua")',
    'Include("' + BS * 2 + 'script' + BS * 2 + 'petsys' + BS * 2 + 'petequip_def.lua")',
    "",
    "-- [PETSYS 30/08] TRANG BI DONG HANH - port theo bang goc VLTK.",
    "",
    "-- roll 3 gia tri thuoc tinh cua mon (theo khoang min..max bang goc)",
    "function PetEquip_Roll(nId, nSlot)",
    "\tlocal tb = PETEQUIP_DEF[nId]",
    "\tif not tb then",
    "\t\treturn",
    "\tend",
    "\tlocal i",
    "\tfor i = 1, 3 do",
    "\t\tlocal a = tb.tbAttrib[i]",
    "\t\tlocal nVal = 0",
    "\t\tif a then",
    "\t\t\tnVal = random(a[2], a[3])",
    "\t\tend",
    "\t\tSetTask(PETEQUIP_O_ATTRIB + (nSlot - 1) * 3 + i - 1, nVal)",
    "\tend",
    "end",
    "",
    "function PetEquip_CapNhatBo()",
    "\tlocal tbDem = {}",
    "\tlocal i",
    "\tfor i = 0, PETEQUIP_O_SO - 1 do",
    "\t\tlocal nId = GetTask(PETEQUIP_O_DAU + i)",
    "\t\tlocal tb = PETEQUIP_DEF[nId]",
    "\t\tif tb then",
    "\t\t\ttbDem[tb.nSuit] = (tbDem[tb.nSuit] or 0) + 1",
    "\t\tend",
    "\tend",
    "\tlocal nBoTot = -1",
    "\tlocal nSoTot = 0",
    "\tfor k, v in tbDem do",
    "\t\tif v > nSoTot then",
    "\t\t\tnSoTot = v",
    "\t\t\tnBoTot = k",
    "\t\tend",
    "\tend",
    "\tif nBoTot < 0 then",
    "\t\tSetTask(PETEQUIP_O_BOCOUNT, 0)",
    "\telse",
    "\t\tSetTask(PETEQUIP_O_BOCOUNT, nBoTot * 100 + nSoTot)",
    "\tend",
    "\treturn nBoTot, nSoTot",
    "end",
    "",
    "-- dung item trang bi = DEO vao dung o",
    "function main(nItemIndex)",
    "\tif PET_IsCreate() ~= 1 then",
    '\t\tTalk(1, "", "' + vn("Ngươi chưa có bạn đồng hành") + '")',
    "\t\treturn 1",
    "\tend",
    "\tlocal nG, nD, nP = GetItemProp(nItemIndex)",
    "\tlocal tb = PETEQUIP_DEF[nP]",
    "\tif not tb then",
    "\t\treturn 1",
    "\tend",
    "\tlocal nO = PETEQUIP_O_DAU + tb.nSlot - 1",
    "\tlocal nCu = GetTask(nO)",
    "\tif nCu > 0 then",
    "\t\tAddItem(6, 1, nCu, 1, 0, 0, 0)",
    "\tend",
    "\tSetTask(nO, nP)",
    "\tPetEquip_Roll(nP, tb.nSlot)",
    "\tlocal nBo, nSo = PetEquip_CapNhatBo()",
    '\tMsg2Player(format("' + vn("Bạn đồng hành đã trang bị [%s] - bộ %s %d món") + '",',
    '\t\tPETEQUIP_VITRI[tb.nSlot], PETEQUIP_SUIT_TEN[tb.nSuit] or "?", nSo))',
    '\tPLOG("PetEquip: deo o=" .. tb.nSlot .. " id=" .. nP .. " bo=" .. nBo .. " so=" .. nSo)',
    "\treturn",
    "end",
    "",
    "-- mo ta 3 thuoc tinh hien co cua mot o",
    "function PetEquip_MoTa(nSlot)",
    "\tlocal nId = GetTask(PETEQUIP_O_DAU + nSlot - 1)",
    "\tlocal tb = PETEQUIP_DEF[nId]",
    "\tif not tb then",
    '\t\treturn ""',
    "\tend",
    '\tlocal sz = ""',
    "\tlocal i",
    "\tfor i = 1, 3 do",
    "\t\tlocal a = tb.tbAttrib[i]",
    "\t\tif a then",
    "\t\t\tlocal v = GetTask(PETEQUIP_O_ATTRIB + (nSlot - 1) * 3 + i - 1)",
    '\t\t\tsz = sz .. format("[%d]+%d ", a[1], v)',
    "\t\tend",
    "\tend",
    "\treturn sz",
    "end",
    "",
    "-- op 10: cua so trang bi",
    "function PetSys:EquipRebuildDlg()",
    "\tif PET_IsCreate() ~= 1 then",
    "\t\treturn",
    "\tend",
    "\tlocal tbOpt = {}",
    "\tlocal i",
    "\tfor i = 1, PETEQUIP_O_SO do",
    "\t\tlocal nId = GetTask(PETEQUIP_O_DAU + i - 1)",
    "\t\tlocal tb = PETEQUIP_DEF[nId]",
    "\t\tif tb then",
    '\t\t\ttinsert(tbOpt, {format("%s %s", PETEQUIP_VITRI[i], PetEquip_MoTa(i)),',
    "\t\t\t\tPetSys.EquipChon, {PetSys, i}})",
    "\t\tend",
    "\tend",
    "\tif getn(tbOpt) == 0 then",
    '\t\tTalk(1, "", "' + vn("Bạn đồng hành chưa mặc trang bị nào") + '")',
    "\t\treturn",
    "\tend",
    "\ttinsert(tbOpt, {%CANCEL})",
    "\tlocal nBo, nSo = PetEquip_CapNhatBo()",
    '\tCreateNewSayEx(format("' + vn("Trang bị Đồng Hành - bộ %s %d món") + '",',
    '\t\t(nBo >= 0 and PETEQUIP_SUIT_TEN[nBo]) or "-", nSo), tbOpt)',
    "end",
    "",
    "function PetSys:EquipChon(nSlot)",
    "\tlocal tbOpt = {}",
    '\ttinsert(tbOpt, {format("' + vn("Đúc lại (tốn 1 Kết Tinh Đồng Hành)") + '"), PetSys.EquipDuc, {PetSys, nSlot}})',
    '\ttinsert(tbOpt, {"' + vn("Tháo ra") + '", PetSys.EquipThao, {PetSys, nSlot}})',
    "\ttinsert(tbOpt, {%CANCEL})",
    '\tCreateNewSayEx(format("%s: %s", PETEQUIP_VITRI[nSlot], PetEquip_MoTa(nSlot)), tbOpt)',
    "end",
    "",
    "function PetSys:EquipDuc(nSlot)",
    "\tlocal nId = GetTask(PETEQUIP_O_DAU + nSlot - 1)",
    "\tlocal tb = PETEQUIP_DEF[nId]",
    "\tif not tb then",
    "\t\treturn",
    "\tend",
    "\tif CalcItemCount(-1, 6, 1, PETEQUIP_KETTINH, -1) < 1 then",
    '\t\tTalk(1, "", "' + vn("Không đủ Kết Tinh Đồng Hành") + '")',
    "\t\treturn",
    "\tend",
    "\tlocal szCu = PetEquip_MoTa(nSlot)",
    "\tConsumeItem(-1, 1, 6, 1, PETEQUIP_KETTINH)",
    "\t-- roll thu vao o tam 5190.. (khong ghi de gia tri dang mac)",
    "\tlocal tbMoi = {}",
    "\tlocal i",
    '\tlocal szMoi = ""',
    "\tfor i = 1, 3 do",
    "\t\tlocal a = tb.tbAttrib[i]",
    "\t\tif a then",
    "\t\t\ttbMoi[i] = random(a[2], a[3])",
    '\t\t\tszMoi = szMoi .. format("[%d]+%d ", a[1], tbMoi[i])',
    "\t\tend",
    "\tend",
    "\tPETEQUIP_TAM = tbMoi",
    "\tlocal tbOpt = {}",
    '\ttinsert(tbOpt, {"' + vn("Giữ lại kết quả mới") + '", PetSys.EquipNhan, {PetSys, nSlot}})',
    '\ttinsert(tbOpt, {"' + vn("Từ bỏ (giữ thuộc tính cũ)") + '"})',
    '\tCreateNewSayEx(format("' + vn("Cũ: %s\\nMới: %s") + '", szCu, szMoi), tbOpt)',
    '\tPLOG("PetEquip duc: o=" .. nSlot .. " cu=" .. szCu .. " moi=" .. szMoi)',
    "end",
    "",
    "function PetSys:EquipNhan(nSlot)",
    "\tif PETEQUIP_TAM == nil then",
    "\t\treturn",
    "\tend",
    "\tlocal i",
    "\tfor i = 1, 3 do",
    "\t\tif PETEQUIP_TAM[i] ~= nil then",
    "\t\t\tSetTask(PETEQUIP_O_ATTRIB + (nSlot - 1) * 3 + i - 1, PETEQUIP_TAM[i])",
    "\t\tend",
    "\tend",
    "\tPETEQUIP_TAM = nil",
    '\tMsg2Player(format("' + vn("Đúc thành công: %s") + '", PetEquip_MoTa(nSlot)))',
    "end",
    "",
    "function PetSys:EquipThao(nSlot)",
    "\tlocal nO = PETEQUIP_O_DAU + nSlot - 1",
    "\tlocal nId = GetTask(nO)",
    "\tif nId <= 0 then",
    "\t\treturn",
    "\tend",
    "\tAddItem(6, 1, nId, 1, 0, 0, 0)",
    "\tSetTask(nO, 0)",
    "\tlocal i",
    "\tfor i = 1, 3 do",
    "\t\tSetTask(PETEQUIP_O_ATTRIB + (nSlot - 1) * 3 + i - 1, 0)",
    "\tend",
    "\tPetEquip_CapNhatBo()",
    '\tMsg2Player(format("' + vn("Đã tháo trang bị ở vị trí %s") + '", PETEQUIP_VITRI[nSlot]))',
    "end",
    "",
])
io.open(SV + r"\script\petsys\petequip.lua", "w", encoding="latin-1",
        newline="").write(noi.replace("\n", CR + "\n"))
print("da ghi petequip.lua (roll thuoc tinh + duc lai + thao)")
