;通缉追杀系统专用ini
[Main]
;租一小时所需要的钱数（必须同Relay相关配置一致）
MoneyPerHour=10000
;允许目标的最小级别，小于此级别不能追杀
MinTargetLevel=50
;任务最长激活时间，单位小时（必须同Relay相关配置一致）
MaxActiveTaskTime=10
;任务最小赏金（必须同Relay相关配置一致）
MinReward=100000

[Messages]
;目标等级不够时的提示
TargetLevelTooLow=Đối tượng dưới cấp 50 không thể truy nã!
;目标不在线时的提示
TargetAbsent=Nhân vật mục tiêu không trực tuyến, không thể ra lệnh truy nã! 