# -*- coding: utf-8 -*-
#
# [ANDROID 09/09 KYNANG C] LAM LAI nut ky nang cho DUNG nguon tham khao.
#
# Chu che ban truoc: "chua thay dung cac nut chon ky nang de danh - toi da keu co nut
# san o vnku roi. Vi tri nut - chuc nang cac nut. Ban sap xep deu sai vi tri."
# Chu dung: ban truoc toi tu ve o VUONG xep luoi 2 cot o mep phai. Nguon tham khao
# khong he lam vay.
#
# DA DOC LAI NGUON, bo cuc that la:
#
#   D:\USVOLAM\Jx1mClientMobile\Classes\vn\gamescence\KgameWorldVN.cpp:1688
#       //KONIS -- phim ky nang phu    vong tron skill quanh mainskill
#   tuc: MOT NUT DANH CHINH to o goc phai duoi, 8 O KY NANG PHU xep thanh CUNG
#   vong quanh no (khong phai luoi vuong).
#
#   Do lech tung o lay DUNG cua ban tham khao (KgameWorld.cpp:13877-13932), tinh tu
#   goc phai duoi man hinh:
#       nut chinh : phai 105 + ban kinh, day 45 + ban kinh
#       o phu 0..7: phai {215,195,160,100,35,255,220,155} + ban kinh
#                   day  { -5, 60,115,145,115, 40,115,180} + ban kinh
#   O 0..4 la cung trong (vong qua tren dau nut chinh), o 5..7 la cung ngoai.
#
# ANH: dung DUNG bo cua VNKU nhu chu chi, \spr\Ui3\UiSkillControl\:
#       assign_skill_100x100.spr  khung tron nut danh chinh
#       assign_skill_70x70.spr    khung tron o ky nang phu
#       effect_skill.spr          vong sang ngam huong quanh nut dang giu
#   (Ban truoc ve o vuong bang KRUShadow - sai han. Bo anh nay von da nam canh
#   joystick_bg/ctrl ma ban truoc da dung cho can dieu khien, dang le phai thay.)
#
# CHUC NANG - theo dung ban tham khao (KuiMyMenu::onTouchBegan:251):
#   moi ky nang co KIEU DUNG (_useSkillModel): kieu 0 = cham la danh ngay (tu chon
#   muc tieu); kieu 1/2 = phai NGAM huong roi tha ngon moi danh. Ban nay lam:
#       cham nhanh  -> danh con gan nhat  (= kieu 0)
#       giu roi keo -> ngam huong, tha ngon danh con trong huong (= kieu 1/2)
#   Nut danh chinh dung ky nang danh TRAI dang hien tren thanh trang thai
#   (GDI_PLAYER_IMMED_ITEMSKILL) - dung thu ma nut mainskill cua ban tham khao dung.
#   O phu dung ky nang cua chinh no, va dat luon lam ky nang danh trai de lan sau
#   cham thang vao dich la danh bang no.
#
# config.ini [Cham]: KyNang / KyNangCo / KyNangCoPhu / KyNangLenTren / KyNangX / KyNangY
#   KyNangLenTren = nang ca cum len bao nhieu diem anh cho khoi thanh cong cu duoi
#   day cua ban PC (ban tham khao thay han thanh do nen khong can, ban nay con giu).

import io
import os

os.chdir(r"D:\GAMEDEVNEW_wt_mobile")
NL = "\r\n"
P = "Sources/S3Client/Platform/JxCanDieuKhien.cpp"
DAU = "[ANDROID 09/09 KYNANG C]"

s = io.open(P, encoding="latin-1", newline="").read()
if DAU in s:
    print("da va roi, bo qua:", P)
    raise SystemExit

# ---------------------------------------------------------------- 1. cai dat
CU = NL.join([
    "\t// [ANDROID 09/09 KYNANG]",
    '\ts_nKNBat = GetPrivateProfileInt("Cham", "KyNang", 1, szCfg);',
    '\ts_nKNSo  = GetPrivateProfileInt("Cham", "KyNangSo", 6, szCfg);',
    '\ts_nKNCot = GetPrivateProfileInt("Cham", "KyNangCot", 2, szCfg);',
    '\ts_nKNCo  = GetPrivateProfileInt("Cham", "KyNangCo", 56, szCfg);',
    '\ts_nKNX   = GetPrivateProfileInt("Cham", "KyNangX", -1, szCfg);',
    '\ts_nKNY   = GetPrivateProfileInt("Cham", "KyNangY", -1, szCfg);',
    "\tif (s_nKNSo  < 1)  s_nKNSo  = 1;",
    "\tif (s_nKNSo  > KYNANG_TOI_DA) s_nKNSo = KYNANG_TOI_DA;",
    "\tif (s_nKNCot < 1)  s_nKNCot = 1;",
    "\tif (s_nKNCo  < 24) s_nKNCo  = 24;",
])
assert s.count(CU) == 1, "khong tim thay khoi cai dat ky nang (%d)" % s.count(CU)
MOI = NL.join([
    "\t// [ANDROID 09/09 KYNANG C]",
    '\ts_nKNBat     = GetPrivateProfileInt("Cham", "KyNang", 1, szCfg);',
    '\ts_nKNCoChinh = GetPrivateProfileInt("Cham", "KyNangCo", 0, szCfg);',
    '\ts_nKNCoPhu   = GetPrivateProfileInt("Cham", "KyNangCoPhu", 0, szCfg);',
    '\ts_nKNLenTren = GetPrivateProfileInt("Cham", "KyNangLenTren", 60, szCfg);',
    '\ts_nKNX       = GetPrivateProfileInt("Cham", "KyNangX", -1, szCfg);',
    '\ts_nKNY       = GetPrivateProfileInt("Cham", "KyNangY", -1, szCfg);',
    '\tGetPrivateProfileString("Cham", "KyNangAnhChinh", s_szKNAnhChinh, s_szKNAnhChinh,',
    "\t\tsizeof(s_szKNAnhChinh), szCfg);",
    '\tGetPrivateProfileString("Cham", "KyNangAnhPhu", s_szKNAnhPhu, s_szKNAnhPhu,',
    "\t\tsizeof(s_szKNAnhPhu), szCfg);",
    '\tGetPrivateProfileString("Cham", "KyNangAnhNgam", s_szKNAnhNgam, s_szKNAnhNgam,',
    "\t\tsizeof(s_szKNAnhNgam), szCfg);",
])
s = s.replace(CU, MOI)

# ---------------------------------------------------------------- 2. bien
CU = NL.join([
    "// [ANDROID 09/09 KYNANG] bang nut ky nang",
    "#define\tKYNANG_TOI_DA\t\t12\t\t// so nut nhieu nhat cho hien",
    "#define\tKYNANG_DS_TOI_DA\t65\t\t// bang GDI_LEFT_ENABLE_SKILLS tra ve toi da 65 muc",
    "#define\tKYNANG_CACH\t\t\t6\t\t// khe ho giua hai nut",
    "#define\tKYNANG_LAM_MOI_MS\t2000\t// bao lau doc lai danh sach ky nang mot lan",
    "",
    "static int\t\t\ts_nKNBat = 1;",
    "static int\t\t\ts_nKNSo  = 6;",
    "static int\t\t\ts_nKNCot = 2;",
    "static int\t\t\ts_nKNCo  = 56;",
    "static int\t\t\ts_nKNX   = -1;\t\t// -1 = tu tinh",
    "static int\t\t\ts_nKNY   = -1;",
    "",
    "static KUiSkillData\ts_KNBang[KYNANG_DS_TOI_DA];",
    "static int\t\t\ts_nKNCo1 = 0;\t\t// so ky nang doc duoc",
    "static unsigned int\ts_uKNDocLuc = 0;",
    "static int\t\t\ts_nKNDangCam = -1;\t// nut dang giu (0-based), -1 = khong",
    "static int\t\t\ts_nKNNgonX = 0, s_nKNNgonY = 0;",
    "static int\t\t\ts_nKNDichIdx = 0;\t// chi so NPC dang ngam",
    "static int\t\t\ts_nKNDichX = 0, s_nKNDichY = 0;\t// vi tri VE cua no",
])
assert s.count(CU) == 1, "khong tim thay khoi bien ky nang (%d)" % s.count(CU)
MOI = NL.join([
    "// [ANDROID 09/09 KYNANG C] Nut danh chinh + 8 o ky nang phu xep thanh CUNG",
    "// quanh no - bo cuc lay dung cua ban JX1 Mobile tham khao (KgameWorld.cpp:13877,",
    "// KgameWorldVN.cpp:1688 \"vong tron skill quanh mainskill\").",
    "#define\tKYNANG_SO_PHU\t\t8\t\t// ban tham khao: MAX_FUZHUSKILL_COUNT = 8",
    "#define\tKYNANG_DS_TOI_DA\t65\t\t// GDI_LEFT_ENABLE_SKILLS tra ve toi da 65 muc",
    "#define\tKYNANG_LAM_MOI_MS\t2000\t// bao lau doc lai danh sach ky nang mot lan",
    "#define\tKYNANG_NGUONG_NGAM\t18\t\t// keo qua bao nhieu diem anh moi tinh la ngam",
    "",
    "//\tDo lech tam tung o, tinh tu goc PHAI DUOI man hinh (chua cong ban kinh o).",
    "//\tLay dung so cua ban tham khao: KgameWorld.cpp:13877 (o 0..4, cung trong)",
    "//\tva :13908 (o 5..7, cung ngoai).",
    "static const int\ts_nKNDX[KYNANG_SO_PHU] = { 215, 195, 160, 100,  35, 255, 220, 155 };",
    "static const int\ts_nKNDY[KYNANG_SO_PHU] = {  -5,  60, 115, 145, 115,  40, 115, 180 };",
    "#define\tKYNANG_CHINH_DX\t\t105\t\t// nut danh chinh: KgameWorldVN.cpp:804",
    "#define\tKYNANG_CHINH_DY\t\t45",
    "",
    "static int\t\t\ts_nKNBat = 1;",
    "static int\t\t\ts_nKNCoChinh = 0;\t// 0 = lay theo co that cua anh",
    "static int\t\t\ts_nKNCoPhu   = 0;",
    "static int\t\t\ts_nKNLenTren = 60;\t// nang ca cum len, khoi thanh cong cu duoi day",
    "static int\t\t\ts_nKNX   = -1;\t\t// -1 = neo goc phai duoi nhu ban tham khao",
    "static int\t\t\ts_nKNY   = -1;",
    "",
    "//\tBo anh THAT cua VNKU - chu da chi san (\\spr\\Ui3\\UiSkillControl)",
    "static char\t\ts_szKNAnhChinh[128] = \"\\\\spr\\\\Ui3\\\\UiSkillControl\\\\assign_skill_100x100.spr\";",
    "static char\t\ts_szKNAnhPhu[128]   = \"\\\\spr\\\\Ui3\\\\UiSkillControl\\\\assign_skill_70x70.spr\";",
    "static char\t\ts_szKNAnhNgam[128]  = \"\\\\spr\\\\Ui3\\\\UiSkillControl\\\\effect_skill.spr\";",
    "static int\t\t\ts_nKNCoAnh = -1;\t// -1 = chua kiem",
    "",
    "static KUiSkillData\ts_KNBang[KYNANG_DS_TOI_DA];",
    "static int\t\t\ts_nKNCo1 = 0;\t\t// so ky nang doc duoc",
    "static unsigned int\ts_uKNDocLuc = 0;",
    "static KUiGameObject s_KNChinh;\t\t// ky nang danh TRAI dang hien tren thanh trang thai",
    "static int\t\t\ts_nKNDangCam = -1;\t// 0 = nut chinh, 1..8 = o phu; -1 = khong giu",
    "static int\t\t\ts_nKNNgonX = 0, s_nKNNgonY = 0;",
    "static int\t\t\ts_nKNDichIdx = 0;\t// chi so NPC dang ngam",
    "static int\t\t\ts_nKNDichX = 0, s_nKNDichY = 0;\t// vi tri VE cua no",
])
s = s.replace(CU, MOI)

# ---------------------------------------------------------------- 3. than
i0 = s.index("//---------------------------------------------------------------------------" + NL
             + "// [ANDROID 09/09 KYNANG] NUT CHON KY NANG DANH")
i1 = s.index(NL + "void JxIconNpc_Ve()")
THAN = NL.join([
    "//---------------------------------------------------------------------------",
    "// [ANDROID 09/09 KYNANG C] NUT DANH CHINH + 8 O KY NANG PHU XEP THANH CUNG",
    "//",
    "// Bo cuc va anh lay dung cua ban JX1 Mobile tham khao - xem android/va_nguon_android_38.py.",
    "//---------------------------------------------------------------------------",
    "",
    "//\tCo THAT cua mot anh .spr (de neo o theo dung ban kinh cua no).",
    "static int KyNang_CoAnh(const char* pszAnh, int nMacDinh)",
    "{",
    "\tKRPosition2 oOff = { 0, 0 }, oCo = { 0, 0 };",
    "",
    "\tif (g_pRepresentShell",
    "\t\t&& g_pRepresentShell->GetImageFrameParam((char*)pszAnh, 0, &oOff, &oCo, ISI_T_SPR)",
    "\t\t&& oCo.nX > 0)",
    "\t\treturn oCo.nX;",
    "\treturn nMacDinh;",
    "}",
    "",
    "static int KyNang_CoChinh()",
    "{",
    "\treturn s_nKNCoChinh > 0 ? s_nKNCoChinh : KyNang_CoAnh(s_szKNAnhChinh, 100);",
    "}",
    "",
    "static int KyNang_CoPhu()",
    "{",
    "\treturn s_nKNCoPhu > 0 ? s_nKNCoPhu : KyNang_CoAnh(s_szKNAnhPhu, 70);",
    "}",
    "",
    "//\tTam cua mot o, toa do MAN HINH. nNut: 0 = nut danh chinh, 1..8 = o phu.",
    "static void KyNang_TamNut(int nNut, int* px, int* py)",
    "{",
    "\tint nR, nDX, nDY;",
    "",
    "\tif (nNut <= 0)",
    "\t{",
    "\t\tnR = KyNang_CoChinh() / 2;",
    "\t\tnDX = KYNANG_CHINH_DX;",
    "\t\tnDY = KYNANG_CHINH_DY;",
    "\t}",
    "\telse",
    "\t{",
    "\t\tnR = KyNang_CoPhu() / 2;",
    "\t\tnDX = s_nKNDX[nNut - 1];",
    "\t\tnDY = s_nKNDY[nNut - 1];",
    "\t}",
    "\t// Neo goc PHAI DUOI y nhu ban tham khao. KyNangX/Y (neu dat) doi ca cum di.",
    "\t*px = SCREEN_WIDTH  - (nR + nDX) + (s_nKNX >= 0 ? s_nKNX : 0);",
    "\t*py = SCREEN_HEIGHT - (nR + nDY) - s_nKNLenTren + (s_nKNY >= 0 ? s_nKNY : 0);",
    "}",
    "",
    "//\tDoc lai danh sach ky nang danh + ky nang danh trai dang dung.",
    "//\tKhong doc moi khung: GDI nay quet ca cay vo cong nen goi lien tuc la phi.",
    "static void KyNang_DocBang()",
    "{",
    "\tunsigned int uNay = (unsigned int)GetTickCount();",
    "\tKUiPlayerImmedItemSkill oTay;",
    "",
    "\tif (g_pCoreShell == NULL)",
    "\t\treturn;",
    "\tif (s_uKNDocLuc && uNay - s_uKNDocLuc < KYNANG_LAM_MOI_MS)",
    "\t\treturn;",
    "\ts_uKNDocLuc = uNay;",
    "",
    "\tmemset(s_KNBang, 0, sizeof(s_KNBang));",
    "\ts_nKNCo1 = g_pCoreShell->GetGameData(GDI_LEFT_ENABLE_SKILLS, (KUPARAM)&s_KNBang, 0);",
    "\tif (s_nKNCo1 < 0)\t\t\t\ts_nKNCo1 = 0;",
    "\tif (s_nKNCo1 > KYNANG_DS_TOI_DA)\ts_nKNCo1 = KYNANG_DS_TOI_DA;",
    "",
    "\t// Nut danh chinh dung ky nang danh TRAI dang hien tren thanh trang thai -",
    "\t// dung thu ma nut mainskill cua ban tham khao dung.",
    "\tmemset(&oTay, 0, sizeof(oTay));",
    "\tg_pCoreShell->GetGameData(GDI_PLAYER_IMMED_ITEMSKILL, (KNPARAM)&oTay, 0);",
    "\ts_KNChinh = oTay.IMmediaSkill[0];",
    "}",
    "",
    "//\tKy nang gan cho mot o. Tra ve false neu o trong.",
    "static bool KyNang_CuaNut(int nNut, KUiGameObject* pRa)",
    "{",
    "\tif (nNut <= 0)",
    "\t{",
    "\t\t*pRa = s_KNChinh;",
    "\t\treturn (pRa->uGenre != CGOG_NOTHING && pRa->uId != 0);",
    "\t}",
    "\tif (nNut - 1 >= s_nKNCo1)",
    "\t{",
    "\t\tmemset(pRa, 0, sizeof(*pRa));",
    "\t\treturn false;",
    "\t}",
    "\tpRa->uGenre = s_KNBang[nNut - 1].uGenre;",
    "\tpRa->uId    = s_KNBang[nNut - 1].uId;",
    "\treturn (pRa->uGenre != CGOG_NOTHING && pRa->uId != 0);",
    "}",
    "",
    "int JxKyNang_TrungNut(int x, int y)",
    "{",
    "\tint i, nX, nY, nR;",
    "",
    "\tDocCaiDat();",
    "\tif (!s_nKNBat)",
    "\t\treturn 0;",
    "\tKyNang_DocBang();",
    "\t// Xet o phu TRUOC roi moi den nut chinh: cung o phu vong sat nut chinh, uu tien",
    "\t// o nho de cham vao ria cung khong bi nut to nuot mat.",
    "\tfor (i = KYNANG_SO_PHU; i >= 0; i--)",
    "\t{",
    "\t\tKUiGameObject o;",
    "",
    "\t\tif (!KyNang_CuaNut(i, &o))",
    "\t\t\tcontinue;\t\t// o trong thi khong bat cham",
    "\t\tKyNang_TamNut(i, &nX, &nY);",
    "\t\tnR = (i <= 0 ? KyNang_CoChinh() : KyNang_CoPhu()) / 2;",
    "\t\t// khung tron -> do theo BAN KINH, khong phai hinh vuong",
    "\t\tif ((x - nX) * (x - nX) + (y - nY) * (y - nY) <= nR * nR)",
    "\t\t\treturn i + 1;",
    "\t}",
    "\treturn 0;",
    "}",
    "",
    "//\tHoi Core: con dich hop nhat theo huong ngam (0,0 = khong ngam -> gan nhat).",
    "static int KyNang_TimDich(int nHuongX, int nHuongY, int* pVeX, int* pVeY)",
    "{",
    "\tKUiTargetDetailInfo tt;",
    "",
    "\tif (g_pCoreShell == NULL)",
    "\t\treturn 0;",
    "\tmemset(&tt, 0, sizeof(tt));",
    "\ttt.nViTriVeX = nHuongX;",
    "\ttt.nViTriVeY = nHuongY;",
    "\tif (!g_pCoreShell->GetGameData(NPC_OI_TARGET_INFO, (KUPARAM)&tt, 2))",
    "\t\treturn 0;",
    "\tif (pVeX) *pVeX = tt.nViTriVeX;",
    "\tif (pVeY) *pVeY = tt.nViTriVeY;",
    "\treturn tt.nChiSoNpc;",
    "}",
    "",
    "void JxKyNang_BatDau(int nNut, int x, int y)",
    "{",
    "\ts_nKNDangCam = nNut - 1;\t// 0 = nut chinh, 1..8 = o phu",
    "\ts_nKNNgonX = x;",
    "\ts_nKNNgonY = y;",
    "\ts_nKNDichIdx = 0;",
    "}",
    "",
    "void JxKyNang_Keo(int x, int y)",
    "{",
    "\tint nX, nY, dx, dy;",
    "",
    "\tif (s_nKNDangCam < 0)",
    "\t\treturn;",
    "\ts_nKNNgonX = x;",
    "\ts_nKNNgonY = y;",
    "\tKyNang_TamNut(s_nKNDangCam, &nX, &nY);",
    "\tdx = x - nX;",
    "\tdy = y - nY;",
    "\t// Keo chua du xa = chua ngam (tranh rung tay lam doi muc tieu). Ban tham khao",
    "\t// cung co vung chet nay (KuiMyMenu m_ptJXTouch0 / m_bJXAimKeo).",
    "\tif (dx * dx + dy * dy < KYNANG_NGUONG_NGAM * KYNANG_NGUONG_NGAM)",
    "\t{",
    "\t\ts_nKNDichIdx = 0;",
    "\t\treturn;",
    "\t}",
    "\ts_nKNDichIdx = KyNang_TimDich(dx, dy, &s_nKNDichX, &s_nKNDichY);",
    "}",
    "",
    "bool JxKyNang_Nha()",
    "{",
    "\tint nNut = s_nKNDangCam;",
    "\tint nDich = s_nKNDichIdx;",
    "\tKUiGameObject o;",
    "",
    "\ts_nKNDangCam = -1;",
    "\ts_nKNDichIdx = 0;",
    "\tif (nNut < 0 || g_pCoreShell == NULL)",
    "\t\treturn false;",
    "\tif (!KyNang_CuaNut(nNut, &o))",
    "\t\treturn false;",
    "",
    "\t// O phu: dat luon lam ky nang danh TRAI (GOI_SET_IMMDIA_SKILL, y het",
    "\t// UiSkillTree.cpp:156) de o tren thanh trang thai doi theo va lan sau cham",
    "\t// thang vao dich la danh bang dung ky nang nay. Nut chinh thi khong can -",
    "\t// no VON dung ky nang danh trai.",
    "\tif (nNut > 0)",
    "\t\tg_pCoreShell->OperationRequest(GOI_SET_IMMDIA_SKILL, (KUPARAM)&o, 0);",
    "",
    "\t// Khong ngam duoc con nao trong huong keo thi danh con gan nhat (= kieu 0",
    "\t// cua ban tham khao: cham la danh, tu chon muc tieu).",
    "\tif (nDich == 0)",
    "\t\tnDich = KyNang_TimDich(0, 0, NULL, NULL);",
    "\tif (nDich == 0)",
    "\t\treturn true;\t\t// khong co dich: van coi la da xu ly",
    "\tg_pCoreShell->LockSomeoneUseSkill(nDich, (int)o.uId);",
    "\treturn true;",
    "}",
    "",
    "//\tVong tron duoi chan con dang ngam - dung anh vong DICH nhu JxVongChon_Ve.",
    "static void KyNang_VeVongDich(int nVeX, int nVeY)",
    "{",
    "\tstatic KRUImage s_VongNgam;",
    "\tKRPosition2 oOff = { 0, 0 }, oCo = { 0, 0 };",
    "\tint nLuiX = 0, nLuiY = 0;",
    "",
    "\tif (s_nVongCoAnh < 0)",
    "\t\ts_nVongCoAnh = (CoAnh(s_szVongAnh) && CoAnh(s_szVongAnhDich)) ? 1 : 0;",
    "\tif (!s_nVongCoAnh)",
    "\t\treturn;",
    "\tif (s_VongNgam.szImage[0] == 0)",
    "\t{",
    "\t\tmemset(&s_VongNgam, 0, sizeof(s_VongNgam));",
    "\t\ts_VongNgam.nType = ISI_T_SPR;",
    "\t\ts_VongNgam.bRenderStyle = IMAGE_RENDER_STYLE_ALPHA;",
    "\t\ts_VongNgam.Color.Color_dw = 0xffffffff;",
    "\t\ts_VongNgam.nISPosition = IMAGE_IS_POSITION_INIT;",
    "\t\ts_VongNgam.nFrame = 0;",
    "\t\tstrncpy(s_VongNgam.szImage, s_szVongAnhDich, sizeof(s_VongNgam.szImage) - 1);",
    "\t}",
    "\tif (g_pRepresentShell->GetImageFrameParam(s_VongNgam.szImage, 0, &oOff, &oCo, s_VongNgam.nType)",
    "\t\t&& oCo.nX > 0)",
    "\t{",
    "\t\tnLuiX = oCo.nX / 2;",
    "\t\tnLuiY = oCo.nY / 2;",
    "\t}",
    "\ts_VongNgam.oPosition.nX = nVeX - nLuiX;",
    "\ts_VongNgam.oPosition.nY = nVeY - nLuiY;",
    "\t// FALSE = toa do THE GIOI",
    "\tg_pRepresentShell->DrawPrimitives(1, &s_VongNgam, RU_T_IMAGE, false);",
    "}",
    "",
    "void JxKyNang_Ve()",
    "{",
    "\tint i, nX, nY, nR, nIcon;",
    "\tKUiGameObject o;",
    "",
    "\tDocCaiDat();",
    "\tif (!s_nKNBat || g_pCoreShell == NULL || g_pRepresentShell == NULL)",
    "\t\treturn;",
    "\tif (s_nKNCoAnh < 0)",
    "\t{",
    "\t\ts_nKNCoAnh = (CoAnh(s_szKNAnhChinh) && CoAnh(s_szKNAnhPhu)) ? 1 : 0;",
    "\t\tg_DebugLog(\"[KYNANG] anh nut: %s -> co anh=%d\", s_szKNAnhChinh, s_nKNCoAnh);",
    "\t}",
    "\tKyNang_DocBang();",
    "",
    "\t// Ve tu o phu ra ngoai roi den nut chinh, de nut chinh nam TREN CUNG.",
    "\tfor (i = KYNANG_SO_PHU; i >= 0; i--)",
    "\t{",
    "\t\tbool bCo = KyNang_CuaNut(i, &o);",
    "",
    "\t\tif (!bCo && i > 0)",
    "\t\t\tcontinue;\t\t// o phu trong thi khong ve gi ca",
    "\t\tKyNang_TamNut(i, &nX, &nY);",
    "\t\tnR = (i <= 0 ? KyNang_CoChinh() : KyNang_CoPhu()) / 2;",
    "",
    "\t\t// khung tron cua VNKU; thieu anh thi lui ve o mau cho van dung duoc",
    "\t\tif (s_nKNCoAnh)",
    "\t\t\tVeAnh(i <= 0 ? s_szKNAnhChinh : s_szKNAnhPhu, nX, nY);",
    "\t\telse",
    "\t\t\tOVuong(nX, nY, nR, (i == s_nKNDangCam) ? 0xB03A8A3A : 0x80202020);",
    "",
    "\t\t// bieu tuong ky nang nam GON trong khung tron: lui vao ~30% ban kinh",
    "\t\tif (bCo)",
    "\t\t{",
    "\t\t\tnIcon = nR * 7 / 5;\t\t// = 1.4 * ban kinh = 70% duong kinh",
    "\t\t\tg_pCoreShell->DrawGameObj(o.uGenre, o.uId,",
    "\t\t\t\tnX - nIcon / 2, nY - nIcon / 2, nIcon, nIcon, 0);",
    "\t\t}",
    "\t}",
    "",
    "\t// Dang giu mot nut: vong sang ngam + vach chi huong + vong duoi chan con dich.",
    "\tif (s_nKNDangCam >= 0)",
    "\t{",
    "\t\tKRULine oVach;",
    "",
    "\t\tKyNang_TamNut(s_nKNDangCam, &nX, &nY);",
    "\t\tif (CoAnh(s_szKNAnhNgam))",
    "\t\t\tVeAnh(s_szKNAnhNgam, nX, nY);\t// effect_skill.spr cua VNKU",
    "",
    "\t\toVach.oPosition.nX = nX;",
    "\t\toVach.oPosition.nY = nY;",
    "\t\toVach.oEndPos.nX   = s_nKNNgonX;",
    "\t\toVach.oEndPos.nY   = s_nKNNgonY;",
    "\t\toVach.Color.Color_dw = s_nKNDichIdx ? 0xFFFF6666 : 0xA0FFFFFF;",
    "\t\tg_pRepresentShell->DrawPrimitives(1, &oVach, RU_T_LINE, true);",
    "",
    "\t\tif (s_nKNDichIdx)",
    "\t\t\tKyNang_VeVongDich(s_nKNDichX, s_nKNDichY);",
    "\t}",
    "}",
    "",
])
s = s[:i0] + THAN + s[i1:]

io.open(P, "w", encoding="latin-1", newline="").write(s)
print("da va:", P)
