# -*- coding: utf-8 -*-
#
# [ANDROID 11/09 WAUTO B2] Buoc B2: LOP TRANG CHAY THEO BANG cho khung WAuto trong game.
#
# Bang (UiWAutoBang.h) + 15 tep bo cuc uiwauto_tabN.ini do android/sinh_bang_wauto.py + sinh_bocuc_wauto.py SINH tu WAuto.rc /
# SaveRoleData / ipc_shared.h. Tep nay:
#  1. TAO  Sources/S3Client/Ui/UiCase/UiWAutoTrang.h + .cpp - KUiWAutoTrang : KWndWindow, kho widget (22 tick, 12 o nhap, 12 hop chon,
#          32 nhan, 12 nut, 8 o nhom - khop POOL cua sinh_bocuc_wauto.py). NapTab(n): doc ini cua tab, dat lai widget theo khe, dien gia tri doc THANG tu autoData qua offset
#          (JxWAuto_CauHinh). Cham tick / nhap so / chon muc menu -> ghi vao autoData + JxWAuto_LuuCauHinh() (APdata\<id>.dat).
#          Hop chon nguon CHIEU: danh sach chieu that cua nhan vat (JxCore_WAutoDanhSachChieu), gia tri = ma chieu.
#          Da thu tren LDPlayer (20:05): KWndText::Init chi dat Text khi dang rong -> phai SetText("") truoc Init khi doi tab;
#          SetIntText ban WND_N_EDIT_CHANGE -> co m_bDangDien de khong ghi .dat khi dang dien; trinh chieu Android ve anh + chu
#          SAU bong menu (menu chon bi chu cua trang de len) -> tam an widget nam duoi menu (AnDuoiMenu) toi khi menu dong;
#          KWndEdit chi ve chu -> KWndNhapWA ve them nen toi + vien de nhin ra o nhap.
#  2. VA   Sources/S3Client/Ui/UiCase/UiWAuto.h/.cpp: them trang vao khung, ChonTab -> NapTab(the toan cuc), OpenWindow -> DienGiaTri,
#          Breathe -> m_Trang.Breathe() (LetMeBreathe chi goi cua so goc).
#  3. VA   Sources/Core/Src/CoreShell.cpp: JxCore_WAutoDanhSachChieu() (GetAllSkillByType - cung ham IPCMainSync dung cho WAuto.exe).
#  4. VA   android/CMakeLists.txt: them UiWAutoTrang.cpp vao target main.
# Chi Android; ban PC khong doi (CoreShell rao JX_ANDROID; cac tep moi khong nam trong vcxproj). Chay lai vo hai
# (tep da tao / da va thi bo qua; muon sinh lai UiWAutoTrang.h/.cpp thi xoa hai tep roi chay lai).

import io
import os
import sys

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, r"C:\Users\nguye\.claude\skills\swordonline-dev\scripts")
from vn_edit import vn  # noqa: E402

DAU = "[ANDROID 11/09 WAUTO B2]"
DAU2 = "[ANDROID 11/09 WAUTO B2 b]"


def doc(p):
    return io.open(p, encoding="latin-1", newline="").read()


def ghi(p, s):
    io.open(p, "w", encoding="latin-1", newline="").write(s)


def nl_cua(s):
    return "\r\n" if s.count("\r\n") > s.count("\n") // 2 else "\n"


def thay(s, cu, moi, ten, so=1):
    nl = nl_cua(s)
    c = nl.join(cu)
    if s.count(c) == so:
        return s.replace(c, nl.join(moi))
    raise SystemExit("khong tim thay dung %d cho (%d): %s" % (so, s.count(c), ten))


def cao(s):
    return sum(1 for c in s if ord(c) >= 0x80)


def va(p, dau, ham):
    s = doc(p)
    if dau in s:
        print("da va roi, bo qua:", p, dau)
        return
    s2 = ham(s)
    if cao(s) != cao(s2):
        raise SystemExit("so byte cao doi o " + p)
    ghi(p, s2)
    print("da va:", p, dau)


def tao(p, dong, dau):
    if os.path.isfile(p) and dau in doc(p):
        print("da co roi, bo qua:", p)
        return
    ghi(p, "\r\n".join(dong) + "\r\n")
    print("da tao:", p, "(%d dong)" % len(dong))


def C(s):
    return '"' + vn(s) + '"'


# ---------------------------------------------------------------- 1a. UiWAutoTrang.h
H = [
    "//---------------------------------------------------------------------------",
    "// %s TRANG NOI DUNG cua khung WAuto trong game - chay theo BANG (UiWAutoBang.h, sinh bang may tu WAuto.rc)." % DAU,
    "// Mot kho widget dung chung cho ca 15 tab; NapTab(n) doc uiwauto_tabN.ini de dat lai vi tri / nhan, roi dien gia tri doc thang",
    "// tu autoData (JxWAuto_CauHinh) theo offset trong bang. Doi gi -> ghi vao autoData + luu APdata\\<id>.dat ngay.",
    "// Chi bien dich khi JX_ANDROID; khong nam trong vcxproj nao. Xem LOTRINH_WAUTO_MOBILE_1109.md §B2.",
    "//---------------------------------------------------------------------------",
    "#ifndef UiWAutoTrang_H",
    "#define UiWAutoTrang_H",
    "#ifdef JX_ANDROID",
    "#include \"../Elem/WndWindow.h\"",
    "#include \"../Elem/WndButton.h\"",
    "#include \"../Elem/WndLabeledButton.h\"",
    "#include \"../Elem/WndEdit.h\"",
    "#include \"../Elem/WndText.h\"",
    "#include \"../../../Core/Src/ipc_shared.h\"\t// IPCSkillInfo, defSKILLNUMGET, autoData",
    "",
    "#define WA_TR_TICK\t22",
    "#define WA_TR_NHAP\t12",
    "#define WA_TR_CHON\t12",
    "#define WA_TR_NHAN\t32",
    "#define WA_TR_NUT\t12",
    "#define WA_TR_SO_TAB\t15",
    "#define WA_TR_HOP\t8",
    "#define WA_TR_AN_TOI_DA\t(WA_TR_TICK + WA_TR_NHAP + WA_TR_CHON + WA_TR_NHAN + WA_TR_NUT)",
    "",
    "struct WAUiMuc;",
    "struct WAUiTab;",
    "",
    "// O nhap cua trang: KWndEdit chi ve chu, tren nen khung khong nhin ra o nhap -> ve them nen toi + vien truoc chu",
    "class KWndNhapWA : public KWndEdit512",
    "{",
    "public:",
    "\tvirtual void\tPaintWindow();",
    "};",
    "",
    "// O NHOM (chu 11/09: \"phai ke o de phan biet tung nhom\", \"co mau phan biet cac nhom chuc nang\"): nen toi mo + vien + tieu de",
    "// (TieuDe= trong ini, TCVN3); Mau= 0..5 chon bo mau vien / nen tieu de (bang s_aMauHop trong UiWAutoTrang.cpp)",
    "class KWndHopNhomWA : public KWndWindow",
    "{",
    "public:",
    "\tKWndHopNhomWA();",
    "\tvirtual int\t\tInit(KIniFile* pIniFile, const char* pSection);",
    "\tvirtual void\tPaintWindow();",
    "private:",
    "\tchar\tm_szTieuDe[64];",
    "\tint\t\tm_nMau;",
    "};",
    "",
    "class KUiWAutoTrang : public KWndWindow",
    "{",
    "public:",
    "\tKUiWAutoTrang();",
    "\tvoid\tKhoiTao();\t\t\t\t\t// AddChild ca kho widget (goi mot lan truoc khi cha AddChild(this))",
    "\tvoid\tNapTab(int nTab);\t\t\t// 0..14: doc uiwauto_tabN.ini, dat lai widget, dien gia tri",
    "\tvoid\tDienGiaTri();\t\t\t\t// dien lai tu autoData (mo lai cua so, doi nhan vat)",
    "\tint\t\tTabDangHien()\t{ return m_nTab; }",
    "\tvoid\tBreathe();\t\t\t\t\t// cha goi moi nhip (LetMeBreathe chi toi cua so goc)",
    "\tint\t\tWndProc(unsigned int uMsg, KUPARAM uParam, KNPARAM nParam);",
    "private:",
    "\tKWndHopNhomWA\t\tm_Hop[WA_TR_HOP];\t\t// ve truoc (AddChild dau tien) de nam duoi cac o",
    "\tKWndButton\t\t\tm_Tick[WA_TR_TICK];",
    "\tKWndNhapWA\t\t\tm_Nhap[WA_TR_NHAP];",
    "\tKWndLabeledButton\tm_Chon[WA_TR_CHON];",
    "\tKWndText80\t\t\tm_Nhan[WA_TR_NHAN];",
    "\tKWndLabeledButton\tm_Nut[WA_TR_NUT];",
    "\tint\t\t\t\t\tm_nTab;",
    "\tconst WAUiTab*\t\tm_pTab;",
    "\tIPCSkillInfo\t\tm_aChieu[defSKILLNUMGET];",
    "\tint\t\t\t\t\tm_nChieu;\t\t\t\t// -1 = chua nap",
    "\tint\t\t\t\t\tm_bDangDien;\t\t\t// dang dien tu autoData -> bo qua WND_N_EDIT_CHANGE (SetIntText cung ban)",
    "\tKWndWindow*\t\t\tm_apAnTam[WA_TR_AN_TOI_DA];\t// widget tam an khi menu chon dang mo (trinh chieu Android ve anh + chu SAU bong menu)",
    "\tint\t\t\t\t\tm_nAnTam;",
    "\tvoid\tAnHet();",
    "\tconst WAUiMuc*\tMuc(int nLoai, int nKhe);",
    "\tvoid*\tDiaChi(const WAUiMuc* p);",
    "\tint\t\tLayInt(const WAUiMuc* p);",
    "\tvoid\tDatInt(const WAUiMuc* p, int v);",
    "\tvoid\tDienChon(const WAUiMuc* p);",
    "\tvoid\tNapChieu();",
    "\tvoid\tMoMenuChon(int nKhe);",
    "\tvoid\tChonMenu(int nKhe, int nMuc);",
    "\tvoid\tAnDuoiMenu(int bAn);",
    "\tvoid\tThuAn(KWndWindow* p, int x0, int y0, int x1, int y1);",
    "\tvoid\tDaDoi();",
    "};",
    "#endif // JX_ANDROID",
    "#endif",
]

# ---------------------------------------------------------------- 1b. UiWAutoTrang.cpp
CPP = [
    "//---------------------------------------------------------------------------",
    "// %s Trang noi dung chay theo bang - xem UiWAutoTrang.h. Chuoi TCVN3 sinh bang vn_edit.py (android/va_nguon_android_wauto6.py)." % DAU,
    "//---------------------------------------------------------------------------",
    "#include \"KWin32.h\"",
    "#ifdef JX_ANDROID",
    "#include \"KIniFile.h\"",
    "#include \"KDebug.h\"",
    "#include \"../elem/wnds.h\"",
    "#include \"../Elem/WndMessage.h\"",
    "#include \"../Elem/PopupMenu.h\"",
    "#include \"../UiBase.h\"",
    "#include \"../../../Represent/iRepresent/KRepresentUnit.h\"",
    "#include \"../../../Represent/iRepresent/iRepresentShell.h\"",
    "extern iRepresentShell*	g_pRepresentShell;	// nhu WndImage.cpp / WndEdit.cpp",
    "#include \"UiWAutoTrang.h\"",
    "#include \"UiWAutoBang.h\"",
    "#include \"../../Platform/JxWAutoNoiBo.h\"",
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <string.h>",
    "",
    "extern \"C\" int JxCore_WAutoDanhSachChieu(IPCSkillInfo* pOut, int nMax);\t// CoreShell.cpp (chi Android)",
    "",
    "#define WA_CHON_CAO\t\t24",
    "#define WA_MENU_TOI_DA\t40",
    "",
    "// Bong (RU_T_SHADOW): KRepresentShell3 ve voi alpha = 255 - (a << 3) -> a trong 0..31, a CANG NHO cang DAC",
    "static void WA_Bong(int x0, int y0, int x1, int y1, int r, int g, int b, int a)",
    "{",
    "\tKRUShadow S;",
    "\tS.oPosition.nX = x0;",
    "\tS.oPosition.nY = y0;",
    "\tS.oPosition.nZ = 0;",
    "\tS.oEndPos.nX = x1;",
    "\tS.oEndPos.nY = y1;",
    "\tS.oEndPos.nZ = 0;",
    "\tS.Color.Color_b.r = (unsigned char)r;",
    "\tS.Color.Color_b.g = (unsigned char)g;",
    "\tS.Color.Color_b.b = (unsigned char)b;",
    "\tS.Color.Color_b.a = (unsigned char)a;",
    "\tg_pRepresentShell->DrawPrimitives(1, &S, RU_T_SHADOW, true);",
    "}",
    "",
    "// Khung vien 1 px (RU_T_RECT -> DrawRectFrame, mau dac)",
    "static void WA_Vien(int x0, int y0, int x1, int y1, int r, int g, int b)",
    "{",
    "\tKRURect R;",
    "\tR.oPosition.nX = x0;",
    "\tR.oPosition.nY = y0;",
    "\tR.oPosition.nZ = 0;",
    "\tR.oEndPos.nX = x1;",
    "\tR.oEndPos.nY = y1;",
    "\tR.oEndPos.nZ = 0;",
    "\tR.Color.Color_b.r = (unsigned char)r;",
    "\tR.Color.Color_b.g = (unsigned char)g;",
    "\tR.Color.Color_b.b = (unsigned char)b;",
    "\tR.Color.Color_b.a = 255;",
    "\tg_pRepresentShell->DrawPrimitives(1, &R, RU_T_RECT, true);",
    "}",
    "",
    "// ---------------------------------------------------------------- o nhap co nen",
    "void KWndNhapWA::PaintWindow()",
    "{",
    "\tif (g_pRepresentShell && (m_Style & WND_S_VISIBLE))",
    "\t{",
    "\t\tWA_Bong(m_nAbsoluteLeft - 3, m_nAbsoluteTop - 2, m_nAbsoluteLeft + m_Width + 3, m_nAbsoluteTop + m_Height + 1, 12, 14, 18, 6);",
    "\t\tWA_Vien(m_nAbsoluteLeft - 3, m_nAbsoluteTop - 2, m_nAbsoluteLeft + m_Width + 2, m_nAbsoluteTop + m_Height, 150, 120, 70);",
    "\t}",
    "\tKWndEdit512::PaintWindow();",
    "}",
    "",
    "// ---------------------------------------------------------------- o nhom",
    "// bo mau theo Mau= (vien r,g,b ; nen tieu de r,g,b) - 6 bo, khac nhau ro tren nen khung toi; chu tieu de trang nga",
    "static const unsigned char s_aMauHop[6][6] = {",
    "\t{ 150, 110,  60,  60, 40, 10 },\t// vang nau",
    "\t{  60, 140, 140,  10, 50, 50 },\t// xanh ngoc",
    "\t{  80, 110, 180,  15, 25, 60 },\t// xanh lam",
    "\t{  90, 150,  80,  15, 50, 15 },\t// xanh la",
    "\t{ 150,  90, 160,  50, 15, 60 },\t// tim",
    "\t{ 190, 120,  50,  70, 35, 10 },\t// cam",
    "};",
    "",
    "KWndHopNhomWA::KWndHopNhomWA()",
    "{",
    "\tm_szTieuDe[0] = 0;",
    "\tm_nMau = 0;",
    "}",
    "",
    "int KWndHopNhomWA::Init(KIniFile* pIniFile, const char* pSection)",
    "{",
    "\tif (!KWndWindow::Init(pIniFile, pSection))",
    "\t\treturn false;",
    "\tm_szTieuDe[0] = 0;",
    "\tpIniFile->GetString(pSection, \"TieuDe\", \"\", m_szTieuDe, sizeof(m_szTieuDe));",
    "\tpIniFile->GetInteger(pSection, \"Mau\", 0, &m_nMau);",
    "\tif (m_nMau < 0 || m_nMau >= 6)",
    "\t\tm_nMau = 0;",
    "\treturn true;",
    "}",
    "",
    "void KWndHopNhomWA::PaintWindow()",
    "{",
    "\tif (!g_pRepresentShell || !(m_Style & WND_S_VISIBLE))",
    "\t\treturn;",
    "\tconst unsigned char* m = s_aMauHop[m_nMau];",
    "\tint x0 = m_nAbsoluteLeft, y0 = m_nAbsoluteTop, x1 = x0 + m_Width, y1 = y0 + m_Height;",
    "\tWA_Bong(x0, y0, x1, y1, 0, 0, 0, 22);\t\t\t\t// toi nhe (~30%) de tach nhom khoi nen khung",
    "\tWA_Bong(x0, y0, x1, y0 + 3, m[3], m[4], m[5], 6);\t// dai mau mong sat mep tren (nhan mau nhom ca khi khong tieu de)",
    "\tWA_Vien(x0, y0, x1 - 1, y1 - 1, m[0], m[1], m[2]);",
    "\tint n = (int)strlen(m_szTieuDe);",
    "\tif (n > 0)",
    "\t{",
    "\t\tWA_Bong(x0 + 8, y0 + 2, x0 + 8 + n * 6 + 10, y0 + 18, m[3], m[4], m[5], 2);\t// nen mau nhom sau tieu de",
    "\t\tWA_Vien(x0 + 8, y0 + 2, x0 + 8 + n * 6 + 10, y0 + 18, m[0], m[1], m[2]);",
    "\t\tg_pRepresentShell->OutputText(12, m_szTieuDe, n, x0 + 13, y0 + 4, 0x00F0EAD8, 0, TEXT_IN_SINGLE_PLANE_COORD, 0x00000000);",
    "\t}",
    "}",
    "",
    "// ---------------------------------------------------------------- trang",
    "KUiWAutoTrang::KUiWAutoTrang()",
    "{",
    "\tm_nTab = -1;",
    "\tm_pTab = NULL;",
    "\tm_nChieu = -1;",
    "\tm_bDangDien = 0;",
    "\tm_nAnTam = 0;",
    "}",
    "",
    "void KUiWAutoTrang::KhoiTao()",
    "{",
    "\tint i;",
    "\tfor (i = 0; i < WA_TR_HOP; i++)\t\tAddChild(&m_Hop[i]);\t// o nhom ve truoc, nam duoi",
    "\tfor (i = 0; i < WA_TR_NHAN; i++)\tAddChild(&m_Nhan[i]);",
    "\tfor (i = 0; i < WA_TR_TICK; i++)\tAddChild(&m_Tick[i]);",
    "\tfor (i = 0; i < WA_TR_NHAP; i++)\tAddChild(&m_Nhap[i]);",
    "\tfor (i = 0; i < WA_TR_CHON; i++)\tAddChild(&m_Chon[i]);",
    "\tfor (i = 0; i < WA_TR_NUT; i++)\t\tAddChild(&m_Nut[i]);",
    "\tAnHet();",
    "}",
    "",
    "void KUiWAutoTrang::AnHet()",
    "{",
    "\tint i;",
    "\tfor (i = 0; i < WA_TR_HOP; i++)\t\tm_Hop[i].Hide();",
    "\tfor (i = 0; i < WA_TR_NHAN; i++)\tm_Nhan[i].Hide();",
    "\tfor (i = 0; i < WA_TR_TICK; i++)\tm_Tick[i].Hide();",
    "\tfor (i = 0; i < WA_TR_NHAP; i++)\tm_Nhap[i].Hide();",
    "\tfor (i = 0; i < WA_TR_CHON; i++)\tm_Chon[i].Hide();",
    "\tfor (i = 0; i < WA_TR_NUT; i++)\t\tm_Nut[i].Hide();",
    "\tm_nAnTam = 0;",
    "}",
    "",
    "const WAUiMuc* KUiWAutoTrang::Muc(int nLoai, int nKhe)",
    "{",
    "\tif (!m_pTab)",
    "\t\treturn NULL;",
    "\tfor (int i = 0; i < m_pTab->nMuc; i++)",
    "\t\tif (m_pTab->pMuc[i].nLoai == nLoai && m_pTab->pMuc[i].nKhe == nKhe)",
    "\t\t\treturn &m_pTab->pMuc[i];",
    "\treturn NULL;",
    "}",
    "",
    "// Dia chi truong trong autoData dang dung: offset + chi so * co phan tu (mang bTKGio[4]...). Chuoi: ca mang.",
    "void* KUiWAutoTrang::DiaChi(const WAUiMuc* p)",
    "{",
    "\tif (!p || p->nOff < 0)",
    "\t\treturn NULL;",
    "\tint nPhanTu = (p->nKieu == WA_KIEU_SHORT) ? 2 : ((p->nKieu == WA_KIEU_CHUOI) ? (int)p->nCo : 4);",
    "\tint nOff = p->nOff + ((p->nKieu == WA_KIEU_CHUOI) ? 0 : (int)p->nChiSo * nPhanTu);",
    "\tif (nPhanTu <= 0 || nOff < 0 || nOff + nPhanTu > WA_SIZEOF_AUTODATA)",
    "\t\treturn NULL;",
    "\tautoData* pCH = JxWAuto_CauHinh();",
    "\tif (!pCH || sizeof(autoData) != WA_SIZEOF_AUTODATA)\t// bang sinh tu ipc_shared.h khac ban dang dich -> khong ghi bua",
    "\t\treturn NULL;",
    "\treturn (BYTE*)pCH + nOff;",
    "}",
    "",
    "int KUiWAutoTrang::LayInt(const WAUiMuc* p)",
    "{",
    "\tvoid* a = DiaChi(p);",
    "\tif (!a)",
    "\t\treturn 0;",
    "\tif (p->nKieu == WA_KIEU_SHORT)",
    "\t\treturn *(short*)a;",
    "\treturn *(int*)a;",
    "}",
    "",
    "void KUiWAutoTrang::DatInt(const WAUiMuc* p, int v)",
    "{",
    "\tvoid* a = DiaChi(p);",
    "\tif (!a)",
    "\t\treturn;",
    "\tif (p->nKieu == WA_KIEU_SHORT)",
    "\t\t*(short*)a = (short)v;",
    "\telse",
    "\t\t*(int*)a = v;",
    "}",
    "",
    "void KUiWAutoTrang::NapTab(int nTab)",
    "{",
    "\tchar Scheme[128];",
    "\tchar Buff[256];",
    "\tchar szMuc[32];",
    "\tKIniFile Ini;",
    "\tint i;",
    "\tif (nTab < 0 || nTab >= WA_TR_SO_TAB)",
    "\t\treturn;",
    "\tm_nTab = nTab;",
    "\tm_pTab = &s_WAUiTab[nTab];",
    "\tAnHet();",
    "\tg_UiBase.GetCurSchemePath(Scheme, 128);",
    "\tsprintf(Buff, \"%s\\\\%s\", Scheme, m_pTab->szIni);",
    "\tif (!Ini.Load(Buff))",
    "\t{",
    "\t\tg_DebugLog(\"[WAUTO-UI] tab %d: khong doc duoc bo cuc %s\", nTab, Buff);",
    "\t\treturn;",
    "\t}",
    "\tInit(&Ini, \"Trang\");",
    "\tfor (i = 0; i < WA_TR_HOP; i++)",
    "\t{",
    "\t\tsprintf(szMuc, \"Hop%d\", i);",
    "\t\tif (Ini.IsSectionExist(szMuc))",
    "\t\t{",
    "\t\t\tm_Hop[i].Init(&Ini, szMuc);",
    "\t\t\tm_Hop[i].Show();",
    "\t\t}",
    "\t}",
    "\tfor (i = 0; i < WA_TR_NHAN; i++)",
    "\t{",
    "\t\tsprintf(szMuc, \"Nhan%d\", i);",
    "\t\tif (Ini.IsSectionExist(szMuc))",
    "\t\t{",
    "\t\t\tm_Nhan[i].SetText(\"\");\t\t// KWndText::Init chi doc Text= khi dang rong",
    "\t\t\tm_Nhan[i].Init(&Ini, szMuc);",
    "\t\t\tm_Nhan[i].Show();",
    "\t\t}",
    "\t}",
    "\tfor (i = 0; i < m_pTab->nMuc; i++)",
    "\t{",
    "\t\tconst WAUiMuc& m = m_pTab->pMuc[i];",
    "\t\tswitch (m.nLoai)",
    "\t\t{",
    "\t\tcase WA_MUC_TICK:",
    "\t\t\tsprintf(szMuc, \"Tick%d\", m.nKhe);",
    "\t\t\tif (m.nKhe < WA_TR_TICK && Ini.IsSectionExist(szMuc))",
    "\t\t\t{",
    "\t\t\t\tm_Tick[m.nKhe].Init(&Ini, szMuc);",
    "\t\t\t\tm_Tick[m.nKhe].Show();",
    "\t\t\t\tm_Tick[m.nKhe].Enable(m.nOff >= 0);",
    "\t\t\t}",
    "\t\t\tbreak;",
    "\t\tcase WA_MUC_NHAP:",
    "\t\t\tsprintf(szMuc, \"Nhap%d\", m.nKhe);",
    "\t\t\tif (m.nKhe < WA_TR_NHAP && Ini.IsSectionExist(szMuc))",
    "\t\t\t{",
    "\t\t\t\tm_Nhap[m.nKhe].Init(&Ini, szMuc);",
    "\t\t\t\tm_Nhap[m.nKhe].Show();",
    "\t\t\t\tm_Nhap[m.nKhe].Enable(m.nOff >= 0);",
    "\t\t\t}",
    "\t\t\tbreak;",
    "\t\tcase WA_MUC_CHON:",
    "\t\t\tsprintf(szMuc, \"Chon%d\", m.nKhe);",
    "\t\t\tif (m.nKhe < WA_TR_CHON && Ini.IsSectionExist(szMuc))",
    "\t\t\t{",
    "\t\t\t\tm_Chon[m.nKhe].Init(&Ini, szMuc);",
    "\t\t\t\tm_Chon[m.nKhe].Show();",
    "\t\t\t\tm_Chon[m.nKhe].Enable(m.nOff >= 0 && m.nNguon != WA_NGUON_KHAC);",
    "\t\t\t}",
    "\t\t\tbreak;",
    "\t\tcase WA_MUC_NUT:",
    "\t\t\tsprintf(szMuc, \"Nut%d\", m.nKhe);",
    "\t\t\tif (m.nKhe < WA_TR_NUT && Ini.IsSectionExist(szMuc))",
    "\t\t\t{",
    "\t\t\t\tm_Nut[m.nKhe].Init(&Ini, szMuc);",
    "\t\t\t\tm_Nut[m.nKhe].Show();",
    "\t\t\t\tm_Nut[m.nKhe].Enable(0);\t\t// (B2) nut hanh dong: lam o buoc cua tung tab",
    "\t\t\t}",
    "\t\t\tbreak;",
    "\t\tdefault:",
    "\t\t\tbreak;",
    "\t\t}",
    "\t}",
    "\tDienGiaTri();",
    "\tg_DebugLog(\"[WAUTO-UI] tab %d: %d muc, %d hang, %d cot (%s)\", nTab, m_pTab->nMuc, m_pTab->nHang, m_pTab->nCot, m_pTab->szIni);",
    "}",
    "",
    "void KUiWAutoTrang::DienGiaTri()",
    "{",
    "\tif (!m_pTab)",
    "\t\treturn;",
    "\tm_nChieu = -1;\t\t// nap lai danh sach chieu (nhan vat vua hoc them chieu)",
    "\tm_bDangDien = 1;",
    "\tfor (int i = 0; i < m_pTab->nMuc; i++)",
    "\t{",
    "\t\tconst WAUiMuc& m = m_pTab->pMuc[i];",
    "\t\tswitch (m.nLoai)",
    "\t\t{",
    "\t\tcase WA_MUC_TICK:",
    "\t\t\tif (m.nKhe < WA_TR_TICK)",
    "\t\t\t\tm_Tick[m.nKhe].CheckButton(LayInt(&m) ? 1 : 0);",
    "\t\t\tbreak;",
    "\t\tcase WA_MUC_NHAP:",
    "\t\t\tif (m.nKhe < WA_TR_NHAP)",
    "\t\t\t{",
    "\t\t\t\tif (m.nKieu == WA_KIEU_CHUOI)",
    "\t\t\t\t{",
    "\t\t\t\t\tconst char* a = (const char*)DiaChi(&m);",
    "\t\t\t\t\tm_Nhap[m.nKhe].SetText(a ? a : \"\");",
    "\t\t\t\t}",
    "\t\t\t\telse",
    "\t\t\t\t\tm_Nhap[m.nKhe].SetIntText(LayInt(&m));",
    "\t\t\t}",
    "\t\t\tbreak;",
    "\t\tcase WA_MUC_CHON:",
    "\t\t\tDienChon(&m);",
    "\t\t\tbreak;",
    "\t\tdefault:",
    "\t\t\tbreak;",
    "\t\t}",
    "\t}",
    "\tm_bDangDien = 0;",
    "}",
    "",
    "void KUiWAutoTrang::NapChieu()",
    "{",
    "\tm_nChieu = JxCore_WAutoDanhSachChieu(m_aChieu, defSKILLNUMGET);",
    "\tif (m_nChieu < 0)",
    "\t\tm_nChieu = 0;",
    "\tif (m_nChieu > defSKILLNUMGET)",
    "\t\tm_nChieu = defSKILLNUMGET;",
    "}",
    "",
    "void KUiWAutoTrang::DienChon(const WAUiMuc* p)",
    "{",
    "\tchar sz[64];",
    "\tint i, v;",
    "\tif (!p || p->nKhe >= WA_TR_CHON)",
    "\t\treturn;",
    "\tv = LayInt(p);",
    "\tsz[0] = 0;",
    "\tif (p->nNguon == WA_NGUON_CHIEU)",
    "\t{",
    "\t\tif (m_nChieu < 0)",
    "\t\t\tNapChieu();",
    "\t\tif (v == 0)",
    "\t\t\tstrcpy(sz, %s);" % C("Không thiết lập"),
    "\t\telse",
    "\t\t{",
    "\t\t\tsnprintf(sz, sizeof(sz), \"#%d\", v);",
    "\t\t\tfor (i = 0; i < m_nChieu; i++)",
    "\t\t\t\tif (m_aChieu[i].nId == v)",
    "\t\t\t\t{",
    "\t\t\t\t\tstrncpy(sz, m_aChieu[i].szName, 31);",
    "\t\t\t\t\tsz[31] = 0;",
    "\t\t\t\t\tbreak;",
    "\t\t\t\t}",
    "\t\t}",
    "\t}",
    "\telse if (p->pLuaChon && p->nLuaChon > 0)",
    "\t{",
    "\t\tif (v < 0 || v >= (int)p->nLuaChon)",
    "\t\t\tv = 0;",
    "\t\tstrncpy(sz, p->pLuaChon[v], 31);",
    "\t\tsz[31] = 0;",
    "\t}",
    "\telse",
    "\t\tstrcpy(sz, %s);" % C("(chưa hỗ trợ)"),
    "\t// chu dai hon phan trai mui ten (rong - 24) / 6 ky tu -> cat + \"..\" (menu van hien du)",
    "\t{",
    "\t\tint w = 0, h = 0, nMax;",
    "\t\tm_Chon[p->nKhe].GetSize(&w, &h);",
    "\t\tnMax = (w - 24) / 6;",
    "\t\tif (nMax >= 4 && (int)strlen(sz) > nMax)",
    "\t\t{",
    "\t\t\tsz[nMax - 2] = '.';",
    "\t\t\tsz[nMax - 1] = '.';",
    "\t\t\tsz[nMax] = 0;",
    "\t\t}",
    "\t}",
    "\tm_Chon[p->nKhe].SetLabel(sz);",
    "}",
    "",
    "void KUiWAutoTrang::MoMenuChon(int nKhe)",
    "{",
    "\tconst WAUiMuc* p = Muc(WA_MUC_CHON, nKhe);",
    "\tint i, n = 0, x = 0, y = 0;",
    "\tif (!p || nKhe >= WA_TR_CHON)",
    "\t\treturn;",
    "\tif (p->nNguon == WA_NGUON_CHIEU)",
    "\t{",
    "\t\tNapChieu();",
    "\t\tn = m_nChieu + 1;",
    "\t}",
    "\telse if (p->pLuaChon)",
    "\t\tn = p->nLuaChon;",
    "\tif (n <= 0)",
    "\t\treturn;",
    "\tif (n > WA_MENU_TOI_DA)",
    "\t\tn = WA_MENU_TOI_DA;",
    "\tKPopupMenuData* pMenu = (KPopupMenuData*)malloc(MENU_DATA_SIZE(n));",
    "\tif (!pMenu)",
    "\t\treturn;",
    "\tKPopupMenu::InitMenuData(pMenu, n);\t\t// uID = chi so",
    "\tpMenu->nNumItem = 0;",
    "\tpMenu->usMenuFlag |= PM_F_AUTO_DEL_WHEN_HIDE;",
    "\tfor (i = 0; i < n; i++)",
    "\t{",
    "\t\tconst char* s = (p->nNguon == WA_NGUON_CHIEU) ? ((i == 0) ? %s : m_aChieu[i - 1].szName) : p->pLuaChon[i];" % C("Không thiết lập"),
    "\t\tstrncpy(pMenu->Items[i].szData, s ? s : \"\", 63);",
    "\t\tpMenu->Items[i].szData[63] = 0;",
    "\t\tpMenu->Items[i].uDataLen = strlen(pMenu->Items[i].szData);",
    "\t\tpMenu->nNumItem++;",
    "\t}",
    "\tm_Chon[nKhe].GetAbsolutePos(&x, &y);",
    "\tpMenu->nX = x;",
    "\tpMenu->nY = y + WA_CHON_CAO;\t\t// ALW: nua duoi man hinh thi menu mo LEN tren diem nay",
    "\tKPopupMenu::Popup(pMenu, this, nKhe);",
    "\tAnDuoiMenu(1);",
    "}",
    "",
    "void KUiWAutoTrang::ChonMenu(int nKhe, int nMuc)",
    "{",
    "\tconst WAUiMuc* p = Muc(WA_MUC_CHON, nKhe);",
    "\tint v;",
    "\tif (!p || nMuc < 0)",
    "\t\treturn;",
    "\tif (p->nNguon == WA_NGUON_CHIEU)",
    "\t\tv = (nMuc == 0 || nMuc - 1 >= m_nChieu) ? 0 : m_aChieu[nMuc - 1].nId;",
    "\telse",
    "\t\tv = nMuc;",
    "\tDatInt(p, v);",
    "\tDienChon(p);",
    "\tDaDoi();",
    "\tg_DebugLog(\"[WAUTO-UI] %s = %d\", p->szIdc, v);",
    "}",
    "",
    "// Trinh chieu Android ve anh / chu cua cua so SAU bong menu (menu bi chu cua trang de len) -> tam an widget nam duoi menu",
    "void KUiWAutoTrang::ThuAn(KWndWindow* p, int x0, int y0, int x1, int y1)",
    "{",
    "\tint l = 0, t = 0, w = 0, h = 0;",
    "\tif (!p->IsVisible() || m_nAnTam >= WA_TR_AN_TOI_DA)",
    "\t\treturn;",
    "\tp->GetAbsolutePos(&l, &t);",
    "\tp->GetSize(&w, &h);",
    "\tif (l < x1 && l + w > x0 && t < y1 && t + h > y0)",
    "\t{",
    "\t\tp->Hide();",
    "\t\tm_apAnTam[m_nAnTam++] = p;",
    "\t}",
    "}",
    "",
    "void KUiWAutoTrang::AnDuoiMenu(int bAn)",
    "{",
    "\tint i;",
    "\tif (!bAn)",
    "\t{",
    "\t\tfor (i = 0; i < m_nAnTam; i++)",
    "\t\t\tm_apAnTam[i]->Show();",
    "\t\tm_nAnTam = 0;",
    "\t\treturn;",
    "\t}",
    "\tKPopupMenuData* pM = KPopupMenu::GetMenuData();",
    "\tif (!pM)",
    "\t\treturn;",
    "\tint x0 = pM->nX - 2, y0 = pM->nY - 2;",
    "\tint x1 = pM->nX + pM->nItemWidth + 2, y1 = pM->nY + pM->nItemHeight * pM->nNumItem + 4;",
    "\tfor (i = 0; i < WA_TR_NHAN; i++)\tThuAn(&m_Nhan[i], x0, y0, x1, y1);",
    "\tfor (i = 0; i < WA_TR_TICK; i++)\tThuAn(&m_Tick[i], x0, y0, x1, y1);",
    "\tfor (i = 0; i < WA_TR_NHAP; i++)\tThuAn(&m_Nhap[i], x0, y0, x1, y1);",
    "\tfor (i = 0; i < WA_TR_CHON; i++)\tThuAn(&m_Chon[i], x0, y0, x1, y1);",
    "\tfor (i = 0; i < WA_TR_NUT; i++)\t\tThuAn(&m_Nut[i], x0, y0, x1, y1);",
    "}",
    "",
    "void KUiWAutoTrang::Breathe()",
    "{",
    "\tif (m_nAnTam > 0 && KPopupMenu::GetMenuData() == NULL)\t// menu bi huy ma khong bao (Cancel tu noi khac)",
    "\t\tAnDuoiMenu(0);",
    "}",
    "",
    "void KUiWAutoTrang::DaDoi()",
    "{",
    "\tJxWAuto_LuuCauHinh();",
    "}",
    "",
    "int KUiWAutoTrang::WndProc(unsigned int uMsg, KUPARAM uParam, KNPARAM nParam)",
    "{",
    "\tint i;",
    "\tif (uMsg == WND_N_BUTTON_CLICK)",
    "\t{",
    "\t\tfor (i = 0; i < WA_TR_TICK; i++)",
    "\t\t\tif (uParam == (KUPARAM)(KWndWindow*)&m_Tick[i])",
    "\t\t\t{",
    "\t\t\t\tconst WAUiMuc* p = Muc(WA_MUC_TICK, i);",
    "\t\t\t\tif (p)",
    "\t\t\t\t{",
    "\t\t\t\t\tint v = LayInt(p) ? 0 : 1;",
    "\t\t\t\t\tDatInt(p, v);",
    "\t\t\t\t\tm_Tick[i].CheckButton(v);",
    "\t\t\t\t\tDaDoi();",
    "\t\t\t\t\tg_DebugLog(\"[WAUTO-UI] %s = %d\", p->szIdc, v);",
    "\t\t\t\t}",
    "\t\t\t\treturn 1;",
    "\t\t\t}",
    "\t\tfor (i = 0; i < WA_TR_CHON; i++)",
    "\t\t\tif (uParam == (KUPARAM)(KWndWindow*)&m_Chon[i])",
    "\t\t\t{",
    "\t\t\t\tMoMenuChon(i);",
    "\t\t\t\treturn 1;",
    "\t\t\t}",
    "\t\tfor (i = 0; i < WA_TR_NUT; i++)",
    "\t\t\tif (uParam == (KUPARAM)(KWndWindow*)&m_Nut[i])",
    "\t\t\t\treturn 1;\t\t// (B2) chua co hanh dong",
    "\t}",
    "\telse if (uMsg == WND_N_EDIT_CHANGE && !m_bDangDien)",
    "\t{",
    "\t\tfor (i = 0; i < WA_TR_NHAP; i++)",
    "\t\t\tif (uParam == (KUPARAM)(KWndWindow*)&m_Nhap[i])",
    "\t\t\t{",
    "\t\t\t\tconst WAUiMuc* p = Muc(WA_MUC_NHAP, i);",
    "\t\t\t\tif (p)",
    "\t\t\t\t{",
    "\t\t\t\t\tif (p->nKieu == WA_KIEU_CHUOI)",
    "\t\t\t\t\t{",
    "\t\t\t\t\t\tchar* a = (char*)DiaChi(p);",
    "\t\t\t\t\t\tif (a && p->nCo > 0)",
    "\t\t\t\t\t\t{",
    "\t\t\t\t\t\t\tm_Nhap[i].GetText(a, p->nCo, false);",
    "\t\t\t\t\t\t\ta[p->nCo - 1] = 0;",
    "\t\t\t\t\t\t}",
    "\t\t\t\t\t}",
    "\t\t\t\t\telse",
    "\t\t\t\t\t\tDatInt(p, m_Nhap[i].GetIntNumber());",
    "\t\t\t\t\tDaDoi();",
    "\t\t\t\t}",
    "\t\t\t\treturn 1;",
    "\t\t\t}",
    "\t}",
    "\telse if (uMsg == WND_M_MENUITEM_SELECTED)",
    "\t{",
    "\t\tif (uParam == (KUPARAM)(KWndWindow*)this)",
    "\t\t{",
    "\t\t\tAnDuoiMenu(0);",
    "\t\t\tif ((short)LOWORD(nParam) >= 0)",
    "\t\t\t\tChonMenu((int)HIWORD(nParam), (int)(short)LOWORD(nParam));",
    "\t\t\treturn 1;",
    "\t\t}",
    "\t}",
    "\treturn KWndWindow::WndProc(uMsg, uParam, nParam);",
    "}",
    "#endif // JX_ANDROID",
]


# ---------------------------------------------------------------- 2. UiWAuto.h / .cpp
def va_uiwauto_h(s):
    s = thay(s, ["#include \"../Elem/WndText.h\""],
                ["#include \"../Elem/WndText.h\"",
                 "#include \"UiWAutoTrang.h\"\t// %s trang noi dung chay theo bang" % DAU], "UiWAuto.h: include")
    s = thay(s, ["\tKWndText80\t\tm_TenTab;\t\t// (B1) ten tab dang chon, giua vung noi dung con trong"],
                ["\tKWndText80\t\tm_TenTab;\t\t// (B1) ten tab dang chon - tu B2 chi hien khi tab chua co noi dung",
                 "\tKUiWAutoTrang\tm_Trang;\t\t// %s trang noi dung (kho widget dung chung 15 tab)" % DAU], "UiWAuto.h: m_Trang")
    return s


def va_uiwauto_cpp(s):
    s = thay(s, ["#define SCHEME_INI\t\"UiWAuto.ini\""],
                ["#define SCHEME_INI\t\"UiWAuto.ini\"",
                 "",
                 "// %s (nhom, tab con) -> so hieu tab toan cuc (thu tu TEN_TAB cua sinh_bang_wauto.py = thu tu the WAuto.exe): dung de NapTab" % DAU,
                 "static const int s_aNhomTabId[WA_UI_SO_NHOM][WA_UI_TAB_MOI_NHOM] = {",
                 "\t{ 2, 13, 7, 3, 4, -1, -1, -1 },\t// Dieu khien: Chien dau, Chieu KH, PK, Di chuyen, Nhat do",
                 "\t{ 5, 1, 6, -1, -1, -1, -1, -1 },\t// Hau can: Hau can, Phuc hoi, To doi",
                 "\t{ 0, -1, -1, -1, -1, -1, -1, -1 },\t// Cai dat: Co ban",
                 "\t{ 8, 9, 14, 10, 12, 11, -1, -1 },\t// Hoat dong: Da Tau, Tong Kim, CTC, Lien dau, Sat thu, H.dong",
                 "};"], "UiWAuto.cpp: bang tab id")
    s = thay(s, ["\tAddChild(&m_TenTab);",
                 "\tAddChild(&m_Dong);"],
                ["\tAddChild(&m_TenTab);",
                 "\tm_Trang.KhoiTao();\t\t\t\t// %s kho widget cua trang, roi moi ghep trang vao khung" % DAU,
                 "\tAddChild(&m_Trang);",
                 "\tAddChild(&m_Dong);"], "UiWAuto.cpp: AddChild trang")
    s = thay(s, ["\tm_TenTab.SetText(sz);",
                 "}"],
                ["\tm_TenTab.SetText(sz);",
                 "\t// %s nap trang noi dung cua tab nay (bang sinh tu WAuto.rc); co noi dung thi giau dong ten tab" % DAU,
                 "\t{",
                 "\t\tint nId = s_aNhomTabId[m_nNhom][nTab];",
                 "\t\tif (nId >= 0)",
                 "\t\t{",
                 "\t\t\tm_Trang.NapTab(nId);",
                 "\t\t\tm_Trang.Show();",
                 "\t\t\tm_TenTab.Hide();",
                 "\t\t}",
                 "\t\telse",
                 "\t\t{",
                 "\t\t\tm_Trang.Hide();",
                 "\t\t\tm_TenTab.Show();",
                 "\t\t}",
                 "\t}",
                 "}"], "UiWAuto.cpp: ChonTab -> NapTab")
    s = thay(s, ["\t\tm_pSelf->CapNhatTrangThai(1);",
                 "\t\tm_pSelf->Show();"],
                ["\t\tm_pSelf->CapNhatTrangThai(1);",
                 "\t\tm_pSelf->m_Trang.DienGiaTri();\t// %s cau hinh co the da doi (nhan vat khac / tep .dat moi)" % DAU,
                 "\t\tm_pSelf->Show();"], "UiWAuto.cpp: OpenWindow -> DienGiaTri")
    return va_uiwauto_cpp_b(s)


def va_uiwauto_cpp_b(s):
    # LetMeBreathe chi di theo chuoi cua so GOC -> cha phai goi Breathe cua trang (an lai widget khi menu chon bi huy)
    return thay(s, ["\tCapNhatBatTat();",
                    "\tCapNhatTrangThai(0);",
                    "}"],
                   ["\tCapNhatBatTat();",
                    "\tCapNhatTrangThai(0);",
                    "\tm_Trang.Breathe();\t\t// %s LetMeBreathe chi toi cua so goc" % DAU2,
                    "}"], "UiWAuto.cpp: Breathe -> trang")


# ---------------------------------------------------------------- 2c. UiWAuto.h/.cpp: nut nhom / tab / BAT-TAT nam duoi menu chon -> tam an
DAU3 = "[ANDROID 11/09 WAUTO B2 c]"


def va_uiwauto_h_c(s):
    s = thay(s, ["\tvoid\tCapNhatTrangThai(int bEp);"],
                ["\tvoid\tCapNhatTrangThai(int bEp);",
                 "\tvoid\tAnDuoiMenu();\t\t\t\t// %s menu chon cua trang mo (danh sach chieu dai) de len dai nut -> tam an nut" % DAU3,
                 "\tKWndWindow*\tm_apAnTam[WA_UI_SO_NHOM + WA_UI_TAB_MOI_NHOM + 3];",
                 "\tint\t\tm_nAnTam;"], "UiWAuto.h: AnDuoiMenu")
    return s


def va_uiwauto_cpp_c(s):
    s = thay(s, ["#include \"../../Platform/JxWAutoNoiBo.h\"",
                 "#include <stdio.h>"],
                ["#include \"../../Platform/JxWAutoNoiBo.h\"",
                 "#include \"../Elem/PopupMenu.h\"\t// %s" % DAU3,
                 "#include <stdio.h>"], "UiWAuto.cpp: include PopupMenu")
    s = thay(s, ["\tm_nBatCu = -1;",
                 "\tm_uTrangThaiKe = 0;",
                 "}"],
                ["\tm_nBatCu = -1;",
                 "\tm_uTrangThaiKe = 0;",
                 "\tm_nAnTam = 0;",
                 "}"], "UiWAuto.cpp: ctor m_nAnTam")
    s = thay(s, ["\tm_Trang.Breathe();\t\t// %s LetMeBreathe chi toi cua so goc" % DAU2,
                 "}"],
                ["\tm_Trang.Breathe();\t\t// %s LetMeBreathe chi toi cua so goc" % DAU2,
                 "\tAnDuoiMenu();",
                 "}",
                 "",
                 "// %s Trinh chieu Android ve anh / chu cua cua so SAU bong menu -> nut nhom / tab / BAT-TAT nam duoi menu chon (dang mo) tam an," % DAU3,
                 "// menu dong thi hien lai. Chay moi nhip (Breathe) nen tre nhieu nhat mot khung hinh.",
                 "void KUiWAuto::AnDuoiMenu()",
                 "{",
                 "\tKPopupMenuData* pM = KPopupMenu::GetMenuData();",
                 "\tint i;",
                 "\tif (!pM)",
                 "\t{",
                 "\t\tfor (i = 0; i < m_nAnTam; i++)",
                 "\t\t\tm_apAnTam[i]->Show();",
                 "\t\tm_nAnTam = 0;",
                 "\t\treturn;",
                 "\t}",
                 "\tif (m_nAnTam > 0)",
                 "\t\treturn;",
                 "\tint x0 = pM->nX - 2, y0 = pM->nY - 2, x1 = pM->nX + pM->nItemWidth + 2, y1 = pM->nY + pM->nItemHeight * pM->nNumItem + 4;",
                 "\tKWndWindow* ap[WA_UI_SO_NHOM + WA_UI_TAB_MOI_NHOM + 3];",
                 "\tint n = 0;",
                 "\tfor (i = 0; i < WA_UI_SO_NHOM; i++)\t\tap[n++] = &m_Nhom[i];",
                 "\tfor (i = 0; i < WA_UI_TAB_MOI_NHOM; i++)\tap[n++] = &m_Tab[i];",
                 "\tap[n++] = &m_BatTat;",
                 "\tap[n++] = &m_TrangThai;",
                 "\tap[n++] = &m_Dong;",
                 "\tfor (i = 0; i < n; i++)",
                 "\t{",
                 "\t\tint l = 0, t = 0, w = 0, h = 0;",
                 "\t\tif (!ap[i]->IsVisible())",
                 "\t\t\tcontinue;",
                 "\t\tap[i]->GetAbsolutePos(&l, &t);",
                 "\t\tap[i]->GetSize(&w, &h);",
                 "\t\tif (l < x1 && l + w > x0 && t < y1 && t + h > y0)",
                 "\t\t{",
                 "\t\t\tap[i]->Hide();",
                 "\t\t\tm_apAnTam[m_nAnTam++] = ap[i];",
                 "\t\t}",
                 "\t}",
                 "}"], "UiWAuto.cpp: AnDuoiMenu")
    return s


# ---------------------------------------------------------------- 3. CoreShell.cpp
def va_coreshell(s):
    return thay(s, ["\tWA_HoatDong(CLIENT_PLAYER_INDEX, szOut, nMax);",
                    "\treturn szOut[0] ? 1 : 0;",
                    "}",
                    "#endif\t// JX_ANDROID"],
                   ["\tWA_HoatDong(CLIENT_PLAYER_INDEX, szOut, nMax);",
                    "\treturn szOut[0] ? 1 : 0;",
                    "}",
                    "",
                    "// %s Danh sach chieu cua nhan vat cho hop chon chieu trong khung WAuto (UiWAutoTrang.cpp) - cung ham" % DAU,
                    "// GetAllSkillByType ma KProtocolProcess dung de dien IPCMainSync.skill[] cho WAuto.exe. Tra so chieu (<= defSKILLNUMGET). Chi Android.",
                    "extern \"C\" int JxCore_WAutoDanhSachChieu(IPCSkillInfo* pOut, int nMax)",
                    "{",
                    "\tif (!pOut || nMax < defSKILLNUMGET)",
                    "\t\treturn 0;",
                    "\tint nIdx = Player[CLIENT_PLAYER_INDEX].m_nIndex;",
                    "\tif (nIdx <= 0)",
                    "\t\treturn 0;",
                    "\treturn Npc[nIdx].m_SkillList.GetAllSkillByType(pOut);",
                    "}",
                    "#endif\t// JX_ANDROID"], "CoreShell.cpp: JxCore_WAutoDanhSachChieu")


# ---------------------------------------------------------------- 4. CMakeLists.txt
def va_cmake(s):
    nl = nl_cua(s)
    dong = [d for d in s.split(nl) if "UiCase/UiWAuto.cpp)" in d]
    if len(dong) != 1:
        raise SystemExit("CMakeLists.txt: khong thay dong UiWAuto.cpp) (%d)" % len(dong))
    cu = dong[0]
    moi = cu.replace("UiWAuto.cpp)", "UiWAuto.cpp ") + nl + \
        "    ${JX_SRC}/S3Client/Ui/UiCase/UiWAutoTrang.cpp)     # %s trang noi dung chay theo bang (UiWAutoBang.h sinh bang may)" % DAU
    return s.replace(cu, moi)


tao("Sources/S3Client/Ui/UiCase/UiWAutoTrang.h", H, DAU)
tao("Sources/S3Client/Ui/UiCase/UiWAutoTrang.cpp", CPP, DAU)
va("Sources/S3Client/Ui/UiCase/UiWAuto.h", DAU, va_uiwauto_h)
va("Sources/S3Client/Ui/UiCase/UiWAuto.cpp", DAU, va_uiwauto_cpp)
va("Sources/S3Client/Ui/UiCase/UiWAuto.cpp", DAU2, va_uiwauto_cpp_b)
va("Sources/S3Client/Ui/UiCase/UiWAuto.h", DAU3, va_uiwauto_h_c)
va("Sources/S3Client/Ui/UiCase/UiWAuto.cpp", DAU3, va_uiwauto_cpp_c)
va("Sources/Core/Src/CoreShell.cpp", DAU, va_coreshell)
va("android/CMakeLists.txt", DAU, va_cmake)
print("xong")
