# -*- coding: utf-8 -*-
"""Sinh AUTO_SATTHU_SPEC.md - dac ta day du he San Boss Sat Thu cho phien WAuto.
Doc thang tu DU LIEU DANG CHAY (killer.txt, killbosshead.lua, autoexec_npc_hd3.lua)
nen chay lai bat cu luc nao du lieu doi.
"""
import io, os, re, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SRV = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
OUT = r"D:\GAMEDEVNEW\AUTO_SATTHU_SPEC.md"

kt = io.open(os.path.join(SRV, "settings", "task", "tollgate", "killer", "killer.txt"),
             encoding="latin-1", newline="").read().split("\n")
rows = {}
for l in kt[1:]:
    c = l.rstrip("\r").split("\t")
    if len(c) >= 3 and c[0].isdigit():
        rows[int(c[0])] = (c[1].strip(), c[2].strip())

kb = io.open(os.path.join(SRV, "script", "task", "tollgate", "killbosshead.lua"),
             encoding="latin-1", newline="").read().split("\n")
st = next(i for i, l in enumerate(kb) if l.startswith("addkillertasknpc"))
pos = []
for l in kb[st:st + 400]:
    m = re.match(r"\s*\{(\d+),(\d+),(\d+),(\d+),(\d+),(\d+),\"([^\"]*)\"", l)
    if m:
        pos.append((int(m.group(3)), int(m.group(4)), int(m.group(5))))
    if l.startswith("}"):
        break

ax = io.open(os.path.join(SRV, "script", "global", "autoexec_npc_hd3.lua"),
             encoding="latin-1", newline="").read()
npc = re.findall(r"\{769,(\d+),(\d+),(\d+),", ax)

L = []
A = L.append
BT = chr(96)          # dau backtick
A("# DAC TA HE SAN BOSS SAT THU - cho phien viet WAuto tu dong")
A("")
A("> Sinh tu dong boi " + BT + "ReverseTools/gen_spec_satthu.py" + BT + " tu DU LIEU DANG CHAY.")
A("> Nguon goc: ban Linux da port 25/08 (xem " + BT + "BANGIAO_3HOATDONG_2508.md" + BT + ").")
A("")
A("## 1. Tong quan vong choi")
A("")
A("```")
A("NPC 769 \"Nhiep Thi Tran\" (7 thanh)")
A("  |- menu \"Nhiem vu cap 90\"  ->  hien 20 boss (so 141..160), NGUOI CHOI TU CHON 1")
A("  |     |- givetask(n)  ->  nt_setTask(1082, n)      [da nhan nhiem vu]")
A("  |          |- toi map boss, giet DUNG con boss so n")
A("  |               |- nhan: EXP + 1 Sat Thu lenh (cap nhom, NGU HANH THEO BOSS)")
A("  |                    |- task 1082 ve 0, task 1193 +1   [1 luot / 8 luot moi ngay]")
A("  |- menu \"Hop thanh sat thu gian\"  ->  bo 5 Sat Thu lenh CUNG CAP -> 1 Sat Thu Gian")
A("```")
A("")
A("## 2. Task ID (server dong bo sang client qua nt_setTask -> SyncTaskValue)")
A("")
A("| Task | Y nghia | Dung cho auto |")
A("|---|---|---|")
A("| **1082** | so hieu boss dang truy na (1..160); **0 = chua nhan** | biet co nhiem vu khong, va con nao |")
A("| **1193** | so lan da giet **hom nay** (tran 8) | biet con luot khong |")
A("| 1192 | ngay nhan (yymmdd) - engine tu reset 1193 khi sang ngay | khong can dung |")
A("| 1217 | he thuong phu | khong can |")
A("")
A("Doc tu client: " + BT + "g_pCoreShell->GetGameData(GDI_TASK_SAVE_VALUE, <task>, 0)" + BT)
A("(khuon " + BT + "DTG_TaskVal" + BT + " trong " + BT + "UiTaskGuide.cpp" + BT + ").")
A("")
A("## 3. Gioi han / dieu kien")
A("")
A("- **8 luot/ngay** (KILLER_MAXCOUNT; chinh o cauhinh_hoatdong.lua khoa HD3_ST_MAX_NGAY).")
A("- Chi **nhom cap 90** con phat thuong (yeu cau cap nhan vat 90..350).")
A("- Dang co nhiem vu (1082 != 0) thi **khong nhan them** - phai giet xong hoac huy.")
A("- Huy nhiem vu: muc thoai \"Huy nhiem vu.\" (/cancel) hoac nut **Bo nhiem vu** tren F11.")
A("")
A("## 4. Vat pham")
A("")
A("| Bo | Ten | Ghi chu |")
A("|---|---|---|")
A("| " + BT + "6,1,398" + BT + " | **Sat Thu lenh** | nLevel = cap nhom (20/30/.../90), nSeries = ngu hanh **theo con boss** (0 Kim, 1 Moc, 2 Thuy, 3 Hoa, 4 Tho) |")
A("| " + BT + "6,1,399" + BT + " | **Sat Thu Gian** | ghep tu 5 lenh cung cap; ngu hanh **random** trong 5 he cua 5 lenh da bo vao |")
A("| " + BT + "6,1,2356" + BT + " | Sat Thu Bi Bao | dung can **6 Huyen Thien Chuy** (6,1,2357) |")
A("")
A("**LUU Y ENGINE**: tao item bang Lua phai du **>= 7 tham so**:")
A(BT + "AddItem(6,1,398,<cap>,<he>,0,0)" + BT + " - thieu tham so thi JX1 **khong tao item va IM LANG**.")
A("")
A("## 5. QUY TRINH GHEP SAT THU LENH (auto phai lam dung thu tu)")
A("")
A("```")
A("1. Mo thoai NPC 769  ->  chon muc \"Hop thanh sat thu gian\"   (ham compose)")
A("2. Server mo GiveItemUI (giao dien bo do vao)  ->  callback exchange_token")
A("3. Auto bo DUNG 5 Sat Thu lenh (6,1,398) CUNG MOT CAP vao o")
A("4. Bam xac nhan  ->  server kiem theo thu tu:")
A("      - co item KHAC 6,1,398 lan vao   -> bao loi, KHONG ghep")
A("      - du 5 nhung KHAC CAP nhau       -> bao loi, KHONG ghep")
A("      - nhieu hon 5                    -> bao \"de qua nhieu\"")
A("      - it hon 5                       -> bao \"de qua it\"")
A("      - DUNG 5 cai CUNG CAP            -> xoa 5 lenh, tao 1 Sat Thu Gian")
A("5. Ngu hanh Gian = random 1 trong 5 he cua 5 lenh vua bo (ham givesword)")
A("```")
A("")
A("**Dieu kien phu**: tui can it nhat 1 o trong (nen chua 3 o).")
A("Sat Thu Gian la **ve vao Vuot Ai (Thach thuc thoi gian)**: doi truong mang **2 Gian**")
A("cap 90 di bao danh (so cap: 2 Gian duoi cap 90).")
A("")
A("## 6. Vi tri NPC 769 (7 thanh)")
A("")
A("| Map | O X | O Y |")
A("|---|---|---|")
for m in npc:
    A("| %s | %s | %s |" % (m[0], m[1], m[2]))
A("")
A("Client tim NPC nen dung **template id 769** (Npc[i].m_NpcSettingIdx == 769),")
A("KHONG so theo ten (ten TCVN3 co byte cao, g_StrLower co the doi byte).")
A("")
A("## 7. Bang 160 boss")
A("")
A("Du lieu da sinh san cho C++:")
A("- " + BT + "Sources/Core/Src/KSatThuBossPos.h" + BT + " : s_nST3BossMap/X/Y, s_szST3BossMenu/Moc, s_nST3Npc*")
A("- " + BT + "Sources/S3Client/Ui/UiCase/UiTaskGuideSatThuBoss.h" + BT + " : s_szST3BossName/Info")
A("- Chay lai: " + BT + "python ReverseTools/gen_satthu_boss_table.py" + BT)
A("")
A("**Nhom cap 90 = so hieu 141..160** (nhom duy nhat con thuong):")
A("")
A("| So | Ten boss | Map | O X | O Y | Noi o (bang nhiem vu) |")
A("|---|---|---|---|---|---|")
for i in range(141, 161):
    ten, noi = rows.get(i, ("?", "?"))
    p = pos[i - 1]
    A("| %d | %s | %d | %d | %d | %s |" % (i, ten, p[0], p[1], p[2], noi))
A("")
A("## 8. Da co san trong client (auto dung lai duoc ngay)")
A("")
A("| Thu | O dau | Viec |")
A("|---|---|---|")
A("| GOI_TASKGUIDE_GOTO_SATTHU | CoreShell.h | bat/tat dan duong toi boss (Xa Phu -> menu -> map -> di bo) |")
A("| TG_SatThuStart / TG_SatThuTick | CoreShell.cpp | may 6 pha + pha 10/11 (chua nhan nhiem vu -> ve thanh gap NPC) |")
A("| DT_WalkTo / DT_FindNpcName / DT_UsePortal / DT_Answer / DT_Split / DT_FindAns | CoreShell.cpp | nghe di duong + bam thoai cua auto Da Tau |")
A("| g_MoveStation | CoreShell.cpp | toa do Xa Phu tung map |")
A("| SendUiCmdScript(6, \"...\") | KProtocol.cpp | goi ham Lua phia server (da co st3_quit, st3_goboss) |")
A("| KUiTaskGuide::AutoTraceOnTask | UiTaskGuide.cpp | tu bat khung theo doi khi vua nhan nhiem vu |")
A("")
A("## 9. Goi y vong lap cho WAuto")
A("")
A("```")
A("moi nhip:")
A("  neu task 1193 >= 8         -> het luot hom nay, dung (cho sang ngay)")
A("  neu task 1082 == 0         -> chua co nhiem vu:")
A("        ve thanh gap NPC 769 (pha 10/11 co san)")
A("        mo thoai -> \"Nhiem vu cap 90\" -> chon 1 con trong 20 con")
A("  neu task 1082 != 0         -> da co nhiem vu:")
A("        neu KHONG o map boss -> bat GOI_TASKGUIDE_GOTO_SATTHU (tu di)")
A("        neu o map boss       -> tim NPC theo TEN boss (bang muc 7) va danh")
A("        boss chet -> task 1082 tu ve 0, quay lai dau vong")
A("  khi so Sat Thu lenh CUNG CAP >= 5 -> chay quy trinh ghep (muc 5)")
A("```")
A("")
A("**Nhip hoi sinh boss**: ReviveFrame 16200, JX1 chia doi (KNpcTemplate.cpp:140)")
A("=> **~7,5 phut/lan**. Toi noi ma boss chua hoi sinh thi CHO TAI CHO, dung huy nhiem vu.")
A("")
A("## 10. Config chinh duoc (script/header/cauhinh_hoatdong.lua)")
A("")
A("| Khoa | Y nghia |")
A("|---|---|")
A("| HD3_ST_MAX_NGAY | tran luot giet/ngay (goc 8) |")
A("| HD3_ST_HESO_EXP | % kinh nghiem moi lan giet (100 = goc) |")
A("| HD3_ST_SO_LENH | so Sat Thu lenh moi lan giet (goc 1) |")
A("| HD3_ST_EXP | bang exp rieng theo nhom cap (nil = goc) |")
A("| HD3_ST_THUONG | bang thuong hoan thanh nhom 90 (nil = goc) |")
A("| HD3_ST_TIEN_XE | tien thue xe khi F11 dan duong khac map (goc 1000) |")
A("")
io.open(OUT, "w", encoding="utf-8", newline="\r\n").write("\n".join(L))
print("da sinh", OUT, "-", len(L), "dong")
