# -*- coding: ascii -*-
"""gui_patch1.py - [GUI 07/09] Heaven.dll: duong gui cho DONG NGUOI (chuan bi 500 nguoi that).
Ba viec, deu trong Sources/MultiServer/Heaven/ServerStage.cpp + .h (thuan ASCII, CRLF):
 (1) BO KHOA CHUNG m_csCM khoi duong nong. Truoc: moi PackDataToClient (83.000 lan/nhip khi 500 nguoi)
     lay m_csCM (khoa chung ca bang client) roi moi lay csWriteAction (khoa rieng); SendPackToClient(-1)
     giu m_csCM suot vong duyet 500 client; luong IOCP nhan goi (ReadCompleted) cung phai lay m_csCM.
     Nay: bang node co dinh sau ctor (m_ppNode, khong can khoa de tra), duong gui chi giu khoa RIENG
     csWriteAction, duong nhan chi giu csReadAction; noi dat pSocket = NULL (_HelperDelClient,
     ShutdownClient) va noi dat pSocket (_HelperAddClient) lay CA HAI khoa rieng => socket khong bao gio
     bi tha khi mot luong khac dang dung. Thu tu khoa toan cuc: m_csCM < csWriteAction < csReadAction.
     Cong lui: [Server] GuiKhoaRieng=0 (doc luc khoi dong) lay lai m_csCM nhu cu tren moi duong nong.
 (2) BO DEM + DONG HO [GUI-DO] moi 10 s vao jx_gui_server.log (mo-ghi-dong, khong giu handle):
     so goi/byte/thoi gian trong PackDataToClient, so nhip/client/byte/thoi gian trong SendPackToClient,
     thoi gian trung binh mot pSocket->Write, max moi nhip.
 (3) PHEP THU NHAN BAN [Server] MoPhongNhanBan=N (doc lai moi 10 s, khong can khoi dong lai): moi lan gui
     that duoc lam them N-1 lan y het (tra node, khoa rieng, chep vao dem gia; dem day thi cap bo dem IOCP,
     ghi dau goi, ma hoa KSG, tha) - chi KHONG WSASend. Do dung chi phi CPU luong chinh cua N client bang
     mot ket noi that; [GUI-NB] in rieng phan gia va tong uoc tinh moi nhip.
Byte-safe: latin-1, ASCII-only, CRLF, kiem so byte cao va so lan khop."""
import io, re, sys
ROOT = r"D:\GAMEDEVNEW_wt_delta"
F = {
 "cpp": ROOT + r"\Sources\MultiServer\Heaven\ServerStage.cpp",
 "h":   ROOT + r"\Sources\MultiServer\Heaven\ServerStage.h",
}
def rd(p): return io.open(p, "r", encoding="latin-1", newline="").read()
def wr(p, s): io.open(p, "w", encoding="latin-1", newline="").write(s)
def hb(s): return sum(1 for ch in s if ord(ch) >= 0x80)
def crlf(s): return s.replace("\r\n", "\n").replace("\n", "\r\n")
def chk_ascii(*parts):
    for t in parts:
        if any(ord(c) >= 0x80 for c in t): print("FAIL non-ASCII in patch text"); sys.exit(1)

def rep_exact(s, old, new, cnt=1, tag=""):
    old = crlf(old); new = crlf(new); chk_ascii(old, new)
    n = s.count(old)
    if n != cnt: print("FAIL exact[%s]: found %d expect %d: %r" % (tag, n, cnt, old[:90])); sys.exit(1)
    return s.replace(old, new)

def rep_re(s, pat, new, cnt=1, tag="", flags=0):
    new = crlf(new); chk_ascii(new)
    ms = list(re.finditer(pat, s, flags))
    if len(ms) != cnt: print("FAIL regex[%s]: found %d expect %d" % (tag, len(ms), cnt)); sys.exit(1)
    return re.sub(pat, lambda m: new, s, count=cnt, flags=flags)

def rep_func(s, head, new, tag=""):
    """thay TRON mot ham: tu 'head' toi dau ngoac dong o cot 0 dau tien sau do."""
    new = crlf(new); chk_ascii(new)
    i = s.find(head)
    if i < 0 or s.find(head, i + 1) >= 0: print("FAIL func[%s]: head not unique" % tag); sys.exit(1)
    j = s.find("\r\n}\r\n", i)
    if j < 0: print("FAIL func[%s]: no end" % tag); sys.exit(1)
    j += len("\r\n}\r\n")
    old = s[i:j]
    print("   thay ham %-22s %4d dong -> %4d dong" % (tag, old.count("\r\n"), new.count("\r\n")))
    return s[:i] + new + s[j:]

# =====================================================================================================
# HEADER
# =====================================================================================================
h = rd(F["h"]); h_before = hb(h)

h = rep_exact(h,
"class CIOCPServer : public IServer, public OnlineGameLib::Win32::CSocketServer\n",
"struct NB_NODE;	// [GUI 07/09] node gia cua phep thu nhan ban (dinh nghia trong ServerStage.cpp)\n"
"\n"
"class CIOCPServer : public IServer, public OnlineGameLib::Win32::CSocketServer\n", 1, "h-fwd")

h = rep_exact(h,
"	bool _HelperAddClient();\n"
"	bool _HelperDelClient();\n",
"	bool _HelperAddClient();\n"
"	bool _HelperDelClient();\n"
"\n"
"	/*\n"
"	 * [GUI 07/09] Duong gui cho dong nguoi:\n"
"	 *  - m_ppNode: bang tra nhanh node, cap mot lan trong ctor va KHONG BAO GIO doi (node chi bi huy o dtor),\n"
"	 *    nen tra node khong can khoa. Cung con tro voi m_theClientManager.\n"
"	 *  - m_nGuiKhoaRieng ([Server] GuiKhoaRieng, mac dinh 1): duong nong (PackDataToClient, SendPackToClient,\n"
"	 *    SendData, GetPackFromClient, ReadCompleted, ProcessCommand/Message) chi giu khoa RIENG cua node\n"
"	 *    (csWriteAction / csReadAction); noi dat pSocket (them/bot client, ShutdownClient) giu m_csCM + ca hai\n"
"	 *    khoa rieng. Thu tu khoa toan cuc: m_csCM < csWriteAction < csReadAction. Dat 0 de lui ve khoa chung.\n"
"	 *  - _GuiDoBaoCao: bo dem [GUI-DO] moi 10 s (jx_gui_server.log) + doc lai [Server] MoPhongNhanBan.\n"
"	 *  - _NhanBan*: phep thu nhan ban - moi lan gui that lam them N-1 lan vao node gia (khong WSASend).\n"
"	 */\n"
"	LPCLIENT_NODE	*m_ppNode;\n"
"	int				m_nGuiKhoaRieng;\n"
"	LPCLIENT_NODE	_Node( size_t idx ) const { return ( m_ppNode && idx < m_nPlayerMaxCount ) ? m_ppNode[idx] : NULL; }\n"
"	void			_GuiDoBaoCao();\n"
"	void			_NhanBanGoi( const void * const pData, const size_t &datalength, const unsigned long &ulnClientID );\n"
"	void			_NhanBanXa();\n"
"	void			_NhanBanXaMot( NB_NODE &nb );\n", 1, "h-members")

if hb(h) != h_before: print("FAIL high-byte h"); sys.exit(1)

# =====================================================================================================
# CPP
# =====================================================================================================
s = rd(F["cpp"]); s_before = hb(s)

# ---- includes ----
s = rep_re(s, r"#include <process\.h>[^\r\n]*\r\n",
"#include <process.h>		//Thread define\n"
"#include <stdio.h>		// [GUI 07/09] jx_gui_server.log\n"
"#include <stdarg.h>\n"
"#include <string.h>\n"
"#include <vector>\n", 1, "include")

# ---- khoi tinh: bo dem, dong ho, node gia, khoa tuy chon ----
s = rep_exact(s,
"using OnlineGameLib::Win32::CSocketAddress;\n",
"using OnlineGameLib::Win32::CSocketAddress;\n"
"\n"
"/*\n"
" * [GUI 07/09] Do duong gui + phep thu nhan ban.\n"
" * Moi bo dem duoi day chi duoc cham tu LUONG CHINH (Core tick -> PackDataToClient / SendPackToClient(-1)),\n"
" * nen khong can interlocked. Bao cao moi 10 s vao jx_gui_server.log (mo-ghi-dong, khong giu handle de khong\n"
" * can tro viec xoay tep cua Core).\n"
" */\n"
"static LONGLONG gs_qpcTanSo = 0;\n"
"static inline LONGLONG GuiDoQpc() { LARGE_INTEGER li; ::QueryPerformanceCounter( &li ); return li.QuadPart; }\n"
"static inline double   GuiDoMs( LONGLONG t ) { return gs_qpcTanSo ? ( 1000.0 * (double)t / (double)gs_qpcTanSo ) : 0.0; }\n"
"\n"
"static int      gs_nGoi = 0;			// PackDataToClient toi client that\n"
"static int      gs_nGoiTran = 0;		// ... trong do dem day, phai gui ngay\n"
"static LONGLONG gs_nByteGoi = 0;\n"
"static LONGLONG gs_tGoi = 0;			// QPC cong don trong PackDataToClient (cua so 10 s)\n"
"static LONGLONG gs_tGoiNhip = 0;		// ... trong nhip hien tai\n"
"static LONGLONG gs_tGoiNhipMax = 0;\n"
"static int      gs_nXa = 0;			// so lan SendPackToClient = so nhip\n"
"static int      gs_nXaClient = 0;		// so client co du lieu duoc xa\n"
"static LONGLONG gs_nByteXa = 0;\n"
"static LONGLONG gs_tXa = 0;\n"
"static LONGLONG gs_tXaMax = 0;\n"
"static int      gs_nWrite = 0;\n"
"static LONGLONG gs_tWrite = 0;			// QPC trong pSocket->Write (dat vao hang doi IOCP, chua WSASend)\n"
"static int      gs_nNhanBan = 0;		// N cua MoPhongNhanBan: 0/1 = tat\n"
"static int      gs_nNhanBanCap = 0;	// so node gia da cap\n"
"static LONGLONG gs_tNB = 0, gs_tNBNhip = 0, gs_tNBNhipMax = 0, gs_tNBXa = 0, gs_tNBXaMax = 0;\n"
"static LONGLONG gs_nByteNB = 0;\n"
"static int      gs_nGoiNB = 0, gs_nXaNB = 0;\n"
"static DWORD    gs_uBaoCao = 0;\n"
"static size_t   gs_nNBBufMax = 0;\n"
"\n"
"struct NB_NODE\n"
"{\n"
"	CCriticalSection	cs;\n"
"	BYTE				*pBuf;\n"
"	size_t				used;\n"
"	NB_NODE() : pBuf( NULL ), used( 0 ) {}\n"
"	~NB_NODE() { delete [] pBuf; pBuf = NULL; }\n"
"};\n"
"static NB_NODE *gs_pNB = NULL;\n"
"\n"
"static void GuiDoGhi( const char *fmt, ... )\n"
"{\n"
"	char sz[1400];\n"
"	va_list ap;\n"
"	va_start( ap, fmt );\n"
"	_vsnprintf( sz, sizeof( sz ) - 1, fmt, ap );\n"
"	va_end( ap );\n"
"	sz[sizeof( sz ) - 1] = 0;\n"
"	FILE *f = fopen( \"jx_gui_server.log\", \"a\" );\n"
"	if ( !f )\n"
"		return;\n"
"	fprintf( f, \"t=%u pid=%u %s\\n\", (unsigned)::GetTickCount(), (unsigned)::GetCurrentProcessId(), sz );\n"
"	fclose( f );\n"
"}\n"
"\n"
"/*\n"
" * Khoa tuy chon: chi lay khi bOn. Dung cho cong lui GuiKhoaRieng=0 (lay lai m_csCM tren duong nong nhu cu).\n"
" */\n"
"class CKhoaTuyChon\n"
"{\n"
"public:\n"
"	CKhoaTuyChon( CCriticalSection &cs, bool bOn ) : m_p( bOn ? &cs : NULL ) { if ( m_p ) m_p->Enter(); }\n"
"	~CKhoaTuyChon() { if ( m_p ) m_p->Leave(); }\n"
"private:\n"
"	CCriticalSection *m_p;\n"
"	CKhoaTuyChon( const CKhoaTuyChon & );\n"
"	CKhoaTuyChon &operator=( const CKhoaTuyChon & );\n"
"};\n", 1, "statics")

# ---- ctor: bang node + config + dong ho ----
s = rep_re(s, r"(\r\n\t)for \( index = 0; index < nPlayerMaxCount; index \+\+ \)",
"\n"
"	// [GUI 07/09] bang tra nhanh node: cap mot lan, khong bao gio doi sau ctor (node chi bi huy o dtor).\n"
"	// Doc cong lui GuiKhoaRieng, tan so dong ho, va co bo dem gia = co bo dem ghi that (m_nNetworkBufferMaxLen).\n"
"	{\n"
"		const size_t nCap = ( nPlayerMaxCount > 0 ) ? nPlayerMaxCount : 1;\n"
"		m_ppNode = new LPCLIENT_NODE[ nCap ];\n"
"		memset( m_ppNode, 0, sizeof( LPCLIENT_NODE ) * nCap );\n"
"		m_nGuiKhoaRieng = (int)::GetPrivateProfileIntA( \"Server\", \"GuiKhoaRieng\", 1, \".\\\\config.ini\" );\n"
"		LARGE_INTEGER liTanSo;\n"
"		if ( ::QueryPerformanceFrequency( &liTanSo ) )\n"
"			gs_qpcTanSo = liTanSo.QuadPart;\n"
"		gs_nNBBufMax = m_nNetworkBufferMaxLen;\n"
"		GuiDoGhi( \"[GUI-DO] khoi dong: client toi da %u, dem ghi %u byte, GuiKhoaRieng=%d\", (unsigned)nPlayerMaxCount, (unsigned)m_nNetworkBufferMaxLen, m_nGuiKhoaRieng );\n"
"	}\n"
"\n"
"	for ( index = 0; index < nPlayerMaxCount; index ++ )", 1, "ctor-pre")

s = rep_exact(s,
"m_theClientManager[index] = pCN;\n",
"m_theClientManager[index] = pCN;\n"
"\n"
"			m_ppNode[index] = pCN;	// [GUI 07/09]\n", 1, "ctor-loop")

# ---- dtor: tha bang node + node gia (sau khi luong helper da dung) ----
s = rep_re(s, r"(::TerminateThread\( m_hHelperThread, 0L \);\r\n\t\}\r\n)(\}\r\n)",
"::TerminateThread( m_hHelperThread, 0L );\n"
"	}\n"
"\n"
"	// [GUI 07/09] tha sau cung, khi khong con luong nao dung bang node\n"
"	delete [] m_ppNode;\n"
"	m_ppNode = NULL;\n"
"	delete [] gs_pNB;\n"
"	gs_pNB = NULL;\n"
"	gs_nNhanBanCap = 0;\n"
"	gs_nNhanBan = 0;\n"
"}\n", 1, "dtor")

# ---- PackDataToClient: thay tron + them 4 ham moi truoc no ----
s = rep_func(s, "STDMETHODIMP CIOCPServer::PackDataToClient(",
"/*\n"
" * [GUI 07/09] Bao cao [GUI-DO] moi 10 s, doc lai [Server] MoPhongNhanBan (bat/tat khong can khoi dong lai).\n"
" * Goi tu SendPackToClient (luong chinh).\n"
" */\n"
"void CIOCPServer::_GuiDoBaoCao()\n"
"{\n"
"	const DWORD uNay = ::GetTickCount();\n"
"\n"
"	if ( gs_uBaoCao == 0 )\n"
"	{\n"
"		gs_uBaoCao = uNay;\n"
"		return;\n"
"	}\n"
"\n"
"	if ( (DWORD)( uNay - gs_uBaoCao ) < 10000 )\n"
"		return;\n"
"\n"
"	const double giay = (double)( uNay - gs_uBaoCao ) / 1000.0;\n"
"	gs_uBaoCao = uNay;\n"
"\n"
"	const int nNhip = ( gs_nXa > 0 ) ? gs_nXa : 1;\n"
"\n"
"	GuiDoGhi( \"[GUI-DO] %.0fs: goi=%d (dem day gui ngay=%d) byte=%I64d t_goi=%.2f ms | xa=%d nhip, client_xa=%d byte_xa=%I64d (%.1f KB/s) t_xa=%.2f ms (Write %d lan, %.1f us/lan) | moi nhip: goi %.3f ms (max %.3f) + xa %.3f ms (max %.3f) | khoa_rieng=%d client=%u\",\n"
"		giay, gs_nGoi, gs_nGoiTran, gs_nByteGoi, GuiDoMs( gs_tGoi ),\n"
"		gs_nXa, gs_nXaClient, gs_nByteXa, (double)gs_nByteXa / 1024.0 / giay, GuiDoMs( gs_tXa ),\n"
"		gs_nWrite, gs_nWrite ? ( GuiDoMs( gs_tWrite ) * 1000.0 / (double)gs_nWrite ) : 0.0,\n"
"		GuiDoMs( gs_tGoi ) / nNhip, GuiDoMs( gs_tGoiNhipMax ), GuiDoMs( gs_tXa ) / nNhip, GuiDoMs( gs_tXaMax ),\n"
"		m_nGuiKhoaRieng, (unsigned)m_usedClientNode.size() );\n"
"\n"
"	if ( gs_nNhanBan > 1 )\n"
"	{\n"
"		const double msThat = GuiDoMs( gs_tGoi ) + GuiDoMs( gs_tXa );\n"
"		const double msGia  = GuiDoMs( gs_tNB ) + GuiDoMs( gs_tNBXa );\n"
"		GuiDoGhi( \"[GUI-NB] %.0fs nhan ban x%d (%d client gia): goi=%d t=%.2f ms | xa=%d byte=%I64d (%.1f KB/s) t=%.2f ms | moi nhip: goi %.3f ms (max %.3f) + xa %.3f ms (max %.3f) => duong gui uoc tinh moi nhip %.3f ms (that %.3f + gia %.3f)\",\n"
"			giay, gs_nNhanBan, gs_nNhanBan - 1, gs_nGoiNB, GuiDoMs( gs_tNB ),\n"
"			gs_nXaNB, gs_nByteNB, (double)gs_nByteNB / 1024.0 / giay, GuiDoMs( gs_tNBXa ),\n"
"			GuiDoMs( gs_tNB ) / nNhip, GuiDoMs( gs_tNBNhipMax ), GuiDoMs( gs_tNBXa ) / nNhip, GuiDoMs( gs_tNBXaMax ),\n"
"			( msThat + msGia ) / nNhip, msThat / nNhip, msGia / nNhip );\n"
"	}\n"
"\n"
"	gs_nGoi = 0; gs_nGoiTran = 0; gs_nByteGoi = 0; gs_tGoi = 0; gs_tGoiNhipMax = 0;\n"
"	gs_nXa = 0; gs_nXaClient = 0; gs_nByteXa = 0; gs_tXa = 0; gs_tXaMax = 0; gs_nWrite = 0; gs_tWrite = 0;\n"
"	gs_tNB = 0; gs_tNBNhipMax = 0; gs_tNBXa = 0; gs_tNBXaMax = 0; gs_nByteNB = 0; gs_nGoiNB = 0; gs_nXaNB = 0;\n"
"\n"
"	/*\n"
"	 * Doc lai config moi 10 s: MoPhongNhanBan bat/tat khong can khoi dong lai. Node gia chi luong chinh cham\n"
"	 * (PackDataToClient / SendPackToClient / day) nen cap lai ngay tai day la an toan.\n"
"	 */\n"
"	int nMoi = (int)::GetPrivateProfileIntA( \"Server\", \"MoPhongNhanBan\", 0, \".\\\\config.ini\" );\n"
"	if ( nMoi < 0 ) nMoi = 0;\n"
"	if ( nMoi > 2000 ) nMoi = 2000;\n"
"\n"
"	if ( nMoi > 1 && gs_nNhanBanCap < nMoi - 1 )\n"
"	{\n"
"		NB_NODE *pMoi = new NB_NODE[ nMoi - 1 ];\n"
"		for ( int k = 0; k < nMoi - 1; k++ )\n"
"		{\n"
"			pMoi[k].pBuf = new BYTE[ gs_nNBBufMax + 64 ];\n"
"			pMoi[k].used = 0;\n"
"		}\n"
"		delete [] gs_pNB;\n"
"		gs_pNB = pMoi;\n"
"		gs_nNhanBanCap = nMoi - 1;\n"
"	}\n"
"\n"
"	if ( nMoi != gs_nNhanBan )\n"
"	{\n"
"		GuiDoGhi( \"[GUI-NB] doi MoPhongNhanBan %d -> %d (node gia da cap %d, dem %u byte/node)\", gs_nNhanBan, nMoi, gs_nNhanBanCap, (unsigned)gs_nNBBufMax );\n"
"		gs_nNhanBan = nMoi;\n"
"	}\n"
"}\n"
"\n"
"/*\n"
" * [GUI 07/09] Mo phong dung viec ban that lam khi xa mot client: cap bo dem IOCP, ghi dau goi, chep, ma hoa\n"
" * KSG, tha bo dem. Chi KHONG WSASend (khong co socket). Goi duoi khoa nb.cs.\n"
" */\n"
"void CIOCPServer::_NhanBanXaMot( NB_NODE &nb )\n"
"{\n"
"	static const size_t s_len_protocol = sizeof( WORD );\n"
"\n"
"	if ( nb.used == 0 )\n"
"		return;\n"
"\n"
"	try\n"
"	{\n"
"		CIOBuffer *pBuffer = Allocate();\n"
"\n"
"		if ( pBuffer )\n"
"		{\n"
"			const size_t headlength = s_len_protocol + nb.used;\n"
"			pBuffer->AddData( reinterpret_cast< const char * >( &headlength ), s_len_protocol );\n"
"			pBuffer->AddData( reinterpret_cast< const char * >( nb.pBuf ), nb.used );\n"
"\n"
"			unsigned uKey = 0x5A17C3E9u;\n"
"			KSG_EncodeBuf( nb.used, (unsigned char *)( pBuffer->GetBuffer() + s_len_protocol ), &uKey );\n"
"\n"
"			pBuffer->Release();\n"
"		}\n"
"	}\n"
"	catch( ... )\n"
"	{\n"
"	}\n"
"\n"
"	gs_nByteNB += (LONGLONG)( nb.used + s_len_protocol );\n"
"	gs_nXaNB++;\n"
"	nb.used = 0;\n"
"}\n"
"\n"
"/*\n"
" * [GUI 07/09] Phep thu nhan ban, phan PackDataToClient: lam them N-1 lan dung trinh tu that\n"
" * (khoa chung neu che do cu -> tra node -> khoa rieng -> kiem dem day -> chep).\n"
" */\n"
"void CIOCPServer::_NhanBanGoi( const void * const pData, const size_t &datalength, const unsigned long &ulnClientID )\n"
"{\n"
"	const int nSo = gs_nNhanBan - 1;\n"
"\n"
"	if ( nSo <= 0 || !gs_pNB || gs_nNhanBanCap < nSo || datalength == 0 || datalength >= gs_nNBBufMax )\n"
"		return;\n"
"\n"
"	const LONGLONG tBatDau = GuiDoQpc();\n"
"\n"
"	for ( int k = 0; k < nSo; k++ )\n"
"	{\n"
"		CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"		LPCLIENT_NODE pCN = _Node( ulnClientID );\n"
"\n"
"		if ( !pCN )\n"
"			break;\n"
"\n"
"		NB_NODE &nb = gs_pNB[k];\n"
"\n"
"		CCriticalSection::Owner lock( nb.cs );\n"
"\n"
"		if ( ( nb.used >= gs_nNBBufMax ) || ( nb.used + datalength >= gs_nNBBufMax ) )\n"
"		{\n"
"			_NhanBanXaMot( nb );\n"
"		}\n"
"\n"
"		memcpy( nb.pBuf + nb.used, pData, datalength );\n"
"		nb.used += datalength;\n"
"	}\n"
"\n"
"	gs_nGoiNB += nSo;\n"
"\n"
"	const LONGLONG tHet = GuiDoQpc() - tBatDau;\n"
"	gs_tNB += tHet;\n"
"	gs_tNBNhip += tHet;\n"
"}\n"
"\n"
"/*\n"
" * [GUI 07/09] Phep thu nhan ban, phan SendPackToClient: xa N-1 node gia moi nhip.\n"
" */\n"
"void CIOCPServer::_NhanBanXa()\n"
"{\n"
"	const int nSo = gs_nNhanBan - 1;\n"
"\n"
"	if ( nSo <= 0 || !gs_pNB || gs_nNhanBanCap < nSo )\n"
"		return;\n"
"\n"
"	const LONGLONG tBatDau = GuiDoQpc();\n"
"\n"
"	for ( int k = 0; k < nSo; k++ )\n"
"	{\n"
"		NB_NODE &nb = gs_pNB[k];\n"
"\n"
"		CCriticalSection::Owner lock( nb.cs );\n"
"\n"
"		if ( nb.used > 0 )\n"
"			_NhanBanXaMot( nb );\n"
"	}\n"
"\n"
"	const LONGLONG tHet = GuiDoQpc() - tBatDau;\n"
"	gs_tNBXa += tHet;\n"
"	if ( tHet > gs_tNBXaMax )\n"
"		gs_tNBXaMax = tHet;\n"
"}\n"
"\n"
"STDMETHODIMP CIOCPServer::PackDataToClient( const unsigned long &ulnClientID,\n"
"			const void * const	pData,\n"
"			const size_t		&datalength )\n"
"{\n"
"	HRESULT hr = E_FAIL;\n"
"\n"
"	if ( ulnClientID < m_nPlayerMaxCount && datalength > 0 )\n"
"	{\n"
"		/*\n"
"		 * [GUI 07/09] Khong lay m_csCM nua (truoc: 2 khoa moi goi, 83.000 goi/nhip khi 500 nguoi). Bang node\n"
"		 * co dinh sau ctor; pSocket duoc doc va dung duoi khoa RIENG csWriteAction, va noi dat pSocket = NULL\n"
"		 * (_HelperDelClient / ShutdownClient) cung lay khoa do => socket khong bao gio bi tha khi dang dung.\n"
"		 * GuiKhoaRieng=0 lay lai m_csCM truoc csWriteAction, dung thu tu cu.\n"
"		 */\n"
"		const LONGLONG tBatDau = GuiDoQpc();\n"
"\n"
"		CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"		LPCLIENT_NODE pCN = _Node( ulnClientID );\n"
"\n"
"		if ( pCN )\n"
"		{\n"
"			CCriticalSection::Owner	lock( pCN->csWriteAction );\n"
"\n"
"			Socket *pSock = pCN->pSocket;\n"
"\n"
"			if ( pSock )\n"
"			{\n"
"				try\n"
"				{\n"
"					CIOBuffer *pWriteBuffer = pCN->pWriteBuffer;\n"
"\n"
"					const size_t nNetworkBufferLen = pWriteBuffer->GetUsed();\n"
"\n"
"					if ( ( nNetworkBufferLen >= m_nNetworkBufferMaxLen ) || \n"
"						( nNetworkBufferLen + datalength >= m_nNetworkBufferMaxLen ) )\n"
"					{\n"
"						/*\n"
"						 * It need send to client at once, because of buffer is full\n"
"						 */\n"
"						const BYTE *pPackData = pWriteBuffer->GetBuffer();\n"
"						const size_t used = pWriteBuffer->GetUsed();\n"
"\n"
"						_SendDataEx( pCN, pPackData, used );\n"
"\n"
"						pWriteBuffer->Empty();\n"
"\n"
"						gs_nGoiTran++;\n"
"					}\n"
"\n"
"					pWriteBuffer->AddData( static_cast< const char * const >( pData ), datalength );\n"
"\n"
"					gs_nGoi++;\n"
"					gs_nByteGoi += (LONGLONG)datalength;\n"
"\n"
"					hr = S_OK;\n"
"				}\n"
"				catch( const CException &e )\n"
"				{\n"
"					Output( _T(\"CIOCPServer::PackDataToClient Exception: \") + e.GetWhere() + _T(\" - \") + e.GetMessage() );\n"
"\n"
"					pSock->Shutdown();\n"
"				}\n"
"				catch(...)\n"
"				{\n"
"					Output( _T(\"CIOCPServer::PackDataToClient - Unexpected exception\") );\n"
"\n"
"					pSock->Shutdown();\n"
"				}\n"
"			}\n"
"		}\n"
"\n"
"		const LONGLONG tHet = GuiDoQpc() - tBatDau;\n"
"		gs_tGoi += tHet;\n"
"		gs_tGoiNhip += tHet;\n"
"\n"
"		if ( hr == S_OK && gs_nNhanBan > 1 )\n"
"		{\n"
"			_NhanBanGoi( pData, datalength, ulnClientID );\n"
"		}\n"
"	}\n"
"\n"
"	return hr;\n"
"}\n", "PackDataToClient")

# ---- SendPackToClient: thay tron ----
s = rep_func(s, "STDMETHODIMP CIOCPServer::SendPackToClient(",
"STDMETHODIMP CIOCPServer::SendPackToClient( const unsigned long &ulnClientID /* -1 */ )\n"
"{\n"
"	HRESULT hr = E_FAIL;\n"
"\n"
"	static const size_t s_len_protocol = sizeof( WORD );\n"
"\n"
"	/*\n"
"	 * [GUI 07/09] Truoc: giu m_csCM suot vong duyet moi client (500 client = vai ms moi nhip, luong IOCP nhan\n"
"	 * goi phai cho). Nay: chup danh sach client dang dung duoi m_csCM (vai micro giay), roi xa tung client chi\n"
"	 * duoi khoa rieng csWriteAction cua no. Chi cap bo dem khi that su co du lieu (truoc: cap+tha moi client\n"
"	 * moi nhip du rong).\n"
"	 */\n"
"	const LONGLONG tBatDau = GuiDoQpc();\n"
"\n"
"	std::vector< size_t > vDangDung;\n"
"\n"
"	{\n"
"		CCriticalSection::Owner locker( m_csCM );\n"
"\n"
"		vDangDung.assign( m_usedClientNode.begin(), m_usedClientNode.end() );\n"
"	}\n"
"\n"
"	CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"	for ( size_t i = 0; i < vDangDung.size(); i++ )\n"
"	{\n"
"		LPCLIENT_NODE pCN = _Node( vDangDung[i] );\n"
"\n"
"		if ( !pCN )\n"
"			continue;\n"
"\n"
"		CCriticalSection::Owner lock( pCN->csWriteAction );\n"
"\n"
"		Socket *pSock = pCN->pSocket;\n"
"\n"
"		if ( !pSock )\n"
"			continue;\n"
"\n"
"		CIOBuffer *pBuffer = NULL;\n"
"		try\n"
"		{\n"
"			const BYTE * pPackData = pCN->pWriteBuffer->GetBuffer();\n"
"			const size_t used = pCN->pWriteBuffer->GetUsed();\n"
"\n"
"			if ( used > 0 )\n"
"			{\n"
"				pBuffer = Allocate();\n"
"\n"
"				/*\n"
"				 * Add package header\n"
"				 */\n"
"				const size_t headlength = s_len_protocol + used;\n"
"				pBuffer->AddData( reinterpret_cast< const char * >( &headlength ), s_len_protocol );\n"
"\n"
"				pBuffer->AddData( reinterpret_cast< const char * >( pPackData ), used );\n"
"\n"
"				_ASSERT(pCN->uKeyMode == 0);\n"
"				KSG_EncodeBuf(\n"
"					used,\n"
"					(unsigned char *)(pBuffer->GetBuffer() + s_len_protocol),\n"
"					&pCN->uServerKey\n"
"				);\n"
"\n"
"				pCN->pWriteBuffer->Empty();\n"
"\n"
"				const LONGLONG tW = GuiDoQpc();\n"
"				pSock->Write( pBuffer, true );\n"
"				gs_tWrite += GuiDoQpc() - tW;\n"
"				gs_nWrite++;\n"
"\n"
"				gs_nXaClient++;\n"
"				gs_nByteXa += (LONGLONG)( used + s_len_protocol );\n"
"\n"
"				pBuffer->Release();\n"
"				pBuffer = NULL;\n"
"			}\n"
"\n"
"			hr = S_OK;\n"
"		}\n"
"		catch( const CException &e )\n"
"		{\n"
"			if (pBuffer)\n"
"			{\n"
"				pBuffer->Release();	\n"
"				pBuffer = NULL;\n"
"			}\n"
"\n"
"			Output( _T(\"CIOCPServer::SendPackToClient Exception: \") + e.GetWhere() + _T(\" - \") + e.GetMessage() );\n"
"\n"
"			pSock->Shutdown();\n"
"		}\n"
"		catch(...)\n"
"		{\n"
"			if (pBuffer)\n"
"			{\n"
"				pBuffer->Release();	\n"
"				pBuffer = NULL;\n"
"			}\n"
"\n"
"			Output( _T(\"CIOCPServer::SendPackToClient - Unexpected exception\") );\n"
"\n"
"			pSock->Shutdown();\n"
"		}\n"
"	}\n"
"\n"
"	const LONGLONG tHet = GuiDoQpc() - tBatDau;\n"
"	gs_tXa += tHet;\n"
"	if ( tHet > gs_tXaMax )\n"
"		gs_tXaMax = tHet;\n"
"	if ( gs_tGoiNhip > gs_tGoiNhipMax )\n"
"		gs_tGoiNhipMax = gs_tGoiNhip;\n"
"	gs_tGoiNhip = 0;\n"
"	if ( gs_tNBNhip > gs_tNBNhipMax )\n"
"		gs_tNBNhipMax = gs_tNBNhip;\n"
"	gs_tNBNhip = 0;\n"
"	gs_nXa++;\n"
"\n"
"	if ( gs_nNhanBan > 1 )\n"
"		_NhanBanXa();\n"
"\n"
"	_GuiDoBaoCao();\n"
"\n"
"	return hr;\n"
"}\n", "SendPackToClient")

# ---- SendData: thay tron ----
s = rep_func(s, "STDMETHODIMP CIOCPServer::SendData(",
"STDMETHODIMP CIOCPServer::SendData( const unsigned long &ulnClientID,\n"
"					 const void * const	pData,\n"
"					 const size_t		&datalength )\n"
"{\n"
"	HRESULT hr = E_FAIL;\n"
"\n"
"	static const size_t s_len_protocol = sizeof( WORD );\n"
"\n"
"	if ( NULL == pData || 0 == datalength )\n"
"	{\n"
"		return hr;\n"
"	}\n"
"\n"
"	if ( ulnClientID < m_nPlayerMaxCount )\n"
"	{\n"
"		// [GUI 07/09] khoa rieng csWriteAction thay m_csCM (xem PackDataToClient)\n"
"		CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"		LPCLIENT_NODE pCN = _Node( ulnClientID );\n"
"\n"
"		if ( pCN )\n"
"		{\n"
"			CCriticalSection::Owner lock( pCN->csWriteAction );\n"
"\n"
"			Socket *pSock = pCN->pSocket;\n"
"\n"
"			if ( pSock )\n"
"			{\n"
"				CIOBuffer *pBuffer = NULL;\n"
"				try\n"
"				{\n"
"					pBuffer = Allocate();\n"
"\n"
"					/*\n"
"					 * Add package header\n"
"					 */\n"
"					const size_t headlength = s_len_protocol + datalength;\n"
"					pBuffer->AddData( reinterpret_cast< const char * >( &headlength ), s_len_protocol );\n"
"\n"
"					/*\n"
"					 * Add data into buffer that it is will be send\n"
"					 */\n"
"					pBuffer->AddData( reinterpret_cast< const char * >( pData ), datalength );\n"
"\n"
"					_ASSERT(pCN->uKeyMode == 0);\n"
"					KSG_EncodeBuf(\n"
"						datalength,\n"
"						(unsigned char *)(pBuffer->GetBuffer() + s_len_protocol),\n"
"						&pCN->uServerKey\n"
"					);\n"
"\n"
"					pSock->Write( pBuffer, true );\n"
"\n"
"					pBuffer->Release();\n"
"					pBuffer = NULL;\n"
"\n"
"					hr = S_OK;\n"
"				}\n"
"				catch( const CException &e )\n"
"				{\n"
"					if (pBuffer)\n"
"					{\n"
"						pBuffer->Release();\n"
"						pBuffer = NULL;\n"
"					}\n"
"\n"
"					Output( _T(\"CIOCPServer::SendData Exception: \") + e.GetWhere() + _T(\" - \") + e.GetMessage() );\n"
"\n"
"					pSock->Shutdown();\n"
"				}\n"
"				catch(...)\n"
"				{\n"
"					if (pBuffer)\n"
"					{\n"
"						pBuffer->Release();\n"
"						pBuffer = NULL;\n"
"					}\n"
"\n"
"					Output( _T(\"CIOCPServer::SendData - Unexpected exception\") );\n"
"\n"
"					pSock->Shutdown();\n"
"				}\n"
"			}\n"
"		}\n"
"	}\n"
"\n"
"	return hr;\n"
"}\n", "SendData")

# ---- GetPackFromClient: thay tron ----
s = rep_func(s, "STDMETHODIMP_( const void * ) CIOCPServer::GetPackFromClient(",
"STDMETHODIMP_( const void * ) CIOCPServer::GetPackFromClient( const unsigned long &ulnClientID,\n"
"			size_t &datalength )\n"
"{\n"
"	if ( ulnClientID < m_nPlayerMaxCount )\n"
"	{\n"
"		// [GUI 07/09] khoa rieng csReadAction thay m_csCM; pSocket doc va dung duoi khoa do (_HelperDelClient\n"
"		// va ShutdownClient dat NULL duoi cung khoa). ProcessCommand ben trong lay lai csReadAction (de quy, OK).\n"
"		CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"		LPCLIENT_NODE pCN = _Node( ulnClientID );\n"
"\n"
"		if ( pCN )\n"
"		{\n"
"			CCriticalSection::Owner lock( pCN->csReadAction );\n"
"\n"
"			Socket *pSock = pCN->pSocket;\n"
"\n"
"			if ( pSock )\n"
"			{\n"
"				pCN->pReadBuffer->Empty();\n"
"\n"
"				pCN->pRecvBuffer = ProcessDataStream( pSock, pCN->pRecvBuffer );\n"
"\n"
"				const char *pData = reinterpret_cast< const char * >( pCN->pReadBuffer->GetBuffer() );\n"
"				datalength = pCN->pReadBuffer->GetUsed();\n"
"\n"
"				return pData;\n"
"			}\n"
"		}\n"
"	}\n"
"\n"
"	datalength = 0;\n"
"	\n"
"	return NULL;\n"
"}\n", "GetPackFromClient")

# ---- ShutdownClient: them hai khoa rieng ----
s = rep_re(s,
 r"pCN = \( LPCLIENT_NODE \)\( m_theClientManager\[ulnClientID\] \);\s*if \( pCN \)\s*\{\s*if \( pCN->pSocket \)\s*\{\s*// Fix by BladeKnight109 21042020",
"pCN = _Node( ulnClientID );\n"
"\n"
"		if ( pCN )\n"
"		{\n"
"			// [GUI 07/09] duong nong chi giu khoa rieng -> phai lay ca hai khoa rieng truoc khi tha socket\n"
"			CCriticalSection::Owner lockW( pCN->csWriteAction );\n"
"			CCriticalSection::Owner lockR( pCN->csReadAction );\n"
"\n"
"			if ( pCN->pSocket )\n"
"			{\n"
"				// Fix by BladeKnight109 21042020", 1, "ShutdownClient")

# ---- ReadCompleted (luong IOCP) ----
s = rep_re(s,
 r"LPCLIENT_NODE pCN = NULL;\s*\{\s*CCriticalSection::Owner\s+locker\( m_csCM \);\s*pCN = \( LPCLIENT_NODE \)\( m_theClientManager\[dwIndex\] \);\s*if \( pCN \)\s*\{\s*CCriticalSection::Owner lock\( pCN->csReadAction \);\s*pCN->pRecvBuffer->AddData\( pPackData, used \);\s*\}\s*\}",
"LPCLIENT_NODE pCN = NULL;\n"
"			{\n"
"				// [GUI 07/09] chi khoa rieng csReadAction (bang node co dinh, dwIndex duoc kiem bien trong _Node;\n"
"				// truoc day dwIndex = -1 cua ket noi bi tu choi con chen mot muc NULL vao map). GuiKhoaRieng=0 nhu cu.\n"
"				CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"				pCN = _Node( dwIndex );\n"
"\n"
"				if ( pCN )\n"
"				{\n"
"					CCriticalSection::Owner lock( pCN->csReadAction );\n"
"\n"
"					pCN->pRecvBuffer->AddData( pPackData, used );\n"
"				}\n"
"			}", 1, "ReadCompleted")

# ---- ProcessCommand (goi tu GetPackFromClient duoi csReadAction) ----
s = rep_re(s,
 r"\tLPCLIENT_NODE pCN = NULL;\r\n\t\{\s*CCriticalSection::Owner\s+locker\( m_csCM \);\s*if \( NULL == \( pCN = \( LPCLIENT_NODE \)\( m_theClientManager\[dwIndex\] \) \) \)\s*\{\s*return;\s*\}",
"	LPCLIENT_NODE pCN = NULL;\n"
"	{\n"
"		// [GUI 07/09] khoa rieng csReadAction thay m_csCM (goi tu GetPackFromClient dang giu csReadAction: de quy)\n"
"		CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"		if ( NULL == ( pCN = _Node( dwIndex ) ) )\n"
"		{\n"
"			return;\n"
"		}\n"
"\n"
"		CCriticalSection::Owner lockR( pCN->csReadAction );", 1, "ProcessCommand")

# ---- ProcessMessage (luong IOCP, chi khi co IMessageProcess dang ky - GameServer khong dung) ----
s = rep_re(s,
 r"\t\tLPCLIENT_NODE pCN;\r\n\t\t\{\s*CCriticalSection::Owner\s+locker\( m_csCM \);\s*if \( NULL == \( pCN = \( LPCLIENT_NODE \)\( m_theClientManager\[dwIndex\] \) \) \)\s*\{\s*return;\s*\}",
"		LPCLIENT_NODE pCN;\n"
"		{\n"
"			// [GUI 07/09] khoa rieng csReadAction thay m_csCM (cung khoa voi GetPackFromClient/ProcessCommand)\n"
"			CKhoaTuyChon khoaChung( m_csCM, m_nGuiKhoaRieng == 0 );\n"
"\n"
"			if ( NULL == ( pCN = _Node( dwIndex ) ) )\n"
"			{\n"
"				return;\n"
"			}\n"
"\n"
"			CCriticalSection::Owner lockR( pCN->csReadAction );", 1, "ProcessMessage")

# ---- _HelperAddClient: dat khoa/khoa rieng truoc, pSocket sau cung ----
s = rep_re(s,
 r"CCriticalSection::Owner\s+locker\( m_csCM \);\s*m_theClientManager\[dwIndex\]->pSocket\s*=\s*pSocket;\s*m_theClientManager\[dwIndex\]->uServerKey\s*=\s*_Rand\(\);\s*m_theClientManager\[dwIndex\]->uClientKey\s*=\s*_Rand\(\);\s*m_theClientManager\[dwIndex\]->uKeyMode\s*=\s*0;",
"CCriticalSection::Owner	locker( m_csCM );\n"
"\n"
"				// [GUI 07/09] duong gui/nhan chi giu khoa rieng: lay ca hai khoa rieng, dat khoa ma truoc,\n"
"				// pSocket SAU CUNG, de khong luong nao thay pSocket khac NULL ma khoa/dem chua san sang.\n"
"				LPCLIENT_NODE pCNMoi = _Node( dwIndex );\n"
"\n"
"				if ( pCNMoi )\n"
"				{\n"
"					CCriticalSection::Owner lockW( pCNMoi->csWriteAction );\n"
"					CCriticalSection::Owner lockR( pCNMoi->csReadAction );\n"
"\n"
"					pCNMoi->uServerKey = _Rand();\n"
"					pCNMoi->uClientKey = _Rand();\n"
"					pCNMoi->uKeyMode   = 0;\n"
"\n"
"					pCNMoi->pWriteBuffer->Empty();\n"
"					pCNMoi->pReadBuffer->Empty();\n"
"					pCNMoi->pRecvBuffer->Empty();\n"
"\n"
"					pCNMoi->pSocket    = pSocket;\n"
"				}", 1, "HelperAddClient")

# ---- _HelperDelClient: tha socket duoi ca hai khoa rieng ----
s = rep_re(s,
 r"CCriticalSection::Owner\s+locker\( m_csCM \);\s*pCN = \( LPCLIENT_NODE \)\( m_theClientManager\[dwIndex\] \);\s*if \( pCN \)\s*\{\s*pCN->pSocket = NULL;\s*pCN->pReadBuffer->Empty\(\);\s*pCN->pRecvBuffer->Empty\(\);\s*pCN->pWriteBuffer->Empty\(\);\s*\}",
"CCriticalSection::Owner	locker( m_csCM );\n"
"\n"
"			pCN = _Node( dwIndex );\n"
"\n"
"			if ( pCN )\n"
"			{\n"
"				// [GUI 07/09] duong nong chi giu khoa rieng -> lay ca hai khoa rieng roi moi dat pSocket = NULL;\n"
"				// SAFE_RELEASE( pSocket ) o duoi chi chay sau khi ra khoi day => khong luong nao con dang dung socket.\n"
"				CCriticalSection::Owner lockW( pCN->csWriteAction );\n"
"				CCriticalSection::Owner lockR( pCN->csReadAction );\n"
"\n"
"				pCN->pSocket = NULL;\n"
"\n"
"				pCN->pReadBuffer->Empty();\n"
"				pCN->pRecvBuffer->Empty();\n"
"				pCN->pWriteBuffer->Empty();\n"
"			}", 1, "HelperDelClient")

if hb(s) != s_before: print("FAIL high-byte cpp"); sys.exit(1)
if "\r\n" not in s or re.search(r"[^\r]\n", s): print("FAIL bare LF in cpp"); sys.exit(1)
if re.search(r"[^\r]\n", h): print("FAIL bare LF in h"); sys.exit(1)

# con lai bao nhieu cho lay m_csCM tren duong nong? (chi de in, khong chan)
print("   m_csCM con lai trong cpp: %d lan (ctor/dtor/Shutdown/RegisterMsgFilter/GetClientInfo/helper/snapshot/KhoaTuyChon)" % s.count("m_csCM"))

wr(F["h"], h); print("OK h   high-bytes %d" % h_before)
wr(F["cpp"], s); print("OK cpp high-bytes %d" % s_before)
print("ALL APPLIED")
