// UiTaskGuideStr.h - SINH TU DONG boi scratchpad/mine/gen_strings.py. DUNG SUA TAY.
// Chuoi TCVN3 o dang octal escape. Nguon cau chu: UI\taskui_random.lua
// (ban trong update01.pak cua client dang phat hanh) + vn_to_octal cho chuoi moi.
#pragma once

#define DTG_NOTASK "B¹n ch­a tiÕp nhËn nhiÖm vô cña D· TÈu, cã thêi gian h·y ®Õn gÆp «ng ta xem!"
#define DTG_T1_FMT "®Õn  %s mua  %s  cho D· TÈu."
#define DTG_T2A_FMT "®i t×m%s gióp ta."
#define DTG_T2B_FMT "®i t×m%s thÊp nhÊt lµ %s lín nhÊt lµ %s %s vÒ cho D· TÈu!"
#define DTG_T3_FMT "§i t×m bé trang bŞ %s thÊp nhÊt lµ %s cao nhÊt lµ %s cho D· tÈu!"
#define DTG_T4_FMT "§Õn <color=yellow>%s<color> t×m <color=yellow>%s<color> quyÓn %s vÒ cho D· TÈu!<enter>B¹n hiÖn ®· thu thËp ®­îc <color=yellow>%d<color> tÊm %s"
#define DTG_LOAI_DIADO "§Şa §å chİ "
#define DTG_LOAI_MAT "MËt chİ "
#define DTG_T5_FMT "§i n©ng cÊp   %s %s"
#define DTG_T5_SUB1 " cÊp"
#define DTG_T5_SUB2 "®iÓm kinh nghiÖm "
#define DTG_T5_SUB3_FMT "®iÓm danh väng. Danh väng cña b¹n hiÖn t¹i lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T5_SUB4_FMT "®iÓm phóc duyªn. Phóc duyªn cña b¹n hiÖn t¹i lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T5_SUB5 "®iÓm PK"
#define DTG_T5_SUB6_FMT "®iÓm th­ëng Tèng Kim, ®iÓm th­ëng cña b¹n hiÖn lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T6_FMT "®Õn ®­a D· TÈu %s m¶nh b¶n ®å S¬n Hµ X· T¾c.<enter>B¹n hiÖn ®· thu thËp ®­îc <color=yellow>%d<color> tÊm."
#define DTG_PREFIX_LAM "<color=green>[®ang lµm] <color>"
#define DTG_PREFIX_XONG "<color=yellow>[hoµn thµnh - h·y vÒ gÆp D· TÈu] <color>"
#define DTG_EXTRA_FMT "H«m nay ®· lµm: <color=yellow>%d/40<color> nhiÖm vô, ®· hñy: %d lÇn."
#define DTG_HINT_XAFU "<color=Cyan>NhÊp vµo dßng nhiÖm vô ®Ó tù ch¹y ®Õn Xa Phu ®i tíi map lµm nhiÖm vô.<color>"
#define DTG_TRACE_TITLE "<color=yellow>NhiÖm vô D· TÈu<color>"
#define DTG_BRIEF_NONE "Ch­a nhËn nhiÖm vô."
#define DTG_BRIEF_RETURN "<color=yellow>VÒ gÆp D· TÈu tr¶ nhiÖm vô!<color>"
#define DTG_BRIEF_T1 "Mua vËt phÈm cho D· TÈu"
#define DTG_BRIEF_T2 "T×m vËt phÈm nép D· TÈu"
#define DTG_BRIEF_T3 "Khoe trang bŞ víi D· TÈu"
#define DTG_BRIEF_T4_FMT "%s: <color=yellow>%d/%s tÊm<color>"
#define DTG_BRIEF_T5 "N©ng chØ sè theo yªu cÇu"
#define DTG_BRIEF_T6_FMT "M¶nh S¬n Hµ X· T¾c: <color=yellow>%d/%s<color>"
#define DTG_NO_SUPPORT "Ch­a hç trî hiÓn thŞ lo¹i nhiÖm vô nµy."

// [TIN SU 21/08] Chi nam nhiem vu - muc Nhiem vu Tin Su (TaskId 7), them tay (gen_strings.py da mat)
#define TS_NOTASK "B¹n ch­a tiÕp nhËn nhiÖm vô Tİn Sø. H·y ®Õn gÆp DŞch Quan ë Thµnh §« hoÆc §¹i Lı (cÇn cÊp 90) ®Ó nhËn nhiÖm vô."
#define TS_ROUTE_FMT "NhiÖm vô Tİn Sø ®Æc biÖt: ®­a tin tõ <color=yellow>%s<color> ®Õn <color=yellow>%s<color>."
#define TS_ROUTE_1A "Thµnh §«"
#define TS_ROUTE_1B "§¹i Lı"
#define TS_ST10 "<color=green>[§ang lµm]<color> H·y t×m Xa Phu chän <color=yellow>§i n¬i ®Æc biÖt lµm NhiÖm vô Tİn Sø <color>®Ó vµo ¶i Thiªn B¶o Khè, råi ®èi tho¹i víi DŞch Quan trong ¶i."
#define TS_ST20_FMT "<color=green>[§ang lµm]<color> Trong Thiªn B¶o Khè: më <color=yellow>5<color> B¶o R­¬ng ®óng thø tù <color=yellow>%s<color>. §· më: <color=yellow>%s<color> (%d/5). Xong th× t×m Tiªu TrÊn ®Ó ra ¶i."
#define TS_ST21 "<color=green>[§ang lµm]<color> NhiÖm vô t¹m ng­ng. Vµo l¹i ¶i Thiªn B¶o Khè qua Xa Phu vµ ®èi tho¹i víi DŞch Quan trong ¶i ®Ó tiÕp tôc."
#define TS_ST25 "<color=yellow>[Hoµn thµnh mét phÇn]<color> §· rêi ¶i khi ch­a më ®ñ r­¬ng. VÒ gÆp DŞch Quan ë thµnh ®İch ®Ó tr¶ nhiÖm vô."
#define TS_ST30 "<color=yellow>[Hoµn thµnh - vÒ gÆp DŞch Quan]<color> §· v­ît ¶i Thiªn B¶o Khè! VÒ <color=yellow>%s<color> gÆp DŞch Quan nhËn th­ëng (cÇn 5 « trèng hµnh trang)."
#define TS_NONE "(ch­a më)"
#define TS_POINT_FMT "§iÓm tİch luü Tİn Sø: <color=yellow>%d<color>. Danh hiÖu Tİn Sø: <color=yellow>%s<color>. H«m nay ®· hoµn thµnh: %d lÇn."
#define TS_TITLE_0 "ch­a cã"
#define TS_TITLE_1 "Méc"
#define TS_TITLE_2 "§ång"
#define TS_TITLE_3 "Ng©n"
#define TS_TITLE_4 "Kim"
#define TS_TITLE_5 "Ngù Tø"
#define TS_BRIEF_NONE "Ch­a nhËn nhiÖm vô Tİn Sø."

// ---- [CHI NAM 24/08] Bang Chien (tongwar) - task 2369..2378 ----
#define TW_NOTASK      "Ng­¬i ch­a tham gia trËn Bang ChiÕn nµo. Mïa gi¶i diÔn ra vµo cuèi th¸ng 10 - ®Çu th¸ng 11, mçi tèi mét trËn."
#define TW_INFO_FMT    "®iÓm trËn nµy: <color=yellow>%d<color> . Tæng ®iÓm c¶ mïa: <color=yellow>%d<color> ."
#define TW_KILL_FMT    "®· h¹: <color=yellow>%d<color> ng­êi . Chuçi h¹ cao nhÊt: <color=yellow>%d<color> ."
#define TW_DEATH_FMT   "Sè lÇn tö vong: <color=yellow>%d<color> / <color=yellow>%d<color> . HÕt sè m¹ng sÏ bŞ ®­a khái chiÕn tr­êng."
#define TW_RANK_FMT    "Qu©n hµm hiÖn t¹i: <color=yellow>%s<color> ."
#define TW_RANK_0      "ch­a cã"
#define TW_RANK_1      "Binh SÜ"
#define TW_RANK_2      "HiÖu óy"
#define TW_RANK_3      "Thèng LÜnh"
#define TW_RANK_4      "Phã T­íng"
#define TW_RANK_5      "®¹i T­íng"

// ---- [CHI NAM 24/08] Bach Nhan Loi Dai - task 2709 (yymmdd*256 + dem) ----
#define BR_INFO        "B¸ch Nh©n L«i ®µi më mçi ngµy tõ 12:00 ®Õn 24:00 t¹i L«i ®µi Hoµng Thµnh Tõ (vµo b»ng Quan nh¹c nhá ë L©m An)."
#define BR_HOWTO       "Dïng khinh c«ng nh¶y lªn l«i ®µi ®Ó lµm L«i Chñ. ë trong b¶n ®å ®­îc céng kinh nghiÖm mçi 5 phót; gi÷ ®­îc ®µi th× céng thªm."
#define BR_LIMIT_FMT   "L­ît nhËn kinh nghiÖm h«m nay: <color=yellow>%d<color> / <color=yellow>%d<color> ."
#define BR_LIMIT_FULL  "H«m nay ®· dïng hÕt l­ît nhËn kinh nghiÖm. H·y quay l¹i vµo ngµy mai."
// [3HD 25/08] San boss Sat Thu (TaskId 10) - chuoi TCVN3 tho
#define ST3_INFO       "GÆp NhiÕp Thİ TrÇn ë thÊt ®¹i thµnh thŞ ®Ó nhËn nhiÖm vô truy n· s¸t thñ (mçi ngµy tèi ®a 8 lÇn)."
#define ST3_HOWTO      "T×m vµ tiªu diÖt ®óng tªn s¸t thñ ®­îc giao; gép 5 S¸t Thñ lÖnh cïng cÊp thµnh S¸t Thñ Gi¶n - vĞ vµo Th¸ch thøc thêi gian."
#define ST3_CUR_FMT    "§ang truy n· s¸t thñ sè hiÖu <color=yellow>%d <color>(nhãm cÊp %d) - ng­¬i tù chän trong danh s¸ch."
#define ST3_GROUP90    "Nhãm cÊp 90: h¹ xong cã th­ëng lín vµ S¸t Thñ lÖnh cÊp 90."
#define ST3_GROUPLOW   "Nhãm cÊp thÊp: b¶n gèc chØ cßn nhãm 90 ph¸t th­ëng - h·y nhËn nhiÖm vô cÊp 90."
#define ST3_NOTASK     "Ch­a nhËn nhiÖm vô s¸t thñ nµo."
#define ST3_LIMIT_FMT  "Sè lÇn ®· giÕt h«m nay: <color=yellow>%d<color> / 8 ."
// [3HD 25/08 C18] muc tieu boss + khung theo doi cua San Boss Sat Thu
#define ST3_TARGET_FMT "Môc tiªu: <color=yellow>%s <color>%s."
#define ST3_TRACE_TITLE "<color=yellow>S¨n Boss S¸t Thñ <color>"
#define ST3_BRIEF_FMT "%s - %s. GiÕt: %d/8."
#define ST3_BRIEF_NONE "Ch­a nhËn nhiÖm vô s¸t thñ."
#define ST3_HINT_GO    "Kİch vµo dßng nhiÖm vô ®Ó tù ch¹y tíi boss (tèn tiÒn xe nÕu kh¸c map)."
