// UiTaskGuideStr.h - SINH TU DONG boi scratchpad/mine/gen_strings.py. DUNG SUA TAY.
// Chuoi TCVN3 o dang octal escape. Nguon cau chu: UI\taskui_random.lua
// (ban trong update01.pak cua client dang phat hanh) + vn_to_octal cho chuoi moi.
#pragma once

#define DTG_NOTASK "B¹n ch­a tiÕp nhËn nhiÖm vô cña D· TÈu, cã thêi gian h·y ®Õn gÆp «ng ta xem!"
#define DTG_T1_FMT "®Õn  %s mua  %s  cho D· TÈu."
#define DTG_T2A_FMT "®i t×m%s gióp ta."
#define DTG_T2B_FMT "®i t×m%s thÊp nhÊt lµ %s lín nhÊt lµ %s %s vÒ cho D· TÈu!"
#define DTG_T3_FMT "§i t×m bé trang bŞ %s thÊp nhÊt lµ %s cao nhÊt lµ %s cho D· tÈu!"
#define DTG_T4_FMT "§Õn <color=yellow>%s<color> t×m <color=yellow>%s<color> quyÓn %s vÒ cho D· TÈu!<enter>B¹n hiÖn ®· thu thËp ®­îc <color=yellow>%d<color> tÊm %s"
#define DTG_LOAI_DIADO "§Şa §å chİ "
#define DTG_LOAI_MAT "MËt chİ "
#define DTG_T5_FMT "§i n©ng cÊp   %s %s"
#define DTG_T5_SUB1 " cÊp"
#define DTG_T5_SUB2 "®iÓm kinh nghiÖm "
#define DTG_T5_SUB3_FMT "®iÓm danh väng. Danh väng cña b¹n hiÖn t¹i lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T5_SUB4_FMT "®iÓm phóc duyªn. Phóc duyªn cña b¹n hiÖn t¹i lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T5_SUB5 "®iÓm PK"
#define DTG_T5_SUB6_FMT "®iÓm th­ëng Tèng Kim, ®iÓm th­ëng cña b¹n hiÖn lµ %d ®iÓm, cÇn ph¶i n©ng lªn%d ®iÓm,"
#define DTG_T6_FMT "®Õn ®­a D· TÈu %s m¶nh b¶n ®å S¬n Hµ X· T¾c.<enter>B¹n hiÖn ®· thu thËp ®­îc <color=yellow>%d<color> tÊm."
#define DTG_PREFIX_LAM "<color=green>[®ang lµm] <color>"
#define DTG_PREFIX_XONG "<color=yellow>[hoµn thµnh - h·y vÒ gÆp D· TÈu] <color>"
#define DTG_EXTRA_FMT "H«m nay ®· lµm: <color=yellow>%d/40<color> nhiÖm vô, ®· hñy: %d lÇn."
#define DTG_HINT_XAFU "<color=Cyan>NhÊp vµo dßng nhiÖm vô ®Ó tù ch¹y ®Õn Xa Phu ®i tíi map lµm nhiÖm vô.<color>"
#define DTG_TRACE_TITLE "<color=yellow>NhiÖm vô D· TÈu<color>"
#define DTG_BRIEF_NONE "Ch­a nhËn nhiÖm vô."
#define DTG_BRIEF_RETURN "<color=yellow>VÒ gÆp D· TÈu tr¶ nhiÖm vô!<color>"
#define DTG_BRIEF_T1 "Mua vËt phÈm cho D· TÈu"
#define DTG_BRIEF_T2 "T×m vËt phÈm nép D· TÈu"
#define DTG_BRIEF_T3 "Khoe trang bŞ víi D· TÈu"
#define DTG_BRIEF_T4_FMT "%s: <color=yellow>%d/%s tÊm<color>"
#define DTG_BRIEF_T5 "N©ng chØ sè theo yªu cÇu"
#define DTG_BRIEF_T6_FMT "M¶nh S¬n Hµ X· T¾c: <color=yellow>%d/%s<color>"
#define DTG_NO_SUPPORT "Ch­a hç trî hiÓn thŞ lo¹i nhiÖm vô nµy."
