#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PSCB
// {
//
//   int4 g_st0;                        // Offset:    0 Size:    16 [unused]
//   int4 g_st0b;                       // Offset:   16 Size:    16
//   int4 g_st1;                        // Offset:   32 Size:    16
//   int4 g_st1b;                       // Offset:   48 Size:    16
//   float4 g_at;                       // Offset:   64 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_s0                              sampler      NA          NA             s0      1 
// g_s1                              sampler      NA          NA             s1      1 
// g_t0                              texture  float4     2darray             t0      1 
// g_t1                              texture  float4     2darray             t1      1 
// g_pal                             texture  float4          2d             t2      1 
// g_a8                              texture  float4     2darray             t3      1 
// g_a32                             texture  float4     2darray             t4      1 
// PSCB                              cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// PALROW                   0   xy          3     NONE    uint   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[5], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2darray (float,float,float,float) t0
dcl_resource_texture2darray (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2darray (float,float,float,float) t3
dcl_resource_texture2darray (float,float,float,float) t4
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_input_ps constant v3.xy
dcl_output o0.xyzw
dcl_temps 15
ushr r0.x, v3.y, l(8)
ushr r0.y, v3.x, l(27)
and r0.xy, r0.xyxx, l(15, 1, 0, 0)
ine r0.z, r0.x, l(1)
if_nz r0.z
  and r1.z, v3.x, l(0x0000ffff)
  ushr r2.x, v3.x, l(16)
  ushr r2.y, v3.x, l(25)
  ushr r2.z, v3.y, l(12)
  ushr r2.w, v3.y, l(20)
  and r3.xyzw, r2.xyzz, l(511, 3, 3, 4)
  utof r4.z, r3.x
  movc r0.z, r3.w, l(16), l(0)
  iadd r0.z, r0.z, r3.z
  and r2.xy, r2.zwzz, l(8, 15, 0, 0)
  movc r0.w, r2.x, l(32), l(0)
  iadd r0.z, r0.w, r0.z
  ushr r0.w, v3.y, l(24)
  ushr r2.x, v3.x, l(31)
  and r3.xzw, r0.wwww, l(3, 0, 4, 8)
  movc r2.zw, r3.zzzw, l(0,0,16,32), l(0,0,0,0)
  iadd r0.w, r2.z, r3.x
  iadd r0.w, r2.w, r0.w
  ieq r2.z, r3.y, l(1)
  if_nz r2.z
    mov r4.xy, v2.xyxx
    sample r5.xyzw, r4.xyzx, t3.xyzw, s0
  endif 
  if_z r2.z
    ieq r2.w, r3.y, l(2)
    if_nz r2.w
      mov r4.xy, v2.xyxx
      sample r5.xyzw, r4.xyzx, t4.xyzw, s0
    endif 
    if_z r2.w
      mov r6.xy, v2.xyxx
      mov r6.z, l(0)
      sample r5.xyzw, r6.xyzx, t0.xyzw, s0
    endif 
  endif 
  movc r5.xyzw, r2.xxxx, r5.xzwy, l(1.000000,1.000000,1.000000,1.000000)
  ine r2.w, r1.z, l(0x0000ffff)
  ine r2.x, r2.x, l(0)
  and r2.x, r2.x, r2.w
  if_nz r2.x
    if_nz cb0[1].w
      if_nz r2.z
        resinfo r6.xyzw, l(0), t3.xyzw
      else 
        ieq r2.x, r3.y, l(2)
        if_nz r2.x
          resinfo r6.xyzw, l(0), t4.xyzw
        else 
          resinfo r6.xyzw, l(0), t0.xyzw
        endif 
      endif 
      mad r2.xw, v2.xxxy, r6.xxxy, l(-0.500000, 0.000000, 0.000000, -0.500000)
      frc r3.xz, r2.xxwx
      round_ni r2.xw, r2.xxxw
      ftoi r2.xw, r2.xxxw
      ftoi r4.xy, r6.xyxx
      iadd r4.xy, r4.xyxx, l(-1, -1, 0, 0)
      imax r6.xy, r2.xwxx, l(0, 0, 0, 0)
      imin r6.xy, r4.xyxx, r6.xyxx
      if_nz r2.z
        ftoi r6.z, r4.z
        mov r6.w, l(0)
        ld r7.xyzw, r6.xyzw, t3.xyzw
        mov r8.x, r7.y
      endif 
      if_z r2.z
        ieq r3.w, r3.y, l(2)
        if_nz r3.w
          ftoi r6.z, r4.z
          mov r6.w, l(0)
          ld r7.xyzw, r6.xyzw, t4.xyzw
          mov r8.x, r7.y
        endif 
        if_z r3.w
          mov r6.zw, l(0,0,0,0)
          ld r7.xyzw, r6.xyzw, t0.xyzw
          mov r8.x, r7.y
        endif 
      endif 
      mad r3.w, r7.x, l(255.000000), l(0.500000)
      ftou r1.y, r3.w
      mov r1.w, l(0)
      ld r6.xyzw, r1.yzww, t2.xyzw
      iadd r7.xyzw, r2.xwxw, l(1, 0, 0, 1)
      imax r7.xyzw, r7.xyzw, l(0, 0, 0, 0)
      imin r7.xyzw, r4.xyxy, r7.zwxy
      if_nz r2.z
        ftoi r9.z, r4.z
        mov r9.xy, r7.zwzz
        mov r9.w, l(0)
        ld r9.xyzw, r9.xyzw, t3.xyzw
        mov r10.x, r9.y
      endif 
      if_z r2.z
        ieq r3.w, r3.y, l(2)
        if_nz r3.w
          ftoi r11.z, r4.z
          mov r11.xy, r7.zwzz
          mov r11.w, l(0)
          ld r9.xyzw, r11.xyzw, t4.xyzw
          mov r10.x, r9.y
        endif 
        if_z r3.w
          mov r11.xy, r7.zwzz
          mov r11.zw, l(0,0,0,0)
          ld r9.xyzw, r11.xyzw, t0.xyzw
          mov r10.x, r9.y
        endif 
      endif 
      mad r3.w, r9.x, l(255.000000), l(0.500000)
      ftou r1.x, r3.w
      ld r9.xyzw, r1.xzww, t2.xyzw
      if_nz r2.z
        ftoi r7.z, r4.z
        mov r7.w, l(0)
        ld r11.xyzw, r7.xyzw, t3.xyzw
        mov r12.x, r11.y
      endif 
      if_z r2.z
        ieq r3.w, r3.y, l(2)
        if_nz r3.w
          ftoi r7.z, r4.z
          mov r7.w, l(0)
          ld r11.xyzw, r7.xyzw, t4.xyzw
          mov r12.x, r11.y
        endif 
        if_z r3.w
          mov r7.zw, l(0,0,0,0)
          ld r11.xyzw, r7.xyzw, t0.xyzw
          mov r12.x, r11.y
        endif 
      endif 
      mad r3.w, r11.x, l(255.000000), l(0.500000)
      ftou r1.y, r3.w
      ld r7.xyzw, r1.yzww, t2.xyzw
      iadd r2.xw, r2.xxxw, l(1, 0, 0, 1)
      imax r2.xw, r2.xxxw, l(0, 0, 0, 0)
      imin r11.xy, r4.xyxx, r2.xwxx
      if_nz r2.z
        ftoi r11.z, r4.z
        mov r11.w, l(0)
        ld r13.xyzw, r11.xyzw, t3.xyzw
        mov r14.x, r13.y
      endif 
      if_z r2.z
        ieq r2.x, r3.y, l(2)
        if_nz r2.x
          ftoi r11.z, r4.z
          mov r11.w, l(0)
          ld r13.xyzw, r11.xyzw, t4.xyzw
          mov r14.x, r13.y
        endif 
        if_z r2.x
          mov r11.zw, l(0,0,0,0)
          ld r13.xyzw, r11.xyzw, t0.xyzw
          mov r14.x, r13.y
        endif 
      endif 
      mad r2.x, r13.x, l(255.000000), l(0.500000)
      ftou r1.x, r2.x
      ld r4.xyzw, r1.xzww, t2.xyzw
      mov r8.yzw, r6.xxyz
      mov r10.yzw, r9.xxyz
      add r6.xyzw, -r8.yzwx, r10.yzwx
      mad r6.xyzw, r3.xxxx, r6.xyzw, r8.yzwx
      mov r12.yzw, r7.xxyz
      mov r14.yzw, r4.xxyz
      add r4.xyzw, -r12.yzwx, r14.yzwx
      mad r4.xyzw, r3.xxxx, r4.xyzw, r12.yzwx
      add r4.xyzw, -r6.xyzw, r4.xyzw
      mad r5.xyzw, r3.zzzz, r4.xzwy, r6.xzwy
    else 
      mad r2.x, r5.x, l(255.000000), l(0.500000)
      ftou r1.x, r2.x
      mov r1.yw, l(0,0,0,0)
      ld r1.xyzw, r1.xzyw, t2.xyzw
      mov r5.xyz, r1.xyzx
      mov r5.xyzw, r5.xzwy
    endif 
  endif 
  and r1.xyz, r0.zzzz, l(3, 16, 32, 0)
  ieq r2.xz, r1.xxxx, l(1, 0, 2, 0)
  movc r3.xyzw, r2.zzzz, r5.xwyz, l(1.000000,1.000000,1.000000,1.000000)
  movc r3.xyzw, r2.xxxx, v1.xyzw, r3.xyzw
  movc r3.xyzw, r1.xxxx, r3.xyzw, v1.xyzw
  add r4.xyzw, -r3.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
  movc r3.xyzw, r1.yyyy, r4.xyzw, r3.xyzw
  movc r1.xyz, r1.zzzz, r3.wwww, r3.xyzx
  and r0.zw, r0.wwww, l(0, 0, 3, 16)
  ieq r2.xz, r0.zzzz, l(1, 0, 2, 0)
  movc r2.z, r2.z, r5.z, l(1.000000)
  movc r2.x, r2.x, v1.w, r2.z
  movc r0.z, r0.z, r2.x, v1.w
  add r2.x, -r0.z, l(1.000000)
  movc r1.w, r0.w, r2.x, r0.z
  ine r0.z, r0.x, l(2)
  if_nz r0.z
    ushr r0.z, v3.y, l(16)
    and r2.xzw, r0.zzzz, l(3, 0, 4, 8)
    movc r0.zw, r2.zzzw, l(0,0,16,32), l(0,0,0,0)
    iadd r0.z, r0.z, r2.x
    iadd r0.z, r0.w, r0.z
    and r2.xzw, r0.zzzz, l(3, 0, 16, 32)
    ieq r0.zw, r2.xxxx, l(0, 0, 1, 2)
    movc r3.xyzw, r0.wwww, r5.xwyz, l(1.000000,1.000000,1.000000,1.000000)
    movc r3.xyzw, r0.zzzz, v1.xyzw, r3.xyzw
    movc r3.xyzw, r2.xxxx, r3.xyzw, v1.xyzw
    add r4.xyzw, -r3.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    movc r3.xyzw, r2.zzzz, r4.xyzw, r3.xyzw
    movc r2.xzw, r2.wwww, r3.wwww, r3.xxyz
    ine r0.z, r0.x, l(3)
    if_nz r0.z
      mul r3.xyz, r1.xyzx, r2.xzwx
      ine r0.z, r0.x, l(4)
      if_nz r0.z
        ine r0.z, r0.x, l(5)
        if_nz r0.z
          ine r0.z, r0.x, l(6)
          if_nz r0.z
            add r4.xyz, r1.xyzx, r2.xzwx
            ine r0.z, r0.x, l(7)
            if_nz r0.z
              add r5.xyw, r4.xyxz, l(-0.500000, -0.500000, 0.000000, -0.500000)
              ine r0.z, r0.x, l(8)
              if_nz r0.z
                add r6.xyz, r5.xywx, r5.xywx
                add r7.xyz, r1.xyzx, -r2.xzwx
                mad r8.xyz, -r1.xyzx, r2.xzwx, r4.xyzx
                ieq r9.xyzw, r0.xxxx, l(9, 10, 11, 13)
                add r0.xzw, -v1.xxyz, l(1.000000, 0.000000, 1.000000, 1.000000)
                mul r0.xzw, r0.xxzw, r2.xxzw
                mad r0.xzw, r1.xxyz, v1.xxyz, r0.xxzw
                movc r0.xzw, r9.wwww, r0.xxzw, v1.xxyz
                movc r0.xzw, r9.zzzz, r8.xxyz, r0.xxzw
                movc r0.xzw, r9.yyyy, r7.xxyz, r0.xxzw
                movc r1.xyz, r9.xxxx, r6.xyzx, r0.xzwx
              else 
                mov r1.xyz, r5.xywx
              endif 
            else 
              mov r1.xyz, r4.xyzx
            endif 
          else 
            mul r1.xyz, r3.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
          endif 
        else 
          add r1.xyz, r3.xyzx, r3.xyzx
        endif 
      else 
        mov r1.xyz, r3.xyzx
      endif 
    else 
      mov r1.xyz, r2.xzwx
    endif 
  endif 
  ine r0.x, r2.y, l(2)
  if_nz r0.x
    ushr r0.x, v3.y, l(28)
    and r0.xzw, r0.xxxx, l(3, 0, 4, 8)
    movc r0.zw, r0.zzzw, l(0,0,16,32), l(0,0,0,0)
    iadd r0.x, r0.z, r0.x
    iadd r0.x, r0.w, r0.x
    and r0.xz, r0.xxxx, l(3, 0, 16, 0)
    ieq r2.xz, r0.xxxx, l(1, 0, 2, 0)
    movc r0.w, r2.z, r5.z, l(1.000000)
    movc r0.w, r2.x, v1.w, r0.w
    movc r0.x, r0.x, r0.w, v1.w
    add r0.w, -r0.x, l(1.000000)
    movc r0.x, r0.z, r0.w, r0.x
    ine r0.z, r2.y, l(3)
    if_nz r0.z
      mul r0.z, r0.x, r1.w
      ine r0.w, r2.y, l(4)
      if_nz r0.w
        ine r0.w, r2.y, l(5)
        if_nz r0.w
          ine r0.w, r2.y, l(6)
          if_nz r0.w
            add r0.w, r0.x, r1.w
            ine r2.x, r2.y, l(7)
            if_nz r2.x
              add r2.x, r0.w, l(-0.500000)
              add r2.z, r2.x, r2.x
              add r2.w, -r0.x, r1.w
              ieq r3.xyzw, r2.yyyy, l(8, 9, 10, 11)
              mad r2.y, -r1.w, r0.x, r0.w
              movc r2.y, r3.w, r2.y, v1.w
              movc r2.y, r3.z, r2.w, r2.y
              movc r2.y, r3.y, r2.z, r2.y
              movc r1.w, r3.x, r2.x, r2.y
            else 
              mov r1.w, r0.w
            endif 
          else 
            mul r1.w, r0.z, l(4.000000)
          endif 
        else 
          add r1.w, r0.z, r0.z
        endif 
      else 
        mov r1.w, r0.z
      endif 
    else 
      mov r1.w, r0.x
    endif 
  endif 
  mov_sat r1.xyzw, r1.xyzw
  ine r0.x, cb0[2].x, l(1)
  if_nz r0.x
    ftou r0.x, cb0[4].x
    ieq r0.z, r0.x, l(1)
    if_nz r0.z
      mov r2.xy, v2.xyxx
      mov r2.z, cb0[4].y
      sample r2.xyzw, r2.xyzx, t3.xyzw, s1
    endif 
    if_z r0.z
      ieq r0.x, r0.x, l(2)
      if_nz r0.x
        mov r3.xy, v2.xyxx
        mov r3.z, cb0[4].y
        sample r2.xyzw, r3.xyzx, t4.xyzw, s1
      endif 
      if_z r0.x
        mov r3.xy, v2.xyxx
        mov r3.z, l(0)
        sample r2.xyzw, r3.xyzx, t1.xyzw, s1
      endif 
    endif 
    movc r2.xyzw, cb0[3].zzzz, r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
    and r0.xzw, cb0[2].yyyy, l(15, 0, 16, 32)
    ieq r3.xy, r0.xxxx, l(1, 2, 0, 0)
    movc r4.xyzw, r3.yyyy, r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
    movc r3.xyzw, r3.xxxx, r1.xyzw, r4.xyzw
    movc r3.xyzw, r0.xxxx, r3.xyzw, v1.xyzw
    add r4.xyzw, -r3.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    movc r3.xyzw, r0.zzzz, r4.xyzw, r3.xyzw
    movc r0.xzw, r0.wwww, r3.wwww, r3.xxyz
    and r3.xy, cb0[3].xxxx, l(15, 16, 0, 0)
    ieq r3.zw, r3.xxxx, l(0, 0, 1, 2)
    movc r3.w, r3.w, r2.w, l(1.000000)
    movc r3.z, r3.z, r1.w, r3.w
    movc r3.x, r3.x, r3.z, v1.w
    add r3.z, -r3.x, l(1.000000)
    movc r3.x, r3.y, r3.z, r3.x
    ine r3.yz, cb0[2].xxwx, l(0, 2, 2, 0)
    if_nz r3.y
      and r4.xyz, cb0[2].zzzz, l(15, 16, 32, 0)
      ieq r3.yw, r4.xxxx, l(0, 1, 0, 2)
      movc r5.xyzw, r3.wwww, r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
      movc r5.xyzw, r3.yyyy, r1.xyzw, r5.xyzw
      movc r5.xyzw, r4.xxxx, r5.xyzw, v1.xyzw
      add r6.xyzw, -r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
      movc r5.xyzw, r4.yyyy, r6.xyzw, r5.xyzw
      movc r2.xyz, r4.zzzz, r5.wwww, r5.xyzx
      ine r3.y, cb0[2].x, l(3)
      if_nz r3.y
        mul r4.xyz, r0.xzwx, r2.xyzx
        ine r3.y, cb0[2].x, l(4)
        if_nz r3.y
          ine r3.y, cb0[2].x, l(5)
          if_nz r3.y
            ine r3.y, cb0[2].x, l(6)
            if_nz r3.y
              add r5.xyz, r0.xzwx, r2.xyzx
              ine r3.y, cb0[2].x, l(7)
              if_nz r3.y
                add r6.xyz, r5.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
                ine r3.y, cb0[2].x, l(8)
                if_nz r3.y
                  add r7.xyz, r6.xyzx, r6.xyzx
                  add r8.xyz, r0.xzwx, -r2.xyzx
                  mad r9.xyz, -r0.xzwx, r2.xyzx, r5.xyzx
                  ieq r10.xyzw, cb0[2].xxxx, l(9, 10, 11, 13)
                  add r11.xyz, -r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
                  mul r11.xyz, r2.xyzx, r11.xyzx
                  mad r11.xyz, r0.xzwx, r1.xyzx, r11.xyzx
                  movc r11.xyz, r10.wwww, r11.xyzx, r1.xyzx
                  movc r9.xyz, r10.zzzz, r9.xyzx, r11.xyzx
                  movc r8.xyz, r10.yyyy, r8.xyzx, r9.xyzx
                  movc r1.xyz, r10.xxxx, r7.xyzx, r8.xyzx
                else 
                  mov r1.xyz, r6.xyzx
                endif 
              else 
                mov r1.xyz, r5.xyzx
              endif 
            else 
              mul r1.xyz, r4.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
            endif 
          else 
            add r1.xyz, r4.xyzx, r4.xyzx
          endif 
        else 
          mov r1.xyz, r4.xyzx
        endif 
      else 
        mov r1.xyz, r2.xyzx
      endif 
    else 
      mov r1.xyz, r0.xzwx
    endif 
    if_nz r3.z
      and r0.xz, cb0[3].yyyy, l(15, 0, 16, 0)
      ieq r2.xy, r0.xxxx, l(1, 2, 0, 0)
      movc r0.w, r2.y, r2.w, l(1.000000)
      movc r0.w, r2.x, r1.w, r0.w
      movc r0.x, r0.x, r0.w, v1.w
      add r0.w, -r0.x, l(1.000000)
      movc r0.x, r0.z, r0.w, r0.x
      ine r0.z, cb0[2].w, l(3)
      if_nz r0.z
        mul r0.z, r0.x, r3.x
        ine r0.w, cb0[2].w, l(4)
        if_nz r0.w
          ine r0.w, cb0[2].w, l(5)
          if_nz r0.w
            ine r0.w, cb0[2].w, l(6)
            if_nz r0.w
              add r0.w, r0.x, r3.x
              ine r2.x, cb0[2].w, l(7)
              if_nz r2.x
                add r2.x, r0.w, l(-0.500000)
                add r2.y, r2.x, r2.x
                add r2.z, -r0.x, r3.x
                ieq r4.xyzw, cb0[2].wwww, l(8, 9, 10, 11)
                mad r2.w, -r3.x, r0.x, r0.w
                movc r2.w, r4.w, r2.w, r1.w
                movc r2.z, r4.z, r2.z, r2.w
                movc r2.y, r4.y, r2.y, r2.z
                movc r1.w, r4.x, r2.x, r2.y
              else 
                mov r1.w, r0.w
              endif 
            else 
              mul r1.w, r0.z, l(4.000000)
            endif 
          else 
            add r1.w, r0.z, r0.z
          endif 
        else 
          mov r1.w, r0.z
        endif 
      else 
        mov r1.w, r0.x
      endif 
    else 
      mov r1.w, r3.x
    endif 
    mov_sat r1.xyzw, r1.xyzw
  endif 
else 
  mov r1.xyzw, v1.xyzw
endif 
if_nz r0.y
  ushr r0.x, v3.x, l(28)
  and r0.x, r0.x, l(7)
  iadd r0.x, r0.x, l(1)
  ieq r0.y, r0.x, l(1)
  if_nz r0.y
    mov r0.y, l(0)
  else 
    mad r0.z, r1.w, l(255.000000), l(0.500000)
    round_ni r0.z, r0.z
    ftoi r0.z, r0.z
    and r0.w, v3.y, l(255)
    ieq r2.y, r0.w, r0.z
    ige r2.z, r0.w, r0.z
    ieq r3.xyzw, r0.xxxx, l(2, 3, 4, 5)
    ilt r2.xw, r0.zzzw, r0.wwwz
    ine r4.x, r0.w, r0.z
    ieq r4.yz, r0.xxxx, l(0, 6, 7, 0)
    ige r0.x, r0.z, r0.w
    movc r0.x, r4.z, r0.x, l(-1)
    movc r0.x, r4.y, r4.x, r0.x
    movc r0.x, r3.w, r2.w, r0.x
    movc r0.x, r3.z, r2.z, r0.x
    movc r0.x, r3.y, r2.y, r0.x
    movc r0.y, r3.x, r2.x, r0.x
  endif 
  not r0.x, r0.y
  discard_nz r0.x
endif 
mov o0.xyzw, r1.xyzw
ret 
// Approximately 490 instruction slots used
#endif

const BYTE g_Rep3PS11Mang[] =
{
     68,  88,  66,  67,  32, 146, 
    196,  40,   5,  14,  22,   2, 
    242, 118,  88, 121, 143, 166, 
     23, 162,   1,   0,   0,   0, 
    204,  49,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    128,   2,   0,   0,  20,   3, 
      0,   0,  72,   3,   0,   0, 
     80,  49,   0,   0,  82,  68, 
     69,  70,  68,   2,   0,   0, 
      1,   0,   0,   0,  72,   1, 
      0,   0,   8,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    255, 255,   0,   1,   0,   0, 
     28,   2,   0,   0,  28,   1, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
     33,   1,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0,  38,   1,   0,   0, 
      2,   0,   0,   0,   5,   0, 
      0,   0,   5,   0,   0,   0, 
    255, 255, 255, 255,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     13,   0,   0,   0,  43,   1, 
      0,   0,   2,   0,   0,   0, 
      5,   0,   0,   0,   5,   0, 
      0,   0, 255, 255, 255, 255, 
      1,   0,   0,   0,   1,   0, 
      0,   0,  13,   0,   0,   0, 
     48,   1,   0,   0,   2,   0, 
      0,   0,   5,   0,   0,   0, 
      4,   0,   0,   0, 255, 255, 
    255, 255,   2,   0,   0,   0, 
      1,   0,   0,   0,  13,   0, 
      0,   0,  54,   1,   0,   0, 
      2,   0,   0,   0,   5,   0, 
      0,   0,   5,   0,   0,   0, 
    255, 255, 255, 255,   3,   0, 
      0,   0,   1,   0,   0,   0, 
     13,   0,   0,   0,  59,   1, 
      0,   0,   2,   0,   0,   0, 
      5,   0,   0,   0,   5,   0, 
      0,   0, 255, 255, 255, 255, 
      4,   0,   0,   0,   1,   0, 
      0,   0,  13,   0,   0,   0, 
     65,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0, 103,  95, 115,  48, 
      0, 103,  95, 115,  49,   0, 
    103,  95, 116,  48,   0, 103, 
     95, 116,  49,   0, 103,  95, 
    112,  97, 108,   0, 103,  95, 
     97,  56,   0, 103,  95,  97, 
     51,  50,   0,  80,  83,  67, 
     66,   0, 171, 171,  65,   1, 
      0,   0,   5,   0,   0,   0, 
     96,   1,   0,   0,  80,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 216,   1, 
      0,   0,   0,   0,   0,   0, 
     16,   0,   0,   0,   0,   0, 
      0,   0, 224,   1,   0,   0, 
      0,   0,   0,   0, 240,   1, 
      0,   0,  16,   0,   0,   0, 
     16,   0,   0,   0,   2,   0, 
      0,   0, 224,   1,   0,   0, 
      0,   0,   0,   0, 247,   1, 
      0,   0,  32,   0,   0,   0, 
     16,   0,   0,   0,   2,   0, 
      0,   0, 224,   1,   0,   0, 
      0,   0,   0,   0, 253,   1, 
      0,   0,  48,   0,   0,   0, 
     16,   0,   0,   0,   2,   0, 
      0,   0, 224,   1,   0,   0, 
      0,   0,   0,   0,   4,   2, 
      0,   0,  64,   0,   0,   0, 
     16,   0,   0,   0,   2,   0, 
      0,   0,  12,   2,   0,   0, 
      0,   0,   0,   0, 103,  95, 
    115, 116,  48,   0, 171, 171, 
      1,   0,   2,   0,   1,   0, 
      4,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 103,  95, 
    115, 116,  48,  98,   0, 103, 
     95, 115, 116,  49,   0, 103, 
     95, 115, 116,  49,  98,   0, 
    103,  95,  97, 116,   0, 171, 
    171, 171,   1,   0,   3,   0, 
      1,   0,   4,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     77, 105,  99, 114, 111, 115, 
    111, 102, 116,  32,  40,  82, 
     41,  32,  72,  76,  83,  76, 
     32,  83, 104,  97, 100, 101, 
    114,  32,  67, 111, 109, 112, 
    105, 108, 101, 114,  32,  49, 
     48,  46,  49,   0,  73,  83, 
     71,  78, 140,   0,   0,   0, 
      4,   0,   0,   0,   8,   0, 
      0,   0, 104,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,  15,   0, 
      0,   0, 116,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   0,   0,  15,  15, 
      0,   0, 122,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      2,   0,   0,   0,   3,   3, 
      0,   0, 131,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      3,   0,   0,   0,   3,   3, 
      0,   0,  83,  86,  95,  80, 
    111, 115, 105, 116, 105, 111, 
    110,   0,  67,  79,  76,  79, 
     82,   0,  84,  69,  88,  67, 
     79,  79,  82,  68,   0,  80, 
     65,  76,  82,  79,  87,   0, 
    171, 171,  79,  83,  71,  78, 
     44,   0,   0,   0,   1,   0, 
      0,   0,   8,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,   0,   0,   0, 
     83,  86,  95,  84,  97, 114, 
    103, 101, 116,   0, 171, 171, 
     83,  72,  68,  82,   0,  46, 
      0,   0,  64,   0,   0,   0, 
    128,  11,   0,   0,  89,   0, 
      0,   4,  70, 142,  32,   0, 
      0,   0,   0,   0,   5,   0, 
      0,   0,  90,   0,   0,   3, 
      0,  96,  16,   0,   0,   0, 
      0,   0,  90,   0,   0,   3, 
      0,  96,  16,   0,   1,   0, 
      0,   0,  88,  64,   0,   4, 
      0, 112,  16,   0,   0,   0, 
      0,   0,  85,  85,   0,   0, 
     88,  64,   0,   4,   0, 112, 
     16,   0,   1,   0,   0,   0, 
     85,  85,   0,   0,  88,  24, 
      0,   4,   0, 112,  16,   0, 
      2,   0,   0,   0,  85,  85, 
      0,   0,  88,  64,   0,   4, 
      0, 112,  16,   0,   3,   0, 
      0,   0,  85,  85,   0,   0, 
     88,  64,   0,   4,   0, 112, 
     16,   0,   4,   0,   0,   0, 
     85,  85,   0,   0,  98,  16, 
      0,   3, 242,  16,  16,   0, 
      1,   0,   0,   0,  98,  16, 
      0,   3,  50,  16,  16,   0, 
      2,   0,   0,   0,  98,   8, 
      0,   3,  50,  16,  16,   0, 
      3,   0,   0,   0, 101,   0, 
      0,   3, 242,  32,  16,   0, 
      0,   0,   0,   0, 104,   0, 
      0,   2,  15,   0,   0,   0, 
     85,   0,   0,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     26,  16,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      8,   0,   0,   0,  85,   0, 
      0,   7,  34,   0,  16,   0, 
      0,   0,   0,   0,  10,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,  27,   0, 
      0,   0,   1,   0,   0,  10, 
     50,   0,  16,   0,   0,   0, 
      0,   0,  70,   0,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,  15,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     39,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      1,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   7,  66,   0,  16,   0, 
      1,   0,   0,   0,  10,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0, 255, 255, 
      0,   0,  85,   0,   0,   7, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  10,  16,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,  16,   0,   0,   0, 
     85,   0,   0,   7,  34,   0, 
     16,   0,   2,   0,   0,   0, 
     10,  16,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
     25,   0,   0,   0,  85,   0, 
      0,   7,  66,   0,  16,   0, 
      2,   0,   0,   0,  26,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,  12,   0, 
      0,   0,  85,   0,   0,   7, 
    130,   0,  16,   0,   2,   0, 
      0,   0,  26,  16,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,  20,   0,   0,   0, 
      1,   0,   0,  10, 242,   0, 
     16,   0,   3,   0,   0,   0, 
     70,  10,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
    255,   1,   0,   0,   3,   0, 
      0,   0,   3,   0,   0,   0, 
      4,   0,   0,   0,  86,   0, 
      0,   5,  66,   0,  16,   0, 
      4,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     55,   0,   0,   9,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
     16,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     30,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,   1,   0, 
      0,  10,  50,   0,  16,   0, 
      2,   0,   0,   0, 230,  10, 
     16,   0,   2,   0,   0,   0, 
      2,  64,   0,   0,   8,   0, 
      0,   0,  15,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,  32,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,   0,  30,   0,   0,   7, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     85,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     26,  16,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
     24,   0,   0,   0,  85,   0, 
      0,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  10,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,  31,   0, 
      0,   0,   1,   0,   0,  10, 
    210,   0,  16,   0,   3,   0, 
      0,   0, 246,  15,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   4,   0, 
      0,   0,   8,   0,   0,   0, 
     55,   0,   0,  15, 194,   0, 
     16,   0,   2,   0,   0,   0, 
    166,  14,  16,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
     32,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     30,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  30,   0, 
      0,   7, 130,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  32,   0,   0,   7, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,   1,   0,   0,   0, 
     31,   0,   4,   3,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     54,   0,   0,   5,  50,   0, 
     16,   0,   4,   0,   0,   0, 
     70,  16,  16,   0,   2,   0, 
      0,   0,  69,   0,   0,   9, 
    242,   0,  16,   0,   5,   0, 
      0,   0,  70,   2,  16,   0, 
      4,   0,   0,   0,  70, 126, 
     16,   0,   3,   0,   0,   0, 
      0,  96,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     31,   0,   0,   3,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     32,   0,   0,   7, 130,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   3,  58,   0,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   5,  50,   0,  16,   0, 
      4,   0,   0,   0,  70,  16, 
     16,   0,   2,   0,   0,   0, 
     69,   0,   0,   9, 242,   0, 
     16,   0,   5,   0,   0,   0, 
     70,   2,  16,   0,   4,   0, 
      0,   0,  70, 126,  16,   0, 
      4,   0,   0,   0,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      0,   3,  58,   0,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   5,  50,   0,  16,   0, 
      6,   0,   0,   0,  70,  16, 
     16,   0,   2,   0,   0,   0, 
     54,   0,   0,   5,  66,   0, 
     16,   0,   6,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,   0,  69,   0,   0,   9, 
    242,   0,  16,   0,   5,   0, 
      0,   0,  70,   2,  16,   0, 
      6,   0,   0,   0,  70, 126, 
     16,   0,   0,   0,   0,   0, 
      0,  96,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     21,   0,   0,   1,  55,   0, 
      0,  12, 242,   0,  16,   0, 
      5,   0,   0,   0,   6,   0, 
     16,   0,   2,   0,   0,   0, 
    134,   7,  16,   0,   5,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,  39,   0, 
      0,   7, 130,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0, 255, 255, 
      0,   0,  39,   0,   0,   7, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   7,  18,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   3,  10,   0,  16,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   4,  58, 128,  32,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  61,   0,   0,   7, 
    242,   0,  16,   0,   6,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  70, 126, 
     16,   0,   3,   0,   0,   0, 
     18,   0,   0,   1,  32,   0, 
      0,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  61,   0,   0,   7, 
    242,   0,  16,   0,   6,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  70, 126, 
     16,   0,   4,   0,   0,   0, 
     18,   0,   0,   1,  61,   0, 
      0,   7, 242,   0,  16,   0, 
      6,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     21,   0,   0,   1,  50,   0, 
      0,  12, 146,   0,  16,   0, 
      2,   0,   0,   0,   6,  20, 
     16,   0,   2,   0,   0,   0, 
      6,   4,  16,   0,   6,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0, 191,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 191,  26,   0, 
      0,   5,  82,   0,  16,   0, 
      3,   0,   0,   0,   6,   3, 
     16,   0,   2,   0,   0,   0, 
     65,   0,   0,   5, 146,   0, 
     16,   0,   2,   0,   0,   0, 
      6,  12,  16,   0,   2,   0, 
      0,   0,  27,   0,   0,   5, 
    146,   0,  16,   0,   2,   0, 
      0,   0,   6,  12,  16,   0, 
      2,   0,   0,   0,  27,   0, 
      0,   5,  50,   0,  16,   0, 
      4,   0,   0,   0,  70,   0, 
     16,   0,   6,   0,   0,   0, 
     30,   0,   0,  10,  50,   0, 
     16,   0,   4,   0,   0,   0, 
     70,   0,  16,   0,   4,   0, 
      0,   0,   2,  64,   0,   0, 
    255, 255, 255, 255, 255, 255, 
    255, 255,   0,   0,   0,   0, 
      0,   0,   0,   0,  36,   0, 
      0,  10,  50,   0,  16,   0, 
      6,   0,   0,   0, 198,   0, 
     16,   0,   2,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  37,   0,   0,   7, 
     50,   0,  16,   0,   6,   0, 
      0,   0,  70,   0,  16,   0, 
      4,   0,   0,   0,  70,   0, 
     16,   0,   6,   0,   0,   0, 
     31,   0,   4,   3,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     27,   0,   0,   5,  66,   0, 
     16,   0,   6,   0,   0,   0, 
     42,   0,  16,   0,   4,   0, 
      0,   0,  54,   0,   0,   5, 
    130,   0,  16,   0,   6,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   6,   0,   0,   0, 
     70, 126,  16,   0,   3,   0, 
      0,   0,  54,   0,   0,   5, 
     18,   0,  16,   0,   8,   0, 
      0,   0,  26,   0,  16,   0, 
      7,   0,   0,   0,  21,   0, 
      0,   1,  31,   0,   0,   3, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  32,   0,   0,   7, 
    130,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,   2,   0,   0,   0, 
     31,   0,   4,   3,  58,   0, 
     16,   0,   3,   0,   0,   0, 
     27,   0,   0,   5,  66,   0, 
     16,   0,   6,   0,   0,   0, 
     42,   0,  16,   0,   4,   0, 
      0,   0,  54,   0,   0,   5, 
    130,   0,  16,   0,   6,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   6,   0,   0,   0, 
     70, 126,  16,   0,   4,   0, 
      0,   0,  54,   0,   0,   5, 
     18,   0,  16,   0,   8,   0, 
      0,   0,  26,   0,  16,   0, 
      7,   0,   0,   0,  21,   0, 
      0,   1,  31,   0,   0,   3, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  54,   0,   0,   8, 
    194,   0,  16,   0,   6,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   6,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   5, 
     18,   0,  16,   0,   8,   0, 
      0,   0,  26,   0,  16,   0, 
      7,   0,   0,   0,  21,   0, 
      0,   1,  21,   0,   0,   1, 
     50,   0,   0,   9, 130,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   7,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 127,  67,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     28,   0,   0,   5,  34,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  54,   0,   0,   5, 
    130,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      6,   0,   0,   0, 150,  15, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   2,   0, 
      0,   0,  30,   0,   0,  10, 
    242,   0,  16,   0,   7,   0, 
      0,   0, 198,  12,  16,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     36,   0,   0,  10, 242,   0, 
     16,   0,   7,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  37,   0, 
      0,   7, 242,   0,  16,   0, 
      7,   0,   0,   0,  70,   4, 
     16,   0,   4,   0,   0,   0, 
    230,   4,  16,   0,   7,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  27,   0,   0,   5, 
     66,   0,  16,   0,   9,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5,  50,   0,  16,   0, 
      9,   0,   0,   0, 230,  10, 
     16,   0,   7,   0,   0,   0, 
     54,   0,   0,   5, 130,   0, 
     16,   0,   9,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,   0,  45,   0,   0,   7, 
    242,   0,  16,   0,   9,   0, 
      0,   0,  70,  14,  16,   0, 
      9,   0,   0,   0,  70, 126, 
     16,   0,   3,   0,   0,   0, 
     54,   0,   0,   5,  18,   0, 
     16,   0,  10,   0,   0,   0, 
     26,   0,  16,   0,   9,   0, 
      0,   0,  21,   0,   0,   1, 
     31,   0,   0,   3,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     32,   0,   0,   7, 130,   0, 
     16,   0,   3,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   3,  58,   0,  16,   0, 
      3,   0,   0,   0,  27,   0, 
      0,   5,  66,   0,  16,   0, 
     11,   0,   0,   0,  42,   0, 
     16,   0,   4,   0,   0,   0, 
     54,   0,   0,   5,  50,   0, 
     16,   0,  11,   0,   0,   0, 
    230,  10,  16,   0,   7,   0, 
      0,   0,  54,   0,   0,   5, 
    130,   0,  16,   0,  11,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      9,   0,   0,   0,  70,  14, 
     16,   0,  11,   0,   0,   0, 
     70, 126,  16,   0,   4,   0, 
      0,   0,  54,   0,   0,   5, 
     18,   0,  16,   0,  10,   0, 
      0,   0,  26,   0,  16,   0, 
      9,   0,   0,   0,  21,   0, 
      0,   1,  31,   0,   0,   3, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  54,   0,   0,   5, 
     50,   0,  16,   0,  11,   0, 
      0,   0, 230,  10,  16,   0, 
      7,   0,   0,   0,  54,   0, 
      0,   8, 194,   0,  16,   0, 
     11,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,   9,   0,   0,   0, 
     70,  14,  16,   0,  11,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     10,   0,   0,   0,  26,   0, 
     16,   0,   9,   0,   0,   0, 
     21,   0,   0,   1,  21,   0, 
      0,   1,  50,   0,   0,   9, 
    130,   0,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      9,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 127,  67, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  28,   0,   0,   5, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  58,   0,  16,   0, 
      3,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      9,   0,   0,   0, 134,  15, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  27,   0,   0,   5, 
     66,   0,  16,   0,   7,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5, 130,   0,  16,   0, 
      7,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  11,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,  70, 126,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     12,   0,   0,   0,  26,   0, 
     16,   0,  11,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      0,   3,  42,   0,  16,   0, 
      2,   0,   0,   0,  32,   0, 
      0,   7, 130,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  27,   0,   0,   5, 
     66,   0,  16,   0,   7,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5, 130,   0,  16,   0, 
      7,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  11,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,  70, 126,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     12,   0,   0,   0,  26,   0, 
     16,   0,  11,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      0,   3,  58,   0,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      0,   8, 194,   0,  16,   0, 
      7,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  11,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     12,   0,   0,   0,  26,   0, 
     16,   0,  11,   0,   0,   0, 
     21,   0,   0,   1,  21,   0, 
      0,   1,  50,   0,   0,   9, 
    130,   0,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
     11,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 127,  67, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  28,   0,   0,   5, 
     34,   0,  16,   0,   1,   0, 
      0,   0,  58,   0,  16,   0, 
      3,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      7,   0,   0,   0, 150,  15, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   2,   0, 
      0,   0,  30,   0,   0,  10, 
    146,   0,  16,   0,   2,   0, 
      0,   0,   6,  12,  16,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     36,   0,   0,  10, 146,   0, 
     16,   0,   2,   0,   0,   0, 
      6,  12,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  37,   0, 
      0,   7,  50,   0,  16,   0, 
     11,   0,   0,   0,  70,   0, 
     16,   0,   4,   0,   0,   0, 
    198,   0,  16,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  27,   0,   0,   5, 
     66,   0,  16,   0,  11,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5, 130,   0,  16,   0, 
     11,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  13,   0,   0,   0, 
     70,  14,  16,   0,  11,   0, 
      0,   0,  70, 126,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     14,   0,   0,   0,  26,   0, 
     16,   0,  13,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      0,   3,  42,   0,  16,   0, 
      2,   0,   0,   0,  32,   0, 
      0,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  27,   0,   0,   5, 
     66,   0,  16,   0,  11,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5, 130,   0,  16,   0, 
     11,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  13,   0,   0,   0, 
     70,  14,  16,   0,  11,   0, 
      0,   0,  70, 126,  16,   0, 
      4,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     14,   0,   0,   0,  26,   0, 
     16,   0,  13,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      0,   3,  10,   0,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   8, 194,   0,  16,   0, 
     11,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,  13,   0,   0,   0, 
     70,  14,  16,   0,  11,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,  54,   0, 
      0,   5,  18,   0,  16,   0, 
     14,   0,   0,   0,  26,   0, 
     16,   0,  13,   0,   0,   0, 
     21,   0,   0,   1,  21,   0, 
      0,   1,  50,   0,   0,   9, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
     13,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 127,  67, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  28,   0,   0,   5, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  45,   0, 
      0,   7, 242,   0,  16,   0, 
      4,   0,   0,   0, 134,  15, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   2,   0, 
      0,   0,  54,   0,   0,   5, 
    226,   0,  16,   0,   8,   0, 
      0,   0,   6,   9,  16,   0, 
      6,   0,   0,   0,  54,   0, 
      0,   5, 226,   0,  16,   0, 
     10,   0,   0,   0,   6,   9, 
     16,   0,   9,   0,   0,   0, 
      0,   0,   0,   8, 242,   0, 
     16,   0,   6,   0,   0,   0, 
    150,   3,  16, 128,  65,   0, 
      0,   0,   8,   0,   0,   0, 
    150,   3,  16,   0,  10,   0, 
      0,   0,  50,   0,   0,   9, 
    242,   0,  16,   0,   6,   0, 
      0,   0,   6,   0,  16,   0, 
      3,   0,   0,   0,  70,  14, 
     16,   0,   6,   0,   0,   0, 
    150,   3,  16,   0,   8,   0, 
      0,   0,  54,   0,   0,   5, 
    226,   0,  16,   0,  12,   0, 
      0,   0,   6,   9,  16,   0, 
      7,   0,   0,   0,  54,   0, 
      0,   5, 226,   0,  16,   0, 
     14,   0,   0,   0,   6,   9, 
     16,   0,   4,   0,   0,   0, 
      0,   0,   0,   8, 242,   0, 
     16,   0,   4,   0,   0,   0, 
    150,   3,  16, 128,  65,   0, 
      0,   0,  12,   0,   0,   0, 
    150,   3,  16,   0,  14,   0, 
      0,   0,  50,   0,   0,   9, 
    242,   0,  16,   0,   4,   0, 
      0,   0,   6,   0,  16,   0, 
      3,   0,   0,   0,  70,  14, 
     16,   0,   4,   0,   0,   0, 
    150,   3,  16,   0,  12,   0, 
      0,   0,   0,   0,   0,   8, 
    242,   0,  16,   0,   4,   0, 
      0,   0,  70,  14,  16, 128, 
     65,   0,   0,   0,   6,   0, 
      0,   0,  70,  14,  16,   0, 
      4,   0,   0,   0,  50,   0, 
      0,   9, 242,   0,  16,   0, 
      5,   0,   0,   0, 166,  10, 
     16,   0,   3,   0,   0,   0, 
    134,   7,  16,   0,   4,   0, 
      0,   0, 134,   7,  16,   0, 
      6,   0,   0,   0,  18,   0, 
      0,   1,  50,   0,   0,   9, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      5,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 127,  67, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  28,   0,   0,   5, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   8, 162,   0,  16,   0, 
      1,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     45,   0,   0,   7, 242,   0, 
     16,   0,   1,   0,   0,   0, 
    134,  13,  16,   0,   1,   0, 
      0,   0,  70, 126,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   5, 114,   0,  16,   0, 
      5,   0,   0,   0,  70,   2, 
     16,   0,   1,   0,   0,   0, 
     54,   0,   0,   5, 242,   0, 
     16,   0,   5,   0,   0,   0, 
    134,   7,  16,   0,   5,   0, 
      0,   0,  21,   0,   0,   1, 
     21,   0,   0,   1,   1,   0, 
      0,  10, 114,   0,  16,   0, 
      1,   0,   0,   0, 166,  10, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   3,   0, 
      0,   0,  16,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,  32,   0,   0,  10, 
     82,   0,  16,   0,   2,   0, 
      0,   0,   6,   0,  16,   0, 
      1,   0,   0,   0,   2,  64, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
     55,   0,   0,  12, 242,   0, 
     16,   0,   3,   0,   0,   0, 
    166,  10,  16,   0,   2,   0, 
      0,   0, 198,   9,  16,   0, 
      5,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
     55,   0,   0,   9, 242,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   0,  16,   0,   2,   0, 
      0,   0,  70,  30,  16,   0, 
      1,   0,   0,   0,  70,  14, 
     16,   0,   3,   0,   0,   0, 
     55,   0,   0,   9, 242,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   0,  16,   0,   1,   0, 
      0,   0,  70,  14,  16,   0, 
      3,   0,   0,   0,  70,  30, 
     16,   0,   1,   0,   0,   0, 
      0,   0,   0,  11, 242,   0, 
     16,   0,   4,   0,   0,   0, 
     70,  14,  16, 128,  65,   0, 
      0,   0,   3,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,  55,   0,   0,   9, 
    242,   0,  16,   0,   3,   0, 
      0,   0,  86,   5,  16,   0, 
      1,   0,   0,   0,  70,  14, 
     16,   0,   4,   0,   0,   0, 
     70,  14,  16,   0,   3,   0, 
      0,   0,  55,   0,   0,   9, 
    114,   0,  16,   0,   1,   0, 
      0,   0, 166,  10,  16,   0, 
      1,   0,   0,   0, 246,  15, 
     16,   0,   3,   0,   0,   0, 
     70,   2,  16,   0,   3,   0, 
      0,   0,   1,   0,   0,  10, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 246,  15,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,  16,   0,   0,   0, 
     32,   0,   0,  10,  82,   0, 
     16,   0,   2,   0,   0,   0, 
    166,  10,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,  55,   0, 
      0,   9,  66,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   5,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 128,  63,  55,   0, 
      0,   9,  18,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
     58,  16,  16,   0,   1,   0, 
      0,   0,  42,   0,  16,   0, 
      2,   0,   0,   0,  55,   0, 
      0,   9,  66,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  58,  16,  16,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   8,  18,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16, 128,  65,   0,   0,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 128,  63, 
     55,   0,   0,   9, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     39,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      0,   0,   0,   0,  85,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  26,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,  16,   0, 
      0,   0,   1,   0,   0,  10, 
    210,   0,  16,   0,   2,   0, 
      0,   0, 166,  10,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   4,   0, 
      0,   0,   8,   0,   0,   0, 
     55,   0,   0,  15, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
     32,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     30,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  30,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,   1,   0,   0,  10, 
    210,   0,  16,   0,   2,   0, 
      0,   0, 166,  10,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,  32,   0,   0,   0, 
     32,   0,   0,  10, 194,   0, 
     16,   0,   0,   0,   0,   0, 
      6,   0,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      2,   0,   0,   0,  55,   0, 
      0,  12, 242,   0,  16,   0, 
      3,   0,   0,   0, 246,  15, 
     16,   0,   0,   0,   0,   0, 
    198,   9,  16,   0,   5,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      3,   0,   0,   0, 166,  10, 
     16,   0,   0,   0,   0,   0, 
     70,  30,  16,   0,   1,   0, 
      0,   0,  70,  14,  16,   0, 
      3,   0,   0,   0,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      3,   0,   0,   0,   6,   0, 
     16,   0,   2,   0,   0,   0, 
     70,  14,  16,   0,   3,   0, 
      0,   0,  70,  30,  16,   0, 
      1,   0,   0,   0,   0,   0, 
      0,  11, 242,   0,  16,   0, 
      4,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
     55,   0,   0,   9, 242,   0, 
     16,   0,   3,   0,   0,   0, 
    166,  10,  16,   0,   2,   0, 
      0,   0,  70,  14,  16,   0, 
      4,   0,   0,   0,  70,  14, 
     16,   0,   3,   0,   0,   0, 
     55,   0,   0,   9, 210,   0, 
     16,   0,   2,   0,   0,   0, 
    246,  15,  16,   0,   2,   0, 
      0,   0, 246,  15,  16,   0, 
      3,   0,   0,   0,   6,   9, 
     16,   0,   3,   0,   0,   0, 
     39,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      3,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      0,   0,   0,   0,  56,   0, 
      0,   7, 114,   0,  16,   0, 
      3,   0,   0,   0,  70,   2, 
     16,   0,   1,   0,   0,   0, 
    134,   3,  16,   0,   2,   0, 
      0,   0,  39,   0,   0,   7, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   4,   0,   0,   0, 
     31,   0,   4,   3,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     39,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      5,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      0,   0,   0,   0,  39,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   6,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   0,   7, 
    114,   0,  16,   0,   4,   0, 
      0,   0,  70,   2,  16,   0, 
      1,   0,   0,   0, 134,   3, 
     16,   0,   2,   0,   0,   0, 
     39,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      7,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  10, 178,   0,  16,   0, 
      5,   0,   0,   0,  70,   8, 
     16,   0,   4,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0, 191,   0,   0,   0, 191, 
      0,   0,   0,   0,   0,   0, 
      0, 191,  39,   0,   0,   7, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   8,   0,   0,   0, 
     31,   0,   4,   3,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      0,   0,   0,   7, 114,   0, 
     16,   0,   6,   0,   0,   0, 
     70,   3,  16,   0,   5,   0, 
      0,   0,  70,   3,  16,   0, 
      5,   0,   0,   0,   0,   0, 
      0,   8, 114,   0,  16,   0, 
      7,   0,   0,   0,  70,   2, 
     16,   0,   1,   0,   0,   0, 
    134,   3,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
     50,   0,   0,  10, 114,   0, 
     16,   0,   8,   0,   0,   0, 
     70,   2,  16, 128,  65,   0, 
      0,   0,   1,   0,   0,   0, 
    134,   3,  16,   0,   2,   0, 
      0,   0,  70,   2,  16,   0, 
      4,   0,   0,   0,  32,   0, 
      0,  10, 242,   0,  16,   0, 
      9,   0,   0,   0,   6,   0, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   9,   0, 
      0,   0,  10,   0,   0,   0, 
     11,   0,   0,   0,  13,   0, 
      0,   0,   0,   0,   0,  11, 
    210,   0,  16,   0,   0,   0, 
      0,   0,   6,  25,  16, 128, 
     65,   0,   0,   0,   1,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,  56,   0, 
      0,   7, 210,   0,  16,   0, 
      0,   0,   0,   0,   6,  14, 
     16,   0,   0,   0,   0,   0, 
      6,  14,  16,   0,   2,   0, 
      0,   0,  50,   0,   0,   9, 
    210,   0,  16,   0,   0,   0, 
      0,   0,   6,   9,  16,   0, 
      1,   0,   0,   0,   6,  25, 
     16,   0,   1,   0,   0,   0, 
      6,  14,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    210,   0,  16,   0,   0,   0, 
      0,   0, 246,  15,  16,   0, 
      9,   0,   0,   0,   6,  14, 
     16,   0,   0,   0,   0,   0, 
      6,  25,  16,   0,   1,   0, 
      0,   0,  55,   0,   0,   9, 
    210,   0,  16,   0,   0,   0, 
      0,   0, 166,  10,  16,   0, 
      9,   0,   0,   0,   6,   9, 
     16,   0,   8,   0,   0,   0, 
      6,  14,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    210,   0,  16,   0,   0,   0, 
      0,   0,  86,   5,  16,   0, 
      9,   0,   0,   0,   6,   9, 
     16,   0,   7,   0,   0,   0, 
      6,  14,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    114,   0,  16,   0,   1,   0, 
      0,   0,   6,   0,  16,   0, 
      9,   0,   0,   0,  70,   2, 
     16,   0,   6,   0,   0,   0, 
    134,   3,  16,   0,   0,   0, 
      0,   0,  18,   0,   0,   1, 
     54,   0,   0,   5, 114,   0, 
     16,   0,   1,   0,   0,   0, 
     70,   3,  16,   0,   5,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 114,   0,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   4,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  56,   0,   0,  10, 
    114,   0,  16,   0,   1,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  64, 
      0,   0, 128,  64,   0,   0, 
    128,  64,   0,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,   0,   0,   0,   7, 
    114,   0,  16,   0,   1,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,  70,   2, 
     16,   0,   3,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    114,   0,  16,   0,   1,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,  21,   0, 
      0,   1,  18,   0,   0,   1, 
     54,   0,   0,   5, 114,   0, 
     16,   0,   1,   0,   0,   0, 
    134,   3,  16,   0,   2,   0, 
      0,   0,  21,   0,   0,   1, 
     21,   0,   0,   1,  39,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,  31,   0,   4,   3, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  85,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  26,  16,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,  28,   0,   0,   0, 
      1,   0,   0,  10, 210,   0, 
     16,   0,   0,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   4,   0,   0,   0, 
      8,   0,   0,   0,  55,   0, 
      0,  15, 194,   0,  16,   0, 
      0,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     16,   0,   0,   0,  32,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  30,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  30,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   0,  10,  82,   0, 
     16,   0,   0,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,  32,   0, 
      0,  10,  82,   0,  16,   0, 
      2,   0,   0,   0,   6,   0, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   5,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  63,  55,   0,   0,   9, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  58,  16, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
     58,  16,  16,   0,   1,   0, 
      0,   0,   0,   0,   0,   8, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16, 128, 
     65,   0,   0,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 128,  63,  55,   0, 
      0,   9,  18,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  39,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   3,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  56,   0,   0,   7, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   1,   0,   0,   0, 
     39,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      4,   0,   0,   0,  31,   0, 
      4,   3,  58,   0,  16,   0, 
      0,   0,   0,   0,  39,   0, 
      0,   7, 130,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   5,   0, 
      0,   0,  31,   0,   4,   3, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  39,   0,   0,   7, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  26,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   6,   0,   0,   0, 
     31,   0,   4,   3,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      0,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      1,   0,   0,   0,  39,   0, 
      0,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   7,   0, 
      0,   0,  31,   0,   4,   3, 
     10,   0,  16,   0,   2,   0, 
      0,   0,   0,   0,   0,   7, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0, 191, 
      0,   0,   0,   7,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   8, 130,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16, 128,  65,   0,   0,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   1,   0,   0,   0, 
     32,   0,   0,  10, 242,   0, 
     16,   0,   3,   0,   0,   0, 
     86,   5,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      8,   0,   0,   0,   9,   0, 
      0,   0,  10,   0,   0,   0, 
     11,   0,   0,   0,  50,   0, 
      0,  10,  34,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16, 128,  65,   0,   0,   0, 
      1,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
     58,  16,  16,   0,   1,   0, 
      0,   0,  55,   0,   0,   9, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  55,   0,   0,   9, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  18,   0,   0,   1, 
     54,   0,   0,   5, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  56,   0, 
      0,   7, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  64,  21,   0,   0,   1, 
     18,   0,   0,   1,   0,   0, 
      0,   7, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    130,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  21,   0, 
      0,   1,  21,   0,   0,   1, 
     54,  32,   0,   5, 242,   0, 
     16,   0,   1,   0,   0,   0, 
     70,  14,  16,   0,   1,   0, 
      0,   0,  39,   0,   0,   8, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10, 128,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      1,   0,   0,   0,  31,   0, 
      4,   3,  10,   0,  16,   0, 
      0,   0,   0,   0,  28,   0, 
      0,   6,  18,   0,  16,   0, 
      0,   0,   0,   0,  10, 128, 
     32,   0,   0,   0,   0,   0, 
      4,   0,   0,   0,  32,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   1,   0, 
      0,   0,  31,   0,   4,   3, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   5, 
     50,   0,  16,   0,   2,   0, 
      0,   0,  70,  16,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   6,  66,   0,  16,   0, 
      2,   0,   0,   0,  26, 128, 
     32,   0,   0,   0,   0,   0, 
      4,   0,   0,   0,  69,   0, 
      0,   9, 242,   0,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     70, 126,  16,   0,   3,   0, 
      0,   0,   0,  96,  16,   0, 
      1,   0,   0,   0,  21,   0, 
      0,   1,  31,   0,   0,   3, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  32,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   2,   0,   0,   0, 
     31,   0,   4,   3,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     54,   0,   0,   5,  50,   0, 
     16,   0,   3,   0,   0,   0, 
     70,  16,  16,   0,   2,   0, 
      0,   0,  54,   0,   0,   6, 
     66,   0,  16,   0,   3,   0, 
      0,   0,  26, 128,  32,   0, 
      0,   0,   0,   0,   4,   0, 
      0,   0,  69,   0,   0,   9, 
    242,   0,  16,   0,   2,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,  70, 126, 
     16,   0,   4,   0,   0,   0, 
      0,  96,  16,   0,   1,   0, 
      0,   0,  21,   0,   0,   1, 
     31,   0,   0,   3,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     54,   0,   0,   5,  50,   0, 
     16,   0,   3,   0,   0,   0, 
     70,  16,  16,   0,   2,   0, 
      0,   0,  54,   0,   0,   5, 
     66,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  69,   0, 
      0,   9, 242,   0,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,   3,   0,   0,   0, 
     70, 126,  16,   0,   1,   0, 
      0,   0,   0,  96,  16,   0, 
      1,   0,   0,   0,  21,   0, 
      0,   1,  21,   0,   0,   1, 
     55,   0,   0,  13, 242,   0, 
     16,   0,   2,   0,   0,   0, 
    166, 138,  32,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,   1,   0, 
      0,  11, 210,   0,  16,   0, 
      0,   0,   0,   0,  86, 133, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,  15,   0,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,  32,   0,   0,   0, 
     32,   0,   0,  10,  50,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  55,   0, 
      0,  12, 242,   0,  16,   0, 
      4,   0,   0,   0,  86,   5, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      3,   0,   0,   0,   6,   0, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   1,   0, 
      0,   0,  70,  14,  16,   0, 
      4,   0,   0,   0,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      3,   0,   0,   0,   6,   0, 
     16,   0,   0,   0,   0,   0, 
     70,  14,  16,   0,   3,   0, 
      0,   0,  70,  30,  16,   0, 
      1,   0,   0,   0,   0,   0, 
      0,  11, 242,   0,  16,   0, 
      4,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
     55,   0,   0,   9, 242,   0, 
     16,   0,   3,   0,   0,   0, 
    166,  10,  16,   0,   0,   0, 
      0,   0,  70,  14,  16,   0, 
      4,   0,   0,   0,  70,  14, 
     16,   0,   3,   0,   0,   0, 
     55,   0,   0,   9, 210,   0, 
     16,   0,   0,   0,   0,   0, 
    246,  15,  16,   0,   0,   0, 
      0,   0, 246,  15,  16,   0, 
      3,   0,   0,   0,   6,   9, 
     16,   0,   3,   0,   0,   0, 
      1,   0,   0,  11,  50,   0, 
     16,   0,   3,   0,   0,   0, 
      6, 128,  32,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      2,  64,   0,   0,  15,   0, 
      0,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  32,   0,   0,  10, 
    194,   0,  16,   0,   3,   0, 
      0,   0,   6,   0,  16,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   2,   0,   0,   0, 
     55,   0,   0,   9, 130,   0, 
     16,   0,   3,   0,   0,   0, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 128,  63, 
     55,   0,   0,   9,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,  58,   0,  16,   0, 
      1,   0,   0,   0,  58,   0, 
     16,   0,   3,   0,   0,   0, 
     55,   0,   0,   9,  18,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,  58,  16, 
     16,   0,   1,   0,   0,   0, 
      0,   0,   0,   8,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  63,  55,   0,   0,   9, 
     18,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  39,   0,   0,  11, 
     98,   0,  16,   0,   3,   0, 
      0,   0,   6, 131,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,  31,   0, 
      4,   3,  26,   0,  16,   0, 
      3,   0,   0,   0,   1,   0, 
      0,  11, 114,   0,  16,   0, 
      4,   0,   0,   0, 166, 138, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,  15,   0,   0,   0, 
     16,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
     32,   0,   0,  10, 162,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   0,  16,   0,   4,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,  55,   0, 
      0,  12, 242,   0,  16,   0, 
      5,   0,   0,   0, 246,  15, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      5,   0,   0,   0,  86,   5, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   1,   0, 
      0,   0,  70,  14,  16,   0, 
      5,   0,   0,   0,  55,   0, 
      0,   9, 242,   0,  16,   0, 
      5,   0,   0,   0,   6,   0, 
     16,   0,   4,   0,   0,   0, 
     70,  14,  16,   0,   5,   0, 
      0,   0,  70,  30,  16,   0, 
      1,   0,   0,   0,   0,   0, 
      0,  11, 242,   0,  16,   0, 
      6,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      5,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
     55,   0,   0,   9, 242,   0, 
     16,   0,   5,   0,   0,   0, 
     86,   5,  16,   0,   4,   0, 
      0,   0,  70,  14,  16,   0, 
      6,   0,   0,   0,  70,  14, 
     16,   0,   5,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,   2,   0,   0,   0, 
    166,  10,  16,   0,   4,   0, 
      0,   0, 246,  15,  16,   0, 
      5,   0,   0,   0,  70,   2, 
     16,   0,   5,   0,   0,   0, 
     39,   0,   0,   8,  34,   0, 
     16,   0,   3,   0,   0,   0, 
     10, 128,  32,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   3,   0, 
      0,   0,  31,   0,   4,   3, 
     26,   0,  16,   0,   3,   0, 
      0,   0,  56,   0,   0,   7, 
    114,   0,  16,   0,   4,   0, 
      0,   0, 134,   3,  16,   0, 
      0,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     39,   0,   0,   8,  34,   0, 
     16,   0,   3,   0,   0,   0, 
     10, 128,  32,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   4,   0, 
      0,   0,  31,   0,   4,   3, 
     26,   0,  16,   0,   3,   0, 
      0,   0,  39,   0,   0,   8, 
     34,   0,  16,   0,   3,   0, 
      0,   0,  10, 128,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      5,   0,   0,   0,  31,   0, 
      4,   3,  26,   0,  16,   0, 
      3,   0,   0,   0,  39,   0, 
      0,   8,  34,   0,  16,   0, 
      3,   0,   0,   0,  10, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   6,   0,   0,   0, 
     31,   0,   4,   3,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      0,   0,   0,   7, 114,   0, 
     16,   0,   5,   0,   0,   0, 
    134,   3,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,  39,   0, 
      0,   8,  34,   0,  16,   0, 
      3,   0,   0,   0,  10, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   7,   0,   0,   0, 
     31,   0,   4,   3,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      0,   0,   0,  10, 114,   0, 
     16,   0,   6,   0,   0,   0, 
     70,   2,  16,   0,   5,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0, 191,   0,   0, 
      0, 191,   0,   0,   0, 191, 
      0,   0,   0,   0,  39,   0, 
      0,   8,  34,   0,  16,   0, 
      3,   0,   0,   0,  10, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   8,   0,   0,   0, 
     31,   0,   4,   3,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      0,   0,   0,   7, 114,   0, 
     16,   0,   7,   0,   0,   0, 
     70,   2,  16,   0,   6,   0, 
      0,   0,  70,   2,  16,   0, 
      6,   0,   0,   0,   0,   0, 
      0,   8, 114,   0,  16,   0, 
      8,   0,   0,   0, 134,   3, 
     16,   0,   0,   0,   0,   0, 
     70,   2,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
     50,   0,   0,  10, 114,   0, 
     16,   0,   9,   0,   0,   0, 
    134,   3,  16, 128,  65,   0, 
      0,   0,   0,   0,   0,   0, 
     70,   2,  16,   0,   2,   0, 
      0,   0,  70,   2,  16,   0, 
      5,   0,   0,   0,  32,   0, 
      0,  11, 242,   0,  16,   0, 
     10,   0,   0,   0,   6, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,   9,   0,   0,   0, 
     10,   0,   0,   0,  11,   0, 
      0,   0,  13,   0,   0,   0, 
      0,   0,   0,  11, 114,   0, 
     16,   0,  11,   0,   0,   0, 
     70,   2,  16, 128,  65,   0, 
      0,   0,   1,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
      0,   0,  56,   0,   0,   7, 
    114,   0,  16,   0,  11,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,  11,   0,   0,   0, 
     50,   0,   0,   9, 114,   0, 
     16,   0,  11,   0,   0,   0, 
    134,   3,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,  11,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,  11,   0,   0,   0, 
    246,  15,  16,   0,  10,   0, 
      0,   0,  70,   2,  16,   0, 
     11,   0,   0,   0,  70,   2, 
     16,   0,   1,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,   9,   0,   0,   0, 
    166,  10,  16,   0,  10,   0, 
      0,   0,  70,   2,  16,   0, 
      9,   0,   0,   0,  70,   2, 
     16,   0,  11,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,   8,   0,   0,   0, 
     86,   5,  16,   0,  10,   0, 
      0,   0,  70,   2,  16,   0, 
      8,   0,   0,   0,  70,   2, 
     16,   0,   9,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,   1,   0,   0,   0, 
      6,   0,  16,   0,  10,   0, 
      0,   0,  70,   2,  16,   0, 
      7,   0,   0,   0,  70,   2, 
     16,   0,   8,   0,   0,   0, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 114,   0,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   6,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    114,   0,  16,   0,   1,   0, 
      0,   0,  70,   2,  16,   0, 
      5,   0,   0,   0,  21,   0, 
      0,   1,  18,   0,   0,   1, 
     56,   0,   0,  10, 114,   0, 
     16,   0,   1,   0,   0,   0, 
     70,   2,  16,   0,   4,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  64,   0,   0, 
    128,  64,   0,   0, 128,  64, 
      0,   0,   0,   0,  21,   0, 
      0,   1,  18,   0,   0,   1, 
      0,   0,   0,   7, 114,   0, 
     16,   0,   1,   0,   0,   0, 
     70,   2,  16,   0,   4,   0, 
      0,   0,  70,   2,  16,   0, 
      4,   0,   0,   0,  21,   0, 
      0,   1,  18,   0,   0,   1, 
     54,   0,   0,   5, 114,   0, 
     16,   0,   1,   0,   0,   0, 
     70,   2,  16,   0,   4,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 114,   0,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    114,   0,  16,   0,   1,   0, 
      0,   0, 134,   3,  16,   0, 
      0,   0,   0,   0,  21,   0, 
      0,   1,  31,   0,   4,   3, 
     42,   0,  16,   0,   3,   0, 
      0,   0,   1,   0,   0,  11, 
     82,   0,  16,   0,   0,   0, 
      0,   0,  86, 133,  32,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,  32,   0, 
      0,  10,  50,   0,  16,   0, 
      2,   0,   0,   0,   6,   0, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   1,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  26,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  63,  55,   0,   0,   9, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
     58,  16,  16,   0,   1,   0, 
      0,   0,   0,   0,   0,   8, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16, 128, 
     65,   0,   0,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 128,  63,  55,   0, 
      0,   9,  18,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  39,   0, 
      0,   8,  66,   0,  16,   0, 
      0,   0,   0,   0,  58, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   3,   0,   0,   0, 
     31,   0,   4,   3,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     56,   0,   0,   7,  66,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  39,   0, 
      0,   8, 130,   0,  16,   0, 
      0,   0,   0,   0,  58, 128, 
     32,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   4,   0,   0,   0, 
     31,   0,   4,   3,  58,   0, 
     16,   0,   0,   0,   0,   0, 
     39,   0,   0,   8, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     58, 128,  32,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   5,   0, 
      0,   0,  31,   0,   4,   3, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  39,   0,   0,   8, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  58, 128,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      6,   0,   0,   0,  31,   0, 
      4,   3,  58,   0,  16,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   7, 130,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  39,   0,   0,   8, 
     18,   0,  16,   0,   2,   0, 
      0,   0,  58, 128,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      7,   0,   0,   0,  31,   0, 
      4,   3,  10,   0,  16,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0, 191,   0,   0,   0,   7, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
      0,   0,   0,   8,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  32,   0,   0,  11, 
    242,   0,  16,   0,   4,   0, 
      0,   0, 246, 143,  32,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      8,   0,   0,   0,   9,   0, 
      0,   0,  10,   0,   0,   0, 
     11,   0,   0,   0,  50,   0, 
      0,  10, 130,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16, 128,  65,   0,   0,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      4,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   1,   0, 
      0,   0,  55,   0,   0,   9, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   2,   0, 
      0,   0,  55,   0,   0,   9, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      4,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  55,   0,   0,   9, 
    130,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      4,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  18,   0,   0,   1, 
     54,   0,   0,   5, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  56,   0, 
      0,   7, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  64,  21,   0,   0,   1, 
     18,   0,   0,   1,   0,   0, 
      0,   7, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 130,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     21,   0,   0,   1,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    130,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  21,   0, 
      0,   1,  18,   0,   0,   1, 
     54,   0,   0,   5, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  21,   0,   0,   1, 
     54,  32,   0,   5, 242,   0, 
     16,   0,   1,   0,   0,   0, 
     70,  14,  16,   0,   1,   0, 
      0,   0,  21,   0,   0,   1, 
     18,   0,   0,   1,  54,   0, 
      0,   5, 242,   0,  16,   0, 
      1,   0,   0,   0,  70,  30, 
     16,   0,   1,   0,   0,   0, 
     21,   0,   0,   1,  31,   0, 
      4,   3,  26,   0,  16,   0, 
      0,   0,   0,   0,  85,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,  28,   0, 
      0,   0,   1,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   7,   0,   0,   0, 
     30,   0,   0,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      1,   0,   0,   0,  32,   0, 
      0,   7,  34,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   1,   0, 
      0,   0,  31,   0,   4,   3, 
     26,   0,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   5, 
     34,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  18,   0, 
      0,   1,  50,   0,   0,   9, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 127,  67, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  65,   0,   0,   5, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      0,   0,   0,   0,  27,   0, 
      0,   5,  66,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     26,  16,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
    255,   0,   0,   0,  32,   0, 
      0,   7,  34,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16,   0,   0,   0, 
      0,   0,  33,   0,   0,   7, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     32,   0,   0,  10, 242,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      2,   0,   0,   0,   3,   0, 
      0,   0,   4,   0,   0,   0, 
      5,   0,   0,   0,  34,   0, 
      0,   7, 146,   0,  16,   0, 
      2,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
    246,  11,  16,   0,   0,   0, 
      0,   0,  39,   0,   0,   7, 
     18,   0,  16,   0,   4,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     32,   0,   0,  10,  98,   0, 
     16,   0,   4,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   6,   0, 
      0,   0,   7,   0,   0,   0, 
      0,   0,   0,   0,  33,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 255, 255, 
    255, 255,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  26,   0,  16,   0, 
      4,   0,   0,   0,  10,   0, 
     16,   0,   4,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      3,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
     34,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     59,   0,   0,   5,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     26,   0,  16,   0,   0,   0, 
      0,   0,  13,   0,   4,   3, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  21,   0,   0,   1, 
     54,   0,   0,   5, 242,  32, 
     16,   0,   0,   0,   0,   0, 
     70,  14,  16,   0,   1,   0, 
      0,   0,  62,   0,   0,   1, 
     83,  84,  65,  84, 116,   0, 
      0,   0, 234,   1,   0,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,   4,   0,   0,   0, 
     62,   0,   0,   0,  76,   0, 
      0,   0,  30,   0,   0,   0, 
     31,   0,   0,   0,  57,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   6,   0, 
      0,   0,  17,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     66,   0,   0,   0,  65,   0, 
      0,   0,  21,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0
};
