[Main]
Left=0
Top=0
Width=429
Height=118
Image=\spr\Ui4\Ö÷½çÃæ\ÅÄÂôÐÐ\µ¥¸öÅÄÂô¿ò.spr
Moveable=0
Trans=0

[NameOfItem]
Left=86
Top=6
Width=292
Height=16
Color=218,165,105
HAlign=1
Font=12
Text=Siªu Quang

[CurrentPriceTitle]
Left=125
Top=34
Width=120
Height=16
Color=169,211,190
Font=14
Text=Gi¸ ®Êu gi¸: 

[CurrentPrice]
Left=165
Top=34
Width=120
Height=16
Color=169,211,190
Font=14
Text=1000
HAlign=2

[BasePriceTitle]
Font=31

[BasePrice]
Font=31

[CurrencyTypeTitle]
Font=31
;Left=125
;Top=46
;Width=120
;Height=16
;Color=169,211,190
;Font=12
;Text=»õ±ÒÖÖÀà

[CurrencyType]
Left=194
Top=34
Width=120
Height=16
Color=169,211,190
Font=14
HAlign=2
Text=Vµng nÐn

[FreshRemainingTimeTitle]
Font=31

[FreshRemainingTime]
Font=31

[NextPriceTitle]
Font=31

[NextPrice]
Font=31

[TotalRemainingTimeTitle]
Left=125
Top=60
Width=120
Height=16
Color=169,211,190
Font=14
Text=Thêi gian b¸n: 

[TotalRemainingTime]
Left=194
Top=60
Width=120
Height=16
Color=169,211,190
Font=14
Text=0
HAlign=2

[btnBid]
Left=200
Top=86
Width=67
Height=19
Font=12
HAlign=1
VAlign=1
LabelYOffset=3
Color=218,165,105
BorderColor=0,0,0
SelectColor=255,253,122
SelectBorderColor=0,0,0
OverColor=240,127,80
DisableColor=145,155,145
DisableBorderColor=65,75,65
Up=0
Down=1
OverFrame=2
Trans=0
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Ta muèn ®Êu gi¸
Text=0

[btnGetBackItem]
Left=200
Top=86
Width=67
Height=19
Font=12
HAlign=1
VAlign=1
LabelYOffset=3
Color=218,165,105
BorderColor=0,0,0
SelectColor=255,253,122
SelectBorderColor=0,0,0
OverColor=240,127,80
DisableColor=145,155,145
DisableBorderColor=65,75,65
Up=0
Down=1
OverFrame=2
Trans=0
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Ta muèn gì bá
Text=0