# Sinh boi android/gen_lists.py tu Core/Core.vcxproj [Client ReleaseSDL|x64] - KHONG sua tay
set(JX_CORE_SOURCES
    ${JX_ROOT}/Sources/Core/KMeridian.cpp
    ${JX_ROOT}/Sources/Core/Src/KBiaoChe.cpp
    ${JX_ROOT}/Sources/Core/Src/base64.cpp
    ${JX_ROOT}/Sources/Core/Src/KMySQLDB.cpp
    ${JX_ROOT}/Sources/Core/Src/KGameKV.cpp
    ${JX_ROOT}/Sources/Core/Src/BauCua.cpp
    ${JX_ROOT}/Sources/Core/Src/KScriptProtocol.cpp
    ${JX_ROOT}/Sources/Core/Src/KMailClient.cpp
    ${JX_ROOT}/Sources/Core/Src/KAuctionClient.cpp
    ${JX_ROOT}/Sources/Core/Src/KChienLenhClient.cpp
    ${JX_ROOT}/Sources/Core/Src/KMailServer.cpp
    ${JX_ROOT}/Sources/Core/Src/KAuctionServer.cpp
    ${JX_ROOT}/Sources/Core/Src/KChienLenh.cpp
    ${JX_ROOT}/Sources/Core/Src/KCauHinhWeb.cpp
    ${JX_ROOT}/Sources/Core/Src/CoreDrawGameObj.cpp
    ${JX_ROOT}/Sources/Core/Src/CoreShell.cpp
    ${JX_ROOT}/Sources/Core/Src/GiftCodeManager.cpp
    ${JX_ROOT}/Sources/Core/Src/ImgRef.cpp
    ${JX_ROOT}/Sources/Core/Src/kautoai.cpp
    ${JX_ROOT}/Sources/Core/Src/KBasPropTbl.CPP
    ${JX_ROOT}/Sources/Core/Src/KBuySell.cpp
    ${JX_ROOT}/Sources/Core/Src/KCore.cpp
    ${JX_ROOT}/Sources/Core/Src/KFaction.cpp
    ${JX_ROOT}/Sources/Core/Src/KGMCommand.cpp
    ${JX_ROOT}/Sources/Core/Src/KInventory.cpp
    ${JX_ROOT}/Sources/Core/Src/KItem.cpp
    ${JX_ROOT}/Sources/Core/Src/KItemChangeRes.cpp
    ${JX_ROOT}/Sources/Core/Src/KItemGenerator.CPP
    ${JX_ROOT}/Sources/Core/Src/KItemList.cpp
    ${JX_ROOT}/Sources/Core/Src/KItemSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KJXPathFinder.cpp
    ${JX_ROOT}/Sources/Core/Src/KLadder.cpp
    ${JX_ROOT}/Sources/Core/Src/KLittleMap.cpp
    ${JX_ROOT}/Sources/Core/Src/KMagicDesc.cpp
    ${JX_ROOT}/Sources/Core/Src/KMapMusic.cpp
    ${JX_ROOT}/Sources/Core/Src/KMath.cpp
    ${JX_ROOT}/Sources/Core/Src/KMissle.cpp
    ${JX_ROOT}/Sources/Core/Src/KMissleRes.cpp
    ${JX_ROOT}/Sources/Core/Src/KMissleSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KJx2SharedStore.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpc.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcAI.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcAttribModify.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcDeathCalcExp.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcFindPath.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcGold.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcRes.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcResList.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcResNode.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KNpcTemplate.cpp
    ${JX_ROOT}/Sources/Core/Src/KObj.cpp
    ${JX_ROOT}/Sources/Core/Src/KObjSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KOption.cpp
    ${JX_ROOT}/Sources/Core/Src/KPartnerSkill.cpp
    ${JX_ROOT}/Sources/Core/Src/KPerfTick.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayer.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerAuto.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerChat.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerDBFuns.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerFaction.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerFuYuan.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerMenuState.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerPartner.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerPet.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerPK.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerReBorn.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerRepute.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerTask.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerTeam.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerTong.cpp
    ${JX_ROOT}/Sources/Core/Src/KPlayerTrade.cpp
    ${JX_ROOT}/Sources/Core/Src/KProtocol.cpp
    ${JX_ROOT}/Sources/Core/Src/KProtocolProcess.cpp
    ${JX_ROOT}/Sources/Core/Src/KRegion.cpp
    ${JX_ROOT}/Sources/Core/Src/KScriptValueSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KSellItem.cpp
    ${JX_ROOT}/Sources/Core/Src/KSkillList.cpp
    ${JX_ROOT}/Sources/Core/Src/KSkillManager.cpp
    ${JX_ROOT}/Sources/Core/Src/KSkills.cpp
    ${JX_ROOT}/Sources/Core/Src/KSkillSpecial.cpp
    ${JX_ROOT}/Sources/Core/Src/KSortScript.cpp
    ${JX_ROOT}/Sources/Core/Src/KSprControl.cpp
    ${JX_ROOT}/Sources/Core/Src/KSubWorld.cpp
    ${JX_ROOT}/Sources/Core/Src/KSubWorldSet.cpp
    ${JX_ROOT}/Sources/Core/Src/KTaskFuns.cpp
    ${JX_ROOT}/Sources/Core/Src/KThiefSkill.cpp
    ${JX_ROOT}/Sources/Core/Src/KViewItem.cpp
    ${JX_ROOT}/Sources/Core/Src/KWeatherMgr.cpp
    ${JX_ROOT}/Sources/Core/Src/KWorldMsg.cpp
    ${JX_ROOT}/Sources/Core/Src/MapHandler.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KIpotBranch.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KIpotLeaf.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KIpoTree.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KScenePlaceC.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KScenePlaceRegionC.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/KWeather.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/SceneMath.cpp
    ${JX_ROOT}/Sources/Core/Src/Scene/ScenePlaceMapC.cpp
    ${JX_ROOT}/Sources/Core/Src/ScriptFuns.cpp
    ${JX_ROOT}/Sources/Core/Src/Skill.cpp
    ${JX_ROOT}/Sources/Core/Src/stdafx.cpp
)
set(JX_CORE_DEFS NDEBUG JX_PLATFORM_SDL CORE_EXPORTS SWORDONLINE_SHOW_DBUG_INFO)
set(JX_CORE_INCS
    ${JX_ROOT}/Sources/engine/src
    ${JX_ROOT}/Sources/engine/include
    ${JX_ROOT}/Sources/Network
    ${JX_ROOT}/Headers
    ${JX_ROOT}/Sources/Core/src
)
# loai (0): 
