# Sinh boi android/gen_lists.py tu Engine/Engine.vcxproj [ReleaseSDL|x64] - KHONG sua tay
set(JX_ENGINE_SOURCES
    ${JX_ROOT}/Sources/Engine/Src/Cryptography/EDOneTimePad.cpp
    ${JX_ROOT}/Sources/Engine/Src/KAutoMutex.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBitmap.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBitmap16.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBitmapConvert.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBmp2Spr.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBmpFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KBmpFile24.cpp
    ${JX_ROOT}/Sources/Engine/Src/KCache.cpp
    ${JX_ROOT}/Sources/Engine/Src/KCanvas.cpp
    ${JX_ROOT}/Sources/Engine/Src/KCodec.cpp
    ${JX_ROOT}/Sources/Engine/Src/KCodecLzo.cpp
    ${JX_ROOT}/Sources/Engine/Src/KColors.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDebug.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawBase.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawBitmap.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawBitmap16.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawFade.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawFont.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawSprite.cpp
    ${JX_ROOT}/Sources/Engine/Src/KDrawSpriteAlpha.cpp
    ${JX_ROOT}/Sources/Engine/Src/KEicScript.cpp
    ${JX_ROOT}/Sources/Engine/Src/KEicScriptSet.cpp
    ${JX_ROOT}/Sources/Engine/Src/KEngine.cpp
    ${JX_ROOT}/Sources/Engine/Src/KEvent.cpp
    ${JX_ROOT}/Sources/Engine/Src/KFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KFileCopy.cpp
    ${JX_ROOT}/Sources/Engine/Src/KFilePath.cpp
    ${JX_ROOT}/Sources/Engine/Src/KFindBinTree.cpp
    ${JX_ROOT}/Sources/Engine/Src/KFont.cpp
    ${JX_ROOT}/Sources/Engine/Src/KGifFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KGraphics.cpp
    ${JX_ROOT}/Sources/Engine/Src/KHashList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KHashNode.cpp
    ${JX_ROOT}/Sources/Engine/Src/KHashTable.cpp
    ${JX_ROOT}/Sources/Engine/Src/KIniFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KJpgFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KLinkArray.cpp
    ${JX_ROOT}/Sources/Engine/Src/KList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KLuaScript.cpp
    ${JX_ROOT}/Sources/Engine/Src/KLuaScriptSet.cpp
    ${JX_ROOT}/Sources/Engine/Src/KLubCmpl_Blocker.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMemBase.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMemClass.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMemClass1.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMemManager.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMemStack.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMessage.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMsgNode.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMusic.cpp
    ${JX_ROOT}/Sources/Engine/Src/KMutex.cpp
    ${JX_ROOT}/Sources/Engine/Src/KNode.cpp
    ${JX_ROOT}/Sources/Engine/Src/KOctree.cpp
    ${JX_ROOT}/Sources/Engine/Src/KOctreeNode.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPakData.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPakFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPakList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPakTool.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPalette.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPcxFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPolygon.cpp
    ${JX_ROOT}/Sources/Engine/Src/KPolyRelation.cpp
    ${JX_ROOT}/Sources/Engine/Src/KRandom.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSafeList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KScanDir.cpp
    ${JX_ROOT}/Sources/Engine/Src/KScript.cpp
    ${JX_ROOT}/Sources/Engine/Src/KScriptCache.cpp
    ${JX_ROOT}/Sources/Engine/Src/KScriptList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KScriptSet.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSG_MD5_String.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSG_StringProcess.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSortBinTree.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSortList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSoundCache.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSoundMa.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSprite.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSpriteCache.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSpriteCodec.cpp
    ${JX_ROOT}/Sources/Engine/Src/KSpriteMaker.cpp
    ${JX_ROOT}/Sources/Engine/Src/KStepLuaScript.cpp
    ${JX_ROOT}/Sources/Engine/Src/KStrBase.cpp
    ${JX_ROOT}/Sources/Engine/Src/KStrList.cpp
    ${JX_ROOT}/Sources/Engine/Src/KStrNode.cpp
    ${JX_ROOT}/Sources/Engine/Src/KTabFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KTabFileCtrl.cpp
    ${JX_ROOT}/Sources/Engine/Src/KTgaFile32.cpp
    ${JX_ROOT}/Sources/Engine/Src/KThread.cpp
    ${JX_ROOT}/Sources/Engine/Src/KTimer.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWavCodec.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWavFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWavMusic.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWavSound.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWin32.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWin32App.cpp
    ${JX_ROOT}/Sources/Engine/Src/KWin32Wnd.cpp
    ${JX_ROOT}/Sources/Engine/Src/KZipCodec.cpp
    ${JX_ROOT}/Sources/Engine/Src/KZipData.cpp
    ${JX_ROOT}/Sources/Engine/Src/KZipFile.cpp
    ${JX_ROOT}/Sources/Engine/Src/KZipList.cpp
    ${JX_ROOT}/Sources/Engine/Src/md5.cpp
    ${JX_ROOT}/Sources/Engine/Src/stdafx.cpp
    ${JX_ROOT}/Sources/Engine/Src/Text.cpp
    ${JX_ROOT}/Sources/Engine/Src/ucl/alloc.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/io.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_99.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_d.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_ds.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_to.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_99.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_d.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_ds.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_to.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_99.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_d.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_ds.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_to.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_crc.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_dll.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_init.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_ptr.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_str.c
    ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_util.c
    ${JX_ROOT}/Sources/Engine/Src/XPackFile.cpp
)
set(JX_ENGINE_DEFS NDEBUG JX_PLATFORM_SDL ENGINE_EXPORTS USE_STANDALONE_SPR)
set(JX_ENGINE_INCS
    ${JX_ROOT}/Sources/Engine/include
    ${JX_ROOT}/Sources/Engine/src
    ${JX_ROOT}/Sources/Core/Src
)
set_source_files_properties(${JX_ROOT}/Sources/Engine/Src/ucl/alloc.c ${JX_ROOT}/Sources/Engine/Src/ucl/io.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_99.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_d.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_ds.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2b_to.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_99.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_d.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_ds.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2d_to.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_99.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_d.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_ds.c ${JX_ROOT}/Sources/Engine/Src/ucl/n2e_to.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_crc.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_dll.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_init.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_ptr.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_str.c ${JX_ROOT}/Sources/Engine/Src/ucl/ucl_util.c PROPERTIES LANGUAGE C)
# loai (15): Sources/Engine/Src/KAviFile.cpp; Sources/Engine/Src/KDDraw.cpp; Sources/Engine/Src/KDError.cpp; Sources/Engine/Src/KDInput.cpp; Sources/Engine/Src/KDSound.cpp; Sources/Engine/Src/KFileDialog.cpp; Sources/Engine/Src/Kime.cpp; Sources/Engine/Src/KKeyboard.cpp; Sources/Engine/Src/KMouse.cpp; Sources/Engine/Src/KMp3Music.cpp; Sources/Engine/Src/KMp4Audio.cpp; Sources/Engine/Src/KMp4Movie.cpp; Sources/Engine/Src/KMp4Video.cpp; Sources/Engine/Src/KMpgMusic.cpp; Sources/Engine/Src/KVideo.cpp
