# Sinh boi android/gen_lists.py tu S3Client/S3Client.vcxproj [ReleaseSDL|x64] - KHONG sua tay
set(JX_S3CLIENT_SOURCES
    ${JX_ROOT}/Sources/S3Client/ErrorCode.cpp
    ${JX_ROOT}/Sources/S3Client/Login/Login.cpp
    ${JX_ROOT}/Sources/S3Client/NetConnect/NetConnectAgent.cpp
    ${JX_ROOT}/Sources/S3Client/S3Client.cpp
    ${JX_ROOT}/Sources/S3Client/Platform/KSdlApp.cpp
    ${JX_ROOT}/Sources/S3Client/stdafx.cpp
    ${JX_ROOT}/Sources/S3Client/TextCtrlCmd/TextCtrlCmd.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/ChatFilter.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/AutoLocateWnd.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/ComWindow.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/MouseHover.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/PopupMenu.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/SpecialFuncs.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/TextPic.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/UiCursor.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/UiImage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/vongsang.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndButton.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndChessPanel.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndEdit.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndImage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndImagePart.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndLabeledButton.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndLine.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndList.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndList2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndMessageListBox.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndMovingImage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndObjContainer.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndPage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndPureTextBtn.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/UiToaDo.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/Wnds.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndScrollBar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/elem/WndShadow.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndShowAnimate.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndText.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndToolBar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndValueImage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/Elem/WndWindow.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/FilterTextLib.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/GameSpaceChangedNotify.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/GourdCrabFishTigerLogic.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/ShortcutKey.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiBase.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/KUiKtc.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/SpringGame.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiAddPoint.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiAffairItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMantleInlay.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMantleWash.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSmelt.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiAuto.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiAutoParty.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiAutoPlay.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiBattleReport.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiBreakItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiJxrPlayer.cpp
    ${JX_ROOT}/Sources/S3Client/JxrDrawAdapter.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChangePWBox.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChannelSubscibe.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChatCentre.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChatItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChatStatus.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiChooseFace.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiCityWar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiCompoundItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiConnectInfo.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiContainer.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiESCDlg.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiExBox1.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiExBox2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiExBox3.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiFaceSelector.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiFindPos.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiFinishQuest.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiFlashMessage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTongKimScore.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTongKimInfo.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGamble.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGame.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGetMoney.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGetNumber.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGetString.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiGetString2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiHeaderControlBar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiHelper.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiHelper2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiInformation.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiInformation2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiInformation3.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiInit.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiItemEX.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiLogin.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiLoginBg.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMapCave.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMeridian.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/uicase/UiMiniMap.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/uicase/UiMsgCentrePad.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMsgSel.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMsgSel2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMsgSel3.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiMsgSel4.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiNewPlayer.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiNewPlayerStartMsg.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiNewsMessage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiNewsMessage1.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiNotice.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiOptions.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiOptions2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiParadeItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiPK.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiPlayerBar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiPlayerShop.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPopupPasswordQuery.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiQuestDT.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiQuestDT1.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiRankData.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiReconnect.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiResetPass.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSelColor.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSelNativePlace.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSelPlayer.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSelPlayerNearby.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSelServer.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UIcase/UiShop.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiShopGold.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSkills.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSkillsNew.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSkillTree.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiStatus.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/uicase/UiStoreBox.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiStrengthRank.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSuperShop.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiSysMsgCentre.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTargetInfo.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTaskDataFile.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTaskGuide.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTaskTrace.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTaskNote.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTeamManage.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTeamManager2.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTimeBox.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiTongAssignBox.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTongGrant.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTongChangeTitle.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiTongCreateSheet.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTongGetString.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiTongJX2.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiTongManager.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiToolsControlBar.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTrade.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiTradeConfirmWnd.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiDiceItem.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiMail.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiAuction.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiChienLenh.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPartnerCommon.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPartnerAttr.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPartnerSkill.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPartnerBag.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPartnerBar.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiPet.cpp
    ${JX_ROOT}/Sources/S3Client/ui/uicase/UiTrembleItem.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiUnlockBox.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiCase/UiWorldMap.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiChatPhrase.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiShell.cpp
    ${JX_ROOT}/Sources/S3Client/Ui/UiSoundSetting.cpp
)
set(JX_S3CLIENT_DEFS S3_CLIENT JX_PLATFORM_SDL SWORDONLINE_USE_MD5_PASSWORD)
set(JX_S3CLIENT_INCS
    ${JX_ROOT}/Sources/Engine/src
    ${JX_ROOT}/Sources/Core/src
    ${JX_ROOT}/Sources/Engine/include
    ${JX_ROOT}/Headers
)
# loai (16): Sources/S3Client/AntiHack/CheckSumCRC/CheckSumCRC.cpp; Sources/S3Client/AntiHack/CheckSumCRC/CRC32.cpp; Sources/S3Client/AntiHack/CheckSumCRC/ShowLogCRC.cpp; Sources/S3Client/AntiHack/DetectHide/DetectHide.cpp; Sources/S3Client/AntiHack/DetectWindowsClassName/DetectWindowsClassName.cpp; Sources/S3Client/AntiHack/DetectWindowsText/DetectWindowsText.cpp; Sources/S3Client/AntiHack/DetectWindowsTitle/DetectWindowsTitle.cpp; Sources/S3Client/AntiHack/DumpMemory/DumpMemory.cpp; Sources/S3Client/AntiHack/ExistMainName/ExistMainName.cpp; Sources/S3Client/AntiHack/Splash/Splash.cpp; Sources/S3Client/AntiHack/Splash/splash2.cpp; Sources/S3Client/Ui/TrayMode.cpp; Sources/S3Client/JxReplay.cpp; Sources/S3Client/Ui/UiCase/UiPlayVideo.cpp; Sources/S3Client/CrashLog.cpp; Sources/S3Client/Ui/PerfHud.cpp
