[Main]
WndType=WndImage
Parent=
ScriptFile=\script\ui\season_ticket_2026.lua
Left=100
Top=85
Width=595
Height=474
Moveable=1
Trans=0
Image=\spr\Ui4\chienlenh\cl_00.spr
;;;;;;;;;;;;;;;;;;;;Ì§Í·;;;;;;;;;;;;;;;;;;;;
[TxtTitle]
WndType=WndText
Parent=Main
Left=200
Top=7
Width=200
Height=0
Font=16
HAlign=1
Color=255,253,179
Text=ChiÕn LÖnh

[BtnClose]
WndType=WndButton
Parent=Main
Left=570
Top=3
Width=24
Height=24
Image=\spr\Ui4\chienlenh\cl_01.spr
Over=1
OverFrame=2

[BtnHelp]
WndType=WndButton
Parent=Main
Left=5
Top=30
Width=24
Height=24
Image=\spr\Ui4\chienlenh\cl_02.spr
Tip=TÝnh N¨ng
Over=1
OverFrame=2

[TxtRemainTime]
WndType=WndText
Parent=Main
Left=20
Top=45
Width=400
Height=0
Font=16
HAlign=0
Color=255,253,179
Text=Ho¹t ®éng cßn: x ngµy x giê x phót x gi©y

[BtnBuyVipCard]
WndType=WndLabeledButton
Parent=Main
Left=460
Top=35
Width=108
Height=35
Label=Mua ChiÕn LÖnh
Font=12
LabelYOffset=10
Color=255,255,179
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_03.spr
;;;;;;;;;;;;;;;;;;;;Ì§Í·;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;½±Àø;;;;;;;;;;;;;;;;;;;;
[ImgAwardListBG]
WndType=WndImage
Parent=Main
Left=2
Top=75
Width=580
Height=176
;BKColor=255,0,255
;BKColorAlpha=100

[TxtPlayerRankTitle]
WndType=WndText
Parent=ImgAwardListBG
Left=10
Top=7
Width=57
Height=16
Font=12
HAlign=1
VAlign=1
Color=153,217,234
Text=CÊp ChiÕn LÖnh
Image=\spr\Ui4\chienlenh\cl_04.spr

[TxtPlayerRank]
WndType=WndText
Parent=ImgAwardListBG
Left=10
Top=25
Width=57
Height=16
Font=12
HAlign=1
Color=255,253,179
Text=LV30

[ImgLowAwardTitle]
WndType=WndImage
Parent=ImgAwardListBG
Left=6
Top=43
Width=64
Height=66
Image=\spr\Ui4\chienlenh\cl_05.spr

[ImgVipAwardTitle]
WndType=WndImage
Parent=ImgAwardListBG
Left=6
Top=110
Width=64
Height=66
Image=\spr\Ui4\chienlenh\cl_06.spr

;;;;;;;;;;;;;;;;;;;;½±Àø¿Ø¼þ;;;;;;;;;;;;;;;;;;;;
[ElemImgRankAwardInfoBG]
WndType=WndImage
Left=72
Top=0
Width=57
Height=175
;BKColor=255,0,255
;BKColorAlpha=100

[ElemImgProgressBg]
WndType=WndImage
Left=0
Top=9
Width=57
Height=9
Image=\spr\Ui4\chienlenh\cl_07.spr

[ElemImgProgress]
WndType=WndImagePart
Left=1
Top=2
Width=55
Height=5
Image=\spr\Ui4\chienlenh\cl_08.spr

[ElemImgAwardRankBG]
WndType=WndImage
Left=1
Top=20
Width=54
Height=24
Image=\spr\Ui4\chienlenh\cl_09.spr

[ElemTxtAwardRank]
WndType=WndText
Left=0
Top=5
Width=53
Height=17
Font=12
HAlign=1
Color=255,253,179
Text=10

[ElemImgLowAwardBG]
WndType=WndImage
Parent=
Left=0
Top=43
Width=56
Height=66
Image=\spr\Ui4\chienlenh\cl_10.spr
[ElemImgLowAwardLight]
WndType=WndButton
Up=0
Down=0
Parent=
Left=1
Top=1
Width=54
Height=64
Image=\spr\Ui4\chienlenh\cl_11.spr
[ElemImgLowAwardEffect]
WndType=WndImage
Parent=
Left=6
Top=11
Width=44
Height=44
Image=\spr\Ui4\chienlenh\cl_12.spr
[ElemImgLowAwardIconBG]
WndType=WndImage
Parent=
Left=14
Top=19
Width=28
Height=28
Image=\spr\Ui4\chienlenh\cl_13.spr
[ElemImgLowAwardIcon]
WndType=WndButton
Up=0
Down=0
Parent=
Left=2
Top=2
Width=24
Height=24
Image=\spr\item\questkey\obj_item_burseb.spr
[ElemTxtLowAwardNum]
WndType=WndText
Left=2
Top=15
Width=24
Height=0
Font=12
HAlign=2
Color=255,253,179
Text=0
[ElemImgLowAwardGray]
WndType=WndImage
Parent=
Left=1
Top=1
Width=54
Height=64
Image=\spr\Ui4\chienlenh\cl_15.spr
[ElemImgLowAwardFinish]
WndType=WndImage
Parent=
Left=10
Top=10
Width=38
Height=39
Image=\spr\Ui4\chienlenh\cl_16.spr

[ElemImgVipAwardBG]
WndType=WndImage
Parent=
Left=0
Top=110
Width=56
Height=66
Image=\spr\Ui4\chienlenh\cl_17.spr
[ElemImgVipAwardLight]
WndType=WndButton
Up=0
Down=0
Parent=
Left=1
Top=1
Width=54
Height=64
Image=\spr\Ui4\chienlenh\cl_18.spr
[ElemImgVipAwardEffect]
WndType=WndImage
Parent=
Left=6
Top=11
Width=44
Height=44
Image=\spr\Ui4\chienlenh\cl_12.spr
[ElemImgVipAwardIconBG]
WndType=WndImage
Parent=
Left=14
Top=19
Width=28
Height=28
Image=\spr\Ui4\chienlenh\cl_19.spr
[ElemImgVipAwardIcon]
WndType=WndButton
Up=0
Down=0
Parent=
Left=2
Top=2
Width=24
Height=24
[ElemTxtVipAwardNum]
WndType=WndText
Left=2
Top=15
Width=24
Height=0
Font=12
HAlign=2
Color=255,253,179
Text=0
[ElemImgVipAwardGray]
WndType=WndImage
Parent=
Left=1
Top=1
Width=54
Height=64
Image=\spr\Ui4\chienlenh\cl_15.spr
[ElemImgVipAwardFinish]
WndType=WndImage
Parent=
Left=10
Top=10
Width=38
Height=39
Image=\spr\Ui4\chienlenh\cl_16.spr

[ElemImgVipAwardLock]
WndType=WndImage
Parent=
Left=35
Top=10
Width=15
Height=17
Image=\spr\Ui4\chienlenh\cl_20.spr
;;;;;;;;;;;;;;;;;;;;½±Àø¿Ø¼þ;;;;;;;;;;;;;;;;;;;;
[BtnPrevPage]
WndType=WndLabeledButton
Parent=Main
Left=175
Top=252
Width=67
Height=19
Label=Tr­íc
Font=12
LabelYOffset=3
Color=255,255,179
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_21.spr

[BtnNextPage]
WndType=WndLabeledButton
Parent=Main
Left=360
Top=252
Width=67
Height=19
Label= Trang kÕ 
Font=14
LabelYOffset=3
Color=255,255,179
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_21.spr
;;;;;;;;;;;;;;;;;;;;½±Àø;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;ÈÎÎñ;;;;;;;;;;;;;;;;;;;;
[ImgDailyMissionBG]
WndType=WndImage
Parent=Main
Left=6
Top=273
Width=291
Height=21
Image=\spr\Ui4\chienlenh\cl_22.spr
[TxtDailyMission]
WndType=WndText
Disable=1
Color=255,253,179
Parent=ImgDailyMissionBG
Left=0
Top=0
Width=291
Height=21
Font=14
HAlign=1
VAlign=1
Text=NhiÖm Vô Ngµy

[ImgWeeklyMissionBG]
WndType=WndImage
Parent=Main
Left=297
Top=273
Width=291
Height=21
Image=\spr\Ui4\chienlenh\cl_22.spr
[TxtWeeklyMission]
WndType=WndText
Disable=1
Color=255,253,179
Parent=ImgWeeklyMissionBG
Left=0
Top=0
Width=291
Height=21
Font=14
HAlign=1
VAlign=1
Text=NhiÖm Vô TuÇn

;;;;;;;;;;;;;;;;;;;;ÈÕ³£;;;;;;;;;;;;;;;;;;;;
[DlyList]
WndType=WndImage
Parent=Main
Top=294
Left=6
Width=582
Height=173
WheelDelta=5
Image=\spr\Ui4\chienlenh\cl_23.spr

[DlyScr]
WndType=WndScrollBar
Parent=DlyList
Embed=1
Left=566
Top=1
Width=15
Height=170
Type=1
;PageSize=1
SlideBegin=18
SlideEnd=152
Image=\spr\Ui4\chienlenh\cl_24.spr

[DlyScr_Btn]
WndType=WndButton
Parent=DlyScr
Embed=1
Left=1
Width=14
Height=37
Up=0
Down=0
Over=0
OverFrame=0
Image=\spr\Ui4\chienlenh\cl_25.spr

[WndDailyMissionList]
WndType=WndImage
Parent=DlyList
Left=0
Top=0
Width=176
Height=0

;;;;;;;;;;;;;;;;;;;;ÖÜ³£;;;;;;;;;;;;;;;;;;;;
[WkList]
WndType=WndImage
Parent=Main
Top=294
Left=6
Width=582
Height=173
WheelDelta=5
Image=\spr\Ui4\chienlenh\cl_23.spr

[WkScr]
WndType=WndScrollBar
Parent=WkList
Embed=1
Left=566
Top=1
Width=15
Height=170
Type=1
;PageSize=1
SlideBegin=18
SlideEnd=152

[WkScr_Btn]
WndType=WndButton
Parent=WkScr
Embed=1
Left=1
Width=14
Height=37
Up=0
Down=0
Over=0
OverFrame=0
Image=\spr\Ui4\chienlenh\cl_25.spr

[WndWeeklyMissionList]
WndType=WndImage
Parent=WkList
Left=0
Top=0
Width=176
Height=0

;;;;;;;;;;;;;;;;;;;;ÈÎÎñ¿Ø¼þ;;;;;;;;;;;;;;;;;;;;
[ElemImgMissionInfoBG]
WndType=WndImage
Left=3
Top=3
Width=563
Height=38
Image=\spr\Ui4\chienlenh\cl_26.spr
BKColor=104,97,68
BKColorAlpha=100

[ElemImgMissionInfoBG_Finish]
WndType=WndImage
Left=0
Top=0
Width=563
Height=38
Image=\spr\Ui4\chienlenh\cl_27.spr
BKColor=104,97,68
BKColorAlpha=100

[ElemImgMissionAwardIconBG]
WndType=WndImage
Left=5
Top=5
Width=28
Height=28
[ElemImgMissionAwardIcon]
WndType=WndImage
Left=9
Top=7
Width=24
Height=24
Image=\spr\Ui4\chienlenh\cl_28.spr

[ElemTxtMissionAwardIconNum]
WndType=WndText
Left=9
Top=20
Width=24
Height=12
Font=12
HAlign=2
Color=255,253,179
Text=10

[ElemTxtMissionInfo]
WndType=WndText
Left=35
Top=0
Width=435
Height=38
Font=12
HAlign=1
VAlign=1
Color=199,211,161
Text=10


[ElemBtnGoToMissionArea]
WndType=WndLabeledButton
Left=470
Top=6
Width=74
Height=26
Label=§Õn
Font=14
LabelYOffset=6
Color=255,255,179
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_29.spr

[ElemBtnGetMissionAward]
WndType=WndLabeledButton
Left=470
Top=6
Width=74
Height=26
Label=NhËn
Font=14
LabelYOffset=6
Color=255,253,122
BorderColor=255,0,0
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_29.spr

[ElemBtnHaveGetAward]
WndType=WndLabeledButton
Left=470
Top=6
Width=74
Height=26
Label=§· nhËn
Font=14
LabelYOffset=6
Color=255,255,179
SelectColor=255,253,122
SelectBorderColor=255,0,0
DisableColor=77,77,77
OverColor=0,255,0
Image=\spr\Ui4\chienlenh\cl_29.spr
Disable=1
Up=2