;----------------------------------------------------------------------------------------------
;--  新增门派时,需要同步更改GameDateDef.h中的MAX_FACTION,由于门派排行将该值用于枚举当中，无法配置表化  --
;--  注意：各个门派的定义，这份是C++的，lua的定义在\script\faction_def.lua                         --
;--  注意：faction_settings一共有四份，修改时请四份一起修改                                       --
;----------------------------------------------------------------------------------------------
[Name]
New=Mới nhập giang hồ 
Old=giang hồ hiệp khách

;示例
;[-1]
;Name=shaolin
;ShowName=少林派
;Series=0-金 1-木 2-ậđ 3-火 4-土
;Camp=0-新手（未加门派） 1-正派 2-邪派 3-中立 4-杀手 5-野兽 6-路人
;TaskId=门派任务变量

;少林派 金 中派
[0]
Name=shaolin
ShowName=Thiếu Lâm phái
Series=0
Camp=1
TaskId=7

;天王帮 金 中立
[1]
Name=tianwang
ShowName=Thiên Vương Bang
Series=0
Camp=3
TaskId=3

;唐门 木 中立
[2]
Name=tangmen
ShowName=Đường Môn
Series=1
Camp=3
TaskId=2

;五毒教 木 邪派
[3]
Name=wudu
ShowName=Ngũ Độc Giáo
Series=1
Camp=2
TaskId=10

;峨嵋派 水 正派
[4]
Name=emei
ShowName=Nga My phái
Series=2
Camp=1
TaskId=1

;翠烟门 水 中立
[5]
Name=cuiyan
ShowName=Thúy Yên môn
Series=2
Camp=3
TaskId=6

;丐帮 火 中立
[6]
Name=gaibang
ShowName=Cái Bang
Series=3
Camp=1
TaskId=8

;天忍教 火 邪派
[7]
Name=tianren
ShowName=Thiên Nhẫn Giáo
Series=3
Camp=2
TaskId=4

;武当派 土 正派
[8]
Name=wudang
ShowName=Võ Đang phái
Series=4
Camp=1
TaskId=5

;昆仑派 土 中立
[9]
Name=kunlun
ShowName=Côn Lôn phái
Series=4
Camp=3
TaskId=9

;华山派 水 中立
[10]
Name=huashan
ShowName=Hoa Sơn phái
Series=2
Camp=3
TaskId=3481

;武魂堂 火 正派
[11]
Name=wuhun
ShowName=Vũ Hồn 
Series=3
Camp=1
TaskId=4406

;逍遥派 土 中立
[12]
Name=xiaoyao
ShowName=Phái Tiêu Dao
Series=4
Camp=3
TaskId=4464