;----------------------------------------------------------------------------------------------
;--  ĞÂÔöÃÅÅÉÊ±,ĞèÒªÍ¬²½¸ü¸ÄGameDateDef.hÖĞµÄMAX_FACTION,ÓÉÓÚÃÅÅÉÅÅĞĞ½«¸ÃÖµÓÃÓÚÃ¶¾Ùµ±ÖĞ£¬ÎŞ·¨ÅäÖÃ±í»¯  --
;--  ×¢Òâ£º¸÷¸öÃÅÅÉµÄ¶¨Òå£¬Õâ·İÊÇC++µÄ£¬luaµÄ¶¨ÒåÔÚ\script\faction_def.lua                         --
;--  ×¢Òâ£ºfaction_settingsÒ»¹²ÓĞËÄ·İ£¬ĞŞ¸ÄÊ±ÇëËÄ·İÒ»ÆğĞŞ¸Ä                                       --
;----------------------------------------------------------------------------------------------
[Name]
New=Míi nhËp giang hå 
Old=giang hå hiÖp kh¸ch

;Ê¾Àı
;[-1]
;Name=shaolin
;ShowName=ÉÙÁÖÅÉ
;Series=0-½ğ 1-Ä¾ 2-Ë® 3-»ğ 4-ÍÁ
;Camp=0-ĞÂÊÖ£¨Î´¼ÓÃÅÅÉ£© 1-ÕıÅÉ 2-Ğ°ÅÉ 3-ÖĞÁ¢ 4-É±ÊÖ 5-Ò°ÊŞ 6-Â·ÈË
;TaskId=ÃÅÅÉÈÎÎñ±äÁ¿

;ÉÙÁÖÅÉ ½ğ ÖĞÅÉ
[0]
Name=shaolin
ShowName=ThiÕu L©m ph¸i
Series=0
Camp=1
TaskId=7

;ÌìÍõ°ï ½ğ ÖĞÁ¢
[1]
Name=tianwang
ShowName=Thiªn V­¬ng Bang
Series=0
Camp=3
TaskId=3

;ÌÆÃÅ Ä¾ ÖĞÁ¢
[2]
Name=tangmen
ShowName=§­êng M«n
Series=1
Camp=3
TaskId=2

;Îå¶¾½Ì Ä¾ Ğ°ÅÉ
[3]
Name=wudu
ShowName=Ngò §éc Gi¸o
Series=1
Camp=2
TaskId=10

;¶ëáÒÅÉ Ë® ÕıÅÉ
[4]
Name=emei
ShowName=Nga My ph¸i
Series=2
Camp=1
TaskId=1

;´äÑÌÃÅ Ë® ÖĞÁ¢
[5]
Name=cuiyan
ShowName=Thóy Yªn m«n
Series=2
Camp=3
TaskId=6

;Ø¤°ï »ğ ÖĞÁ¢
[6]
Name=gaibang
ShowName=C¸i Bang
Series=3
Camp=1
TaskId=8

;ÌìÈÌ½Ì »ğ Ğ°ÅÉ
[7]
Name=tianren
ShowName=Thiªn NhÉn Gi¸o
Series=3
Camp=2
TaskId=4

;Îäµ±ÅÉ ÍÁ ÕıÅÉ
[8]
Name=wudang
ShowName=Vâ §ang ph¸i
Series=4
Camp=1
TaskId=5

;À¥ÂØÅÉ ÍÁ ÖĞÁ¢
[9]
Name=kunlun
ShowName=C«n L«n ph¸i
Series=4
Camp=3
TaskId=9

;»ªÉ½ÅÉ Ë® ÖĞÁ¢
[10]
Name=huashan
ShowName=Hoa S¬n ph¸i
Series=2
Camp=3
TaskId=3481

;Îä»êÌÃ »ğ ÕıÅÉ
[11]
Name=wuhun
ShowName=Vò Hån 
Series=3
Camp=1
TaskId=4406

;åĞÒ£ÅÉ ÍÁ ÖĞÁ¢
[12]
Name=xiaoyao
ShowName=Ph¸i Tiªu Dao
Series=4
Camp=3
TaskId=4464