# -*- coding: utf-8 -*-
"""B3v2 - sinh hd3_admin.lua (menu test 3 hoat dong tren Lenh Bai Admin).
Chuoi tieng Viet ma hoa TCVN3 bang unicode_to_tcvn3_bytes cua skill.
Ghi ca JX1 lan MIRROR.

V2 (25/08, theo audit A7):
 - sua nhan "Ba Lang Huyen" -> "Phuong Tuong" (map 1 = Phuong Tuong, WorldSet:5)
 - sua chuoi co backslash bi Lua 4 nuot -> dung dau /
 - nut "Sinh lai NPC" them canh bao nhan ban
 - them nut THOAT khoi map thuyen (khong la GM ket trong 337)
 - them: nhan 2 Sat Thu Gian / dat task 1082 theo so nhap / xem mission PLD /
   dat task 2636-2639 test rank / in cac khoa HD3_* dang hieu luc
LUU Y nhan menu: CAM dau '/' trong nhan (ScriptFuns.cpp:717 cat o dau / DAU TIEN).
"""
import io, os, sys
sys.path.insert(0, r"C:\Users\nguye\.claude\skills\swordonline-dev\scripts")
from vn_to_octal import unicode_to_tcvn3_bytes

JX1 = r"E:\SourceTuanLe\SourceVs22\TESTLOFFF_ONLINE\bin\server"
MIRROR = r"D:\GAMEDEVNEW\serverscript_jx2\3hoatdong"


def V(s):
    b = unicode_to_tcvn3_bytes(s)
    assert b.count(b"/") == 0 or True  # dau / chi duoc o cuoi nhan (tach ham)
    return b.decode("latin-1")


L = []
a = L.append
a('-- ============================================================================')
a('-- HD3_ADMIN.LUA - Menu TEST 3 hoat dong ban Linux tren Lenh Bai Admin. (v2)')
a('-- Include tu lenhbaiadmin.lua (main() dofile lai) => SUA KHONG CAN RESTART.')
a('-- Cau hinh: script\\header\\cauhinh_hoatdong.lua (khoi [6]).')
a('-- CAM dau "/" trong nhan menu (ScriptFuns.cpp:717 cat o dau / dau tien).')
a('-- ============================================================================')
a('Include("\\\\script\\\\tinhnang\\\\3hoatdong\\\\hd3_driver.lua")')
a('')
a('function HD3_AdminMenu()')
a('\tSayEx({"<color=yellow>' + V("Hoạt động ban Linux (test)") + '<color>: ' + V("chọn mục") + '",')
a('\t"1. ' + V("Săn Boss Sát Thủ") + '/HD3_ADM_ST",')
a('\t"2. ' + V("Phong Lăng Độ") + '/HD3_ADM_PLD",')
a('\t"3. ' + V("Vượt ải") + '/HD3_ADM_VA",')
a('\t"4. ' + V("Nạp lại CONFIG") + '/HD3_ADM_Reload",')
a('\t"5. ' + V("Xem các khoá cấu hình HD3 đang hiệu lực") + '/HD3_ADM_ShowCfg",')
a('\t"' + V("Kết thúc đối thoại") + './no"})')
a('end')
a('')
# ---------------- (1) SAN BOSS SAT THU ----------------
a('function HD3_ADM_ST()')
a('\tSayEx({"<color=yellow>' + V("Săn Boss Sát Thủ") + '<color> - ' + V("trần") + ' " .. HD_CFG("HD3_ST_MAX_NGAY", 8) .. " ' + V("lần một ngày; chỉ nhóm cấp 90 (chỉ số 141-160) phát thưởng") + '",')
a('\t"' + V("Sinh lại NPC 769 và 160 boss - Chỉ khi boot lỗi, gọi lặp sẽ nhân bản NPC") + '/HD3_ADM_ST_Boot",')
a('\t"' + V("Dịch chuyển: NPC Nhiếp Thí Trần (Phượng Tường)") + '/HD3_ADM_ST_Tele",')
a('\t"' + V("Nhận 5 Sát Thủ lệnh cấp 90 (test gộp Giản)") + '/HD3_ADM_ST_Lenh",')
a('\t"' + V("Nhận 2 Sát Thủ Giản cấp 90 (đủ vé báo danh Vượt ải cao cấp)") + '/HD3_ADM_ST_Gian2",')
a('\t"' + V("Đặt boss đang nhận (task 1082) theo số nhập 1-160") + '/HD3_ADM_ST_SetBoss",')
a('\t"' + V("Xem biến nhiệm vụ (1082, 1192, 1193, 1217)") + '/HD3_ADM_ST_Task",')
a('\t"' + V("Reset số lần giết trong ngày") + '/HD3_ADM_ST_Reset",')
a('\t"' + V("Quay lại") + '/HD3_AdminMenu"})')
a('end')
a('function HD3_ADM_ST_Boot() HD3_DriverInit() Msg2Player("' + V("Đã gọi HD3_DriverInit (sinh NPC + boss). Gọi lặp sẽ nhân bản NPC!") + '") end')
a('function HD3_ADM_ST_Tele() NewWorld(1, 1506, 3198) end')
a('function HD3_ADM_ST_Lenh()')
a('\tfor i = 1, 5 do AddItem(6, 1, 398, 90, mod(i, 5), 0) end')
a('\tMsg2Player("' + V("Đã nhận 5 Sát Thủ lệnh cấp 90 (đủ 5 hệ). Gặp Nhiếp Thí Trần để gộp thành Sát Thủ Giản.") + '")')
a('end')
a('function HD3_ADM_ST_Gian2()')
a('\tAddItem(6, 1, 399, 90, 0, 0)')
a('\tAddItem(6, 1, 399, 90, 1, 0)')
a('\tMsg2Player("' + V("Đã nhận 2 Sát Thủ Giản cấp 90 - đủ vé đội trưởng báo danh Vượt ải cao cấp.") + '")')
a('end')
a('function HD3_ADM_ST_SetBoss()')
a('\tOpenGetNumber("' + V("Nhập chỉ số boss (1-160, nhóm 90 = 141-160)") + '", "HD3_ADM_ST_SetBossCB")')
a('end')
a('function HD3_ADM_ST_SetBossCB()')
a('\tlocal n = GetNumberFromUI()')
a('\tif (n == nil or n < 0 or n > 160) then Msg2Player("' + V("Số không hợp lệ (0 = xoá nhiệm vụ).") + '") return end')
a('\tSetTask(1082, n)')
a('\tMsg2Player(format("' + V("Đã đặt task 1082 = %d. Giết đúng boss mang chỉ số này để hoàn thành.") + '", n))')
a('end')
a('function HD3_ADM_ST_Task()')
a('\tMsg2Player(format("' + V("1082=%d (chỉ số) - 1192=%d (ngày) - 1193=%d (số lần) - 1217=%d (tích lũy)") + '", GetTask(1082), GetTask(1192), GetTask(1193), GetTask(1217)))')
a('\tHD3_ADM_ST()')
a('end')
a('function HD3_ADM_ST_Reset() SetTask(1193, 0) Msg2Player("' + V("Đã reset số lần giết boss trong ngày.") + '") end')
a('')
# ---------------- (2) PHONG LANG DO ----------------
a('function HD3_ADM_PLD()')
a('\tSayEx({"<color=yellow>' + V("Phong Lăng Độ") + '<color> - ' + V("mở theo giờ trong HD3_PLD_GIO; giờ tốn phí dùng Lệnh Bài Thủy Tặc") + '",')
a('\t"' + V("Khai cuộc NGAY (mở đăng ký thuyền)") + '/HD3_ADM_PLD_Now",')
a('\t"' + V("Xem trạng thái 3 thuyền (mission 15)") + '/HD3_ADM_PLD_TrangThai",')
a('\t"' + V("Dịch chuyển: Thuyền phu bờ Nam (map 336)") + '/HD3_ADM_PLD_Tele336",')
a('\t"' + V("Vào map thuyền 337 (xem nút thoát bên dưới!)") + '/HD3_ADM_PLD_Tele337",')
a('\t"' + V("Thoát khỏi map thuyền về Phượng Tường") + '/HD3_ADM_PLD_Thoat",')
a('\t"' + V("Nhận Lệnh bài Phong Lăng Độ (4,489)") + '/HD3_ADM_PLD_LB",')
a('\t"' + V("Nhận Lệnh Bài Thủy Tặc (6,1,3363)") + '/HD3_ADM_PLD_LBTT",')
a('\t"' + V("Quay lại") + '/HD3_AdminMenu"})')
a('end')
a('function HD3_ADM_PLD_Now() HD3_Adm_PLD_Now() Msg2Player("' + V("Đã ép khai cuộc Phong Lăng Độ (fenglingdu_main).") + '") end')
a('function HD3_ADM_PLD_TrangThai()')
a('\tlocal tbMap = {337, 338, 339}')
a('\tlocal nOld = SubWorld')
a('\tfor i = 1, 3 do')
a('\t\tlocal idx = SubWorldID2Idx(tbMap[i])')
a('\t\tif (idx >= 0) then')
a('\t\t\tSubWorld = idx')
a('\t\t\tMsg2Player(format("' + V("Thuyền %d (map %d): mission=%d, người=%d, phút=%d") + '", i, tbMap[i], IsMission(15), GetMSPlayerCount(15, 1), GetMissionV(2)))')
a('\t\tend')
a('\tend')
a('\tSubWorld = nOld')
a('\tHD3_ADM_PLD()')
a('end')
a('function HD3_ADM_PLD_Tele336() NewWorld(336, 1147, 3018) end')
a('function HD3_ADM_PLD_Tele337() NewWorld(337, 1646, 3233) end')
a('function HD3_ADM_PLD_Thoat() NewWorld(1, 1506, 3198) Msg2Player("' + V("Đã thoát về Phượng Tường.") + '") end')
a('function HD3_ADM_PLD_LB() AddItem(4, 489, 0, 0, 0, 0) Msg2Player("' + V("Đã nhận Lệnh bài Phong Lăng Độ.") + '") end')
a('function HD3_ADM_PLD_LBTT() AddItem(6, 1, 3363, 0, 0, 0) Msg2Player("' + V("Đã nhận Lệnh Bài Thủy Tặc (6,1,3363).") + '") end')
a('')
# ---------------- (3) VUOT AI ----------------
a('function HD3_ADM_VA()')
a('\tSayEx({"<color=yellow>' + V("Vượt ải") + '<color> - ' + V("báo danh theo giờ HD3_VA_GIO; đội trưởng cần 2 Sát Thủ Giản + tổ đội 4 người") + '",')
a('\t"' + V("Báo danh NGAY (mở mission các map ải)") + '/HD3_ADM_VA_Now",')
a('\t"' + V("Xem trạng thái ải (map 464 sơ cấp, 480 cao cấp)") + '/HD3_ADM_VA_TrangThai",')
a('\t"' + V("Trao bảng xếp hạng ngày (Ladder 10235)") + '/HD3_ADM_VA_Rank",')
a('\t"' + V("Đặt thành tích hôm qua (task 2636-2639) để test nhận thưởng") + '/HD3_ADM_VA_SetRank",')
a('\t"' + V("Nhận 2 Sát Thủ Giản cấp 90 (vé vào)") + '/HD3_ADM_ST_Gian2",')
a('\t"' + V("Dịch chuyển tới Nhiếp Thí Trần (Phượng Tường)") + '/HD3_ADM_ST_Tele",')
a('\t"' + V("Quay lại") + '/HD3_AdminMenu"})')
a('end')
a('function HD3_ADM_VA_Now() HD3_Adm_VA_Now() Msg2Player("' + V("Đã ép báo danh Vượt ải (trigger OnTrigger).") + '") end')
a('function HD3_ADM_VA_TrangThai()')
a('\tlocal tbMap = {464, 480, 957}')
a('\tlocal nOld = SubWorld')
a('\tfor i = 1, 3 do')
a('\t\tlocal idx = SubWorldID2Idx(tbMap[i])')
a('\t\tif (idx >= 0) then')
a('\t\t\tSubWorld = idx')
a('\t\t\tMsg2Player(format("' + V("Map %d: mission22=%d, người=%d, trạng thái=%d") + '", tbMap[i], IsMission(22), GetMSPlayerCount(22, 1), GetMissionV(4)))')
a('\t\telse')
a('\t\t\tMsg2Player(format("' + V("Map %d: chưa nạp (WorldSet)") + '", tbMap[i]))')
a('\t\tend')
a('\tend')
a('\tSubWorld = nOld')
a('\tHD3_ADM_VA()')
a('end')
a('function HD3_ADM_VA_Rank() HD3_Adm_VA_Rank() Msg2Player("' + V("Đã chạy bảng xếp hạng ngày (Ladder 10235).") + '") end')
a('function HD3_ADM_VA_SetRank()')
a('\tlocal nHomQua = tonumber(GetLocalDate("%y%m%d")) - 1')
a('\tSetTask(2636, nHomQua)')
a('\tSetTask(2637, 600)')
a('\tSetTask(2638, 0)')
a('\tSetTask(2639, 0)')
a('\tMsg2Player(format("' + V("Đã đặt 2636=%d (hôm qua), 2637=600 (10 phút). Gặp Nhiếp Thí Trần bấm nhận thưởng xếp hạng.") + '", nHomQua))')
a('end')
a('')
# ---------------- (4)(5) ----------------
a('function HD3_ADM_Reload()')
a('\tif (HD_NapLaiCauHinh ~= nil) then HD_NapLaiCauHinh() end')
a('\tMsg2Player("' + V("Đã nạp lại CONFIG (script/header/cauhinh_hoatdong.lua) trong state admin. Các khoá [RESTART] vẫn cần restart.") + '")')
a('\tHD3_AdminMenu()')
a('end')
a('function HD3_ADM_ShowCfg()')
a('\tlocal k, v = next(tbCHD, nil)')
a('\tlocal n = 0')
a('\twhile (k ~= nil) do')
a('\t\tif (type(k) == "string" and strsub(k, 1, 4) == "HD3_") then')
a('\t\t\tif (type(v) == "table") then')
a('\t\t\t\tMsg2Player(format("%s = {%d ' + V("mục") + '}", k, getn(v)))')
a('\t\t\telseif (v == nil) then')
a('\t\t\t\tMsg2Player(format("%s = nil (' + V("bảng gốc") + ')", k))')
a('\t\t\telse')
a('\t\t\t\tMsg2Player(format("%s = %s", k, tostring(v)))')
a('\t\t\tend')
a('\t\t\tn = n + 1')
a('\t\tend')
a('\t\tk, v = next(tbCHD, k)')
a('\tend')
a('\tMsg2Player(format("' + V("Tổng %d khoá HD3_*.") + '", n))')
a('\tHD3_AdminMenu()')
a('end')
a('')

data = ("\r\n".join(L) + "\r\n").encode("latin-1")
rel = os.path.join("script", "item", "hd3_admin.lua")
for base in (JX1, MIRROR):
    p = os.path.join(base, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "wb").write(data)
    print("ghi", p, os.path.getsize(p), "byte")
