# -*- coding: utf-8 -*-
"""C24 - lam DUNG Y CHU GAME: "di chuyen toi Xa Phu -> KICH VAO menu len dung map
nhiem vu -> roi moi di chuyen den toa do boss".
Ban C20 cua toi tu che duong "thue xe" (server NewWorld thang) - SAI y. Nay thay
bang may 6 pha BAM MENU THAT cua Xa Phu:
   1 = chay toi Xa Phu           4 = chon TEN MAP (menu trang 3)
   2 = chon "luyen cong"          5 = doi chuyen map
   3 = chon "Moc XX"              6 = di bo toi o boss
Bang ten menu tung boss: KSatThuBossPos.h (s_szST3BossMenu/Moc) SINH TU DONG tu
XP_TEN/BOT_BAI cua station.lua nen khop tung byte voi nhan menu that.
Map KHONG co trong menu luyen cong (nhom 20-80, 116/160 con) -> giu duong thue xe
st3_goboss lam du phong (cung dap xuong waypoint) + bao ro cho nguoi choi.
"""
import io, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, r"C:\Users\nguye\.claude\skills\swordonline-dev\scripts")
from vn_to_octal import unicode_to_tcvn3_bytes
V = lambda s: unicode_to_tcvn3_bytes(s).decode("latin-1")

P = r"D:\GAMEDEVNEW\Sources\Core\Src\CoreShell.cpp"
T = "\t"
d = io.open(P, encoding="latin-1", newline="").read()
NL = "\r\n" if "\r\n" in d else "\n"
if "g_nTGSTDlgTry" in d:
    print("da va roi"); raise SystemExit

i0 = d.index('#include "KSatThuBossPos.h"')
i1 = d.index("// [DaTau] tim quai con SONG da sync NGOAI tam danh")
assert i0 < i1

MSG_HUY      = V("[Chỉ nam] Đã hủy dẫn đường tới boss.")
MSG_KHONGNV  = V("[Chỉ nam] Chưa nhận nhiệm vụ sát thủ.")
MSG_KHONGXP  = V("[Chỉ nam] Không thấy Xa Phu ở map này - hãy về thành rồi bấm lại.")
MSG_BATDAU   = V("[Chỉ nam] Đang dẫn đường tới boss - bấm lại vào dòng nhiệm vụ để hủy.")
MSG_GAPXP    = V("[Chỉ nam] Đã gặp Xa Phu - đang chọn bản đồ nhiệm vụ...")
MSG_LAU      = V("[Chỉ nam] Đi quá lâu - dừng dẫn đường.")
MSG_KHONGQUA = V("[Chỉ nam] Chưa lên được bản đồ - dừng dẫn đường.")
MSG_TOI      = V("[Chỉ nam] Đã tới khu vực boss - cẩn thận!")
MSG_MENU     = V("[Chỉ nam] Thoại Xa Phu không có mục cần chọn - hãy tự chọn trong khung thoại.")
MSG_THUEXE   = V("[Chỉ nam] Bản đồ này Xa Phu không chở tới - thuê xe riêng (tốn tiền).")
MSG_LENMAP   = V("[Chỉ nam] Đã lên bản đồ nhiệm vụ - đang chạy tới boss...")

body = NL.join([
    '#include "KSatThuBossPos.h"',
    "",
    "//---------------------------------------------------------------------------",
    "// [3HD C24] Bam nhiem vu 'San Boss Sat Thu' tren F11 -> dan duong DUNG luong",
    "// nguoi choi that: chay toi Xa Phu -> BAM MENU (luyen cong -> moc -> ten map)",
    "// -> len map o TOA DO MAC DINH -> di bo toi o boss. Map khong co trong menu",
    "// thi thue xe rieng (st3_goboss - server tru tien, cung dap xuong waypoint).",
    "// Tai dung nghe Da Tau: DT_WalkTo / DT_FindNpcName / g_MoveStation / DT_Answer.",
    "//---------------------------------------------------------------------------",
    "static int  g_nTGSTOn = 0;",
    "static int  g_nTGSTPhase = 0;\t\t// 1 di XaPhu, 2..4 bam menu, 5 doi len map, 6 di toi boss",
    "static int  g_nTGSTMap = 0;",
    "static int  g_nTGSTX = 0, g_nTGSTY = 0;",
    "static int  g_nTGSTBoss = 0;",
    "static int  g_nTGSTTry = 0;",
    "static int  g_nTGSTDlgTry = 0;\t\t// so lan go lai thoai trong 1 pha menu",
    "static UINT g_uTGSTNext = 0;",
    "static UINT g_uTGSTDlgSeen = 0;",
    "static int  g_nTGSTNpc = 0;\t\t\t// idx Xa Phu dang noi chuyen",
    "",
    "static void TG_SatThuStop(const char* szMsg)",
    "{",
    T + "if (g_nTGSTOn && szMsg)",
    T + T + "DT_Msg(CLIENT_PLAYER_INDEX, szMsg);",
    T + "g_nTGSTOn = 0;",
    "}",
    "",
    "static int TG_SatThuStart()",
    "{",
    T + "int nPlayerIdx = CLIENT_PLAYER_INDEX;",
    T + "if (g_nTGSTOn)",
    T + "{",
    T + T + 'TG_SatThuStop("<color=Cyan>' + MSG_HUY + '");',
    T + T + "return 0;",
    T + "}",
    T + "if (Player[nPlayerIdx].m_nIndex <= 0)",
    T + T + "return 0;",
    T + "int nBoss = (int)Player[nPlayerIdx].m_cTask.GetSaveVal(1082);",
    T + "if (nBoss < 1 || nBoss > ST3_POS_MAX)",
    T + "{",
    T + T + 'DT_Msg(nPlayerIdx, "<color=Yellow>' + MSG_KHONGNV + '");',
    T + T + "return 0;",
    T + "}",
    T + "g_nTGSTBoss = nBoss;",
    T + "g_nTGSTMap = s_nST3BossMap[nBoss];",
    T + "g_nTGSTX = s_nST3BossX[nBoss];",
    T + "g_nTGSTY = s_nST3BossY[nBoss];",
    T + "g_nTGSTTry = 0;",
    T + "g_nTGSTDlgTry = 0;",
    T + "g_uTGSTNext = 0;",
    T + "g_nTGSTNpc = 0;",
    T + "g_uTGSTDlgSeen = g_sDTCap.uDlgSeq;",
    T + "if (SubWorld[0].m_SubWorldID == g_nTGSTMap)",
    T + "{",
    T + T + "g_nTGSTPhase = 6;\t// da dung tren map boss - di bo thang",
    T + "}",
    T + "else",
    T + "{",
    T + T + "MapStation::iterator it = g_MoveStation.find(SubWorld[0].m_SubWorldID);",
    T + T + "if (it == g_MoveStation.end() || it->second.empty())",
    T + T + "{",
    T + T + T + 'DT_Msg(nPlayerIdx, "<color=Yellow>' + MSG_KHONGXP + '");',
    T + T + T + "return 0;",
    T + T + "}",
    T + T + "g_nTGSTPhase = 1;",
    T + "}",
    T + "g_nTGSTOn = 1;",
    T + 'DT_Msg(nPlayerIdx, "<color=Cyan>' + MSG_BATDAU + '");',
    T + "return 1;",
    "}",
    "",
    "// chon mot muc trong thoai dang mo; tra 1 neu da bam, 0 neu chua co thoai moi,",
    "// -1 neu thoai co roi ma KHONG tim thay muc can chon.",
    "static int TG_SatThuPickAns(int nPlayerIdx, const char* szMark)",
    "{",
    T + "if (g_sDTCap.uDlgSeq == g_uTGSTDlgSeen)",
    T + "{",
    T + T + "// chua co thoai moi: cu ~3.2s go lai NPC mot lan",
    T + T + "if (g_nTGSTNpc > 0 && (++g_nTGSTDlgTry % 8) == 0)",
    T + T + T + "Player[nPlayerIdx].DialogNpc(g_nTGSTNpc);",
    T + T + "return 0;",
    T + "}",
    T + "g_uTGSTDlgSeen = g_sDTCap.uDlgSeq;",
    T + "g_nTGSTDlgTry = 0;",
    T + "char szBuf[2048];",
    T + "char* apAns[24];",
    T + "g_StrCpyLen(szBuf, g_sDTCap.szDlg, sizeof(szBuf));",
    T + "int nAns = DT_Split(szBuf, apAns, 24);",
    T + "int nOpt = DT_FindAns(apAns, nAns, szMark);",
    T + "if (nOpt < 0)",
    T + T + "return -1;",
    T + "DT_Answer(nPlayerIdx, nOpt);",
    T + "return 1;",
    "}",
    "",
    "static void TG_SatThuTick()",
    "{",
    T + "if (!g_nTGSTOn)",
    T + T + "return;",
    T + "int nPlayerIdx = CLIENT_PLAYER_INDEX;",
    T + "if (Player[nPlayerIdx].m_nIndex <= 0)",
    T + "{",
    T + T + "g_nTGSTOn = 0;",
    T + T + "return;",
    T + "}",
    T + "UINT uCur = timeGetTime();",
    T + "if (uCur < g_uTGSTNext)",
    T + T + "return;",
    T + "g_uTGSTNext = uCur + 400;",
    T + "if (++g_nTGSTTry > ((g_nTGSTPhase == 6) ? 900 : 450))",
    T + "{",
    T + T + 'TG_SatThuStop("<color=Yellow>' + MSG_LAU + '");',
    T + T + "return;",
    T + "}",
    T + "// --- pha 1: chay toi Xa Phu roi mo thoai ---",
    T + "if (g_nTGSTPhase == 1)",
    T + "{",
    T + T + "MapStation::iterator it = g_MoveStation.find(SubWorld[0].m_SubWorldID);",
    T + T + "if (it == g_MoveStation.end() || it->second.empty())",
    T + T + "{",
    T + T + T + 'TG_SatThuStop("<color=Yellow>' + MSG_KHONGXP + '");',
    T + T + T + "return;",
    T + T + "}",
    T + T + "sStation& s = it->second[0];",
    T + T + 'int nIdx = DT_FindNpcName(nPlayerIdx, "xa phu", s.x, s.y, 400);',
    T + T + "if (nIdx)",
    T + T + "{",
    T + T + T + "int nX, nY, dX, dY;",
    T + T + T + "Npc[Player[nPlayerIdx].m_nIndex].GetMpsPos(&nX, &nY);",
    T + T + T + "Npc[nIdx].GetMpsPos(&dX, &dY);",
    T + T + T + "if (g_GetDistance(nX, nY, dX, dY) <= 160)",
    T + T + T + "{",
    T + T + T + T + "g_nTGSTNpc = nIdx;",
    T + T + T + T + "g_nTGSTTry = 0;",
    T + T + T + T + "g_nTGSTDlgTry = 0;",
    T + T + T + T + "g_uTGSTDlgSeen = g_sDTCap.uDlgSeq;",
    T + T + T + T + "Player[nPlayerIdx].DialogNpc(nIdx);",
    T + T + T + T + "// map khong co trong menu luyen cong -> thue xe rieng",
    T + T + T + T + "if (s_szST3BossMenu[g_nTGSTBoss][0] == 0)",
    T + T + T + T + "{",
    T + T + T + T + T + 'DT_Msg(nPlayerIdx, "<color=Yellow>' + MSG_THUEXE + '");',
    T + T + T + T + T + 'SendUiCmdScript(6, (char*)"st3_goboss");',
    T + T + T + T + T + "g_nTGSTPhase = 5;",
    T + T + T + T + T + "return;",
    T + T + T + T + "}",
    T + T + T + T + 'DT_Msg(nPlayerIdx, "<color=Cyan>' + MSG_GAPXP + '");',
    T + T + T + T + "g_nTGSTPhase = 2;",
    T + T + T + T + "return;",
    T + T + T + "}",
    T + T + T + "DT_WalkTo(nPlayerIdx, dX, dY, 128, uCur);",
    T + T + T + "return;",
    T + T + "}",
    T + T + "DT_WalkTo(nPlayerIdx, s.x, s.y, 200, uCur);",
    T + T + "return;",
    T + "}",
    T + "// --- pha 2..4: bam 3 cap menu cua Xa Phu ---",
    T + "if (g_nTGSTPhase >= 2 && g_nTGSTPhase <= 4)",
    T + "{",
    T + T + "const char* szMark = ST3_MENU_LUYENCONG;",
    T + T + "if (g_nTGSTPhase == 3)",
    T + T + T + "szMark = s_szST3BossMoc[g_nTGSTBoss];",
    T + T + "else if (g_nTGSTPhase == 4)",
    T + T + T + "szMark = s_szST3BossMenu[g_nTGSTBoss];",
    T + T + "int nRet = TG_SatThuPickAns(nPlayerIdx, szMark);",
    T + T + "if (nRet == 1)",
    T + T + "{",
    T + T + T + "g_nTGSTTry = 0;",
    T + T + T + "g_nTGSTPhase++;\t// 4 -> 5: da bam ten map, cho chuyen map",
    T + T + "}",
    T + T + "else if (nRet < 0)",
    T + T + "{",
    T + T + T + 'TG_SatThuStop("<color=Yellow>' + MSG_MENU + '");',
    T + T + "}",
    T + T + "return;",
    T + "}",
    T + "// --- pha 5: doi len dung map nhiem vu ---",
    T + "if (g_nTGSTPhase == 5)",
    T + "{",
    T + T + "if (SubWorld[0].m_SubWorldID == g_nTGSTMap)",
    T + T + "{",
    T + T + T + "g_nTGSTPhase = 6;",
    T + T + T + "g_nTGSTTry = 0;",
    T + T + T + 'DT_Msg(nPlayerIdx, "<color=Cyan>' + MSG_LENMAP + '");',
    T + T + T + "return;",
    T + T + "}",
    T + T + "if (g_nTGSTTry > 25)",
    T + T + T + 'TG_SatThuStop("<color=Yellow>' + MSG_KHONGQUA + '");',
    T + T + "return;",
    T + "}",
    T + "// --- pha 6: di bo tu toa do mac dinh cua map toi o boss ---",
    T + "if (SubWorld[0].m_SubWorldID != g_nTGSTMap)",
    T + "{",
    T + T + "g_nTGSTOn = 0;\t// bi keo sang map khac - tat im lang",
    T + T + "return;",
    T + "}",
    T + "if (DT_WalkTo(nPlayerIdx, g_nTGSTX * 32, g_nTGSTY * 32, 250, uCur))",
    T + T + 'TG_SatThuStop("<color=Cyan>' + MSG_TOI + '");',
    "}",
    "",
    "",
])
d = d[:i0] + body + d[i1:]
io.open(P, "w", encoding="latin-1", newline="").write(d)
print("da thay may TG_SatThu bang ban BAM MENU (6 pha)")
