-- ============================================================================
-- CFGW_META.LUA - SINH TU DONG boi ReverseTools\cauhinh_web\sinh_cfgw_meta.py - DUNG SUA TAY
-- [CFGW 04/09] mo ta / nhom / kieu / khoang / ap_dung cua tung khoa cau hinh, de cfgw_driver.lua
-- khai len bang MySQL gcfg (web admin doc). Khoa = { nhom, mo ta, kieu, min, max, ap_dung, nguon, don_vi }
--   kieu: 0 so nguyen | 1 so thuc | 2 chuoi | 3 bat/tat | 4 gio HHMM
--   ap_dung: 1 = an trong <= 1 phut (G_CFG doc song / timerserver tu nap lai) | 2 = can nap lai script hoac restart
-- TEP NAY LA 'LA': CAM Include bat cu gi vao day.
-- ============================================================================
tbCFGW_META = {
DT_SO_NV_MOI_VONG = {"DATAU", "so nhiem vu phai lam xong de qua mot vong moi", 0, 0, 0, 2, "ch_chung.lua", ""},
DT_SO_VONG_MOI_CHU_KY = {"DATAU", "so vong nhiem vu trong mot chu ky", 0, 0, 0, 2, "ch_chung.lua", ""},
DT_SO_CHU_KY_TOI_DA = {"DATAU", "so chu ky toi da truoc khi dem quay ve 0", 0, 0, 0, 2, "ch_chung.lua", ""},
BDH_SO_O_TRANGBI = {"BANDONGHANH", "so o trang bi cua Ban Dong Hanh", 0, 0, 0, 1, "ch_chung.lua", "o"},
BDH_CHANNGUYEN_DOI_1_TUCHAN = {"BANDONGHANH", "so diem chan nguyen bo ra de doi lay 1 diem Tu Chan", 0, 0, 0, 2, "ch_chung.lua", ""},
BDH_TUCHAN_TOI_DA = {"BANDONGHANH", "tran diem Tu Chan cua Ban Dong Hanh", 0, 0, 0, 2, "ch_chung.lua", ""},
BDH_SO_LAN_CHO_AN_MOI_NGAY = {"BANDONGHANH", "so lan moi ngay duoc cho an MOI LOAI qua (dem rieng tung loai)", 0, 0, 0, 2, "ch_chung.lua", "lan"},
BDH_GIA_DOI_NGOAI_QUAN = {"BANDONGHANH", "so Xu phai tra de doi ngoai quan", 0, 0, 0, 2, "ch_chung.lua", "luong"},
BDH_GIA_DOI_TEN = {"BANDONGHANH", "so Xu phai tra de doi ten", 0, 0, 0, 2, "ch_chung.lua", "luong"},
BDH_CAP_TOI_DA = {"BANDONGHANH", "cap toi da cua Ban Dong Hanh. !! ten bien nay rat chung - chi doi trong tep petsys\\common.lua", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_BUOC_CAP_NGOAI_QUAN = {"BANDONGHANH", "cu moi bao nhieu cap thi mo them mot nhom ngoai quan", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_CAP_NHANVAT_TOI_THIEU = {"BANDONGHANH", "cap nhan vat toi thieu de tao duoc Ban Dong Hanh", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_CAP_MO_KYNANG_BIKIP = {"BANDONGHANH", "cap Ban Dong Hanh toi thieu de bat dau hoc ky nang tu Bi kip", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_SO_O_KYNANG_TOI_DA = {"BANDONGHANH", "so o ky nang bi dong toi da", 0, 0, 0, 2, "ch_chung.lua", "o"},
BDH_BUOC_CAP_MO_O_KYNANG = {"BANDONGHANH", "cu moi bao nhieu cap thi mo them mot o ky nang", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_KYNANG_BIKIP_CAP_TOI_DA = {"BANDONGHANH", "tran cap MOI ky nang bi kip (nang bang diem Tu Chan)", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BDH_TUCHAN_MOI_CAP_KYNANG = {"BANDONGHANH", "ky nang cap N len N+1 ton N x (so nay) diem Tu Chan", 0, 0, 0, 2, "ch_chung.lua", "cap"},
BHK_PHUT_BOSS_TON_TAI = {"BOSS", "boss song bao lau (phut) roi tu bien mat neu khong ai giet", 0, 0, 0, 2, "ch_chung.lua", "phut"},
BHK_MAU_BOSS_TIEU = {"BOSS", "mau cua Boss Tieu Hoang Kim (ghi chu trong ma: mac dinh cu 8.000.000)", 0, 0, 0, 2, "ch_chung.lua", "mau"},
BHK_MAU_BOSS_DAI = {"BOSS", "mau cua boss dai + boss may chu + boss PLD. !! dang la 1, ghi chu noi mac dinh 18.000.000", 0, 0, 0, 2, "ch_chung.lua", "mau"},
BHK_NETRANH_BOSS = {"BOSS", "chi so ne tranh cua boss - cang cao nguoi choi cang hay danh truot", 0, 0, 0, 2, "ch_chung.lua", ""},
BHK_HOIMAU_BOSS = {"BOSS", "luong mau boss tu hoi moi nhip", 0, 0, 0, 2, "ch_chung.lua", "mau"},
BHK_EXP_NPC_BOSS_DAI = {"BOSS", "exp gan thang vao con NPC boss dai (dang 0 - exp thuong phat o tep death*)", 0, 0, 0, 2, "ch_chung.lua", "exp"},
BHK_EXP_NPC_BOSS_TIEU = {"BOSS", "exp gan thang vao con NPC boss tieu (dang 0)", 0, 0, 0, 2, "ch_chung.lua", "exp"},
CTC_DIEM_PHA_LONGTRU = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", "diem"},
CTC_EXP_TOP10_BANSAO = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", "exp"},
CTC_GIA_LENHBAI = {"CONGTHANH", "doc tai missions\\citywar_global\\head.lua", 0, 0, 0, 2, "ch_chung.lua", "luong"},
CTC_GIA_TRA_LAI_LENHBAI = {"CONGTHANH", "doc tai missions\\citywar_global\\head.lua", 0, 0, 0, 2, "ch_chung.lua", "luong"},
CTC_MAX_LIENMINH_CONG_VEBINH = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_MAX_LIENMINH_THU_VEBINH = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_MAX_NGUOI_PHE_CONG_VEBINH = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", "nguoi"},
CTC_MAX_NGUOI_PHE_THU_VEBINH = {"CONGTHANH", "doc tai tinhnang\\congthanhchien\\lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", "nguoi"},
CTC_CHUKY_LOA_GIAY = {"CONGTHANH", "chu ky loa trong tran: bao nhieu giay bao mot lan tinh hinh", 0, 0, 0, 2, "ch_chung.lua", "giay"},
CTC_DODAI_TRAN_PHUT = {"CONGTHANH", "do dai mot tran Cong Thanh (phut)", 0, 0, 0, 2, "ch_chung.lua", "phut"},
CTC_EXP_TOP10 = {"CONGTHANH", "kinh nghiem thuong cho 10 nguoi dan dau bang cong trang. !! co mot ban nua o lib_ctc.lua", 0, 0, 0, 2, "ch_chung.lua", "exp"},
CTC_SO_LONGTRU = {"CONGTHANH", "so Long Tru trong tran. Pha du ca ba la thang ngay", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_SO_CONG_THANH = {"CONGTHANH", "so cong thanh phai pha. !! phai khop so dong trong bang DoorPos", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_MAX_NGUOI_PHE_THU = {"CONGTHANH", "so nguoi toi da phe THU vao tran (ban CUA TRAN dung). !! NPC ve binh dung so khac", 0, 0, 0, 2, "ch_chung.lua", "nguoi"},
CTC_MAX_NGUOI_PHE_CONG = {"CONGTHANH", "so nguoi toi da phe CONG vao tran (ban CUA TRAN dung)", 0, 0, 0, 2, "ch_chung.lua", "nguoi"},
CTC_MAX_LIENMINH_THU = {"CONGTHANH", "so nguoi ngoai bang tro giup phe THU (ban CUA TRAN dung)", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_MAX_LIENMINH_CONG = {"CONGTHANH", "so nguoi ngoai bang tro giup phe CONG (ban CUA TRAN dung)", 0, 0, 0, 2, "ch_chung.lua", ""},
CTC_CAP_LONGTRU = {"CONGTHANH", "cap do NPC Long Tru khi sinh ra (anh huong mau)", 0, 0, 0, 2, "ch_chung.lua", "cap"},
CTC_CAP_CONG_THANH = {"CONGTHANH", "cap do NPC cong thanh - quyet dinh cong kho pha den dau", 0, 0, 0, 2, "ch_chung.lua", "cap"},
CTC_DIEM_GIET_NGUOI = {"CONGTHANH", "diem cong trang co ban moi lan ha guc doi phuong", 0, 0, 0, 1, "ch_chung.lua", "diem"},
CTC_DIEM_LIEN_TRAM = {"CONGTHANH", "diem thuong moi lan dat moc lien tram", 0, 0, 0, 1, "ch_chung.lua", "diem"},
GLB_GIO_MO_SERVER = {"HETHONG", "moc gio mo cua, dang yymmddHHMM. 7 cho trong game doc de chan nguoi choi", 4, 0, 2359, 2, "ch_chung.lua", "HHMM"},
GLB_CHE_DO_TEST = {"HETHONG", "1 = MO che do thu nghiem. !! Dang mo: hai NPC 'Ho Tro Test' o lang tan thu phat do GM cho MOI nguoi choi. Dat 0 de tat", 3, 0, 1, 2, "ch_chung.lua", ""},
GLB_TILE_TIEN = {"TIEN", "he so nhan tien thuong toan server (1 = giu nguyen)", 0, 0, 0, 2, "ch_chung.lua", "x"},
GLB_TILE_EXP = {"EXP", "he so nhan kinh nghiem toan server. NUT CHINH de dieu chinh toc do len cap", 0, 0, 0, 2, "ch_chung.lua", "x"},
GLB_SATTHUONG_BOSS_HK = {"CHUNG", "he so sat thuong Boss Hoang Kim tieu. (dang tat cung hoat dong)", 3, 0, 1, 2, "ch_chung.lua", ""},
GLB_SATTHUONG_QUAI_PLD = {"CHUNG", "he so sat thuong quai Thuy Tac tren thuyen Phong Lang Do ban Viet cu. (dang tat)", 3, 0, 1, 2, "ch_chung.lua", ""},
GLB_SATTHUONG_BOSS_TTDL = {"CHUNG", "he so sat thuong boss Thuy Tac Dau Linh ban Viet cu. (dang tat)", 3, 0, 1, 2, "ch_chung.lua", ""},
GLB_MANH_BOSS_VUOTAI = {"CHUNG", "he so mau + sat thuong quai va boss Vuot Ai ban Viet cu. (dang tat)", 3, 0, 1, 2, "ch_chung.lua", ""},
GLB_MANH_NGUYENSOAI_TK = {"CHUNG", "he so mau + sat thuong Nguyen Soai hai phe trong Tong Kim - DANG CHAY", 0, 0, 0, 2, "ch_chung.lua", ""},
GLB_MAX_DONG_THUOCTINH = {"CHUNG", "tran so dong thuoc tinh do roi tu quai. !! khong tep script nao doc so nay - so that dang chan nam trong ma C++", 0, 0, 0, 2, "ch_chung.lua", ""},
CH_NAPLAI_PHUT = {"HETHONG", "--------------------------------------------------------------------------- NHIP NAP LAI SCRIPT --------------------------------------------------------------------------- timerserver.lua:40 co dong `dofile(\"script/ti...", 3, 0, 1, 2, "ch_chung.lua", ""},
CH_LOG_CAUHINH = {"HETHONG", "--------------------------------------------------------------------------- GHI LOG --------------------------------------------------------------------------- Bat/tat log cua he cau hinh + he thuong (0/1). Duong log:...", 3, 0, 1, 2, "ch_chung.lua", ""},
CH_LOG_THUONG = {"HETHONG", "--------------------------------------------------------------------------- GHI LOG --------------------------------------------------------------------------- Bat/tat log cua he cau hinh + he thuong (0/1). Duong log:...", 3, 0, 1, 2, "ch_chung.lua", ""},
BOT_TU_GOI = {"CHUNG", "1 = bat toan bo phan tu dong duoi day | 0 = tat het", 3, 0, 1, 1, "ch_chung.lua", ""},
BOT_SO_LUONG = {"CHUNG", "so bot goi khi may chu len (tran engine PB_MAX_BOTS = 1000)", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_CHO_PHUT = {"CHUNG", "doi bao nhieu phut sau khi may chu len roi moi goi (cho Goddess san sang)", 0, 0, 0, 1, "ch_chung.lua", "phut"},
BOT_GOI_GIAN = {"CHUNG", "toi thieu bao nhieu phut giua hai lan xep hang doi sinh bot", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_DA_TAU = {"CHUNG", "so bot di lam Da Tau (CHI chon duoc bot cap >= 70)", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_BAN_SAP = {"CHUNG", "so bot ve thanh bay sap ban hang", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_SAP_NGUONG = {"CHUNG", "sap tut duoi bao nhieu %% so tren thi moi dat lai (dat lai = dep het sap cu)", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_SAP_GIAN = {"CHUNG", "toi thieu bao nhieu phut giua hai lan dat lai ban sap", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_TK_TRAN = {"CHUNG", "tran bot moi tran Tong Kim (0 = khong gioi han)", 0, 0, 0, 1, "ch_chung.lua", ""},
BOT_TK_TU_DONG = {"CHUNG", "1 = bot tu vao Tong Kim THEO GIO | 0 = tat", 3, 0, 1, 1, "ch_chung.lua", ""},
BOT_BAO_PHUT = {"CHUNG", "cu bao nhieu phut in mot dong trang thai [BotAuto] vao logs\\hethong.log (0 = tat)", 0, 0, 0, 1, "ch_chung.lua", "phut"},
BOT_VAO_PHAI = {"CHUNG", "[BOTAUTO3] chu game: bot da tren cap 100, KHONG can vao phai nua (1 = bat lai)", 3, 0, 1, 1, "ch_chung.lua", ""},
BOT_TU_DANH = {"CHUNG", "[BOTAUTO2] 1 = tu BAT DANH QUAI (khong bat thi bot dung yen o thanh)", 3, 0, 1, 1, "ch_chung.lua", ""},
BOT_DANH_GIAN = {"CHUNG", "cu bao nhieu phut goi lai lenh bat danh quai (bat cho bot moi sinh)", 0, 0, 0, 1, "ch_chung.lua", ""},
CTC_CHUKY_QUET_MO_TRAN_PHUT = {"CONGTHANH", "doc tai missions\\citywar_global\\mission.lua", 0, 0, 0, 2, "ch_lich.lua", "phut"},
CTLD_MAX_NGUOI_MOI_PHE = {"LOIDAI", "so nguoi toi da moi bang vao dau truong Loi Dai", 0, 0, 0, 2, "ch_lich.lua", "nguoi"},
CTLD_CHUKY_LOA_GIAY = {"LOIDAI", "chu ky loa trong Loi Dai (giay)", 0, 0, 0, 2, "ch_lich.lua", "giay"},
CTLD_DODAI_TRAN_PHUT = {"LOIDAI", "do dai mot tran Loi Dai (phut). !! chu thich trong ma ghi nham la mot tieng", 0, 0, 0, 2, "ch_lich.lua", "phut"},
CTLD_GIAY_CHO_VAO_DAUTRUONG = {"LOIDAI", "thoi gian cho hai ben vao dau truong (giay). !! chu thich ghi nham la 10 phut", 0, 0, 0, 2, "ch_lich.lua", "giay"},
CTLD_EXP_BANG_THANG = {"LOIDAI", "kinh nghiem bang hoi cong cho ben thang mot tran Loi Dai", 0, 0, 0, 2, "ch_lich.lua", "exp"},
TK_PHUT_BAODANH = {"LICH", "so PHUT bao danh. !! chu thich trong ma ghi 10 - dang chay 1", 0, 0, 0, 2, "ch_lich.lua", "phut"},
TK_PHUT_TRAN = {"LICH", "so PHUT ca tran. !! chu thich trong ma ghi 70 - dang chay 30", 0, 0, 0, 2, "ch_lich.lua", "phut"},
TK_PHUT_NGUYENSOAI = {"LICH", "so PHUT den luc ra Nguyen Soai. !! chu thich ghi 30 - dang chay 1", 0, 0, 0, 2, "ch_lich.lua", "phut"},
TK_PHUT_XOANPC = {"LICH", "so PHUT xoa NPC sau tran", 0, 0, 0, 2, "ch_lich.lua", "phut"},
TK_NGUOI_MOI_PHE = {"LICH", "so nguoi toi da moi phe", 0, 0, 0, 2, "ch_lich.lua", "nguoi"},
BAT_TONGKIM = {"HOATDONG", "Tong Kim", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_HATHUYHOANG = {"HOATDONG", "Ha Thuy Hoang", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_BOSS_HOANGKIM = {"HOATDONG", "Boss Hoang Kim", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_HOADANG = {"HOATDONG", "Hoa Dang / Trang Nguyen", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_TRONG_BANGHOI = {"HOATDONG", "Trong Bang Hoi", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_KIEMMONQUAN = {"HOATDONG", "Kiem Mon Quan", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_VANTIEU_LOA = {"HOATDONG", "loa Van Tieu (NPC van chay khong can khoa nay)", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_DUATOP = {"HOATDONG", "Dua Top", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_SONGBAC = {"HOATDONG", "Song Bac", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_CHECK_KICK = {"HOATDONG", "tu kich tai khoan", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_PUBG = {"HOATDONG", "Sinh Ton (PUBG)", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_HD3 = {"HOATDONG", "cum 3 hoat dong Linux: Sat Thu / Phong Lang Do / Vuot Ai", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_VIEMDE = {"HOATDONG", "Viem De Bao Tang", 3, 0, 1, 1, "ch_lich.lua", ""},
BAT_CTC_JX2 = {"HOATDONG", "Cong Thanh + Loi Dai bang hoi (ban JX2)", 3, 0, 1, 1, "ch_lich.lua", ""},
TBH_PHUT_TRONG_TON_TAI = {"TRONGBANG", "so PHUT trong do bang chu tu danh ra ton tai (ma viet dang 30*60*18 nen day la con so dau)", 0, 0, 0, 2, "ch_thuong.lua", "phut"},
TBH_GIO_MO = {"TRONGBANG", "gio som nhat trong ngay duoc dung Trong Khai Hoan, dang HHMM. !! ten bien trong ma rat chung", 4, 0, 2359, 2, "ch_thuong.lua", "HHMM"},
TBH_GIO_DONG = {"TRONGBANG", "gio muon nhat trong ngay duoc dung Trong Khai Hoan, dang HHMM", 4, 0, 2359, 2, "ch_thuong.lua", "HHMM"},
TBH_EXP_TRAN_NGAY = {"TRONGBANG", "tran exp moi nguoi nhan trong mot ngay tu danh trong bang", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
TBH_EXP_MIN = {"TRONGBANG", "exp thap nhat cho MOI NHIP (mot lan danh co 10 nhip)", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
TBH_EXP_MAX = {"TRONGBANG", "exp cao nhat cho MOI NHIP (mot lan danh co 10 nhip)", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BDH_THOIHAN_DANHHIEU_NGAY = {"BANDONGHANH", "so NGAY danh hieu Ban Dong Hanh ton tai (ma viet dang 30*24*60*60*18*36 nen day la con so dau tien). !! khai lai y het o partner_reward2.lua", 0, 0, 0, 2, "ch_thuong.lua", "ngay"},
BHK_EXP_GIET_BOSS_PLD = {"BOSS", "exp cho nguoi ha Boss Hoang Kim ban do Phong Lang Do", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BHK_EXP_LANCAN_BOSS_PLD = {"BOSS", "exp cho nguoi dung gan cho ha boss Phong Lang Do", 0, 0, 0, 2, "ch_thuong.lua", "lan"},
BHK_PHAMVI_HUONG_EXP_PLD = {"BOSS", "ban kinh chia exp quanh xac boss Phong Lang Do", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BHK_EXP_GIET_BOSS_DAI = {"BOSS", "exp cho nguoi ha Boss Dai Hoang Kim va to doi cua ho", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BHK_EXP_LANCAN_BOSS_DAI = {"BOSS", "exp cho nguoi dung gan cho ha boss dai nhung khac to doi", 0, 0, 0, 2, "ch_thuong.lua", "lan"},
BHK_PHAMVI_HUONG_EXP_DAI = {"BOSS", "ban kinh chia exp quanh xac boss dai", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BHK_EXP_GIET_BOSS_TIEU = {"BOSS", "exp cho nguoi ha Boss Tieu Hoang Kim va to doi cua ho", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
BHK_EXP_LANCAN_BOSS_TIEU = {"BOSS", "exp cho nguoi dung gan cho danh boss tieu nhung khac to doi", 0, 0, 0, 2, "ch_thuong.lua", "lan"},
BHK_PHAMVI_HUONG_EXP_TIEU = {"BOSS", "ban kinh quanh xac boss ma nguoi choi phai dung trong do moi duoc chia exp (boss tieu)", 0, 0, 0, 2, "ch_thuong.lua", "exp"},
TKT_GIA_DOI_NHACVUONGKIEM = {"TONGKIM", "so tien can de doi Nhac Vuong Kiem", 0, 0, 0, 2, "ch_thuong.lua", "luong"},
TKT_PHI_TRINHSAT = {"TONGKIM", "phi moi lan dung chuc nang trinh sat", 0, 0, 0, 2, "ch_thuong.lua", "luong"},
TKT_SL_HONTHACH_DOI_KIEM = {"TONGKIM", "so Nhac Vuong Hon Thach can de doi mot Nhac Vuong Kiem", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_CAP_TOI_THIEU = {"TONGKIM", "cap toi thieu moi duoc bao danh", 0, 0, 0, 2, "ch_thuong.lua", "cap"},
TKT_LECH_QUANSO_TOIDA = {"TONGKIM", "chenh lech quan so toi da giua hai phe; qua muc nay phe dong hon bi chan bao danh", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_PHI_BAO_DANH = {"TONGKIM", "phi bao danh. !! hien CHI HIEN CHU, khong tru tien - moi lenh Pay da bi comment", 0, 0, 0, 2, "ch_thuong.lua", "luong"},
TKT_THUONG_TICHLUY_THANG = {"TONGKIM", "diem tich luy cong them cho phe THANG, nhan voi cap quan ham 1-6", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_THUONG_TICHLUY_THUA = {"TONGKIM", "diem tich luy cong them cho phe THUA, nhan voi cap quan ham", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_THUONG_TICHLUY_HOA = {"TONGKIM", "diem tich luy cong them khi tran HOA, nhan voi cap quan ham", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_DIEM_TOITHIEU_NHAN_THUONG = {"TONGKIM", "duoi nguong diem nay thi het tran KHONG duoc goi qua", 0, 0, 0, 2, "ch_thuong.lua", "diem"},
TKT_SO_CO_TOIDA = {"TONGKIM", "moi phe chi duoc cam toi da bay nhieu la co trong mot tran", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_DIEM_CAM_CO = {"TONGKIM", "diem moi lan mang co ve cam thanh cong (cong ca ca nhan lan phe)", 0, 0, 0, 2, "ch_thuong.lua", "diem"},
TKT_MUC_GIAM_TOCDO_GIU_CO = {"TONGKIM", "muc giam toc do chay cua nguoi dang vac co", 0, 0, 0, 2, "ch_thuong.lua", ""},
TKT_GIAY_TRONG_DOANHTRAI = {"TONGKIM", "so GIAY toi da duoc dung trong doanh trai truoc khi bi day ra", 0, 0, 0, 2, "ch_thuong.lua", "giay"},
TKT_GIAY_DELAY_RA_TRAI = {"TONGKIM", "so GIAY con lai duoc giu khi buoc ra khoi trai", 0, 0, 0, 2, "ch_thuong.lua", "giay"},
TKT_MAU_NGUYENSOAI = {"TONGKIM", "mau cua Nguyen Soai hai phe. !! con duoc nhan them voi GLB_MANH_NGUYENSOAI_TK", 0, 0, 0, 2, "ch_thuong.lua", "mau"},
TKT_DIEM_GIET_NGUYENSOAI = {"TONGKIM", "diem cho nguoi ha guc Nguyen Soai (nguoi danh don cuoi an tron)", 0, 0, 0, 2, "ch_thuong.lua", "diem"},
VT_EXP_NEN_LAN = {"VANTIEU", "so lan cong exp nen", 0, 0, 0, 1, "ch_thuong.lua", "lan"},
VT_EXP_NEN_MOI = {"VANTIEU", "moi lan cong bao nhieu (1000 x 50.000 = 50 trieu)", 0, 0, 0, 1, "ch_thuong.lua", "exp"},
VT_EXP_NEN_SUM = {"VANTIEU", "exp nen cong THEM (thong bao chi ghi 50.000.000)", 0, 0, 0, 1, "ch_thuong.lua", "exp"},
VT_EXP_DONG = {"VANTIEU", "tieu dong: exp cong them (thong bao ghi 10.000.000)", 0, 0, 0, 1, "ch_thuong.lua", "exp"},
VT_EXP_BAC = {"VANTIEU", "tieu bac: exp cong them (thong bao ghi 30.000.000)", 0, 0, 0, 1, "ch_thuong.lua", "exp"},
VT_EXP_VANG = {"VANTIEU", "tieu vang: exp cong them (thong bao ghi 50.000.000)", 0, 0, 0, 1, "ch_thuong.lua", "exp"},
VT_HOMACH_DONG = {"VANTIEU", "tieu dong: so Ho Mach Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_CHANNGUYEN_DONG = {"VANTIEU", "tieu dong: so Chan Nguyen Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_RUONG_DONG = {"VANTIEU", "tieu dong: so ruong trang bi xanh", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_HOMACH_BAC = {"VANTIEU", "tieu bac: so Ho Mach Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_CHANNGUYEN_BAC = {"VANTIEU", "tieu bac: so Chan Nguyen Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_RUONG_BAC = {"VANTIEU", "tieu bac: so ruong trang bi xanh", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_HOMACH_VANG = {"VANTIEU", "tieu vang: so Ho Mach Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_CHANNGUYEN_VANG = {"VANTIEU", "tieu vang: so Chan Nguyen Don", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_RUONG_VANG = {"VANTIEU", "tieu vang: so ruong trang bi xanh", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_LENHBAI_BOSS = {"VANTIEU", "so Lenh Bai Boss moi chuyen (moi loai tieu)", 0, 0, 0, 1, "ch_thuong.lua", ""},
VT_DIEM_TONG_DONG = {"VANTIEU", "tieu dong: diem cong cho bang hoi", 0, 0, 0, 1, "ch_thuong.lua", "diem"},
VT_DIEM_TONG_BAC = {"VANTIEU", "tieu bac: diem cong cho bang hoi", 0, 0, 0, 1, "ch_thuong.lua", "diem"},
VT_DIEM_TONG_VANG = {"VANTIEU", "tieu vang: diem cong cho bang hoi", 0, 0, 0, 1, "ch_thuong.lua", "diem"},
BRXP_MOC_CS = {"EXP", "moc chuyen sinh: <= so nay dung tran CS4, +1 dung CS5", 0, 0, 0, 1, "ch_exp.lua", ""},
BRXP_TRAN_CS4 = {"EXP", "tran exp/ngay tu MOI bao ruong (trieu) - chuyen sinh thap", 0, 0, 0, 1, "ch_exp.lua", ""},
BRXP_TRAN_CS5 = {"EXP", "tran exp/ngay (trieu) - chuyen sinh dung moc+1", 0, 0, 0, 1, "ch_exp.lua", ""},
BRXP_TRAN_CS6 = {"EXP", "tran exp/ngay (trieu) - chuyen sinh cao hon", 0, 0, 0, 1, "ch_exp.lua", ""},
DRQ_HESO_TIEN = {"ROTDO", "nhan vao so tien quai roi ra", 0, 0, 0, 1, "ch_drop.lua", "x"},
DRQ_CAP_BAC_TOITHIEU = {"ROTDO", "duoi cap nay thi xep vao bac 1", 0, 0, 0, 1, "ch_drop.lua", "cap"},
DRQ_CAP_BAC_TOIDA = {"ROTDO", "tren cap nay thi boc ngau nhien bac 9-10", 0, 0, 0, 1, "ch_drop.lua", "cap"},
DRQ_QUAY_BOSSXANH = {"ROTDO", "boss xanh: so mon roi ra moi lan chet", 0, 0, 0, 1, "ch_drop.lua", ""},
DRQ_MAU_BOSSXANH = {"ROTDO", "boss xanh: mau so cua phep boc tien", 0, 0, 0, 1, "ch_drop.lua", "mau"},
DRQ_NGUONG_TIEN_BOSSXANH = {"ROTDO", "boss xanh: vuot nguong nay moi roi tien (mau 10 => ~18%)", 0, 0, 0, 1, "ch_drop.lua", "luong"},
DRQ_MAU_QUAI = {"ROTDO", "quai thuong: mau so cua phep boc", 0, 0, 0, 1, "ch_drop.lua", "mau"},
DRQ_NGUONG_TIEN = {"ROTDO", "quai thuong: trung dung so nay thi roi tien (mau 30 => ~3,2%). Dat -1 de tat han", 0, 0, 0, 1, "ch_drop.lua", "luong"},
DRQ_NGUONG_ITEM = {"ROTDO", "quai thuong: duoi so nay thi quay bang rot do (mau 30 => 2/31 sau khi tru nhanh tien)", 0, 0, 0, 1, "ch_drop.lua", ""},
DRQ_QUAY_QUAI = {"ROTDO", "quai thuong: so mon roi ra moi lan trung", 0, 0, 0, 1, "ch_drop.lua", ""},
DRQ_MAU_SUKIEN = {"ROTDO", "mau so cua phep boc goi dropeventmap", 0, 0, 0, 1, "ch_drop.lua", "mau"},
DRQ_CAP_SUKIEN = {"ROTDO", "quai tu bac nay tro len moi goi nhanh su kien", 0, 0, 0, 1, "ch_drop.lua", "cap"},
DRQ_NGUONG_SUKIEN = {"ROTDO", "duoi so nay thi goi dropeventmap (mau 4 => 40%). Dat -1 de tat han", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_RANDMAP = {"ROTDO", "mau so cho dropeventmap/HCNT/HMD/manhhkmp", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_RANDPLD = {"ROTDO", "mau so nhanh Phong Lang Do (ham than rong)", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_RANDOTHER = {"ROTDO", "mau so cho dropeventboss / dropntiendong", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_RANDTK = {"ROTDO", "mau so nhanh Tong Kim (ham than rong)", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_RANDVA = {"ROTDO", "mau so nhanh Vuot Ai (ham than rong)", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_DROPMDTB = {"ROTDO", "mau so cho dropnvdt / dropnvdt01", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_MAP_NGUONG = {"ROTDO", "vuot nguong nay moi rot (mau 100 => con 20%)", 0, 0, 0, 1, "ch_drop.lua", "map"},
SKD_MAP_ITEM = {"ROTDO", "ma vat pham rot theo su kien tren ban do", 0, 0, 0, 1, "ch_drop.lua", "map"},
SKD_HCNT_NGUONG = {"ROTDO", "Hiep Cot Nhu Tinh: vuot nguong moi rot (=> 50%)", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_HCNT_MA_MIN = {"ROTDO", "dai ma trang bi Hiep Cot Nhu Tinh - dau", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_HCNT_MA_MAX = {"ROTDO", "dai ma trang bi Hiep Cot Nhu Tinh - cuoi", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_PUBG_MA_MIN = {"ROTDO", "dai ma vat pham Sinh Ton - dau", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_PUBG_MA_MAX = {"ROTDO", "dai ma vat pham Sinh Ton - cuoi", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_HKMP_MA_MIN = {"ROTDO", "dai ma trang bi Hoang Kim Mon Phai - dau", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_HKMP_MA_MAX = {"ROTDO", "dai ma trang bi Hoang Kim Mon Phai - cuoi", 0, 0, 0, 2, "ch_drop.lua", ""},
SKD_HKMP_HAN_NGAY = {"ROTDO", "so ngay ton tai cua trang bi HKMP rot ra", 0, 0, 0, 2, "ch_drop.lua", "ngay"},
SKD_HMD_NGUONG = {"ROTDO", "Huy Hoang Don: vuot nguong moi rot (mau 100 => dang la 99%)", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_HMD_SOLUONG = {"ROTDO", "moi lan rot bao nhieu Huy Hoang Don", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_HMD_ITEM = {"ROTDO", "ma Huy Hoang Don", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_MANHHKMP_NGUONG = {"ROTDO", "manh do pho HKMP: duoi nguong nay thi rot (mau 100 => dang la 79%)", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_BOSS_NGUONG = {"ROTDO", "boss su kien: vuot nguong moi rot (mau 10 => dang la 90%)", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_BOSS_MA_MIN = {"ROTDO", "dai ma trang bi boss su kien - dau", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_BOSS_MA_MAX = {"ROTDO", "dai ma trang bi boss su kien - cuoi", 0, 0, 0, 1, "ch_drop.lua", ""},
SKD_TIENDONG_NGUONG = {"ROTDO", "Tien Dong: vuot nguong moi rot (mau 10 => dang la 90%)", 0, 0, 0, 1, "ch_drop.lua", "luong"},
SKD_TIENDONG_SL_MIN = {"ROTDO", "so Tien Dong moi lan - it nhat", 0, 0, 0, 2, "ch_drop.lua", "luong"},
SKD_TIENDONG_SL_MAX = {"ROTDO", "so Tien Dong moi lan - nhieu nhat", 0, 0, 0, 2, "ch_drop.lua", "luong"},
SKD_TIENDONG_ITEM = {"ROTDO", "ma Tien Dong", 0, 0, 0, 1, "ch_drop.lua", "luong"},
TW_CAP_TOITHIEU = {"BANGCHIEN", "Cap toi thieu de bao danh + vao dau truong. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
TW_GIO_KHAICHIEN = {"BANGCHIEN", "Gio khai chien / gio dong tran, dang HHMM (2000 = 20:00, 2130 = 21:30). Driver tick 15 phut mot lan, cua so khop +-5 phut quanh moc. [LIVE] LUU Y: text NPC o event\\tongwar\\head.lua:492 dang ghi \"08:00~08:29 / 08:30~09...", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
TW_GIO_KETTHUC = {"BANGCHIEN", "Gio khai chien / gio dong tran, dang HHMM (2000 = 20:00, 2130 = 21:30). Driver tick 15 phut mot lan, cua so khop +-5 phut quanh moc. [LIVE] LUU Y: text NPC o event\\tongwar\\head.lua:492 dang ghi \"08:00~08:29 / 08:30~09...", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
TW_PHUT_TRAN = {"BANGCHIEN", "Do dai tran (phut) va thoi gian chuan bi truoc khai chien (phut). [RESTART] Nen de TW_PHUT_TRAN khop voi (TW_GIO_KETTHUC - TW_GIO_KHAICHIEN).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
TW_PHUT_CHUANBI = {"BANGCHIEN", "Do dai tran (phut) va thoi gian chuan bi truoc khai chien (phut). [RESTART] Nen de TW_PHUT_TRAN khop voi (TW_GIO_KETTHUC - TW_GIO_KHAICHIEN).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
TW_NGUOI_TOIDA = {"BANGCHIEN", "Nguoi moi phe: tran vao tran + so nguoi toi thieu (duoi muc = xu thua).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "nguoi"},
TW_NGUOI_TOITHIEU = {"BANGCHIEN", "Nguoi moi phe: tran vao tran + so nguoi toi thieu (duoi muc = xu thua).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "nguoi"},
TW_GIAY_HAUDOANH = {"BANGCHIEN", "So giay toi da nam o hau doanh (qua = day ra ngoai). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "giay"},
TW_SO_MANG = {"BANGCHIEN", "So mang chet toi da 1 tran (du = bi loai khoi tran). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "mang"},
TW_DIEM_KILL = {"BANGCHIEN", "Diem cong khi giet 1 dich (nhan he so quan ham RANK_PKBONUS o missions\\tongwar\\head.lua:44) va thuong lien tram (moi 3 mang lien tiep).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "diem"},
TW_DIEM_LIENTRAM = {"BANGCHIEN", "Diem cong khi giet 1 dich (nhan he so quan ham RANK_PKBONUS o missions\\tongwar\\head.lua:44) va thuong lien tram (moi 3 mang lien tiep).", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "diem"},
TS_CAP_TOITHIEU = {"THANHBAO", "CÊp tèi thiÓu nhËn nhiÖm vô (gèc Linux 120, chñ game ®· h¹ 90). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "cap"},
TS_LUOT_THUONG_NGAY = {"THANHBAO", "Sè l­ît th­êng/ngµy + sè l­ît mua thªm b»ng item Thiªn Khè B¶o LÖnh (6,1,3431). ®Õm theo ngµy ë task 4128. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "ngay"},
TS_LUOT_ITEM_NGAY = {"THANHBAO", "Sè l­ît th­êng/ngµy + sè l­ît mua thªm b»ng item Thiªn Khè B¶o LÖnh (6,1,3431). ®Õm theo ngµy ë task 4128. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "ngay"},
TS_TRA_HANHHIEP = {"THANHBAO", "Th­ëng khi TR¶ nhiÖm vô ë tr¹m dÞch (posthouse.lua, hµm messenger_treasureprize): lÇn ®ÇU trong ngµy: TS_TRA_HANHHIEP c¸i Hµnh HiÖp LÖnh (6,1,2575) MäI lÇn tr¶: TS_TRA_BAORUONG c¸i TÝn Sø B¶o R­¬ng (6,1,3430) (riªng n...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
TS_TRA_BAORUONG = {"THANHBAO", "Th­ëng khi TR¶ nhiÖm vô ë tr¹m dÞch (posthouse.lua, hµm messenger_treasureprize): lÇn ®ÇU trong ngµy: TS_TRA_HANHHIEP c¸i Hµnh HiÖp LÖnh (6,1,2575) MäI lÇn tr¶: TS_TRA_BAORUONG c¸i TÝn Sø B¶o R­¬ng (6,1,3430) (riªng n...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
BR_CAP_TOITHIEU = {"BACHNHAN", "Cap toi thieu. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
BR_GIO_MO = {"BACHNHAN", "Gio mo trong ngay dang HHMM (1200 = 12:00 trua) va gio dong dang GIO (0 = 0h dem - tra nguoi ve). [LIVE]", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
BR_GIO_DONG_H = {"BACHNHAN", "Gio mo trong ngay dang HHMM (1200 = 12:00 trua) va gio dong dang GIO (0 = 0h dem - tra nguoi ve). [LIVE]", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
BR_PHUT_CHUKY_EXP = {"BACHNHAN", "Exp moi tick: chu ky (phut), exp nguoi trong map, exp CONG THEM cho Loi Chu dang giu dai. Co buff Co Thu thi exp thuong x2. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "phut"},
BR_EXP_TICK = {"BACHNHAN", "Exp moi tick: chu ky (phut), exp nguoi trong map, exp CONG THEM cho Loi Chu dang giu dai. Co buff Co Thu thi exp thuong x2. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "exp"},
BR_EXP_LOICHU = {"BACHNHAN", "Exp moi tick: chu ky (phut), exp nguoi trong map, exp CONG THEM cho Loi Chu dang giu dai. Co buff Co Thu thi exp thuong x2. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "exp"},
BR_TRAN_LUOT_NGAY = {"BACHNHAN", "Tran so tick exp / nguoi / ngay (task daily 2709). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "ngay"},
BR_PHUT_COTHU = {"BACHNHAN", "NPC Co Thu (phat buff x2): chu ky xuat hien (phut) va ti le so nguoi duoc buff moi dot (0.2 = 20%). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "phut"},
BR_TILE_BUFFX2 = {"BACHNHAN", "NPC Co Thu (phat buff x2): chu ky xuat hien (phut) va ti le so nguoi duoc buff moi dot (0.2 = 20%). [LIVE]", 1, 0, 0, 1, "cauhinh_hoatdong.lua", "x"},
BR_GIAY_CHO_KHIEUCHIEN = {"BACHNHAN", "Nhip dau: giay cho nguoi khieu chien (het gio -> goi NPC cao thu), giay dem nguoc truoc khi danh, phut moi luot dau (het gio -> so sat thuong, Loi Chu thang neu chiu it sat thuong hon). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "giay"},
BR_GIAY_DEM_NGUOC = {"BACHNHAN", "Nhip dau: giay cho nguoi khieu chien (het gio -> goi NPC cao thu), giay dem nguoc truoc khi danh, phut moi luot dau (het gio -> so sat thuong, Loi Chu thang neu chiu it sat thuong hon). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "giay"},
BR_PHUT_MOI_LUOT = {"BACHNHAN", "Nhip dau: giay cho nguoi khieu chien (het gio -> goi NPC cao thu), giay dem nguoc truoc khi danh, phut moi luot dau (het gio -> so sat thuong, Loi Chu thang neu chiu it sat thuong hon). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
BR_PHUT_DUNG_YEN = {"BACHNHAN", "Phut dung yen toi da (bi da ra) va phut hieu luc buff x2. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
BR_PHUT_BUFF_X2 = {"BACHNHAN", "Phut dung yen toi da (bi da ra) va phut hieu luc buff x2. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
BR_TRAN_CHUOI = {"BACHNHAN", "Chuoi thang toi da 1 doi (den muc = loa \"truyen thuyet\" + reset). Moi 10 tran thang o dai 1 se loa toan server. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
BR_CAP_NPC_GOC = {"BACHNHAN", "Cap goc NPC cao thu (cap that = goc + so_luot_thang/10, tran goc+9). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
BR_NPC_MAP = {"BACHNHAN", "NPC loi vao (dat luc boot): map / template / cap. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "map"},
BR_NPC_ID = {"BACHNHAN", "NPC loi vao (dat luc boot): map / template / cap. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
BR_NPC_LEVEL = {"BACHNHAN", "NPC loi vao (dat luc boot): map / template / cap. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
BW_CAP_TOITHIEU = {"TYVO", "(khong co lich - mo ca ngay; 2 doi truong bao danh la mo tran) Cap toi thieu (khan gia khong bi chan). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
BW_DOI_TOIDA = {"TYVO", "So nguoi toi da moi doi (menu NPC hien \"1 vs 1\"..\"8 vs 8\" - neu tang qua 8 thi menu van chi hien 8 lua chon, sua them text o bwmanager.lua:55). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
BW_PHUT_CHO = {"TYVO", "Phut cho truoc khi danh (mac dinh 2) va tong phut 1 tran ke ca cho (mac dinh 12 = 2 cho + 10 danh). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
BW_PHUT_TRAN = {"TYVO", "Phut cho truoc khi danh (mac dinh 2) va tong phut 1 tran ke ca cho (mac dinh 12 = 2 cho + 10 danh). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
TC_CAP_TOITHIEU = {"THANHBAO", "!! CLIENT CHUA CO DU LIEU MAP 984 - nguoi choi chua vao duoc map cho den khi chu game bo sung pak client (server da san sang). Cap toi thieu + so phut phai vao bang truoc khi tham gia (1440 = 1 ngay).", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
TC_VAO_BANG_PHUT = {"THANHBAO", "!! CLIENT CHUA CO DU LIEU MAP 984 - nguoi choi chua vao duoc map cho den khi chu game bo sung pak client (server da san sang). Cap toi thieu + so phut phai vao bang truoc khi tham gia (1440 = 1 ngay).", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "phut"},
TC_THU = {"THANHBAO", "Thu mo cua trong tuan: 0 = Chu nhat, 1 = Thu hai ... 6 = Thu bay. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
TC_GIO_NHANDIEM_TU = {"THANHBAO", "Khung nhan diem Than Moc (HHMM) + so phut luu tru toi thieu. [LIVE]", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
TC_GIO_NHANDIEM_DEN = {"THANHBAO", "Khung nhan diem Than Moc (HHMM) + so phut luu tru toi thieu. [LIVE]", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
TC_PHUT_TOITHIEU = {"THANHBAO", "Khung nhan diem Than Moc (HHMM) + so phut luu tru toi thieu. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "phut"},
TC_GIA_LENH_1 = {"THANHBAO", "Gia doi Than Moc Lenh (diem Than Moc): 3205 Thanh Dong / 3206 Bach Ngan / 3207 Hoang Kim; tran so lenh doi 1 lan; tran moi loai / tuan. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
TC_GIA_LENH_2 = {"THANHBAO", "Gia doi Than Moc Lenh (diem Than Moc): 3205 Thanh Dong / 3206 Bach Ngan / 3207 Hoang Kim; tran so lenh doi 1 lan; tran moi loai / tuan. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
TC_GIA_LENH_3 = {"THANHBAO", "Gia doi Than Moc Lenh (diem Than Moc): 3205 Thanh Dong / 3206 Bach Ngan / 3207 Hoang Kim; tran so lenh doi 1 lan; tran moi loai / tuan. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
TC_DOI_LENH_TOIDA = {"THANHBAO", "Gia doi Than Moc Lenh (diem Than Moc): 3205 Thanh Dong / 3206 Bach Ngan / 3207 Hoang Kim; tran so lenh doi 1 lan; tran moi loai / tuan. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
TC_LENH_TUAN = {"THANHBAO", "Gia doi Than Moc Lenh (diem Than Moc): 3205 Thanh Dong / 3206 Bach Ngan / 3207 Hoang Kim; tran so lenh doi 1 lan; tran moi loai / tuan. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
TC_GIA_BUA = {"THANHBAO", "Bua trieu Thu Ve 3204: gia (diem Than Moc), tran mua 1 lan, tran tong so Thu Ve dung trong map, ban kinh phai dung gan cay (met). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
TC_MUA_BUA_TOIDA = {"THANHBAO", "Bua trieu Thu Ve 3204: gia (diem Than Moc), tran mua 1 lan, tran tong so Thu Ve dung trong map, ban kinh phai dung gan cay (met). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
TC_TRAN_THUVE = {"THANHBAO", "Bua trieu Thu Ve 3204: gia (diem Than Moc), tran mua 1 lan, tran tong so Thu Ve dung trong map, ban kinh phai dung gan cay (met). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
TC_BANKINH_BUA = {"THANHBAO", "Bua trieu Thu Ve 3204: gia (diem Than Moc), tran mua 1 lan, tran tong so Thu Ve dung trong map, ban kinh phai dung gan cay (met). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
HD3_ST_CAP_TOITHIEU = {"HOATDONG", "---- (A) SAN BOSS SAT THU ---- Cap toi thieu - CHI HIEN THI tren menu admin (ban Linux khong chan cap o buoc nhan nhiem vu; nhom boss chia theo cap 20..90 san trong killbosshead). [HIEN THI]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
HD3_ST_MAX_NGAY = {"HOATDONG", "---- (A) SAN BOSS SAT THU ---- Cap toi thieu - CHI HIEN THI tren menu admin (ban Linux khong chan cap o buoc nhan nhiem vu; nhom boss chia theo cap 20..90 san trong killbosshead). [HIEN THI] Tran so lan giet boss / ng...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "ngay"},
HD3_BD_BAT = {"HOATDONG", "---- (B) PHONG LANG DO ---- Cap toi thieu - CHI HIEN THI (ban Linux chi doi co mon phai, fld_head.lua:40). [HIEN THI] BAC DAU LENH BAI (he gom lenh bai tu cac hoat dong roi doi thuong) 1 = bat he Bac Dau, 0 = tat han ...", 3, 0, 1, 1, "cauhinh_hoatdong.lua", ""},
HD3_BD_GIO_MO = {"HOATDONG", "Khung gio NPC Bac Dau lam viec (gio may chu). Ban Linux: 8 den 22.", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
HD3_BD_GIO_DONG = {"HOATDONG", "Khung gio NPC Bac Dau lam viec (gio may chu). Ban Linux: 8 den 22.", 4, 0, 2359, 1, "cauhinh_hoatdong.lua", "HHMM"},
HD3_BD_CAP_TOITHIEU = {"HOATDONG", "Cap toi thieu (hoac da trung sinh). Ban Linux: 150.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
HD3_BD_SO_LAN_NGAY = {"HOATDONG", "So lan nhan nhiem vu Bac Dau moi ngay. Ban Linux: 30.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "lan"},
HD3_BD_EXP_NHIEMVU = {"HOATDONG", "Kinh nghiem thuong moi nhiem vu di duong. Ban Linux: 8.000.000.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "exp"},
HD3_BD_HAN_LENHBAI = {"HOATDONG", "Han dung cua lenh bai (phut). Ban Linux: 1440 = 1 ngay.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
HD3_BD_LINHDAN_NGAY = {"HOATDONG", "So lan dung Bac Dau Huyet Linh Don moi ngay. Ban Linux: 15.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "ngay"},
HD3_BD_QUYDOI_LENHBAI = {"HOATDONG", "1 = hoat dong phat KEM 1 'Lenh bai Bac Dau' (ma dung de doi thuong 15/20) ben canh lenh bai rieng cua hoat dong. 0 = y het ban Linux: hoat dong CHI phat lenh bai rieng - ma 13 lenh bai rieng do KHONG CHO NAO TIEU nen ...", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
HD3_BD_LENHBAI_RIENG = {"HOATDONG", "Co phat them 'Lenh bai Bac Dau - <ten hoat dong>' rieng khong. 0 = KHONG (mac dinh): moi hoat dong chi cho 1 'Lenh bai Bac Dau' - ma nay xep chong 50 cai/o va la ma DUY NHAT dung de doi thuong 15/20. 1 = CO, dung y ba...", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
HD3_PLD_CAP_TOITHIEU = {"HOATDONG", "", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
HD3_PLD_SUC_CHUA = {"HOATDONG", "Gio mo trong ngay (dang HHMM, moi so = 1 luot dua). Ban Linux relay chay MOI GIO dung phut :00 (24 luot/ngay) - DUNG 100% Linux (TaskList.ini Task_86 dang ky ban interval 60; cac tep _NN00 gio chan KHONG duoc dang ky)...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
HD3_VA_CAP_TOITHIEU = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
HD3_VA_PHUT_BAODANH = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI] Gio bao danh (HHMM) - Linux relay chay moi gio phut :...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
HD3_VA_PHUT_NHIEMVU = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI] Gio bao danh (HHMM) - Linux relay chay moi gio phut :...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
HD3_VA_NGUOI_TOIDA = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI] Gio bao danh (HHMM) - Linux relay chay moi gio phut :...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "nguoi"},
HD3_VA_GIO_XEPHANG = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI] Gio bao danh (HHMM) - Linux relay chay moi gio phut :...", 4, 0, 2359, 2, "cauhinh_hoatdong.lua", "HHMM"},
HD3_VA_LUOT_NGAY = {"HOATDONG", "---- (C) VUOT AI ---- Cap toi thieu - CHI HIEN THI (gioi han that = tbLevels trong include.lua: so cap 50-89, cao cap 90+; doi o day KHONG co tac dung). [HIEN THI] Gio bao danh (HHMM) - Linux relay chay moi gio phut :...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "ngay"},
HD3_ST_HESO_EXP = {"HOATDONG", "(A) SAT THU - bang thuong hoan thanh nhom cap 90 (25 dong vat pham + 10.000.000 exp). Goc: kill_level.lua:89-118 OnFinishKillerTask. [RESTART] (A) SAT THU - THUONG MOI LAN GIET 1 BOSS (add_shashouling): * He so % kinh...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "x"},
HD3_ST_EXP_QUAY = {"HOATDONG", "(A) SAT THU - bang thuong hoan thanh nhom cap 90 (25 dong vat pham + 10.000.000 exp). Goc: kill_level.lua:89-118 OnFinishKillerTask. [RESTART] (A) SAT THU - THUONG MOI LAN GIET 1 BOSS (add_shashouling): * He so % kinh...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "exp"},
HD3_ST_SO_LENH = {"HOATDONG", "", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
HD3_ST_TIEN_XE = {"HOATDONG", "* Bang kinh nghiem theo nhom cap - nil = dung so goc ban Linux. Muon doi: HD3_ST_EXP = {[20]=15000, [30]=20000, [40]=30000, [50]=50000, (A) SAT THU - gia thue xe toi cho boss khi bam dan duong tren F11 (khuon cu cua b...", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
HD3_PLD_CO_THUYENPHU_BAC = {"HOATDONG", "(B) PLD - so Thi Gia Chi An (6,1,1095) roi tu boss dau linh 725 (goc 2; bang co Dao Chu tien dai thi tu x2 theo getSignetDropRate). [RESTART] Co sinh thuyen phu o BO BAC khong. Ban Linux KHONG co (chi 3 ben bo Nam); 1...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
HD3_PLD_PHI_VENAM = {"HOATDONG", "Phi qua song cua thuyen phu bo Bac (quan tien). Du an cu: 1000.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "luong"},
HD3_PLD_SO_AN_BOSS = {"HOATDONG", "", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
HD3_PLD_TILE_HAILONG = {"HOATDONG", "(B) PLD - ti le roi Hai Long Chau 6,1,2124 tu boss (goc 0.005 = 0,5%). [RESTART]", 1, 0, 0, 2, "cauhinh_hoatdong.lua", "x"},
HD3_PLD_TILE_TRUYCONG = {"HOATDONG", "(B) PLD - ti le roi Hai Long Chau 6,1,2124 tu boss (goc 0.005 = 0,5%). [RESTART] (B) PLD - ti le roi Truy Cong Lenh 6,1,2024 tu Thuy tac thuong trong gio su kien (goc: nCurRate < 50 tren random(1,100) = 49%). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "x"},
HD3_PLD_TILE_TRUYCONG_BOSS = {"HOATDONG", "Ti le phan tram roi Truy Cong Lenh tu BOSS dau linh (moi con, khi trong gio hoat dong). 100 = luon roi, dung y ban Linux. Ha xuong neu thay ra qua nhieu.", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "x"},
HD3_PLD_THUONG_CAPBEN = {"HOATDONG", "Ti le phan tram roi Truy Cong Lenh tu BOSS dau linh (moi con, khi trong gio hoat dong). 100 = luon roi, dung y ban Linux. Ha xuong neu thay ra qua nhieu. (B) PLD - so Bao Ruong Thuy Tac 6,1,3361 khi cap ben thanh cong...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "cap"},
HCD_EXP = {"HOATDONG", "Exp Hoang Chan Don 2273 (duong exp CO tran cap 200). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "exp"},
QDHK_EXP = {"HOATDONG", "Exp Hoang Chan Don 2273 (duong exp CO tran cap 200). [LIVE] Exp Qua Dai Hoang Kim 4864 (duong exp thuong). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "exp"},
YDBZ_BAT = {"VIEMDE", "Bat/tat toan bo tinh nang. 0 = tat han (driver khong lam gi). [RESTART]", 3, 0, 1, 2, "cauhinh_hoatdong.lua", ""},
YDBZ_GIO = {"VIEMDE", "Gio mo bao danh, dang HHMM cach nhau bang dau phay. Goc Linux: gateway\\s3relay\\relaysetting\\task\\baotangviemde\\*.lua TaskTime(8,25) (10,25) (14,25) (16,25) (18,25) (20,25) (22,25). [LIVE]", 2, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
YDBZ_CAP_TOITHIEU = {"VIEMDE", "Cap toi thieu de bao danh. Goc: head.lua:48 = 120. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "cap"},
YDBZ_LAN_TUAN = {"VIEMDE", "Tran so lan tham gia trong TUAN / trong NGAY. Goc: head.lua:49 = 10, :50 = 4. Mang Viem De Lenh thi duoc mien tran (dung y ban goc). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "lan"},
YDBZ_LAN_NGAY = {"VIEMDE", "Tran so lan tham gia trong TUAN / trong NGAY. Goc: head.lua:49 = 10, :50 = 4. Mang Viem De Lenh thi duoc mien tran (dung y ban goc). [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "lan"},
YDBZ_DOI_MIN = {"VIEMDE", "So nguoi trong to doi: it nhat / nhieu nhat. Goc: readymap\\include.lua:25,26. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
YDBZ_DOI_MAX = {"VIEMDE", "So nguoi trong to doi: it nhat / nhieu nhat. Goc: readymap\\include.lua:25,26. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", ""},
YDBZ_PHONG_TOIDA = {"VIEMDE", "So to doi (= so phong cho) toi da moi dot. Goc: head.lua:47 = 15. !! Doi so nay PHAI khai them ban do vao MapList.ini + WorldSet_GameServer.ini (be hien tai: 1003-1017). Xem ReverseTools\\viemde\\v02_khai_bando.py. [RES...", 0, 0, 0, 2, "cauhinh_hoatdong.lua", ""},
YDBZ_PHUT_BAODANH = {"VIEMDE", "Thoi gian bao danh (phut). Goc: ready.lua:38 nReadyTime = 5*60. [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "phut"},
YDBZ_PHUT_TRAN = {"VIEMDE", "Thoi han mot tran (phut). Goc: head.lua:42 YDBZ_LIMIT_FINISH = 30*60. [LIVE]", 0, 0, 0, 1, "cauhinh_hoatdong.lua", "phut"},
YDBZ_NPC_MAP = {"VIEMDE", "Ban do dat 4 NPC \"Binh Binh co nuong\" va toa do. Goc: server1\\script\\global\\autoexec_npc.lua:141-144 (map 37 = Bien Kinh, NPC template 1320 - JX1 DA CO san trong npcs.txt). [RESTART]", 0, 0, 0, 2, "cauhinh_hoatdong.lua", "map"},
}
