; Giao dien man hinh
; Ui Designed Muaroilangtham
; 12:20 PM 28/2/2024

[Main]
Left=0
Top=0
Width=800
Height=600
Moveable=0
Trans=1
Image=\Spr\Ui3\UiPlayerBar\bg9o.spr
Image1024=\Spr\Ui3\UiPlayerBar\khungPlayerBar.spr
DummyWnd=1
Button0=Run
Button1=Sit
; Button2=Status
; Button3=Items
Button2=Horse
; Button5=Skills
Button3=Exchange
; Button7=Team
Button4=PK

[Run]
Left=92
Top=68
Width=28
Height=28
;Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÅÜ²½.spr
Image=\Spr\Ui3\UiPlayerBar\chay.spr
CheckBox=1
Up=0
Down=1
Trans=0
Tip=Ch¹y/§i
ClassType=Player_Run


[Sit]
Left=122
Top=68
Width=28
Height=28
;Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\´ò×ø.spr
Image=\Spr\Ui3\UiPlayerBar\ngoi.spr
CheckBox=1
Up=0
Down=2
Trans=0
Tip=Ngåi
ClassType=Player_Sit


[Horse]
Left=152
Top=68
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÆïÂí.spr
Image=\Spr\Ui3\UiPlayerBar\lenngua.spr
CheckBox=1
Up=1
Down=0
Trans=0
Tip=Lªn/Xuèng ngùa
ClassType=Player_Horse


[Exchange]
Left=182
Top=68
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\½»Ò×.spr
Image=\Spr\Ui3\UiPlayerBar\giaodich.spr
CheckBox=1
Up=0
Down=1
Tip=Giao dÞch
ClassType=Player_Exchange


[PK]
Left=212
Top=68
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\pk.spr
Image=\Spr\Ui3\UiPlayerBar\F9.spr
Up=0
Down=1
CheckBox=1
;Tip=Tr¹ng th¸i PK
ClassType=Player_PK

[Market]
Left=728
Top=497
Width=65
Height=60
Trans=0
;Image=\Spr\Ui3\ÂòÂô\ktc_ÆæÕä¸ó°´Å¥.spr
Image=\spr\UI3\Ö÷½çÃæ\ÆæÕä¸ó°´Å¥_vn.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Kú tr©n c¸c


[DateTime]
Left=0
Top=2
Width=125
Height=15
Font=12
Trans=0
Image=\Spr\Ui3\±íÇé\
Tip=Thêi Gian
Color=255,217,78
OverColor=0,255,0
SelColor=205,167,28
GameLogo=Vâ L©m TruyÒn Kú
SmoothColor=60,255,160
SmoothMsg=Ho¹t ®éng tèt
SmoothPing=500
CrowdColor=255,200,0
CrowdMsg=Server qu?t¶i
CrowdPing=2000
BlockColor=255,0,0
BlockMsg=Server gi¸n ®o¹n
BlockPing=

[WifiStatus]
Left=3
Top=20
Width=20
Height=20
Image=\Spr\Ui3\UiPlayerBar\wifi_status.spr
Trans=0
Up=0
Down=0
Over=0
OverFrame=0
Tip=Server Status

[HideWindow]
Left=748
Top=160
Width=50
Height=20
Image=\Spr\Ui3\UiPlayerBar\angame.spr
Trans=0
Up=0
Down=0
Over=1
OverFrame=1
Tip=

[Zalo]
Left=765
Top=185
Width=20
Height=20
Image=\Spr\Ui3\UiPlayerBar\nut_zl.spr
Trans=0
Up=0
Down=0
Over=1
OverFrame=1
Tip=

[Facebook]
Left=765
Top=213
Width=20
Height=20
Image=\Spr\Ui3\UiPlayerBar\nut_fb.spr
Trans=0
Up=0
Down=0
Over=1
OverFrame=1
Tip=

[HideGraphic]
Left=765
Top=241
Width=20
Height=20
Image=\Spr\Ui3\UiPlayerBar\nut_fb.spr
Trans=0
Up=0
Down=0
Over=1
OverFrame=1
Tip=Hide Graphic

[SpringGame]
Left=765
Top=243
Width=50
Height=50
Image=\spr\Ui3\SpringGame\iconbaucua.spr
Trans=0
Up=0
Down=0
Over=1
OverFrame=0
Tip=Bau cua

[ChannelBtn]
Left=1
Top=520
Width=20
Height=20
Font=12
Trans=0
;Æ½³£ÑÕÉ«
Color=255,217,78
;Êó±êÒÆÉÏÈ¥Ê±µÄÎÄ×ÖÑÕÉ«
OverColor=0,255,0
;Êó±ê°´ÏÂÈ¥Ê±µÄÎÄ×ÖÑÕÉ«
SelColor=205,167,28
Tip=Chän kªnh chat

[OpenChannelBtn]
Left=0
Top=0
Width=0
Height=0
Font=12
Trans=0
Up=0
Down=1
Over=2
OverFrame=2
Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\
;Æ½³£ÑÕÉ«
Color=255,217,78
;Êó±êÒÆÉÏÈ¥Ê±µÄÎÄ×ÖÑÕÉ«
OverColor=0,255,0
;Êó±ê°´ÏÂÈ¥Ê±µÄÎÄ×ÖÑÕÉ«
SelColor=205,167,28


[InputEdit]
Left=28
Top=525
Width=248
Height=15
Font=13
Type=2
MultiLine=0
MaxLen=250
Color=254,255,160
FocusBKColor=25,31,11
FocusBKColorAlpha=120
FocusNoCanBKColor=97,2,0
FocusNoCanBKColorAlpha=150


[Face]
Left=281
Top=522
Width=22
Height=22
Trans=0
Image=\Spr\Ui3\±íÇé\01.spr
Up=0
Down=0
Over=0
OverFrame=0
Tip=BiÓu c¶m

[SendBtn]
Left=304
Top=522
Width=22
Height=22
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Tip=Göi tin
Image=\Spr\Ui3\Ö÷½çÃæ\Ö÷½çÃæ°´Å¥-ÁÄÌì·¢ËÍ.spr
Tip=Göi ®i

;ÅóÓÑ°´Å¥
[Friend]
Left=677
Top=559
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\Ö÷½çÃæ°´Å¥-ºÃÓÑ.spr
Image=\Spr\Ui3\UiPlayerBar\banhuu.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=H¶o h÷u 

;Ñ¡Ïî°´Å¥
[Options]
Left=708
Top=559
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\Ö÷½çÃæ°´Å¥£­ÏµÍ³Ñ¡Ïî.spr
Image=\Spr\Ui3\UiPlayerBar\caidat.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Tïy chän h?thèng

[HideChat]
Left=647
Top=559
Width=28
Height=28
Trans=0
;Image=\Spr\Ui3\Ö÷½çÃæ\Ö÷½çÃæ°´Å¥£­ÏµÍ³Ñ¡Ïî.spr
Image=\Spr\Ui3\UiPlayerBar\chat.spr
Up=1
Down=0
Over=2
OverFrame=2
Tip=Èn Chat

;¿ì½Ý¼¼ÄÜ
[ImediaLeftSkill]
Left=372
Top=529
Width=36
Height=36
EnableClickEmpty=1
HaveBgColor=0

[ImediaRightSkill]
Left=410
Top=529
Width=36
Height=36
EnableClickEmpty=1
HaveBgColor=0


;ÎïÆ·0
[Item_0]
Width=36
Height=36
Left=11
Top=545
HaveBgColor=0


;ÎïÆ·1
[Item_1]
Width=36
Height=36
Left=49
Top=545
HaveBgColor=0

;ÎïÆ·2
[Item_2]
Width=36
Height=36
Left=87
Top=545
HaveBgColor=0

[Item_3]
Width=36
Height=36
Left=125
Top=545
HaveBgColor=0

[Item_4]
Width=36
Height=36
Left=163
Top=545
HaveBgColor=0

[Item_5]
Width=36
Height=36
Left=201
Top=545
HaveBgColor=0

[Item_6]
Width=36
Height=36
Left=239
Top=545
HaveBgColor=0

[Item_7]
Width=36
Height=36
Left=277
Top=545
HaveBgColor=0

[Item_8]
Width=36
Height=36
Left=315
Top=545
HaveBgColor=0


[ChatItem]
Left=0
Top=0
Width=0
Height=0
Font=12
;Color=0,255,255
;BorderColor=25,25,25
;OverColor=255,253,122
;OverBorderColor=200,50,0
;SelColor=255,253,122
;SelBorderColor=25,25,25

[BuffPos]
XY=120,28
End=26,27
MaxIHeight=10,20

[BuffImage]
Left=0
Top=0
Width=34
Height=24
Trans=1
Up=0
Down=0
Over=0
OverFrame=0

[txtBuffTime]
Left=0
Top=0
Width=24
Height=12
Font=12
HAlign=1
Color=55,231,63

[Status]
Left=461
Top=559
Width=28
Height=28
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÈËÎï.spr
Image=\Spr\Ui3\UiPlayerBar\status.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Nh©n vËt
ClassType=Player_Status

[Items]
Left=492
Top=559
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÎïÆ·.spr
Image=\Spr\Ui3\UiPlayerBar\item.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Hµnh trang
ClassType=Player_Items

[ItemEx]
Left=523
Top=559
Width=28
Height=28
; Image=\Spr\Ui3\UiPlayerBar\itembag2.spr
Image=\Spr\Ui3\UiPlayerBar\itembag.spr
CheckBox=0
Up=0
Down=1
Over=2
OverFrame=2
Tip=Tói hµnh trang më réng
ClassType=Player_ItemEx


[Skills]
Left=554
Top=559
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\Îä¹¦.spr
Image=\Spr\Ui3\UiPlayerBar\skill.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Kü N¨ng
ClassType=Player_Skills


[Team]
Left=585
Top=559
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\×é¶Ó.spr
Image=\Spr\Ui3\UiPlayerBar\team.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Tæ §éi
ClassType=Player_Team

[Faction]
Left=616
Top=559
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\°ïÅÉ.spr
Image=\Spr\Ui3\UiPlayerBar\banghoi.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=Bang héi
ClassType=Player_Faction


; [ChatRoom]
; Left=196
; Top=559
; Width=1
; Height=1
; Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\°ïÅÉ.spr
; Image=\Spr\Ui3\UiPlayerBar\ChatRoom.spr
; Up=0
; Down=1
; Over=2
; OverFrame=2
; Tip=ChatRoom
; ClassType=Player_Skills



[Run]
Left=92
Top=500
Width=28
Height=28
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÅÜ²½.spr
Image=\Spr\Ui3\UiPlayerBar\chay.spr
CheckBox=1
Up=0
Down=1
Trans=0
Tip=Ch¹y/§i
ClassType=Player_Run


[Sit]
Left=122
Top=500
Width=28
Height=28
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\´ò×ø.spr
Image=\Spr\Ui3\UiPlayerBar\ngoi.spr
CheckBox=1
Up=0
Down=2
Trans=0
Tip=Ngåi
ClassType=Player_Sit


[Horse]
Left=152
Top=500
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\ÆïÂí.spr
Image=\Spr\Ui3\UiPlayerBar\lenngua.spr
CheckBox=1
Up=1
Down=0
Trans=0
Tip=Lªn/Xuèng ngùa
ClassType=Player_Horse


[Exchange]
Left=182
Top=500
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\½»Ò×.spr
Image=\Spr\Ui3\UiPlayerBar\giaodich.spr
CheckBox=1
Up=0
Down=1
Tip=Giao dÞch
ClassType=Player_Exchange


[PK]
Left=212
Top=500
Width=28
Height=28
Trans=0
; Image=\Spr\Ui3\Ö÷½çÃæ\°´Å¥Ìõ°´Å¥\pk.spr
Image=\Spr\Ui3\UiPlayerBar\F9.spr
Up=0
Down=1
CheckBox=1
; Tip=Tr¹ng th¸i PK
ClassType=Player_PK


[AutoPlay]
Left=738
Top=559
Width=28
Height=28
Trans=0
Image=\Spr\Ui3\UiPlayerBar\autobt3.spr
CheckBox=1
Up=0
Down=1
Over=2
OverFrame=2
Tip=Tù ®éng ®¸nh qu¸i
ClassType=Player_AutoPlay

[TraceBtn]
Left=765
Top=185
Width=25
Height=25
Image=\spr\Ui4\Ö÷½çÃæ\ÈÎÎñÖ¸ÄÏ×ÊÔ´\opentracebtn.spr
Trans=0
Up=0
Down=1
Tip=Theo dâi nhiÖm vô
